//HintName: G.Models.ResponsesPostRequestBodyContentApplicationJsonSchemaInputOneOf1Items.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    public sealed partial class ResponsesPostRequestBodyContentApplicationJsonSchemaInputOneOf1Items
    {
        /// <summary>
        /// The role of the sender (user or assistant).
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("role")]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required string Role { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("content")]
        [global::System.Text.Json.Serialization.JsonConverter(typeof(global::G.JsonConverters.ResponsesPostRequestBodyContentApplicationJsonSchemaInputOneOf1ItemsContentJsonConverter))]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required global::G.ResponsesPostRequestBodyContentApplicationJsonSchemaInputOneOf1ItemsContent Content { get; set; }

        /// <summary>
        /// The type of input item.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("type")]
        public string? Type { get; set; }

        /// <summary>
        /// The ID of the input item, typically used when inputting items that were output by the model.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The status of the input item, typically used when inputting items that were output by the model.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("status")]
        public string? Status { get; set; }

        /// <summary>
        /// The arguments used for the tool call made by the model.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("arguments")]
        public string? Arguments { get; set; }

        /// <summary>
        /// The call_id of the tool call made by the model. Generated by the model in the output.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("call_id")]
        public string? CallId { get; set; }

        /// <summary>
        /// The name of the tool used in the tool call from the previous output.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get; set; }

        /// <summary>
        /// Any type
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("output")]
        public object? Output { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::System.Text.Json.Serialization.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponsesPostRequestBodyContentApplicationJsonSchemaInputOneOf1Items" /> class.
        /// </summary>
        /// <param name="role">
        /// The role of the sender (user or assistant).
        /// </param>
        /// <param name="content"></param>
        /// <param name="type">
        /// The type of input item.
        /// </param>
        /// <param name="id">
        /// The ID of the input item, typically used when inputting items that were output by the model.
        /// </param>
        /// <param name="status">
        /// The status of the input item, typically used when inputting items that were output by the model.
        /// </param>
        /// <param name="arguments">
        /// The arguments used for the tool call made by the model.
        /// </param>
        /// <param name="callId">
        /// The call_id of the tool call made by the model. Generated by the model in the output.
        /// </param>
        /// <param name="name">
        /// The name of the tool used in the tool call from the previous output.
        /// </param>
        /// <param name="output">
        /// Any type
        /// </param>
#if NET7_0_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
#endif
        public ResponsesPostRequestBodyContentApplicationJsonSchemaInputOneOf1Items(
            string role,
            global::G.ResponsesPostRequestBodyContentApplicationJsonSchemaInputOneOf1ItemsContent content,
            string? type,
            string? id,
            string? status,
            string? arguments,
            string? callId,
            string? name,
            object? output)
        {
            this.Role = role ?? throw new global::System.ArgumentNullException(nameof(role));
            this.Content = content;
            this.Type = type;
            this.Id = id;
            this.Status = status;
            this.Arguments = arguments;
            this.CallId = callId;
            this.Name = name;
            this.Output = output;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponsesPostRequestBodyContentApplicationJsonSchemaInputOneOf1Items" /> class.
        /// </summary>
        public ResponsesPostRequestBodyContentApplicationJsonSchemaInputOneOf1Items()
        {
        }
    }
}