//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.ActionEnumJsonConverter),
            typeof(global::G.JsonConverters.ActionEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ActionsEnumJsonConverter),
            typeof(global::G.JsonConverters.ActionsEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.AgreementMethodologyEnumJsonConverter),
            typeof(global::G.JsonConverters.AgreementMethodologyEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.AgreementV2BackfillJobStatusEnumJsonConverter),
            typeof(global::G.JsonConverters.AgreementV2BackfillJobStatusEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.AnnotatedEnumJsonConverter),
            typeof(global::G.JsonConverters.AnnotatedEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.AuthMethodEnumJsonConverter),
            typeof(global::G.JsonConverters.AuthMethodEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.AuthTypeEnumJsonConverter),
            typeof(global::G.JsonConverters.AuthTypeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.BudgetResetPeriodEnumJsonConverter),
            typeof(global::G.JsonConverters.BudgetResetPeriodEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.DashboardTypeEnumJsonConverter),
            typeof(global::G.JsonConverters.DashboardTypeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.Default165EnumJsonConverter),
            typeof(global::G.JsonConverters.Default165EnumNullableJsonConverter),
            typeof(global::G.JsonConverters.EditionEnumJsonConverter),
            typeof(global::G.JsonConverters.EditionEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.FinishedEnumJsonConverter),
            typeof(global::G.JsonConverters.FinishedEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.LabelStreamTaskDistributionEnumJsonConverter),
            typeof(global::G.JsonConverters.LabelStreamTaskDistributionEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.LastActionEnumJsonConverter),
            typeof(global::G.JsonConverters.LastActionEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ModeEnumJsonConverter),
            typeof(global::G.JsonConverters.ModeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelRunStatusEnumJsonConverter),
            typeof(global::G.JsonConverters.ModelRunStatusEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.OnboardingStateEnumJsonConverter),
            typeof(global::G.JsonConverters.OnboardingStateEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.Options165EnumJsonConverter),
            typeof(global::G.JsonConverters.Options165EnumNullableJsonConverter),
            typeof(global::G.JsonConverters.OrganizationMemberTagImportStatusStatusEnumJsonConverter),
            typeof(global::G.JsonConverters.OrganizationMemberTagImportStatusStatusEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectGroupRoleEnumJsonConverter),
            typeof(global::G.JsonConverters.ProjectGroupRoleEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectSubsetEnumJsonConverter),
            typeof(global::G.JsonConverters.ProjectSubsetEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptsStatusEnumJsonConverter),
            typeof(global::G.JsonConverters.PromptsStatusEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ProviderEnumJsonConverter),
            typeof(global::G.JsonConverters.ProviderEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ReasonEnumJsonConverter),
            typeof(global::G.JsonConverters.ReasonEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.RequeueRejectedTasksModeEnumJsonConverter),
            typeof(global::G.JsonConverters.RequeueRejectedTasksModeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ReviewCriteriaEnumJsonConverter),
            typeof(global::G.JsonConverters.ReviewCriteriaEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ReviewSettingsSamplingEnumJsonConverter),
            typeof(global::G.JsonConverters.ReviewSettingsSamplingEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ReviewedEnumJsonConverter),
            typeof(global::G.JsonConverters.ReviewedEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.Role9e7EnumJsonConverter),
            typeof(global::G.JsonConverters.Role9e7EnumNullableJsonConverter),
            typeof(global::G.JsonConverters.SamplingDe5EnumJsonConverter),
            typeof(global::G.JsonConverters.SamplingDe5EnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ScopeEnumJsonConverter),
            typeof(global::G.JsonConverters.ScopeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.SegmentationEnumJsonConverter),
            typeof(global::G.JsonConverters.SegmentationEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.SkillNameEnumJsonConverter),
            typeof(global::G.JsonConverters.SkillNameEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.SkipQueueEnumJsonConverter),
            typeof(global::G.JsonConverters.SkipQueueEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.SkippedEnumJsonConverter),
            typeof(global::G.JsonConverters.SkippedEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.StateEnumJsonConverter),
            typeof(global::G.JsonConverters.StateEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.Status7bfEnumJsonConverter),
            typeof(global::G.JsonConverters.Status7bfEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.StatusC5aEnumJsonConverter),
            typeof(global::G.JsonConverters.StatusC5aEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.TrialRoleEnumJsonConverter),
            typeof(global::G.JsonConverters.TrialRoleEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.TypeEnumJsonConverter),
            typeof(global::G.JsonConverters.TypeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmActionsCreateRequestFiltersConjunctionJsonConverter),
            typeof(global::G.JsonConverters.ApiDmActionsCreateRequestFiltersConjunctionNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmActionsCreateRequestFiltersItemFilterJsonConverter),
            typeof(global::G.JsonConverters.ApiDmActionsCreateRequestFiltersItemFilterNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmActionsCreateRequestFiltersItemOperatorJsonConverter),
            typeof(global::G.JsonConverters.ApiDmActionsCreateRequestFiltersItemOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmActionsCreateRequestOrderingItemJsonConverter),
            typeof(global::G.JsonConverters.ApiDmActionsCreateRequestOrderingItemNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsCreateRequestDataFiltersConjunctionJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsCreateRequestDataFiltersConjunctionNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsCreateRequestDataFiltersItemFilterJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsCreateRequestDataFiltersItemFilterNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsCreateRequestDataFiltersItemOperatorJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsCreateRequestDataFiltersItemOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsCreateRequestDataOrderingItemJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsCreateRequestDataOrderingItemNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsPartialUpdateRequestDataFiltersConjunctionJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsPartialUpdateRequestDataFiltersConjunctionNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsPartialUpdateRequestDataFiltersItemFilterJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsPartialUpdateRequestDataFiltersItemFilterNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsPartialUpdateRequestDataFiltersItemOperatorJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsPartialUpdateRequestDataFiltersItemOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsPartialUpdateRequestDataOrderingItemJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsPartialUpdateRequestDataOrderingItemNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsUpdateRequestDataFiltersConjunctionJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsUpdateRequestDataFiltersConjunctionNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsUpdateRequestDataFiltersItemFilterJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsUpdateRequestDataFiltersItemFilterNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsUpdateRequestDataFiltersItemOperatorJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsUpdateRequestDataFiltersItemOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsUpdateRequestDataOrderingItemJsonConverter),
            typeof(global::G.JsonConverters.ApiDmViewsUpdateRequestDataOrderingItemNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiLlmOpenaiChatCompletionsCreateRequestMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ApiLlmOpenaiChatCompletionsCreateRequestMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiMlCreateRequestAuthMethodJsonConverter),
            typeof(global::G.JsonConverters.ApiMlCreateRequestAuthMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiMlPartialUpdateRequestAuthMethodJsonConverter),
            typeof(global::G.JsonConverters.ApiMlPartialUpdateRequestAuthMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesCreateRequestFiltersConjunctionJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesCreateRequestFiltersConjunctionNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesCreateRequestFiltersItemFilterJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesCreateRequestFiltersItemFilterNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesCreateRequestFiltersItemOperatorJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesCreateRequestFiltersItemOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesCreateRequestTypeJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesCreateRequestTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesPartialUpdateRequestTypeJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesPartialUpdateRequestTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesCreate2RequestTypeJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesCreate2RequestTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiActivityLogsListMethodJsonConverter),
            typeof(global::G.JsonConverters.ApiActivityLogsListMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiDmActionsCreateIdJsonConverter),
            typeof(global::G.JsonConverters.ApiDmActionsCreateIdNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesDestroyTypeJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsTasksAssigneesDestroyTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiPromptsCompatibleProjectsListProjectTypeJsonConverter),
            typeof(global::G.JsonConverters.ApiPromptsCompatibleProjectsListProjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiPromptsVersionsInferenceRunsListProjectSubsetJsonConverter),
            typeof(global::G.JsonConverters.ApiPromptsVersionsInferenceRunsListProjectSubsetNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiTasksListFieldsJsonConverter),
            typeof(global::G.JsonConverters.ApiTasksListFieldsNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsAwsCustomFunctionRetrieveResponseStatusJsonConverter),
            typeof(global::G.JsonConverters.ApiProjectsAwsCustomFunctionRetrieveResponseStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.MaybeExpandedCommentJsonConverter),
            typeof(global::G.JsonConverters.RoleBasedTaskJsonConverter),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, int?, float?, bool?, object, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ApiDmActionsCreateRequestSelectedItemsAllFalse, global::G.ApiDmActionsCreateRequestSelectedItemsAllTrue>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, int?, float?, bool?, object, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, int?, float?, bool?, object, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, int?, float?, bool?, object, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, int?, float?, bool?, object, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ApiProjectsTasksAssigneesCreateRequestSelectedItemsAllFalse, global::G.ApiProjectsTasksAssigneesCreateRequestSelectedItemsAllTrue>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::System.Collections.Generic.IList<global::System.Collections.Generic.IList<double>>, global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.IList<global::System.Collections.Generic.IList<double>>>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::System.Collections.Generic.IList<global::System.Collections.Generic.IList<double>>, global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.IList<global::System.Collections.Generic.IList<double>>>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<double?, global::System.Collections.Generic.Dictionary<string, double>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<double?, global::System.Collections.Generic.Dictionary<string, double>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ApiProjectsStatsTotalAgreementRetrieveResponseVariant1, global::G.ApiProjectsStatsTotalAgreementRetrieveResponseVariant2>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<double?, global::System.Collections.Generic.Dictionary<string, double>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<double?, global::System.Collections.Generic.Dictionary<string, double>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<double?, global::System.Collections.Generic.Dictionary<string, double>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<double?, global::System.Collections.Generic.Dictionary<string, double>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<double?, global::System.Collections.Generic.Dictionary<string, double>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<double?, global::System.Collections.Generic.Dictionary<string, double>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<double?, global::System.Collections.Generic.Dictionary<string, double>>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}