//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.ASRQualityJsonConverter),
            typeof(global::G.JsonConverters.ASRQualityNullableJsonConverter),
            typeof(global::G.JsonConverters.ASRProviderJsonConverter),
            typeof(global::G.JsonConverters.ASRProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.ASRInputFormatJsonConverter),
            typeof(global::G.JsonConverters.ASRInputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOperatorNodeInputLeftDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOperatorNodeInputLeftDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOperatorNodeInputRightDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOperatorNodeInputRightDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOperatorNodeInputLeftDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOperatorNodeInputLeftDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOperatorNodeInputRightDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOperatorNodeInputRightDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTNotEqualsOperatorNodeInputLeftDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTNotEqualsOperatorNodeInputLeftDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTNotEqualsOperatorNodeInputRightDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTNotEqualsOperatorNodeInputRightDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTEqualsOperatorNodeInputLeftDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTEqualsOperatorNodeInputLeftDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTEqualsOperatorNodeInputRightDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTEqualsOperatorNodeInputRightDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTOrOperatorNodeInputChildrenItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTOrOperatorNodeInputChildrenItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTAndOperatorNodeInputChildrenItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTAndOperatorNodeInputChildrenItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOrEqualsOperatorNodeInputLeftDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOrEqualsOperatorNodeInputLeftDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOrEqualsOperatorNodeInputRightDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOrEqualsOperatorNodeInputRightDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOrEqualsOperatorNodeInputLeftDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOrEqualsOperatorNodeInputLeftDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOrEqualsOperatorNodeInputRightDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOrEqualsOperatorNodeInputRightDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOperatorNodeOutputLeftDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOperatorNodeOutputLeftDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOperatorNodeOutputRightDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOperatorNodeOutputRightDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOperatorNodeOutputLeftDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOperatorNodeOutputLeftDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOperatorNodeOutputRightDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOperatorNodeOutputRightDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTNotEqualsOperatorNodeOutputLeftDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTNotEqualsOperatorNodeOutputLeftDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTNotEqualsOperatorNodeOutputRightDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTNotEqualsOperatorNodeOutputRightDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTEqualsOperatorNodeOutputLeftDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTEqualsOperatorNodeOutputLeftDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTEqualsOperatorNodeOutputRightDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTEqualsOperatorNodeOutputRightDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTOrOperatorNodeOutputChildrenItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTOrOperatorNodeOutputChildrenItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTAndOperatorNodeOutputChildrenItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTAndOperatorNodeOutputChildrenItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOrEqualsOperatorNodeOutputLeftDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOrEqualsOperatorNodeOutputLeftDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOrEqualsOperatorNodeOutputRightDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTGreaterThanOrEqualsOperatorNodeOutputRightDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOrEqualsOperatorNodeOutputLeftDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOrEqualsOperatorNodeOutputLeftDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOrEqualsOperatorNodeOutputRightDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ASTLessThanOrEqualsOperatorNodeOutputRightDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChapterWithContentResponseModelStateJsonConverter),
            typeof(global::G.JsonConverters.ChapterWithContentResponseModelStateNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelTargetAudience2JsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelTargetAudience2NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelStateJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelStateNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelAccessLevelJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelAccessLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelFiction2JsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelFiction2NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectCreationMetaResponseModelStatusJsonConverter),
            typeof(global::G.JsonConverters.ProjectCreationMetaResponseModelStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectCreationMetaResponseModelTypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectCreationMetaResponseModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelSourceType2JsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelSourceType2NullableJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleModelTextAlign2JsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleModelTextAlign2NullableJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleModelTextStyle2JsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleModelTextStyle2NullableJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleModelTextWeight2JsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleModelTextWeight2NullableJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleSectionAnimationModelEnterTypeJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleSectionAnimationModelEnterTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleSectionAnimationModelExitTypeJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleSectionAnimationModelExitTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleWordAnimationModelEnterTypeJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleWordAnimationModelEnterTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleWordAnimationModelExitTypeJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleWordAnimationModelExitTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleCharacterAnimationModelEnterTypeJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleCharacterAnimationModelEnterTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleCharacterAnimationModelExitTypeJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleCharacterAnimationModelExitTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleHorizontalPlacementModelAlignJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleHorizontalPlacementModelAlignNullableJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleVerticalPlacementModelAlignJsonConverter),
            typeof(global::G.JsonConverters.CaptionStyleVerticalPlacementModelAlignNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelAspectRatio2JsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelAspectRatio2NullableJsonConverter),
            typeof(global::G.JsonConverters.AddPronunciationDictionaryResponseModelPermissionOnResource2JsonConverter),
            typeof(global::G.JsonConverters.AddPronunciationDictionaryResponseModelPermissionOnResource2NullableJsonConverter),
            typeof(global::G.JsonConverters.ExportOptionsDiscriminatorFormatJsonConverter),
            typeof(global::G.JsonConverters.ExportOptionsDiscriminatorFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.TurnModeJsonConverter),
            typeof(global::G.JsonConverters.TurnModeNullableJsonConverter),
            typeof(global::G.JsonConverters.TurnEagernessJsonConverter),
            typeof(global::G.JsonConverters.TurnEagernessNullableJsonConverter),
            typeof(global::G.JsonConverters.SpellingPatienceJsonConverter),
            typeof(global::G.JsonConverters.SpellingPatienceNullableJsonConverter),
            typeof(global::G.JsonConverters.TTSConversationalModelJsonConverter),
            typeof(global::G.JsonConverters.TTSConversationalModelNullableJsonConverter),
            typeof(global::G.JsonConverters.TTSModelFamilyJsonConverter),
            typeof(global::G.JsonConverters.TTSModelFamilyNullableJsonConverter),
            typeof(global::G.JsonConverters.TTSOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.TTSOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.TextNormalisationTypeJsonConverter),
            typeof(global::G.JsonConverters.TextNormalisationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ClientEventJsonConverter),
            typeof(global::G.JsonConverters.ClientEventNullableJsonConverter),
            typeof(global::G.JsonConverters.LlmJsonConverter),
            typeof(global::G.JsonConverters.LlmNullableJsonConverter),
            typeof(global::G.JsonConverters.LLMReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.LLMReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolCallSoundTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolCallSoundTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolCallSoundBehaviorJsonConverter),
            typeof(global::G.JsonConverters.ToolCallSoundBehaviorNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolErrorHandlingModeJsonConverter),
            typeof(global::G.JsonConverters.ToolErrorHandlingModeNullableJsonConverter),
            typeof(global::G.JsonConverters.TransferTypeEnumJsonConverter),
            typeof(global::G.JsonConverters.TransferTypeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.SystemToolConfigInputParamsDiscriminatorSystemToolTypeJsonConverter),
            typeof(global::G.JsonConverters.SystemToolConfigInputParamsDiscriminatorSystemToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.KnowledgeBaseDocumentTypeJsonConverter),
            typeof(global::G.JsonConverters.KnowledgeBaseDocumentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DocumentUsageModeEnumJsonConverter),
            typeof(global::G.JsonConverters.DocumentUsageModeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.CustomLLMAPITypeJsonConverter),
            typeof(global::G.JsonConverters.CustomLLMAPITypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingModelEnumJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingModelEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentAPIModelInputBackupLlmConfigDiscriminatorPreferenceJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentAPIModelInputBackupLlmConfigDiscriminatorPreferenceNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolExecutionModeJsonConverter),
            typeof(global::G.JsonConverters.ToolExecutionModeNullableJsonConverter),
            typeof(global::G.JsonConverters.WebhookToolApiSchemaConfigInputMethodJsonConverter),
            typeof(global::G.JsonConverters.WebhookToolApiSchemaConfigInputMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.LiteralJsonSchemaPropertyTypeJsonConverter),
            typeof(global::G.JsonConverters.LiteralJsonSchemaPropertyTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WebhookToolApiSchemaConfigInputContentTypeJsonConverter),
            typeof(global::G.JsonConverters.WebhookToolApiSchemaConfigInputContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IntegrationTypeJsonConverter),
            typeof(global::G.JsonConverters.IntegrationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MCPApprovalPolicyJsonConverter),
            typeof(global::G.JsonConverters.MCPApprovalPolicyNullableJsonConverter),
            typeof(global::G.JsonConverters.MCPToolConfigInputInputOverridesDiscriminatorSourceJsonConverter),
            typeof(global::G.JsonConverters.MCPToolConfigInputInputOverridesDiscriminatorSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiIntegrationWebhookOverridesInputSchemaOverridesDiscriminatorSourceJsonConverter),
            typeof(global::G.JsonConverters.ApiIntegrationWebhookOverridesInputSchemaOverridesDiscriminatorSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFilterModeJsonConverter),
            typeof(global::G.JsonConverters.ResponseFilterModeNullableJsonConverter),
            typeof(global::G.JsonConverters.SMBToolConfigParamsDiscriminatorSmbToolTypeJsonConverter),
            typeof(global::G.JsonConverters.SMBToolConfigParamsDiscriminatorSmbToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentAPIModelInputToolDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentAPIModelInputToolDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbedVariantJsonConverter),
            typeof(global::G.JsonConverters.EmbedVariantNullableJsonConverter),
            typeof(global::G.JsonConverters.WidgetPlacementJsonConverter),
            typeof(global::G.JsonConverters.WidgetPlacementNullableJsonConverter),
            typeof(global::G.JsonConverters.WidgetExpandableJsonConverter),
            typeof(global::G.JsonConverters.WidgetExpandableNullableJsonConverter),
            typeof(global::G.JsonConverters.WidgetFeedbackModeJsonConverter),
            typeof(global::G.JsonConverters.WidgetFeedbackModeNullableJsonConverter),
            typeof(global::G.JsonConverters.WidgetEndFeedbackTypeJsonConverter),
            typeof(global::G.JsonConverters.WidgetEndFeedbackTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WidgetConfigInputSyntaxHighlightTheme2JsonConverter),
            typeof(global::G.JsonConverters.WidgetConfigInputSyntaxHighlightTheme2NullableJsonConverter),
            typeof(global::G.JsonConverters.WebhookEventTypeJsonConverter),
            typeof(global::G.JsonConverters.WebhookEventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GuardrailExecutionModeJsonConverter),
            typeof(global::G.JsonConverters.GuardrailExecutionModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConfigEntityTypeJsonConverter),
            typeof(global::G.JsonConverters.ConfigEntityTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowExpressionConditionModelInputExpressionDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowExpressionConditionModelInputExpressionDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowEdgeModelInputForwardConditionVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowEdgeModelInputForwardConditionVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowEdgeModelInputBackwardConditionVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowEdgeModelInputBackwardConditionVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowPhoneNumberNodeModelInputCustomSipHeaderDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowPhoneNumberNodeModelInputCustomSipHeaderDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowPhoneNumberNodeModelInputTransferDestinationDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowPhoneNumberNodeModelInputTransferDestinationDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowPhoneNumberNodeModelInputPostDialDigitsVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowPhoneNumberNodeModelInputPostDialDigitsVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentAPIModelWorkflowOverrideInputToolsVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentAPIModelWorkflowOverrideInputToolsVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentWorkflowRequestModelNodesDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.AgentWorkflowRequestModelNodesDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PhoneNumberTransferCustomSipHeaderDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PhoneNumberTransferCustomSipHeaderDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PhoneNumberTransferTransferDestinationVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PhoneNumberTransferTransferDestinationVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PhoneNumberTransferPostDialDigitsVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PhoneNumberTransferPostDialDigitsVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BranchProtectionStatusJsonConverter),
            typeof(global::G.JsonConverters.BranchProtectionStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ResourceAccessInfoRoleJsonConverter),
            typeof(global::G.JsonConverters.ResourceAccessInfoRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.SystemToolConfigOutputParamsDiscriminatorSystemToolTypeJsonConverter),
            typeof(global::G.JsonConverters.SystemToolConfigOutputParamsDiscriminatorSystemToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentAPIModelOutputBackupLlmConfigDiscriminatorPreferenceJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentAPIModelOutputBackupLlmConfigDiscriminatorPreferenceNullableJsonConverter),
            typeof(global::G.JsonConverters.WebhookToolApiSchemaConfigOutputMethodJsonConverter),
            typeof(global::G.JsonConverters.WebhookToolApiSchemaConfigOutputMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.WebhookToolApiSchemaConfigOutputContentTypeJsonConverter),
            typeof(global::G.JsonConverters.WebhookToolApiSchemaConfigOutputContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MCPToolConfigOutputInputOverridesDiscriminatorSourceJsonConverter),
            typeof(global::G.JsonConverters.MCPToolConfigOutputInputOverridesDiscriminatorSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiIntegrationWebhookOverridesOutputSchemaOverridesDiscriminatorSourceJsonConverter),
            typeof(global::G.JsonConverters.ApiIntegrationWebhookOverridesOutputSchemaOverridesDiscriminatorSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentAPIModelOutputToolDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentAPIModelOutputToolDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentAPIModelWorkflowOverrideOutputToolsVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentAPIModelWorkflowOverrideOutputToolsVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentDefinitionSourceJsonConverter),
            typeof(global::G.JsonConverters.AgentDefinitionSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.WidgetConfigOutputSyntaxHighlightTheme2JsonConverter),
            typeof(global::G.JsonConverters.WidgetConfigOutputSyntaxHighlightTheme2NullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptResponseModelRoleJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptResponseModelRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptToolCallCommonModelOutputToolDetailsVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptToolCallCommonModelOutputToolDetailsVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptOtherToolsResultCommonModelType2JsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptOtherToolsResultCommonModelType2NullableJsonConverter),
            typeof(global::G.JsonConverters.TransferToAgentToolResultSuccessModelBranchInfoVariant1DiscriminatorBranchReasonJsonConverter),
            typeof(global::G.JsonConverters.TransferToAgentToolResultSuccessModelBranchInfoVariant1DiscriminatorBranchReasonNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptSystemToolResultCommonModelOutputResultVariant1DiscriminatorResultTypeJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptSystemToolResultCommonModelOutputResultVariant1DiscriminatorResultTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowToolResponseModelOutputStepDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowToolResponseModelOutputStepDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UserFeedbackScoreJsonConverter),
            typeof(global::G.JsonConverters.UserFeedbackScoreNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatSourceMediumJsonConverter),
            typeof(global::G.JsonConverters.ChatSourceMediumNullableJsonConverter),
            typeof(global::G.JsonConverters.EvaluationSuccessResultJsonConverter),
            typeof(global::G.JsonConverters.EvaluationSuccessResultNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentSortByJsonConverter),
            typeof(global::G.JsonConverters.AgentSortByNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentTestEntityTypeJsonConverter),
            typeof(global::G.JsonConverters.AgentTestEntityTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowExpressionConditionModelOutputExpressionDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowExpressionConditionModelOutputExpressionDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowEdgeModelOutputForwardConditionVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowEdgeModelOutputForwardConditionVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowEdgeModelOutputBackwardConditionVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowEdgeModelOutputBackwardConditionVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowPhoneNumberNodeModelOutputCustomSipHeaderDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowPhoneNumberNodeModelOutputCustomSipHeaderDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowPhoneNumberNodeModelOutputTransferDestinationDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowPhoneNumberNodeModelOutputTransferDestinationDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowPhoneNumberNodeModelOutputPostDialDigitsVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowPhoneNumberNodeModelOutputPostDialDigitsVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentWorkflowResponseModelNodesDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.AgentWorkflowResponseModelNodesDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AllowedOutputFormatsJsonConverter),
            typeof(global::G.JsonConverters.AllowedOutputFormatsNullableJsonConverter),
            typeof(global::G.JsonConverters.AsyncConversationMetadataDeliveryStatusJsonConverter),
            typeof(global::G.JsonConverters.AsyncConversationMetadataDeliveryStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.AudioNativeProjectSettingsResponseModelStatusJsonConverter),
            typeof(global::G.JsonConverters.AudioNativeProjectSettingsResponseModelStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.AuthorizationMethodJsonConverter),
            typeof(global::G.JsonConverters.AuthorizationMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.TelephonyProviderJsonConverter),
            typeof(global::G.JsonConverters.TelephonyProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchCallStatusJsonConverter),
            typeof(global::G.JsonConverters.BatchCallStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchCallRecipientStatusJsonConverter),
            typeof(global::G.JsonConverters.BatchCallRecipientStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationInitiationSourceJsonConverter),
            typeof(global::G.JsonConverters.ConversationInitiationSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.BillingPeriodJsonConverter),
            typeof(global::G.JsonConverters.BillingPeriodNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess2JsonConverter),
            typeof(global::G.JsonConverters.BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromRulesPostWorkspaceAccess2JsonConverter),
            typeof(global::G.JsonConverters.BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromRulesPostWorkspaceAccess2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyAudioIsolationStreamV1AudioIsolationStreamPostFileFormat2JsonConverter),
            typeof(global::G.JsonConverters.BodyAudioIsolationStreamV1AudioIsolationStreamPostFileFormat2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyAudioIsolationV1AudioIsolationPostFileFormat2JsonConverter),
            typeof(global::G.JsonConverters.BodyAudioIsolationV1AudioIsolationPostFileFormat2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyComposeMusicWithADetailedResponseV1MusicDetailedPostModelIdJsonConverter),
            typeof(global::G.JsonConverters.BodyComposeMusicWithADetailedResponseV1MusicDetailedPostModelIdNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyComposeMusicV1MusicPostModelIdJsonConverter),
            typeof(global::G.JsonConverters.BodyComposeMusicV1MusicPostModelIdNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostQualityPresetJsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostQualityPresetNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostTargetAudience2JsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostTargetAudience2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostFiction2JsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostFiction2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostApplyTextNormalization2JsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostApplyTextNormalization2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostSourceType2JsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostSourceType2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1StudioPodcastsPostQualityPresetJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1StudioPodcastsPostQualityPresetNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1StudioPodcastsPostDurationScaleJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1StudioPodcastsPostDurationScaleNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1StudioPodcastsPostApplyTextNormalization2JsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1StudioPodcastsPostApplyTextNormalization2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatesAudioNativeEnabledProjectV1AudioNativePostApplyTextNormalization2JsonConverter),
            typeof(global::G.JsonConverters.BodyCreatesAudioNativeEnabledProjectV1AudioNativePostApplyTextNormalization2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyDubAVideoOrAnAudioFileV1DubbingPostModeJsonConverter),
            typeof(global::G.JsonConverters.BodyDubAVideoOrAnAudioFileV1DubbingPostModeNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyGenerateCompositionPlanV1MusicPlanPostModelIdJsonConverter),
            typeof(global::G.JsonConverters.BodyGenerateCompositionPlanV1MusicPlanPostModelIdNullableJsonConverter),
            typeof(global::G.JsonConverters.SeatTypeJsonConverter),
            typeof(global::G.JsonConverters.SeatTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyRegisterATwilioCallAndReturnTwiMLV1ConvaiTwilioRegisterCallPostDirectionJsonConverter),
            typeof(global::G.JsonConverters.BodyRegisterATwilioCallAndReturnTwiMLV1ConvaiTwilioRegisterCallPostDirectionNullableJsonConverter),
            typeof(global::G.JsonConverters.RenderType2JsonConverter),
            typeof(global::G.JsonConverters.RenderType2NullableJsonConverter),
            typeof(global::G.JsonConverters.WhatsAppTemplateHeaderComponentParamsParameterDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WhatsAppTemplateHeaderComponentParamsParameterDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BodySendAnOutboundMessageViaWhatsAppV1ConvaiWhatsappOutboundMessagePostTemplateParamDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.BodySendAnOutboundMessageViaWhatsAppV1ConvaiWhatsappOutboundMessagePostTemplateParamDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyShareWorkspaceResourceV1WorkspaceResourcesResourceIdSharePostRoleJsonConverter),
            typeof(global::G.JsonConverters.BodyShareWorkspaceResourceV1WorkspaceResourcesResourceIdSharePostRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkspaceResourceTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkspaceResourceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptCommonModelInputRoleJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptCommonModelInputRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptToolCallCommonModelInputToolDetailsVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptToolCallCommonModelInputToolDetailsVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptSystemToolResultCommonModelInputResultVariant1DiscriminatorResultTypeJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptSystemToolResultCommonModelInputResultVariant1DiscriminatorResultTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkflowToolResponseModelInputStepDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkflowToolResponseModelInputStepDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPostFileFormat2JsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPostFileFormat2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToSpeechV1SpeechToSpeechVoiceIdPostFileFormat2JsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToSpeechV1SpeechToSpeechVoiceIdPostFileFormat2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToTextV1SpeechToTextPostModelIdJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToTextV1SpeechToTextPostModelIdNullableJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToTextV1SpeechToTextPostTimestampsGranularityJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToTextV1SpeechToTextPostTimestampsGranularityNullableJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToTextV1SpeechToTextPostFileFormatJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToTextV1SpeechToTextPostFileFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyStemSeparationV1MusicStemSeparationPostStemVariationIdJsonConverter),
            typeof(global::G.JsonConverters.BodyStemSeparationV1MusicStemSeparationPostStemVariationIdNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyStreamComposedMusicV1MusicStreamPostModelIdJsonConverter),
            typeof(global::G.JsonConverters.BodyStreamComposedMusicV1MusicStreamPostModelIdNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToDialogueMultiVoiceStreamingV1TextToDialogueStreamPostApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToDialogueMultiVoiceStreamingV1TextToDialogueStreamPostApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToDialogueMultiVoiceV1TextToDialoguePostApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToDialogueMultiVoiceV1TextToDialoguePostApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.ChapterContentBlockInputModelSubType2JsonConverter),
            typeof(global::G.JsonConverters.ChapterContentBlockInputModelSubType2NullableJsonConverter),
            typeof(global::G.JsonConverters.PermissionTypeJsonConverter),
            typeof(global::G.JsonConverters.PermissionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToDialogueFullWithTimestampsApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToDialogueFullWithTimestampsApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToDialogueStreamWithTimestampsApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToDialogueStreamWithTimestampsApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechFullApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechFullApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechFullWithTimestampsApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechFullWithTimestampsApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechStreamApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechStreamApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechStreamWithTimestampsApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechStreamWithTimestampsApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.BreakdownTypesJsonConverter),
            typeof(global::G.JsonConverters.BreakdownTypesNullableJsonConverter),
            typeof(global::G.JsonConverters.ChapterResponseModelStateJsonConverter),
            typeof(global::G.JsonConverters.ChapterResponseModelStateNullableJsonConverter),
            typeof(global::G.JsonConverters.CharacterRefreshPeriodJsonConverter),
            typeof(global::G.JsonConverters.CharacterRefreshPeriodNullableJsonConverter),
            typeof(global::G.JsonConverters.ClipAnimationEnterEffectJsonConverter),
            typeof(global::G.JsonConverters.ClipAnimationEnterEffectNullableJsonConverter),
            typeof(global::G.JsonConverters.ClipAnimationExitEffectJsonConverter),
            typeof(global::G.JsonConverters.ClipAnimationExitEffectNullableJsonConverter),
            typeof(global::G.JsonConverters.DependentAvailableToolIdentifierAccessLevelJsonConverter),
            typeof(global::G.JsonConverters.DependentAvailableToolIdentifierAccessLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.ConvAIStoredSecretDependenciesToolDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ConvAIStoredSecretDependenciesToolDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DependentAvailableAgentIdentifierAccessLevelJsonConverter),
            typeof(global::G.JsonConverters.DependentAvailableAgentIdentifierAccessLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.ConvAIStoredSecretDependenciesAgentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ConvAIStoredSecretDependenciesAgentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SecretDependencyTypeJsonConverter),
            typeof(global::G.JsonConverters.SecretDependencyTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationFeedbackTypeJsonConverter),
            typeof(global::G.JsonConverters.ConversationFeedbackTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTwilioPhoneCallModelDirectionJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTwilioPhoneCallModelDirectionNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistorySIPTrunkingPhoneCallModelDirectionJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistorySIPTrunkingPhoneCallModelDirectionNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryMetadataCommonModelPhoneCallVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryMetadataCommonModelPhoneCallVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WhatsAppConversationInfoDirectionJsonConverter),
            typeof(global::G.JsonConverters.WhatsAppConversationInfoDirectionNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptCommonModelOutputRoleJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptCommonModelOutputRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationSummaryResponseModelStatusJsonConverter),
            typeof(global::G.JsonConverters.ConversationSummaryResponseModelStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationSummaryResponseModelDirection2JsonConverter),
            typeof(global::G.JsonConverters.ConversationSummaryResponseModelDirection2NullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationTokenPurposeJsonConverter),
            typeof(global::G.JsonConverters.ConversationTokenPurposeNullableJsonConverter),
            typeof(global::G.JsonConverters.SIPMediaEncryptionEnumJsonConverter),
            typeof(global::G.JsonConverters.SIPMediaEncryptionEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.SIPTrunkTransportEnumJsonConverter),
            typeof(global::G.JsonConverters.SIPTrunkTransportEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.UnitTestToolCallParameterEvalDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.UnitTestToolCallParameterEvalDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ReferencedToolCommonModelTypeJsonConverter),
            typeof(global::G.JsonConverters.ReferencedToolCommonModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TwilioRegionIdJsonConverter),
            typeof(global::G.JsonConverters.TwilioRegionIdNullableJsonConverter),
            typeof(global::G.JsonConverters.TwilioEdgeLocationJsonConverter),
            typeof(global::G.JsonConverters.TwilioEdgeLocationNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkspaceGroupPermissionJsonConverter),
            typeof(global::G.JsonConverters.WorkspaceGroupPermissionNullableJsonConverter),
            typeof(global::G.JsonConverters.DefaultSharingGroupResponseModelPermissionLevelJsonConverter),
            typeof(global::G.JsonConverters.DefaultSharingGroupResponseModelPermissionLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.DirectPublishingReadResponseModelDisplayMode2JsonConverter),
            typeof(global::G.JsonConverters.DirectPublishingReadResponseModelDisplayMode2NullableJsonConverter),
            typeof(global::G.JsonConverters.DirectPublishingReadResponseModelGenreVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.DirectPublishingReadResponseModelGenreVariant1ItemNullableJsonConverter),
            typeof(global::G.JsonConverters.DirectPublishingReadResponseModelTargetAudience2JsonConverter),
            typeof(global::G.JsonConverters.DirectPublishingReadResponseModelTargetAudience2NullableJsonConverter),
            typeof(global::G.JsonConverters.DirectPublishingReadResponseModelPayoutType2JsonConverter),
            typeof(global::G.JsonConverters.DirectPublishingReadResponseModelPayoutType2NullableJsonConverter),
            typeof(global::G.JsonConverters.SampleConfigDBModelParentType2JsonConverter),
            typeof(global::G.JsonConverters.SampleConfigDBModelParentType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ReviewResponseModelReviewStatusJsonConverter),
            typeof(global::G.JsonConverters.ReviewResponseModelReviewStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ReviewResponseModelRejectReasonsVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.ReviewResponseModelRejectReasonsVariant1ItemNullableJsonConverter),
            typeof(global::G.JsonConverters.DubbingModelJsonConverter),
            typeof(global::G.JsonConverters.DubbingModelNullableJsonConverter),
            typeof(global::G.JsonConverters.RenderStatusJsonConverter),
            typeof(global::G.JsonConverters.RenderStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.DubbingTranscriptsResponseModelTranscriptFormatJsonConverter),
            typeof(global::G.JsonConverters.DubbingTranscriptsResponseModelTranscriptFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.ExtendedSubscriptionResponseModelCurrency2JsonConverter),
            typeof(global::G.JsonConverters.ExtendedSubscriptionResponseModelCurrency2NullableJsonConverter),
            typeof(global::G.JsonConverters.SubscriptionStatusTypeJsonConverter),
            typeof(global::G.JsonConverters.SubscriptionStatusTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.InvoiceResponseModelPaymentIntentStatus2JsonConverter),
            typeof(global::G.JsonConverters.InvoiceResponseModelPaymentIntentStatus2NullableJsonConverter),
            typeof(global::G.JsonConverters.InvoiceResponseModelPaymentIntentStatusseJsonConverter),
            typeof(global::G.JsonConverters.InvoiceResponseModelPaymentIntentStatusseNullableJsonConverter),
            typeof(global::G.JsonConverters.PendingSubscriptionSwitchResponseModelNextTierJsonConverter),
            typeof(global::G.JsonConverters.PendingSubscriptionSwitchResponseModelNextTierNullableJsonConverter),
            typeof(global::G.JsonConverters.FineTuningResponseModelState2JsonConverter),
            typeof(global::G.JsonConverters.FineTuningResponseModelState2NullableJsonConverter),
            typeof(global::G.JsonConverters.StudioClipReferenceClipTypeJsonConverter),
            typeof(global::G.JsonConverters.StudioClipReferenceClipTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WidgetConfigResponseModelSyntaxHighlightTheme2JsonConverter),
            typeof(global::G.JsonConverters.WidgetConfigResponseModelSyntaxHighlightTheme2NullableJsonConverter),
            typeof(global::G.JsonConverters.LivekitStackTypeJsonConverter),
            typeof(global::G.JsonConverters.LivekitStackTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetAgentResponseModelPhoneNumberDiscriminatorProviderJsonConverter),
            typeof(global::G.JsonConverters.GetAgentResponseModelPhoneNumberDiscriminatorProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.GetConvAIDashboardSettingsResponseModelChartDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetConvAIDashboardSettingsResponseModelChartDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetConversationResponseModelStatusJsonConverter),
            typeof(global::G.JsonConverters.GetConversationResponseModelStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseDependentAgentsResponseModelAgentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseDependentAgentsResponseModelAgentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryURLResponseModelDependentAgentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryURLResponseModelDependentAgentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryFileResponseModelDependentAgentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryFileResponseModelDependentAgentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryTextResponseModelDependentAgentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryTextResponseModelDependentAgentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryFolderResponseModelDependentAgentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryFolderResponseModelDependentAgentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseListResponseModelDocumentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseListResponseModelDocumentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LibraryVoiceResponseModelCategoryJsonConverter),
            typeof(global::G.JsonConverters.LibraryVoiceResponseModelCategoryNullableJsonConverter),
            typeof(global::G.JsonConverters.GetPronunciationDictionaryMetadataResponseModelPermissionOnResource2JsonConverter),
            typeof(global::G.JsonConverters.GetPronunciationDictionaryMetadataResponseModelPermissionOnResource2NullableJsonConverter),
            typeof(global::G.JsonConverters.GetPronunciationDictionaryWithRulesResponseModelPermissionOnResource2JsonConverter),
            typeof(global::G.JsonConverters.GetPronunciationDictionaryWithRulesResponseModelPermissionOnResource2NullableJsonConverter),
            typeof(global::G.JsonConverters.SpeechHistoryItemResponseModelVoiceCategory2JsonConverter),
            typeof(global::G.JsonConverters.SpeechHistoryItemResponseModelVoiceCategory2NullableJsonConverter),
            typeof(global::G.JsonConverters.SpeechHistoryItemResponseModelStateJsonConverter),
            typeof(global::G.JsonConverters.SpeechHistoryItemResponseModelStateNullableJsonConverter),
            typeof(global::G.JsonConverters.SpeechHistoryItemResponseModelSource2JsonConverter),
            typeof(global::G.JsonConverters.SpeechHistoryItemResponseModelSource2NullableJsonConverter),
            typeof(global::G.JsonConverters.UnitTestRunResponseModelTestInfoVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.UnitTestRunResponseModelTestInfoVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TestRunStatusJsonConverter),
            typeof(global::G.JsonConverters.TestRunStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.TestRunMetadataTestTypeJsonConverter),
            typeof(global::G.JsonConverters.TestRunMetadataTestTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TestTypeJsonConverter),
            typeof(global::G.JsonConverters.TestTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetToolDependentAgentsResponseModelAgentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetToolDependentAgentsResponseModelAgentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SpeakerSeparationResponseModelStatusJsonConverter),
            typeof(global::G.JsonConverters.SpeakerSeparationResponseModelStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.VoiceResponseModelCategoryJsonConverter),
            typeof(global::G.JsonConverters.VoiceResponseModelCategoryNullableJsonConverter),
            typeof(global::G.JsonConverters.VoiceSharingResponseModelStatusJsonConverter),
            typeof(global::G.JsonConverters.VoiceSharingResponseModelStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.VoiceSharingResponseModelCategoryJsonConverter),
            typeof(global::G.JsonConverters.VoiceSharingResponseModelCategoryNullableJsonConverter),
            typeof(global::G.JsonConverters.VoiceSharingResponseModelReviewStatusJsonConverter),
            typeof(global::G.JsonConverters.VoiceSharingResponseModelReviewStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ReaderResourceResponseModelResourceTypeJsonConverter),
            typeof(global::G.JsonConverters.ReaderResourceResponseModelResourceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.VoiceResponseModelSafetyControl2JsonConverter),
            typeof(global::G.JsonConverters.VoiceResponseModelSafetyControl2NullableJsonConverter),
            typeof(global::G.JsonConverters.KnowledgeBaseDependentTypeJsonConverter),
            typeof(global::G.JsonConverters.KnowledgeBaseDependentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.KnowledgeBaseSortByJsonConverter),
            typeof(global::G.JsonConverters.KnowledgeBaseSortByNullableJsonConverter),
            typeof(global::G.JsonConverters.KnowledgeBaseSummaryBatchSuccessfulResponseModelDataDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.KnowledgeBaseSummaryBatchSuccessfulResponseModelDataDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MCPToolApprovalPolicyJsonConverter),
            typeof(global::G.JsonConverters.MCPToolApprovalPolicyNullableJsonConverter),
            typeof(global::G.JsonConverters.MCPServerTransportJsonConverter),
            typeof(global::G.JsonConverters.MCPServerTransportNullableJsonConverter),
            typeof(global::G.JsonConverters.MCPToolConfigOverrideInputOverridesDiscriminatorSourceJsonConverter),
            typeof(global::G.JsonConverters.MCPToolConfigOverrideInputOverridesDiscriminatorSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.MCPServerResponseModelDependentAgentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MCPServerResponseModelDependentAgentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MCPToolConfigOverrideCreateRequestModelInputOverridesDiscriminatorSourceJsonConverter),
            typeof(global::G.JsonConverters.MCPToolConfigOverrideCreateRequestModelInputOverridesDiscriminatorSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.MCPToolConfigOverrideUpdateRequestModelInputOverridesDiscriminatorSourceJsonConverter),
            typeof(global::G.JsonConverters.MCPToolConfigOverrideUpdateRequestModelInputOverridesDiscriminatorSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.MergingStrategyJsonConverter),
            typeof(global::G.JsonConverters.MergingStrategyNullableJsonConverter),
            typeof(global::G.JsonConverters.MetricTypeJsonConverter),
            typeof(global::G.JsonConverters.MetricTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SpeechToTextWordResponseModelTypeJsonConverter),
            typeof(global::G.JsonConverters.SpeechToTextWordResponseModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.NonStreamingOutputFormatsJsonConverter),
            typeof(global::G.JsonConverters.NonStreamingOutputFormatsNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchConvAIDashboardSettingsRequestChartDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PatchConvAIDashboardSettingsRequestChartDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PendingClipTaskTypeJsonConverter),
            typeof(global::G.JsonConverters.PendingClipTaskTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelTargetAudience2JsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelTargetAudience2NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelStateJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelStateNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelAccessLevelJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelAccessLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelFiction2JsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelFiction2NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelSourceType2JsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelSourceType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelAspectRatio2JsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelAspectRatio2NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelQualityPresetJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelQualityPresetNullableJsonConverter),
            typeof(global::G.JsonConverters.PronunciationDictionaryVersionResponseModelPermissionOnResource2JsonConverter),
            typeof(global::G.JsonConverters.PronunciationDictionaryVersionResponseModelPermissionOnResource2NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExternalAudioResponseModelSourceContextVariant1DiscriminatorSourceTypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectExternalAudioResponseModelSourceContextVariant1DiscriminatorSourceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.RAGIndexStatusJsonConverter),
            typeof(global::G.JsonConverters.RAGIndexStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ResourceMetadataResponseModelAnonymousAccessLevelOverride2JsonConverter),
            typeof(global::G.JsonConverters.ResourceMetadataResponseModelAnonymousAccessLevelOverride2NullableJsonConverter),
            typeof(global::G.JsonConverters.ShareOptionResponseModelTypeJsonConverter),
            typeof(global::G.JsonConverters.ShareOptionResponseModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SafetyRuleJsonConverter),
            typeof(global::G.JsonConverters.SafetyRuleNullableJsonConverter),
            typeof(global::G.JsonConverters.VoiceCategoryJsonConverter),
            typeof(global::G.JsonConverters.VoiceCategoryNullableJsonConverter),
            typeof(global::G.JsonConverters.SingleUseTokenTypeJsonConverter),
            typeof(global::G.JsonConverters.SingleUseTokenTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SortDirectionJsonConverter),
            typeof(global::G.JsonConverters.SortDirectionNullableJsonConverter),
            typeof(global::G.JsonConverters.SubscriptionResponseModelCurrency2JsonConverter),
            typeof(global::G.JsonConverters.SubscriptionResponseModelCurrency2NullableJsonConverter),
            typeof(global::G.JsonConverters.ToolRequestModelToolConfigDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolRequestModelToolConfigDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolResponseModelToolConfigDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolResponseModelToolConfigDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolSortByJsonConverter),
            typeof(global::G.JsonConverters.ToolSortByNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolTypeFilterJsonConverter),
            typeof(global::G.JsonConverters.ToolTypeFilterNullableJsonConverter),
            typeof(global::G.JsonConverters.TurnModelJsonConverter),
            typeof(global::G.JsonConverters.TurnModelNullableJsonConverter),
            typeof(global::G.JsonConverters.UsageAggregationIntervalJsonConverter),
            typeof(global::G.JsonConverters.UsageAggregationIntervalNullableJsonConverter),
            typeof(global::G.JsonConverters.VoiceDesignRequestModelModelIdJsonConverter),
            typeof(global::G.JsonConverters.VoiceDesignRequestModelModelIdNullableJsonConverter),
            typeof(global::G.JsonConverters.WebhookAuthMethodTypeJsonConverter),
            typeof(global::G.JsonConverters.WebhookAuthMethodTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WebhookUsageTypeJsonConverter),
            typeof(global::G.JsonConverters.WebhookUsageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetSpeechHistorySortDirection2JsonConverter),
            typeof(global::G.JsonConverters.GetSpeechHistorySortDirection2NullableJsonConverter),
            typeof(global::G.JsonConverters.GetSpeechHistorySource2JsonConverter),
            typeof(global::G.JsonConverters.GetSpeechHistorySource2NullableJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechFullOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechFullOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechFullWithTimestampsOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechFullWithTimestampsOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechStreamOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechStreamOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechStreamWithTimestampsOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechStreamWithTimestampsOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.SpeechToSpeechFullOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.SpeechToSpeechFullOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.SpeechToSpeechStreamOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.SpeechToSpeechStreamOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.ListDubsDubbingStatusJsonConverter),
            typeof(global::G.JsonConverters.ListDubsDubbingStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ListDubsFilterByCreatorJsonConverter),
            typeof(global::G.JsonConverters.ListDubsFilterByCreatorNullableJsonConverter),
            typeof(global::G.JsonConverters.ListDubsOrderDirectionJsonConverter),
            typeof(global::G.JsonConverters.ListDubsOrderDirectionNullableJsonConverter),
            typeof(global::G.JsonConverters.GetDubbedTranscriptFileFormatTypeJsonConverter),
            typeof(global::G.JsonConverters.GetDubbedTranscriptFileFormatTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetDubbingTranscriptsFormatTypeJsonConverter),
            typeof(global::G.JsonConverters.GetDubbingTranscriptsFormatTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetPronunciationDictionariesMetadataSort2JsonConverter),
            typeof(global::G.JsonConverters.GetPronunciationDictionariesMetadataSort2NullableJsonConverter),
            typeof(global::G.JsonConverters.ListChatResponseTestsRouteSortModeJsonConverter),
            typeof(global::G.JsonConverters.ListChatResponseTestsRouteSortModeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetConversationHistoriesRouteSummaryModeJsonConverter),
            typeof(global::G.JsonConverters.GetConversationHistoriesRouteSummaryModeNullableJsonConverter),
            typeof(global::G.JsonConverters.TextSearchConversationMessagesRouteSummaryModeJsonConverter),
            typeof(global::G.JsonConverters.TextSearchConversationMessagesRouteSummaryModeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetAgentSummariesRouteResponseDiscriminatorStatusJsonConverter),
            typeof(global::G.JsonConverters.GetAgentSummariesRouteResponseDiscriminatorStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetAgentResponseTestRouteResponseDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetAgentResponseTestRouteResponseDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UpdateAgentResponseTestRouteResponseDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.UpdateAgentResponseTestRouteResponseDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListPhoneNumbersRouteResponseItemDiscriminatorProviderJsonConverter),
            typeof(global::G.JsonConverters.ListPhoneNumbersRouteResponseItemDiscriminatorProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.GetPhoneNumberRouteResponseDiscriminatorProviderJsonConverter),
            typeof(global::G.JsonConverters.GetPhoneNumberRouteResponseDiscriminatorProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.UpdatePhoneNumberRouteResponseDiscriminatorProviderJsonConverter),
            typeof(global::G.JsonConverters.UpdatePhoneNumberRouteResponseDiscriminatorProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.GetAgentKnowledgeBaseSummariesRouteResponseDiscriminatorStatusJsonConverter),
            typeof(global::G.JsonConverters.GetAgentKnowledgeBaseSummariesRouteResponseDiscriminatorStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.UpdateDocumentRouteResponseDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.UpdateDocumentRouteResponseDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetDocumentationFromKnowledgeBaseResponseDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetDocumentationFromKnowledgeBaseResponseDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetOrCreateRagIndexesResponseDiscriminatorStatusJsonConverter),
            typeof(global::G.JsonConverters.GetOrCreateRagIndexesResponseDiscriminatorStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ChildrenItemJsonConverter),
            typeof(global::G.JsonConverters.ChildrenItem3JsonConverter),
            typeof(global::G.JsonConverters.LeftJsonConverter),
            typeof(global::G.JsonConverters.Left11JsonConverter),
            typeof(global::G.JsonConverters.Left3JsonConverter),
            typeof(global::G.JsonConverters.Left7JsonConverter),
            typeof(global::G.JsonConverters.Right7JsonConverter),
            typeof(global::G.JsonConverters.Right3JsonConverter),
            typeof(global::G.JsonConverters.Right11JsonConverter),
            typeof(global::G.JsonConverters.RightJsonConverter),
            typeof(global::G.JsonConverters.Left5JsonConverter),
            typeof(global::G.JsonConverters.Right5JsonConverter),
            typeof(global::G.JsonConverters.Left9JsonConverter),
            typeof(global::G.JsonConverters.Right9JsonConverter),
            typeof(global::G.JsonConverters.ChildrenItem2JsonConverter),
            typeof(global::G.JsonConverters.ChildrenItem4JsonConverter),
            typeof(global::G.JsonConverters.Left2JsonConverter),
            typeof(global::G.JsonConverters.Left12JsonConverter),
            typeof(global::G.JsonConverters.Left4JsonConverter),
            typeof(global::G.JsonConverters.Left8JsonConverter),
            typeof(global::G.JsonConverters.Right8JsonConverter),
            typeof(global::G.JsonConverters.Right4JsonConverter),
            typeof(global::G.JsonConverters.Right12JsonConverter),
            typeof(global::G.JsonConverters.Right2JsonConverter),
            typeof(global::G.JsonConverters.Left6JsonConverter),
            typeof(global::G.JsonConverters.Right6JsonConverter),
            typeof(global::G.JsonConverters.Left10JsonConverter),
            typeof(global::G.JsonConverters.Right10JsonConverter),
            typeof(global::G.JsonConverters.ExportOptionsJsonConverter),
            typeof(global::G.JsonConverters.Params2JsonConverter),
            typeof(global::G.JsonConverters.CustomSipHeadersItemJsonConverter),
            typeof(global::G.JsonConverters.TransferDestinationVariant1JsonConverter),
            typeof(global::G.JsonConverters.PostDialDigitsVariant1JsonConverter),
            typeof(global::G.JsonConverters.BackupLlmConfigJsonConverter),
            typeof(global::G.JsonConverters.ToolsItem2JsonConverter),
            typeof(global::G.JsonConverters.InputOverridesVariant1JsonConverter),
            typeof(global::G.JsonConverters.SchemaOverridesVariant1JsonConverter),
            typeof(global::G.JsonConverters.ParamsJsonConverter),
            typeof(global::G.JsonConverters.ForwardConditionVariant1JsonConverter),
            typeof(global::G.JsonConverters.ExpressionJsonConverter),
            typeof(global::G.JsonConverters.BackwardConditionVariant1JsonConverter),
            typeof(global::G.JsonConverters.NodesJsonConverter),
            typeof(global::G.JsonConverters.CustomSipHeadersItem2JsonConverter),
            typeof(global::G.JsonConverters.TransferDestinationJsonConverter),
            typeof(global::G.JsonConverters.PostDialDigitsVariant12JsonConverter),
            typeof(global::G.JsonConverters.ToolsVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.Params3JsonConverter),
            typeof(global::G.JsonConverters.BackupLlmConfig2JsonConverter),
            typeof(global::G.JsonConverters.ToolsItem3JsonConverter),
            typeof(global::G.JsonConverters.InputOverridesVariant12JsonConverter),
            typeof(global::G.JsonConverters.SchemaOverridesVariant12JsonConverter),
            typeof(global::G.JsonConverters.ToolsVariant1Item2JsonConverter),
            typeof(global::G.JsonConverters.ToolDetailsVariant12JsonConverter),
            typeof(global::G.JsonConverters.ResultVariant12JsonConverter),
            typeof(global::G.JsonConverters.BranchInfoVariant1JsonConverter),
            typeof(global::G.JsonConverters.StepsItem2JsonConverter),
            typeof(global::G.JsonConverters.ForwardConditionVariant12JsonConverter),
            typeof(global::G.JsonConverters.Expression2JsonConverter),
            typeof(global::G.JsonConverters.BackwardConditionVariant12JsonConverter),
            typeof(global::G.JsonConverters.Nodes2JsonConverter),
            typeof(global::G.JsonConverters.CustomSipHeadersItem3JsonConverter),
            typeof(global::G.JsonConverters.TransferDestination2JsonConverter),
            typeof(global::G.JsonConverters.PostDialDigitsVariant13JsonConverter),
            typeof(global::G.JsonConverters.TemplateParamsItemJsonConverter),
            typeof(global::G.JsonConverters.ParametersItemJsonConverter),
            typeof(global::G.JsonConverters.ToolDetailsVariant1JsonConverter),
            typeof(global::G.JsonConverters.ResultVariant1JsonConverter),
            typeof(global::G.JsonConverters.StepsItemJsonConverter),
            typeof(global::G.JsonConverters.ToolsItemJsonConverter),
            typeof(global::G.JsonConverters.AgentsItemJsonConverter),
            typeof(global::G.JsonConverters.PhoneCallVariant1JsonConverter),
            typeof(global::G.JsonConverters.EvalJsonConverter),
            typeof(global::G.JsonConverters.PhoneNumbersItemJsonConverter),
            typeof(global::G.JsonConverters.ChartsItemJsonConverter),
            typeof(global::G.JsonConverters.AgentsItem2JsonConverter),
            typeof(global::G.JsonConverters.DocumentsItemJsonConverter),
            typeof(global::G.JsonConverters.DependentAgentsItem4JsonConverter),
            typeof(global::G.JsonConverters.DependentAgentsItemJsonConverter),
            typeof(global::G.JsonConverters.DependentAgentsItem3JsonConverter),
            typeof(global::G.JsonConverters.DependentAgentsItem2JsonConverter),
            typeof(global::G.JsonConverters.TestInfoVariant1JsonConverter),
            typeof(global::G.JsonConverters.AgentsItem3JsonConverter),
            typeof(global::G.JsonConverters.DataJsonConverter),
            typeof(global::G.JsonConverters.InputOverridesVariant13JsonConverter),
            typeof(global::G.JsonConverters.DependentAgentsItem5JsonConverter),
            typeof(global::G.JsonConverters.InputOverridesVariant14JsonConverter),
            typeof(global::G.JsonConverters.InputOverridesVariant15JsonConverter),
            typeof(global::G.JsonConverters.ChartsItem2JsonConverter),
            typeof(global::G.JsonConverters.SourceContextVariant1JsonConverter),
            typeof(global::G.JsonConverters.ToolConfigJsonConverter),
            typeof(global::G.JsonConverters.ToolConfig2JsonConverter),
            typeof(global::G.JsonConverters.GetAgentSummariesRouteResponse2JsonConverter),
            typeof(global::G.JsonConverters.GetAgentResponseTestRouteResponseJsonConverter),
            typeof(global::G.JsonConverters.UpdateAgentResponseTestRouteResponseJsonConverter),
            typeof(global::G.JsonConverters.ListPhoneNumbersRouteResponseItemJsonConverter),
            typeof(global::G.JsonConverters.GetPhoneNumberRouteResponseJsonConverter),
            typeof(global::G.JsonConverters.UpdatePhoneNumberRouteResponseJsonConverter),
            typeof(global::G.JsonConverters.GetAgentKnowledgeBaseSummariesRouteResponse2JsonConverter),
            typeof(global::G.JsonConverters.UpdateDocumentRouteResponseJsonConverter),
            typeof(global::G.JsonConverters.GetDocumentationFromKnowledgeBaseResponseJsonConverter),
            typeof(global::G.JsonConverters.GetOrCreateRagIndexesResponse2JsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ChapterContentBlockTtsNodeResponseModel, global::G.ChapterContentBlockExtendableNodeResponseModel>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator, global::G.ConvAIDynamicVariable>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator, global::G.ConvAIDynamicVariable>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?, double?, bool?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.LiteralJsonSchemaProperty, global::G.ObjectJsonSchemaPropertyInput, global::G.ArrayJsonSchemaPropertyInput>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.LiteralJsonSchemaProperty, global::G.ObjectJsonSchemaPropertyInput, global::G.ArrayJsonSchemaPropertyInput>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?, double?, bool?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.LiteralOverride, global::G.ObjectOverrideInput>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAIDynamicVariable>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.OrbAvatar, global::G.URLAvatar, global::G.ImageAvatar>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.BackupLLMDefault, global::G.BackupLLMDisabled, global::G.BackupLLMOverride, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator, global::G.ConvAIDynamicVariable>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.LiteralJsonSchemaProperty, global::G.ObjectJsonSchemaPropertyOutput, global::G.ArrayJsonSchemaPropertyOutput>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.LiteralJsonSchemaProperty, global::G.ObjectJsonSchemaPropertyOutput, global::G.ArrayJsonSchemaPropertyOutput>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.LiteralOverride, global::G.ObjectOverrideOutput>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAIDynamicVariable>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.BackupLLMDefault, global::G.BackupLLMDisabled, global::G.BackupLLMOverride, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.OrbAvatar, global::G.URLAvatar, global::G.ImageAvatar>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ConversationHistoryTranscriptOtherToolsResultCommonModel, global::G.ConversationHistoryTranscriptSystemToolResultCommonModelOutput, global::G.ConversationHistoryTranscriptApiIntegrationWebhookToolsResultCommonModel, global::G.ConversationHistoryTranscriptWorkflowToolsResultCommonModelOutput>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ConversationHistoryTranscriptOtherToolsResultCommonModel, global::G.ConversationHistoryTranscriptSystemToolResultCommonModelOutput, global::G.ConversationHistoryTranscriptApiIntegrationWebhookToolsResultCommonModel, global::G.ConversationHistoryTranscriptWorkflowToolsResultCommonModelOutput>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PronunciationDictionaryAliasRuleRequestModel, global::G.PronunciationDictionaryPhonemeRuleRequestModel>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PronunciationDictionaryAliasRuleRequestModel, global::G.PronunciationDictionaryPhonemeRuleRequestModel>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.Dictionary<string, string>, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PodcastConversationMode, global::G.PodcastBulletinMode>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PodcastTextSource, global::G.PodcastURLSource, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.PodcastTextSource, global::G.PodcastURLSource>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PodcastTextSource, global::G.PodcastURLSource>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.Dictionary<string, string>, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PronunciationDictionaryAliasRuleRequestModel, global::G.PronunciationDictionaryPhonemeRuleRequestModel>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ConversationHistoryTranscriptOtherToolsResultCommonModel, global::G.ConversationHistoryTranscriptSystemToolResultCommonModelInput, global::G.ConversationHistoryTranscriptApiIntegrationWebhookToolsResultCommonModel, global::G.ConversationHistoryTranscriptWorkflowToolsResultCommonModelInput>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ConversationHistoryTranscriptOtherToolsResultCommonModel, global::G.ConversationHistoryTranscriptSystemToolResultCommonModelInput, global::G.ConversationHistoryTranscriptApiIntegrationWebhookToolsResultCommonModel, global::G.ConversationHistoryTranscriptWorkflowToolsResultCommonModelInput>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.PermissionType>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.PermissionType>, string>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ConversationHistoryTranscriptOtherToolsResultCommonModel, global::G.ConversationHistoryTranscriptSystemToolResultCommonModelOutput, global::G.ConversationHistoryTranscriptApiIntegrationWebhookToolsResultCommonModel, global::G.ConversationHistoryTranscriptWorkflowToolsResultCommonModelOutput>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PendingSubscriptionSwitchResponseModel, global::G.PendingCancellationResponseModel, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.OrbAvatar, global::G.URLAvatar, global::G.ImageAvatar>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PronunciationDictionaryAliasRuleResponseModel, global::G.PronunciationDictionaryPhonemeRuleResponseModel>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConvAISecretLocator, global::G.ConvAIUserSecretDBModel, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator, global::G.ConvAIDynamicVariable>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConvAISecretLocator, global::G.ConvAIUserSecretDBModel, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator, global::G.ConvAIDynamicVariable>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator, global::G.ConvAIDynamicVariable>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ProjectVideoResponseModel, global::G.ProjectExternalAudioResponseModel, global::G.ProjectImageResponseModel>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.CreateResponseUnitTestRequest, global::G.CreateToolCallUnitTestRequest, global::G.CreateSimulationTestRequest>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.UpdateResponseUnitTestRequest, global::G.UpdateToolCallUnitTestRequest, global::G.UpdateSimulationTestRequest>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.CreateTwilioPhoneNumberRequest, global::G.CreateSIPTrunkPhoneNumberRequestV2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.NonStreamingOutputFormats?, global::G.AllowedOutputFormats?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.NonStreamingOutputFormats?, global::G.AllowedOutputFormats?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.DubbingTranscriptResponseModel, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SpeechToTextChunkResponseModel, global::G.MultichannelSpeechToTextResponseModel, global::G.SpeechToTextWebhookResponseModel, global::G.SpeechToTextChunkResponseModel, global::G.MultichannelSpeechToTextResponseModel>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SpeechToTextChunkResponseModel, global::G.MultichannelSpeechToTextResponseModel, global::G.SpeechToTextChunkResponseModel, global::G.MultichannelSpeechToTextResponseModel>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}