//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.ASRQualityJsonConverter),
            typeof(global::G.JsonConverters.ASRQualityNullableJsonConverter),
            typeof(global::G.JsonConverters.ASRProviderJsonConverter),
            typeof(global::G.JsonConverters.ASRProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.ASRInputFormatJsonConverter),
            typeof(global::G.JsonConverters.ASRInputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.ChapterWithContentResponseModelStateJsonConverter),
            typeof(global::G.JsonConverters.ChapterWithContentResponseModelStateNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelTargetAudience2JsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelTargetAudience2NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelStateJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelStateNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelAccessLevelJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelAccessLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelFiction2JsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelFiction2NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectCreationMetaResponseModelStatusJsonConverter),
            typeof(global::G.JsonConverters.ProjectCreationMetaResponseModelStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectCreationMetaResponseModelTypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectCreationMetaResponseModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelSourceType2JsonConverter),
            typeof(global::G.JsonConverters.ProjectResponseModelSourceType2NullableJsonConverter),
            typeof(global::G.JsonConverters.AddPronunciationDictionaryResponseModelPermissionOnResource2JsonConverter),
            typeof(global::G.JsonConverters.AddPronunciationDictionaryResponseModelPermissionOnResource2NullableJsonConverter),
            typeof(global::G.JsonConverters.ExportOptionsDiscriminatorFormatJsonConverter),
            typeof(global::G.JsonConverters.ExportOptionsDiscriminatorFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.BanReasonTypeJsonConverter),
            typeof(global::G.JsonConverters.BanReasonTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LLMJsonConverter),
            typeof(global::G.JsonConverters.LLMNullableJsonConverter),
            typeof(global::G.JsonConverters.WebhookToolApiSchemaConfigInputMethodJsonConverter),
            typeof(global::G.JsonConverters.WebhookToolApiSchemaConfigInputMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.LiteralJsonSchemaPropertyTypeJsonConverter),
            typeof(global::G.JsonConverters.LiteralJsonSchemaPropertyTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SystemToolConfigInputParamsDiscriminatorSystemToolTypeJsonConverter),
            typeof(global::G.JsonConverters.SystemToolConfigInputParamsDiscriminatorSystemToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IntegrationTypeJsonConverter),
            typeof(global::G.JsonConverters.IntegrationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MCPApprovalPolicyJsonConverter),
            typeof(global::G.JsonConverters.MCPApprovalPolicyNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentInputToolDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentInputToolDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.KnowledgeBaseDocumentTypeJsonConverter),
            typeof(global::G.JsonConverters.KnowledgeBaseDocumentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DocumentUsageModeEnumJsonConverter),
            typeof(global::G.JsonConverters.DocumentUsageModeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingModelEnumJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingModelEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.WebhookToolApiSchemaConfigOutputMethodJsonConverter),
            typeof(global::G.JsonConverters.WebhookToolApiSchemaConfigOutputMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.SystemToolConfigOutputParamsDiscriminatorSystemToolTypeJsonConverter),
            typeof(global::G.JsonConverters.SystemToolConfigOutputParamsDiscriminatorSystemToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentOutputToolDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentOutputToolDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentDBModelToolDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptAgentDBModelToolDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbedVariantJsonConverter),
            typeof(global::G.JsonConverters.EmbedVariantNullableJsonConverter),
            typeof(global::G.JsonConverters.WidgetPlacementJsonConverter),
            typeof(global::G.JsonConverters.WidgetPlacementNullableJsonConverter),
            typeof(global::G.JsonConverters.WidgetExpandableJsonConverter),
            typeof(global::G.JsonConverters.WidgetExpandableNullableJsonConverter),
            typeof(global::G.JsonConverters.WidgetFeedbackModeJsonConverter),
            typeof(global::G.JsonConverters.WidgetFeedbackModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptCommonModelOutputRoleJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptCommonModelOutputRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptToolCallCommonModelToolDetailsVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptToolCallCommonModelToolDetailsVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UserFeedbackScoreJsonConverter),
            typeof(global::G.JsonConverters.UserFeedbackScoreNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptCommonModelOutputSourceMedium2JsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptCommonModelOutputSourceMedium2NullableJsonConverter),
            typeof(global::G.JsonConverters.EvaluationSuccessResultJsonConverter),
            typeof(global::G.JsonConverters.EvaluationSuccessResultNullableJsonConverter),
            typeof(global::G.JsonConverters.ResourceAccessInfoRoleJsonConverter),
            typeof(global::G.JsonConverters.ResourceAccessInfoRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.AudioNativeProjectSettingsResponseModelStatusJsonConverter),
            typeof(global::G.JsonConverters.AudioNativeProjectSettingsResponseModelStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.AuthorizationMethodJsonConverter),
            typeof(global::G.JsonConverters.AuthorizationMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.TelephonyProviderJsonConverter),
            typeof(global::G.JsonConverters.TelephonyProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchCallStatusJsonConverter),
            typeof(global::G.JsonConverters.BatchCallStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchCallRecipientStatusJsonConverter),
            typeof(global::G.JsonConverters.BatchCallRecipientStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess2JsonConverter),
            typeof(global::G.JsonConverters.BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromFilePostWorkspaceAccess2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromRulesPostWorkspaceAccess2JsonConverter),
            typeof(global::G.JsonConverters.BodyAddAPronunciationDictionaryV1PronunciationDictionariesAddFromRulesPostWorkspaceAccess2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyAddProjectV1ProjectsAddPostTargetAudience2JsonConverter),
            typeof(global::G.JsonConverters.BodyAddProjectV1ProjectsAddPostTargetAudience2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyAddProjectV1ProjectsAddPostFiction2JsonConverter),
            typeof(global::G.JsonConverters.BodyAddProjectV1ProjectsAddPostFiction2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyAddProjectV1ProjectsAddPostApplyTextNormalization2JsonConverter),
            typeof(global::G.JsonConverters.BodyAddProjectV1ProjectsAddPostApplyTextNormalization2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyAddProjectV1ProjectsAddPostSourceType2JsonConverter),
            typeof(global::G.JsonConverters.BodyAddProjectV1ProjectsAddPostSourceType2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyAudioIsolationStreamV1AudioIsolationStreamPostFileFormat2JsonConverter),
            typeof(global::G.JsonConverters.BodyAudioIsolationStreamV1AudioIsolationStreamPostFileFormat2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyAudioIsolationV1AudioIsolationPostFileFormat2JsonConverter),
            typeof(global::G.JsonConverters.BodyAudioIsolationV1AudioIsolationPostFileFormat2NullableJsonConverter),
            typeof(global::G.JsonConverters.TurnModeJsonConverter),
            typeof(global::G.JsonConverters.TurnModeNullableJsonConverter),
            typeof(global::G.JsonConverters.TTSConversationalModelJsonConverter),
            typeof(global::G.JsonConverters.TTSConversationalModelNullableJsonConverter),
            typeof(global::G.JsonConverters.TTSModelFamilyJsonConverter),
            typeof(global::G.JsonConverters.TTSModelFamilyNullableJsonConverter),
            typeof(global::G.JsonConverters.TTSOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.TTSOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.ClientEventJsonConverter),
            typeof(global::G.JsonConverters.ClientEventNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostTargetAudience2JsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostTargetAudience2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostFiction2JsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostFiction2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostApplyTextNormalization2JsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostApplyTextNormalization2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostSourceType2JsonConverter),
            typeof(global::G.JsonConverters.BodyCreateStudioProjectV1StudioProjectsPostSourceType2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1ProjectsPodcastCreatePostQualityPresetJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1ProjectsPodcastCreatePostQualityPresetNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1ProjectsPodcastCreatePostDurationScaleJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1ProjectsPodcastCreatePostDurationScaleNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1StudioPodcastsPostQualityPresetJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1StudioPodcastsPostQualityPresetNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1StudioPodcastsPostDurationScaleJsonConverter),
            typeof(global::G.JsonConverters.BodyCreatePodcastV1StudioPodcastsPostDurationScaleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChapterContentBlockInputModelSubType2JsonConverter),
            typeof(global::G.JsonConverters.ChapterContentBlockInputModelSubType2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePostGenderJsonConverter),
            typeof(global::G.JsonConverters.BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePostGenderNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePostAgeJsonConverter),
            typeof(global::G.JsonConverters.BodyGenerateARandomVoiceV1VoiceGenerationGenerateVoicePostAgeNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyInviteUserV1WorkspaceInvitesAddPostWorkspacePermission2JsonConverter),
            typeof(global::G.JsonConverters.BodyInviteUserV1WorkspaceInvitesAddPostWorkspacePermission2NullableJsonConverter),
            typeof(global::G.JsonConverters.RenderType2JsonConverter),
            typeof(global::G.JsonConverters.RenderType2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodyShareWorkspaceResourceV1WorkspaceResourcesResourceIdSharePostRoleJsonConverter),
            typeof(global::G.JsonConverters.BodyShareWorkspaceResourceV1WorkspaceResourcesResourceIdSharePostRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.WorkspaceResourceTypeJsonConverter),
            typeof(global::G.JsonConverters.WorkspaceResourceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptCommonModelInputRoleJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptCommonModelInputRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptCommonModelInputSourceMedium2JsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTranscriptCommonModelInputSourceMedium2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPostFileFormat2JsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPostFileFormat2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToSpeechV1SpeechToSpeechVoiceIdPostFileFormat2JsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToSpeechV1SpeechToSpeechVoiceIdPostFileFormat2NullableJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToTextV1SpeechToTextPostTimestampsGranularityJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToTextV1SpeechToTextPostTimestampsGranularityNullableJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToTextV1SpeechToTextPostFileFormatJsonConverter),
            typeof(global::G.JsonConverters.BodySpeechToTextV1SpeechToTextPostFileFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechStreamingV1TextToSpeechVoiceIdStreamPostApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechStreamingV1TextToSpeechVoiceIdStreamPostApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechStreamingWithTimestampsV1TextToSpeechVoiceIdStreamWithTimestampsPostApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechStreamingWithTimestampsV1TextToSpeechVoiceIdStreamWithTimestampsPostApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechV1TextToSpeechVoiceIdPostApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechV1TextToSpeechVoiceIdPostApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechWithTimestampsV1TextToSpeechVoiceIdWithTimestampsPostApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.BodyTextToSpeechWithTimestampsV1TextToSpeechVoiceIdWithTimestampsPostApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyUpdateMemberV1WorkspaceMembersPostWorkspaceRole2JsonConverter),
            typeof(global::G.JsonConverters.BodyUpdateMemberV1WorkspaceMembersPostWorkspaceRole2NullableJsonConverter),
            typeof(global::G.JsonConverters.BreakdownTypesJsonConverter),
            typeof(global::G.JsonConverters.BreakdownTypesNullableJsonConverter),
            typeof(global::G.JsonConverters.ChapterResponseModelStateJsonConverter),
            typeof(global::G.JsonConverters.ChapterResponseModelStateNullableJsonConverter),
            typeof(global::G.JsonConverters.DependentAvailableToolIdentifierAccessLevelJsonConverter),
            typeof(global::G.JsonConverters.DependentAvailableToolIdentifierAccessLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.ConvAIStoredSecretDependenciesToolDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ConvAIStoredSecretDependenciesToolDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DependentAvailableAgentToolIdentifierAccessLevelJsonConverter),
            typeof(global::G.JsonConverters.DependentAvailableAgentToolIdentifierAccessLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.ConvAIStoredSecretDependenciesAgentToolDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ConvAIStoredSecretDependenciesAgentToolDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SecretDependencyTypeJsonConverter),
            typeof(global::G.JsonConverters.SecretDependencyTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTwilioPhoneCallModelDirectionJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryTwilioPhoneCallModelDirectionNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistorySIPTrunkingPhoneCallModelDirectionJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistorySIPTrunkingPhoneCallModelDirectionNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryMetadataCommonModelPhoneCallVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ConversationHistoryMetadataCommonModelPhoneCallVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationSummaryResponseModelStatusJsonConverter),
            typeof(global::G.JsonConverters.ConversationSummaryResponseModelStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationTokenPurposeJsonConverter),
            typeof(global::G.JsonConverters.ConversationTokenPurposeNullableJsonConverter),
            typeof(global::G.JsonConverters.SIPTrunkTransportEnumJsonConverter),
            typeof(global::G.JsonConverters.SIPTrunkTransportEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.SIPMediaEncryptionEnumJsonConverter),
            typeof(global::G.JsonConverters.SIPMediaEncryptionEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.DependentAvailableAgentIdentifierAccessLevelJsonConverter),
            typeof(global::G.JsonConverters.DependentAvailableAgentIdentifierAccessLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.RenderStatusJsonConverter),
            typeof(global::G.JsonConverters.RenderStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ExtendedSubscriptionResponseModelCurrency2JsonConverter),
            typeof(global::G.JsonConverters.ExtendedSubscriptionResponseModelCurrency2NullableJsonConverter),
            typeof(global::G.JsonConverters.SubscriptionStatusTypeJsonConverter),
            typeof(global::G.JsonConverters.SubscriptionStatusTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ExtendedSubscriptionResponseModelBillingPeriod2JsonConverter),
            typeof(global::G.JsonConverters.ExtendedSubscriptionResponseModelBillingPeriod2NullableJsonConverter),
            typeof(global::G.JsonConverters.ExtendedSubscriptionResponseModelCharacterRefreshPeriod2JsonConverter),
            typeof(global::G.JsonConverters.ExtendedSubscriptionResponseModelCharacterRefreshPeriod2NullableJsonConverter),
            typeof(global::G.JsonConverters.FineTuningResponseModelState2JsonConverter),
            typeof(global::G.JsonConverters.FineTuningResponseModelState2NullableJsonConverter),
            typeof(global::G.JsonConverters.GetAgentResponseModelPhoneNumberDiscriminatorProviderJsonConverter),
            typeof(global::G.JsonConverters.GetAgentResponseModelPhoneNumberDiscriminatorProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.GetConvAIDashboardSettingsResponseModelChartDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetConvAIDashboardSettingsResponseModelChartDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetConversationResponseModelStatusJsonConverter),
            typeof(global::G.JsonConverters.GetConversationResponseModelStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseDependentAgentsResponseModelAgentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseDependentAgentsResponseModelAgentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryURLResponseModelDependentAgentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryURLResponseModelDependentAgentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryFileResponseModelDependentAgentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryFileResponseModelDependentAgentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryTextResponseModelDependentAgentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseSummaryTextResponseModelDependentAgentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseListResponseModelDocumentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetKnowledgeBaseListResponseModelDocumentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LibraryVoiceResponseModelCategoryJsonConverter),
            typeof(global::G.JsonConverters.LibraryVoiceResponseModelCategoryNullableJsonConverter),
            typeof(global::G.JsonConverters.GetPronunciationDictionaryMetadataResponseModelPermissionOnResource2JsonConverter),
            typeof(global::G.JsonConverters.GetPronunciationDictionaryMetadataResponseModelPermissionOnResource2NullableJsonConverter),
            typeof(global::G.JsonConverters.SpeechHistoryItemResponseModelVoiceCategory2JsonConverter),
            typeof(global::G.JsonConverters.SpeechHistoryItemResponseModelVoiceCategory2NullableJsonConverter),
            typeof(global::G.JsonConverters.SpeechHistoryItemResponseModelStateJsonConverter),
            typeof(global::G.JsonConverters.SpeechHistoryItemResponseModelStateNullableJsonConverter),
            typeof(global::G.JsonConverters.SpeechHistoryItemResponseModelSource2JsonConverter),
            typeof(global::G.JsonConverters.SpeechHistoryItemResponseModelSource2NullableJsonConverter),
            typeof(global::G.JsonConverters.SpeakerSeparationResponseModelStatusJsonConverter),
            typeof(global::G.JsonConverters.SpeakerSeparationResponseModelStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.VoiceResponseModelCategoryJsonConverter),
            typeof(global::G.JsonConverters.VoiceResponseModelCategoryNullableJsonConverter),
            typeof(global::G.JsonConverters.VoiceSharingResponseModelStatusJsonConverter),
            typeof(global::G.JsonConverters.VoiceSharingResponseModelStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.VoiceSharingResponseModelCategoryJsonConverter),
            typeof(global::G.JsonConverters.VoiceSharingResponseModelCategoryNullableJsonConverter),
            typeof(global::G.JsonConverters.VoiceSharingResponseModelReviewStatusJsonConverter),
            typeof(global::G.JsonConverters.VoiceSharingResponseModelReviewStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ReaderResourceResponseModelResourceTypeJsonConverter),
            typeof(global::G.JsonConverters.ReaderResourceResponseModelResourceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.VoiceResponseModelSafetyControl2JsonConverter),
            typeof(global::G.JsonConverters.VoiceResponseModelSafetyControl2NullableJsonConverter),
            typeof(global::G.JsonConverters.MCPToolApprovalPolicyJsonConverter),
            typeof(global::G.JsonConverters.MCPToolApprovalPolicyNullableJsonConverter),
            typeof(global::G.JsonConverters.MCPServerTransportJsonConverter),
            typeof(global::G.JsonConverters.MCPServerTransportNullableJsonConverter),
            typeof(global::G.JsonConverters.MCPServerResponseModelDependentAgentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MCPServerResponseModelDependentAgentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MetricTypeJsonConverter),
            typeof(global::G.JsonConverters.MetricTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelResponseModelConcurrencyGroupJsonConverter),
            typeof(global::G.JsonConverters.ModelResponseModelConcurrencyGroupNullableJsonConverter),
            typeof(global::G.JsonConverters.ModerationStatusResponseModelSafetyStatus2JsonConverter),
            typeof(global::G.JsonConverters.ModerationStatusResponseModelSafetyStatus2NullableJsonConverter),
            typeof(global::G.JsonConverters.ModerationStatusResponseModelWarningStatus2JsonConverter),
            typeof(global::G.JsonConverters.ModerationStatusResponseModelWarningStatus2NullableJsonConverter),
            typeof(global::G.JsonConverters.PatchConvAIDashboardSettingsRequestChartDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PatchConvAIDashboardSettingsRequestChartDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelTargetAudience2JsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelTargetAudience2NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelStateJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelStateNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelAccessLevelJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelAccessLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelFiction2JsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelFiction2NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelSourceType2JsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelSourceType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelQualityPresetJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelQualityPresetNullableJsonConverter),
            typeof(global::G.JsonConverters.PronunciationDictionaryVersionResponseModelPermissionOnResource2JsonConverter),
            typeof(global::G.JsonConverters.PronunciationDictionaryVersionResponseModelPermissionOnResource2NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelApplyTextNormalizationJsonConverter),
            typeof(global::G.JsonConverters.ProjectExtendedResponseModelApplyTextNormalizationNullableJsonConverter),
            typeof(global::G.JsonConverters.RAGIndexStatusJsonConverter),
            typeof(global::G.JsonConverters.RAGIndexStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ShareOptionResponseModelTypeJsonConverter),
            typeof(global::G.JsonConverters.ShareOptionResponseModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SafetyRuleJsonConverter),
            typeof(global::G.JsonConverters.SafetyRuleNullableJsonConverter),
            typeof(global::G.JsonConverters.SimilarVoiceCategoryJsonConverter),
            typeof(global::G.JsonConverters.SimilarVoiceCategoryNullableJsonConverter),
            typeof(global::G.JsonConverters.SpeechToTextWordResponseModelTypeJsonConverter),
            typeof(global::G.JsonConverters.SpeechToTextWordResponseModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SubscriptionResponseModelCurrency2JsonConverter),
            typeof(global::G.JsonConverters.SubscriptionResponseModelCurrency2NullableJsonConverter),
            typeof(global::G.JsonConverters.SubscriptionResponseModelBillingPeriod2JsonConverter),
            typeof(global::G.JsonConverters.SubscriptionResponseModelBillingPeriod2NullableJsonConverter),
            typeof(global::G.JsonConverters.SubscriptionResponseModelCharacterRefreshPeriod2JsonConverter),
            typeof(global::G.JsonConverters.SubscriptionResponseModelCharacterRefreshPeriod2NullableJsonConverter),
            typeof(global::G.JsonConverters.UsageAggregationIntervalJsonConverter),
            typeof(global::G.JsonConverters.UsageAggregationIntervalNullableJsonConverter),
            typeof(global::G.JsonConverters.WebhookAuthMethodTypeJsonConverter),
            typeof(global::G.JsonConverters.WebhookAuthMethodTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WebhookUsageTypeJsonConverter),
            typeof(global::G.JsonConverters.WebhookUsageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListGeneratedItemsV1HistoryGetSource2JsonConverter),
            typeof(global::G.JsonConverters.ListGeneratedItemsV1HistoryGetSource2NullableJsonConverter),
            typeof(global::G.JsonConverters.SoundGenerationV1SoundGenerationPostOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.SoundGenerationV1SoundGenerationPostOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechV1TextToSpeechVoiceIdPostOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechV1TextToSpeechVoiceIdPostOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechWithTimestampsV1TextToSpeechVoiceIdWithTimestampsPostOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechWithTimestampsV1TextToSpeechVoiceIdWithTimestampsPostOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechStreamingV1TextToSpeechVoiceIdStreamPostOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechStreamingV1TextToSpeechVoiceIdStreamPostOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechStreamingWithTimestampsV1TextToSpeechVoiceIdStreamWithTimestampsPostOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.TextToSpeechStreamingWithTimestampsV1TextToSpeechVoiceIdStreamWithTimestampsPostOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.TextToDialogueMultiVoiceV1TextToDialoguePostOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.TextToDialogueMultiVoiceV1TextToDialoguePostOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.TextToDialogueMultiVoiceStreamingV1TextToDialogueStreamPostOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.TextToDialogueMultiVoiceStreamingV1TextToDialogueStreamPostOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.SpeechToSpeechV1SpeechToSpeechVoiceIdPostOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.SpeechToSpeechV1SpeechToSpeechVoiceIdPostOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.SpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPostOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.SpeechToSpeechStreamingV1SpeechToSpeechVoiceIdStreamPostOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.GenerateAVoicePreviewFromDescriptionV1TextToVoiceCreatePreviewsPostOutputFormatJsonConverter),
            typeof(global::G.JsonConverters.GenerateAVoicePreviewFromDescriptionV1TextToVoiceCreatePreviewsPostOutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.GetDubbedTranscriptV1DubbingDubbingIdTranscriptLanguageCodeGetFormatTypeJsonConverter),
            typeof(global::G.JsonConverters.GetDubbedTranscriptV1DubbingDubbingIdTranscriptLanguageCodeGetFormatTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetPronunciationDictionariesV1PronunciationDictionariesGetSort2JsonConverter),
            typeof(global::G.JsonConverters.GetPronunciationDictionariesV1PronunciationDictionariesGetSort2NullableJsonConverter),
            typeof(global::G.JsonConverters.GetPhoneNumberV1ConvaiPhoneNumbersPhoneNumberIdGetResponseDiscriminatorProviderJsonConverter),
            typeof(global::G.JsonConverters.GetPhoneNumberV1ConvaiPhoneNumbersPhoneNumberIdGetResponseDiscriminatorProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.UpdatePhoneNumberV1ConvaiPhoneNumbersPhoneNumberIdPatchResponseDiscriminatorProviderJsonConverter),
            typeof(global::G.JsonConverters.UpdatePhoneNumberV1ConvaiPhoneNumbersPhoneNumberIdPatchResponseDiscriminatorProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListPhoneNumbersV1ConvaiPhoneNumbersGetResponseItemDiscriminatorProviderJsonConverter),
            typeof(global::G.JsonConverters.ListPhoneNumbersV1ConvaiPhoneNumbersGetResponseItemDiscriminatorProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.UpdateDocumentV1ConvaiKnowledgeBaseDocumentationIdPatchResponseDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.UpdateDocumentV1ConvaiKnowledgeBaseDocumentationIdPatchResponseDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetDocumentationFromKnowledgeBaseV1ConvaiKnowledgeBaseDocumentationIdGetResponseDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetDocumentationFromKnowledgeBaseV1ConvaiKnowledgeBaseDocumentationIdGetResponseDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetDocumentationFromKnowledgeBaseV1ConvaiAgentsAgentIdKnowledgeBaseDocumentationIdGetResponseDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetDocumentationFromKnowledgeBaseV1ConvaiAgentsAgentIdKnowledgeBaseDocumentationIdGetResponseDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ExportOptionsJsonConverter),
            typeof(global::G.JsonConverters.ToolsItem2JsonConverter),
            typeof(global::G.JsonConverters.ParamsJsonConverter),
            typeof(global::G.JsonConverters.ToolsItem3JsonConverter),
            typeof(global::G.JsonConverters.Params2JsonConverter),
            typeof(global::G.JsonConverters.ToolsItem4JsonConverter),
            typeof(global::G.JsonConverters.ToolDetailsVariant1JsonConverter),
            typeof(global::G.JsonConverters.ToolsItemJsonConverter),
            typeof(global::G.JsonConverters.AgentToolsItemJsonConverter),
            typeof(global::G.JsonConverters.PhoneCallVariant1JsonConverter),
            typeof(global::G.JsonConverters.PhoneNumbersItemJsonConverter),
            typeof(global::G.JsonConverters.ChartsItemJsonConverter),
            typeof(global::G.JsonConverters.AgentsItemJsonConverter),
            typeof(global::G.JsonConverters.DocumentsItemJsonConverter),
            typeof(global::G.JsonConverters.DependentAgentsItem3JsonConverter),
            typeof(global::G.JsonConverters.DependentAgentsItemJsonConverter),
            typeof(global::G.JsonConverters.DependentAgentsItem2JsonConverter),
            typeof(global::G.JsonConverters.DependentAgentsItem4JsonConverter),
            typeof(global::G.JsonConverters.ChartsItem2JsonConverter),
            typeof(global::G.JsonConverters.GetPhoneNumberV1ConvaiPhoneNumbersPhoneNumberIdGetResponseJsonConverter),
            typeof(global::G.JsonConverters.UpdatePhoneNumberV1ConvaiPhoneNumbersPhoneNumberIdPatchResponseJsonConverter),
            typeof(global::G.JsonConverters.ListPhoneNumbersV1ConvaiPhoneNumbersGetResponseItemJsonConverter),
            typeof(global::G.JsonConverters.UpdateDocumentV1ConvaiKnowledgeBaseDocumentationIdPatchResponseJsonConverter),
            typeof(global::G.JsonConverters.GetDocumentationFromKnowledgeBaseV1ConvaiKnowledgeBaseDocumentationIdGetResponseJsonConverter),
            typeof(global::G.JsonConverters.GetDocumentationFromKnowledgeBaseV1ConvaiAgentsAgentIdKnowledgeBaseDocumentationIdGetResponseJsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ChapterContentBlockTtsNodeResponseModel, global::G.ChapterContentBlockExtendableNodeResponseModel>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?, double?, bool?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.LiteralJsonSchemaProperty, global::G.ObjectJsonSchemaPropertyInput, global::G.ArrayJsonSchemaPropertyInput>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.LiteralJsonSchemaProperty, global::G.ObjectJsonSchemaPropertyInput, global::G.ArrayJsonSchemaPropertyInput>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator, global::G.ConvAIDynamicVariable>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator, global::G.ConvAIDynamicVariable>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.LiteralJsonSchemaProperty, global::G.ObjectJsonSchemaPropertyOutput, global::G.ArrayJsonSchemaPropertyOutput>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.LiteralJsonSchemaProperty, global::G.ObjectJsonSchemaPropertyOutput, global::G.ArrayJsonSchemaPropertyOutput>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator, global::G.ConvAIDynamicVariable>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.OrbAvatar, global::G.URLAvatar, global::G.ImageAvatar>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.OrbAvatar, global::G.URLAvatar, global::G.ImageAvatar>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PronunciationDictionaryAliasRuleRequestModel, global::G.PronunciationDictionaryPhonemeRuleRequestModel>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PronunciationDictionaryAliasRuleRequestModel, global::G.PronunciationDictionaryPhonemeRuleRequestModel>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PodcastConversationMode, global::G.PodcastBulletinMode>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PodcastTextSource, global::G.PodcastURLSource, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.PodcastTextSource, global::G.PodcastURLSource>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PodcastTextSource, global::G.PodcastURLSource>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PodcastConversationMode, global::G.PodcastBulletinMode>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PodcastTextSource, global::G.PodcastURLSource, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.PodcastTextSource, global::G.PodcastURLSource>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PodcastTextSource, global::G.PodcastURLSource>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, double?, int?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.OrbAvatar, global::G.URLAvatar, global::G.ImageAvatar>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConvAISecretLocator, global::G.ConvAIUserSecretDBModel, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConvAISecretLocator, global::G.ConvAIUserSecretDBModel, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ConvAISecretLocator>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.CreateTwilioPhoneNumberRequest, global::G.CreateSIPTrunkPhoneNumberRequest>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}