//HintName: G.Models.ChatTextGenerationEvent.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    public sealed partial class ChatTextGenerationEvent : ChatStreamEvent
    {
        /// <summary>
        /// The next batch of text generated by the model.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("text", Required = global::Newtonsoft.Json.Required.Always)]
        public string Text { get; set; } = default!;


        /// <summary>
        /// Initializes a new instance of the <see cref="ChatTextGenerationEvent" /> class.
        /// </summary>
        /// <param name="text">
        /// The next batch of text generated by the model.
        /// </param>
        public ChatTextGenerationEvent(
            string text)
        {
            this.Text = text ?? throw new global::System.ArgumentNullException(nameof(text));
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatTextGenerationEvent" /> class.
        /// </summary>
        public ChatTextGenerationEvent()
        {
        }
    }
}