//HintName: G.Models.ChatTextGenerationEvent8yyj22.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    public sealed partial class ChatTextGenerationEvent8yyj22
    {
        /// <summary>
        /// The next batch of text generated by the model.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("text", Required = global::Newtonsoft.Json.Required.Always)]
        public string Text { get; set; } = default!;

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatTextGenerationEvent8yyj22" /> class.
        /// </summary>
        /// <param name="text">
        /// The next batch of text generated by the model.
        /// </param>
        public ChatTextGenerationEvent8yyj22(
            string text)
        {
            this.Text = text ?? throw new global::System.ArgumentNullException(nameof(text));
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatTextGenerationEvent8yyj22" /> class.
        /// </summary>
        public ChatTextGenerationEvent8yyj22()
        {
        }
    }
}