using System.Collections.Immutable;
using AutoSDK.Naming.Methods;
using AutoSDK.Serialization.Json;
using CoreJsonSerializerType = AutoSDK.Serialization.Json.JsonSerializerType;
using CoreMethodNamingConvention = AutoSDK.Naming.Methods.MethodNamingConvention;

namespace AutoSDK.Models;

public record struct CSharpSettings(
    string TargetFramework,
    string Namespace,
    string ClassName,
    string ClsCompliantEnumPrefix,
    IdentifierCharacterSet IdentifierCharacterSet,
    NamingConvention NamingConvention,
    CSharpJsonSerializerType JsonSerializerType,
    SdkFeatureUsage UseRequiredKeyword,
    SdkFeatureUsage UseExperimentalAttributes,
    SdkFeatureUsage UseSetsRequiredMembersAttributes,
    bool GenerateConstructors,
    bool GroupByTags,
    bool GenerateMethods,
    CSharpMethodNamingConvention MethodNamingConvention,
    CSharpMethodNamingConvention MethodNamingConventionFallback,
    bool GenerateMethodsAsHttpClientExtensions,
    bool GenerateMethodsUsingSystemNetHttpJson,
    bool GenerateDependencyInjection,
    bool GenerateConfigurationBinding,
    bool GenerateHttpResilienceExtensions,
    bool GenerateWebhookVerifier,
    string WebhookVerifierClassName,
    string WebhookIdHeaderName,
    string WebhookTimestampHeaderName,
    string WebhookSignatureHeaderName,
    string WebhookSignatureVersion,
    int WebhookTimestampToleranceSeconds,
    bool GenerateDynamicMultipartHelpers,
    string DynamicMultipartHelperClassName,
    bool GeneratePromptTemplateHelpers,
    string PromptTemplateHelperClassName,
    bool GenerateObservabilityLifecycleHelpers,
    string ObservabilityLifecycleHelperClassName,
    bool GeneratePredictionWorkflowHelpers,
    string PredictionWorkflowHelperClassName,
    bool GenerateEvaluationWorkflowHelpers,
    string EvaluationWorkflowHelperClassName,
    ImmutableArray<string> IncludeOperationIds,
    ImmutableArray<string> ExcludeOperationIds,
    ImmutableArray<string> IncludeTags,
    ImmutableArray<string> ExcludeTags,
    bool ExcludeDeprecatedOperations,
    bool UseExtensionNaming,
    string JsonSerializerContext,
    bool GenerateJsonSerializerContextTypes,
    bool ComputeDiscriminators,
    bool AddMissingPathParameters,
    bool GenerateModels,
    bool GenerateModelValidationMethods,
    bool ValidateAnyOfs,
    bool GenerateRawModelData,
    ModelStyle ModelStyle,
    ImmutableArray<string> IncludeModels,
    ImmutableArray<string> ExcludeModels,
    string NamespaceDelimiter,
    ExcludedModelNamespaceMode ExcludedModelNamespaceMode,
    bool IgnoreOpenApiErrors,
    bool IgnoreOpenApiWarnings,
    bool GeneratePolyfills,
    bool GenerateExceptions,
    bool GenerateSdk,
    bool FromCli,
    bool GenerateCli,
    ImmutableArray<string> SecuritySchemes,
    ImmutableArray<string> AuthorizationEnvironmentVariables,
    string BaseUrl,
    ImmutableArray<string> BaseUrlEnvironmentVariables,
    ImmutableArray<string> OpenApiOverrides,
    bool GenerateWebSocketClient,
    string WebSocketClientClassName,
    string TypesNamespace)
{
    public static CSharpSettings Default => FromSettings(Settings.Default);

    public static CSharpSettings FromSettings(Settings settings)
    {
        return new CSharpSettings(
            TargetFramework: settings.TargetFramework,
            Namespace: settings.Namespace,
            ClassName: settings.ClassName,
            ClsCompliantEnumPrefix: settings.ClsCompliantEnumPrefix,
            IdentifierCharacterSet: settings.IdentifierCharacterSet,
            NamingConvention: settings.NamingConvention,
            JsonSerializerType: settings.JsonSerializerType switch
            {
                CoreJsonSerializerType.SystemTextJson => CSharpJsonSerializerType.SystemTextJson,
                CoreJsonSerializerType.NewtonsoftJson => CSharpJsonSerializerType.NewtonsoftJson,
                _ => throw new ArgumentOutOfRangeException(nameof(settings), settings.JsonSerializerType, null),
            },
            UseRequiredKeyword: settings.UseRequiredKeyword,
            UseExperimentalAttributes: settings.UseExperimentalAttributes,
            UseSetsRequiredMembersAttributes: settings.UseSetsRequiredMembersAttributes,
            GenerateConstructors: settings.GenerateConstructors,
            GroupByTags: settings.GroupByTags,
            GenerateMethods: settings.GenerateMethods,
            MethodNamingConvention: settings.MethodNamingConvention switch
            {
                CoreMethodNamingConvention.OperationId => CSharpMethodNamingConvention.OperationId,
                CoreMethodNamingConvention.MethodAndPath => CSharpMethodNamingConvention.MethodAndPath,
                CoreMethodNamingConvention.Summary => CSharpMethodNamingConvention.Summary,
                CoreMethodNamingConvention.OperationIdWithDots => CSharpMethodNamingConvention.OperationIdWithDots,
                CoreMethodNamingConvention.OperationIdSplit => CSharpMethodNamingConvention.OperationIdSplit,
                _ => throw new ArgumentOutOfRangeException(nameof(settings), settings.MethodNamingConvention, null),
            },
            MethodNamingConventionFallback: settings.MethodNamingConventionFallback switch
            {
                CoreMethodNamingConvention.OperationId => CSharpMethodNamingConvention.OperationId,
                CoreMethodNamingConvention.MethodAndPath => CSharpMethodNamingConvention.MethodAndPath,
                CoreMethodNamingConvention.Summary => CSharpMethodNamingConvention.Summary,
                CoreMethodNamingConvention.OperationIdWithDots => CSharpMethodNamingConvention.OperationIdWithDots,
                CoreMethodNamingConvention.OperationIdSplit => CSharpMethodNamingConvention.OperationIdSplit,
                _ => throw new ArgumentOutOfRangeException(nameof(settings), settings.MethodNamingConventionFallback, null),
            },
            GenerateMethodsAsHttpClientExtensions: settings.GenerateMethodsAsHttpClientExtensions,
            GenerateMethodsUsingSystemNetHttpJson: settings.GenerateMethodsUsingSystemNetHttpJson,
            GenerateDependencyInjection: settings.GenerateDependencyInjection,
            GenerateConfigurationBinding: settings.GenerateConfigurationBinding,
            GenerateHttpResilienceExtensions: settings.GenerateHttpResilienceExtensions,
            GenerateWebhookVerifier: settings.GenerateWebhookVerifier,
            WebhookVerifierClassName: settings.WebhookVerifierClassName,
            WebhookIdHeaderName: settings.WebhookIdHeaderName,
            WebhookTimestampHeaderName: settings.WebhookTimestampHeaderName,
            WebhookSignatureHeaderName: settings.WebhookSignatureHeaderName,
            WebhookSignatureVersion: settings.WebhookSignatureVersion,
            WebhookTimestampToleranceSeconds: settings.WebhookTimestampToleranceSeconds,
            GenerateDynamicMultipartHelpers: settings.GenerateDynamicMultipartHelpers,
            DynamicMultipartHelperClassName: settings.DynamicMultipartHelperClassName,
            GeneratePromptTemplateHelpers: settings.GeneratePromptTemplateHelpers,
            PromptTemplateHelperClassName: settings.PromptTemplateHelperClassName,
            GenerateObservabilityLifecycleHelpers: settings.GenerateObservabilityLifecycleHelpers,
            ObservabilityLifecycleHelperClassName: settings.ObservabilityLifecycleHelperClassName,
            GeneratePredictionWorkflowHelpers: settings.GeneratePredictionWorkflowHelpers,
            PredictionWorkflowHelperClassName: settings.PredictionWorkflowHelperClassName,
            GenerateEvaluationWorkflowHelpers: settings.GenerateEvaluationWorkflowHelpers,
            EvaluationWorkflowHelperClassName: settings.EvaluationWorkflowHelperClassName,
            IncludeOperationIds: settings.IncludeOperationIds,
            ExcludeOperationIds: settings.ExcludeOperationIds,
            IncludeTags: settings.IncludeTags,
            ExcludeTags: settings.ExcludeTags,
            ExcludeDeprecatedOperations: settings.ExcludeDeprecatedOperations,
            UseExtensionNaming: settings.UseExtensionNaming,
            JsonSerializerContext: settings.JsonSerializerContext,
            GenerateJsonSerializerContextTypes: settings.GenerateJsonSerializerContextTypes,
            ComputeDiscriminators: settings.ComputeDiscriminators,
            AddMissingPathParameters: settings.AddMissingPathParameters,
            GenerateModels: settings.GenerateModels,
            GenerateModelValidationMethods: settings.GenerateModelValidationMethods,
            ValidateAnyOfs: settings.ValidateAnyOfs,
            GenerateRawModelData: settings.GenerateRawModelData,
            ModelStyle: settings.ModelStyle,
            IncludeModels: settings.IncludeModels,
            ExcludeModels: settings.ExcludeModels,
            NamespaceDelimiter: settings.NamespaceDelimiter,
            ExcludedModelNamespaceMode: settings.ExcludedModelNamespaceMode,
            IgnoreOpenApiErrors: settings.IgnoreOpenApiErrors,
            IgnoreOpenApiWarnings: settings.IgnoreOpenApiWarnings,
            GeneratePolyfills: settings.GeneratePolyfills,
            GenerateExceptions: settings.GenerateExceptions,
            GenerateSdk: settings.GenerateSdk,
            FromCli: settings.FromCli,
            GenerateCli: settings.GenerateCli,
            SecuritySchemes: settings.SecuritySchemes,
            AuthorizationEnvironmentVariables: settings.AuthorizationEnvironmentVariables,
            BaseUrl: settings.BaseUrl,
            BaseUrlEnvironmentVariables: settings.BaseUrlEnvironmentVariables,
            OpenApiOverrides: settings.OpenApiOverrides,
            GenerateWebSocketClient: settings.GenerateWebSocketClient,
            WebSocketClientClassName: settings.WebSocketClientClassName,
            TypesNamespace: settings.TypesNamespace);
    }

    public Settings ToSettings()
    {
        return new Settings(
            TargetFramework: TargetFramework,
            Namespace: Namespace,
            ClassName: ClassName,
            ClsCompliantEnumPrefix: ClsCompliantEnumPrefix,
            IdentifierCharacterSet: IdentifierCharacterSet,
            NamingConvention: NamingConvention,
            JsonSerializerType: JsonSerializerType switch
            {
                CSharpJsonSerializerType.SystemTextJson => CoreJsonSerializerType.SystemTextJson,
                CSharpJsonSerializerType.NewtonsoftJson => CoreJsonSerializerType.NewtonsoftJson,
                _ => throw new ArgumentOutOfRangeException(nameof(JsonSerializerType), JsonSerializerType, null),
            },
            UseRequiredKeyword: UseRequiredKeyword,
            UseExperimentalAttributes: UseExperimentalAttributes,
            UseSetsRequiredMembersAttributes: UseSetsRequiredMembersAttributes,
            GenerateConstructors: GenerateConstructors,
            GroupByTags: GroupByTags,
            GenerateMethods: GenerateMethods,
            MethodNamingConvention: MethodNamingConvention switch
            {
                CSharpMethodNamingConvention.OperationId => CoreMethodNamingConvention.OperationId,
                CSharpMethodNamingConvention.MethodAndPath => CoreMethodNamingConvention.MethodAndPath,
                CSharpMethodNamingConvention.Summary => CoreMethodNamingConvention.Summary,
                CSharpMethodNamingConvention.OperationIdWithDots => CoreMethodNamingConvention.OperationIdWithDots,
                CSharpMethodNamingConvention.OperationIdSplit => CoreMethodNamingConvention.OperationIdSplit,
                _ => throw new ArgumentOutOfRangeException(nameof(MethodNamingConvention), MethodNamingConvention, null),
            },
            MethodNamingConventionFallback: MethodNamingConventionFallback switch
            {
                CSharpMethodNamingConvention.OperationId => CoreMethodNamingConvention.OperationId,
                CSharpMethodNamingConvention.MethodAndPath => CoreMethodNamingConvention.MethodAndPath,
                CSharpMethodNamingConvention.Summary => CoreMethodNamingConvention.Summary,
                CSharpMethodNamingConvention.OperationIdWithDots => CoreMethodNamingConvention.OperationIdWithDots,
                CSharpMethodNamingConvention.OperationIdSplit => CoreMethodNamingConvention.OperationIdSplit,
                _ => throw new ArgumentOutOfRangeException(nameof(MethodNamingConventionFallback), MethodNamingConventionFallback, null),
            },
            GenerateMethodsAsHttpClientExtensions: GenerateMethodsAsHttpClientExtensions,
            GenerateMethodsUsingSystemNetHttpJson: GenerateMethodsUsingSystemNetHttpJson,
            GenerateDependencyInjection: GenerateDependencyInjection,
            GenerateConfigurationBinding: GenerateConfigurationBinding,
            GenerateHttpResilienceExtensions: GenerateHttpResilienceExtensions,
            GenerateWebhookVerifier: GenerateWebhookVerifier,
            WebhookVerifierClassName: WebhookVerifierClassName,
            WebhookIdHeaderName: WebhookIdHeaderName,
            WebhookTimestampHeaderName: WebhookTimestampHeaderName,
            WebhookSignatureHeaderName: WebhookSignatureHeaderName,
            WebhookSignatureVersion: WebhookSignatureVersion,
            WebhookTimestampToleranceSeconds: WebhookTimestampToleranceSeconds,
            GenerateDynamicMultipartHelpers: GenerateDynamicMultipartHelpers,
            DynamicMultipartHelperClassName: DynamicMultipartHelperClassName,
            GeneratePromptTemplateHelpers: GeneratePromptTemplateHelpers,
            PromptTemplateHelperClassName: PromptTemplateHelperClassName,
            GenerateObservabilityLifecycleHelpers: GenerateObservabilityLifecycleHelpers,
            ObservabilityLifecycleHelperClassName: ObservabilityLifecycleHelperClassName,
            GeneratePredictionWorkflowHelpers: GeneratePredictionWorkflowHelpers,
            PredictionWorkflowHelperClassName: PredictionWorkflowHelperClassName,
            GenerateEvaluationWorkflowHelpers: GenerateEvaluationWorkflowHelpers,
            EvaluationWorkflowHelperClassName: EvaluationWorkflowHelperClassName,
            IncludeOperationIds: IncludeOperationIds,
            ExcludeOperationIds: ExcludeOperationIds,
            IncludeTags: IncludeTags,
            ExcludeTags: ExcludeTags,
            ExcludeDeprecatedOperations: ExcludeDeprecatedOperations,
            UseExtensionNaming: UseExtensionNaming,
            JsonSerializerContext: JsonSerializerContext,
            GenerateJsonSerializerContextTypes: GenerateJsonSerializerContextTypes,
            ComputeDiscriminators: ComputeDiscriminators,
            AddMissingPathParameters: AddMissingPathParameters,
            GenerateModels: GenerateModels,
            GenerateModelValidationMethods: GenerateModelValidationMethods,
            ValidateAnyOfs: ValidateAnyOfs,
            GenerateRawModelData: GenerateRawModelData,
            ModelStyle: ModelStyle,
            IncludeModels: IncludeModels,
            ExcludeModels: ExcludeModels,
            NamespaceDelimiter: NamespaceDelimiter,
            ExcludedModelNamespaceMode: ExcludedModelNamespaceMode,
            IgnoreOpenApiErrors: IgnoreOpenApiErrors,
            IgnoreOpenApiWarnings: IgnoreOpenApiWarnings,
            GeneratePolyfills: GeneratePolyfills,
            GenerateExceptions: GenerateExceptions,
            GenerateSdk: GenerateSdk,
            FromCli: FromCli,
            GenerateCli: GenerateCli,
            SecuritySchemes: SecuritySchemes,
            AuthorizationEnvironmentVariables: AuthorizationEnvironmentVariables,
            BaseUrl: BaseUrl,
            BaseUrlEnvironmentVariables: BaseUrlEnvironmentVariables,
            OpenApiOverrides: OpenApiOverrides,
            GenerateWebSocketClient: GenerateWebSocketClient,
            WebSocketClientClassName: WebSocketClientClassName,
            TypesNamespace: TypesNamespace);
    }

    public static implicit operator CSharpSettings(Settings settings)
    {
        return FromSettings(settings);
    }

    public static implicit operator Settings(CSharpSettings settings)
    {
        return settings.ToSettings();
    }
}
