//HintName: G.Models.ChatCompletionStreamResponseDelta.g.cs

#pragma warning disable CS0618 // Type or member is obsolete

#nullable enable

namespace G
{
    /// <summary>
    /// A chat completion delta generated by streamed model responses.
    /// </summary>
    public sealed partial class ChatCompletionStreamResponseDelta
    {
        /// <summary>
        /// The contents of the chunk message.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("content")]
        public string? Content { get; set; }

        /// <summary>
        /// The model's reasoning for a response. Only available for [models that support reasoning](https://console.groq.com/docs/reasoning) when request parameter reasoning_format has value `parsed`.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("reasoning")]
        public string? Reasoning { get; set; }

        /// <summary>
        /// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("function_call")]
        [global::System.Obsolete("This property marked as deprecated.")]
        public global::G.ChatCompletionStreamResponseDeltaFunctionCall? FunctionCall { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("tool_calls")]
        public global::System.Collections.Generic.IList<global::G.ChatCompletionMessageToolCallChunk>? ToolCalls { get; set; }

        /// <summary>
        /// A list of tools that were executed during the chat completion for compound AI systems.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("executed_tools")]
        public global::System.Collections.Generic.IList<global::G.ChatCompletionMessageExecutedTool>? ExecutedTools { get; set; }

        /// <summary>
        /// The role of the author of this message.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("role")]
        public global::G.ChatCompletionStreamResponseDeltaRole? Role { get; set; }

        /// <summary>
        /// A list of annotations providing citations and references for the content in the message.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("annotations")]
        public global::System.Collections.Generic.IList<global::G.Annotation>? Annotations { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatCompletionStreamResponseDelta" /> class.
        /// </summary>
        /// <param name="content">
        /// The contents of the chunk message.
        /// </param>
        /// <param name="reasoning">
        /// The model's reasoning for a response. Only available for [models that support reasoning](https://console.groq.com/docs/reasoning) when request parameter reasoning_format has value `parsed`.
        /// </param>
        /// <param name="toolCalls"></param>
        /// <param name="executedTools">
        /// A list of tools that were executed during the chat completion for compound AI systems.
        /// </param>
        /// <param name="role">
        /// The role of the author of this message.
        /// </param>
        /// <param name="annotations">
        /// A list of annotations providing citations and references for the content in the message.
        /// </param>
        public ChatCompletionStreamResponseDelta(
            string? content,
            string? reasoning,
            global::System.Collections.Generic.IList<global::G.ChatCompletionMessageToolCallChunk>? toolCalls,
            global::System.Collections.Generic.IList<global::G.ChatCompletionMessageExecutedTool>? executedTools,
            global::G.ChatCompletionStreamResponseDeltaRole? role,
            global::System.Collections.Generic.IList<global::G.Annotation>? annotations)
        {
            this.Content = content;
            this.Reasoning = reasoning;
            this.ToolCalls = toolCalls;
            this.ExecutedTools = executedTools;
            this.Role = role;
            this.Annotations = annotations;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatCompletionStreamResponseDelta" /> class.
        /// </summary>
        public ChatCompletionStreamResponseDelta()
        {
        }
    }
}