//HintName: G.Models.ChatCompletionResponseMessage.g.cs

#pragma warning disable CS0618 // Type or member is obsolete

#nullable enable

namespace G
{
    /// <summary>
    /// A chat completion message generated by the model.
    /// </summary>
    public sealed partial class ChatCompletionResponseMessage
    {
        /// <summary>
        /// The contents of the message.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("content")]
        public string? Content { get; set; }

        /// <summary>
        /// The model's reasoning for a response. Only available for [models that support reasoning](https://console.groq.com/docs/reasoning) when request parameter reasoning_format has value `parsed`.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("reasoning")]
        public string? Reasoning { get; set; }

        /// <summary>
        /// The tool calls generated by the model, such as function calls.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("tool_calls")]
        public global::System.Collections.Generic.IList<global::G.ChatCompletionMessageToolCall>? ToolCalls { get; set; }

        /// <summary>
        /// A list of tools that were executed during the chat completion for compound AI systems.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("executed_tools")]
        public global::System.Collections.Generic.IList<global::G.ChatCompletionMessageExecutedTool>? ExecutedTools { get; set; }

        /// <summary>
        /// The role of the author of this message.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("role")]
        [global::Newtonsoft.Json.JsonConverter(typeof(global::G.JsonConverters.ChatCompletionResponseMessageRoleJsonConverter))]
        public global::G.ChatCompletionResponseMessageRole Role { get; set; }

        /// <summary>
        /// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("function_call")]
        [global::System.Obsolete("This property marked as deprecated.")]
        public global::G.ChatCompletionResponseMessageFunctionCall? FunctionCall { get; set; }

        /// <summary>
        /// A list of annotations providing citations and references for the content in the message.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("annotations")]
        public global::System.Collections.Generic.IList<global::G.Annotation>? Annotations { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatCompletionResponseMessage" /> class.
        /// </summary>
        /// <param name="content">
        /// The contents of the message.
        /// </param>
        /// <param name="reasoning">
        /// The model's reasoning for a response. Only available for [models that support reasoning](https://console.groq.com/docs/reasoning) when request parameter reasoning_format has value `parsed`.
        /// </param>
        /// <param name="toolCalls">
        /// The tool calls generated by the model, such as function calls.
        /// </param>
        /// <param name="executedTools">
        /// A list of tools that were executed during the chat completion for compound AI systems.
        /// </param>
        /// <param name="role">
        /// The role of the author of this message.
        /// </param>
        /// <param name="annotations">
        /// A list of annotations providing citations and references for the content in the message.
        /// </param>
        public ChatCompletionResponseMessage(
            string? content,
            string? reasoning,
            global::System.Collections.Generic.IList<global::G.ChatCompletionMessageToolCall>? toolCalls,
            global::System.Collections.Generic.IList<global::G.ChatCompletionMessageExecutedTool>? executedTools,
            global::G.ChatCompletionResponseMessageRole role,
            global::System.Collections.Generic.IList<global::G.Annotation>? annotations)
        {
            this.Content = content;
            this.Reasoning = reasoning;
            this.ToolCalls = toolCalls;
            this.ExecutedTools = executedTools;
            this.Role = role;
            this.Annotations = annotations;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatCompletionResponseMessage" /> class.
        /// </summary>
        public ChatCompletionResponseMessage()
        {
        }
    }
}