//HintName: G.Models.ResponseFunctionCallOutput.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// The output of a function tool call.
    /// </summary>
    public sealed partial class ResponseFunctionCallOutput
    {
        /// <summary>
        /// The type of the function tool call output. Always `function_call_output`.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("type")]
        [global::Newtonsoft.Json.JsonConverter(typeof(global::G.JsonConverters.ResponseFunctionCallOutputTypeJsonConverter))]
        public global::G.ResponseFunctionCallOutputType Type { get; set; }

        /// <summary>
        /// The unique ID of the function tool call output.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The unique ID of the function tool call generated by the model.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("call_id", Required = global::Newtonsoft.Json.Required.Always)]
        public string CallId { get; set; } = default!;

        /// <summary>
        /// A JSON string of the output of the function tool call.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("output", Required = global::Newtonsoft.Json.Required.Always)]
        public string Output { get; set; } = default!;

        /// <summary>
        /// The status of the item.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("status")]
        [global::Newtonsoft.Json.JsonConverter(typeof(global::G.JsonConverters.ResponseFunctionCallOutputStatusJsonConverter))]
        public global::G.ResponseFunctionCallOutputStatus? Status { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseFunctionCallOutput" /> class.
        /// </summary>
        /// <param name="callId">
        /// The unique ID of the function tool call generated by the model.
        /// </param>
        /// <param name="output">
        /// A JSON string of the output of the function tool call.
        /// </param>
        /// <param name="type">
        /// The type of the function tool call output. Always `function_call_output`.
        /// </param>
        /// <param name="id">
        /// The unique ID of the function tool call output.
        /// </param>
        /// <param name="status">
        /// The status of the item.
        /// </param>
        public ResponseFunctionCallOutput(
            string callId,
            string output,
            global::G.ResponseFunctionCallOutputType type,
            string? id,
            global::G.ResponseFunctionCallOutputStatus? status)
        {
            this.Type = type;
            this.Id = id;
            this.CallId = callId ?? throw new global::System.ArgumentNullException(nameof(callId));
            this.Output = output ?? throw new global::System.ArgumentNullException(nameof(output));
            this.Status = status;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseFunctionCallOutput" /> class.
        /// </summary>
        public ResponseFunctionCallOutput()
        {
        }
    }
}