//HintName: G.Models.ChatCompletionMessage.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    public sealed partial class ChatCompletionMessage
    {
        /// <summary>
        /// The role of the author of this message.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("role")]
        public global::G.ChatCompletionMessageRole? Role { get; set; }

        /// <summary>
        /// The content of the message.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("content")]
        public string? Content { get; set; }

        /// <summary>
        /// The tool calls generated by the model.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("tool_calls")]
        public global::System.Collections.Generic.IList<global::G.ToolCall>? ToolCalls { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatCompletionMessage" /> class.
        /// </summary>
        /// <param name="role">
        /// The role of the author of this message.
        /// </param>
        /// <param name="content">
        /// The content of the message.
        /// </param>
        /// <param name="toolCalls">
        /// The tool calls generated by the model.
        /// </param>
        public ChatCompletionMessage(
            global::G.ChatCompletionMessageRole? role,
            string? content,
            global::System.Collections.Generic.IList<global::G.ToolCall>? toolCalls)
        {
            this.Role = role;
            this.Content = content;
            this.ToolCalls = toolCalls;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatCompletionMessage" /> class.
        /// </summary>
        public ChatCompletionMessage()
        {
        }
    }
}