//HintName: G.Models.ReasoningContent.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// Sent via the Anthropic Messages API
    /// </summary>
    public sealed partial class ReasoningContent
    {
        /// <summary>
        /// Indicates this is a reasoning/intermediate step.<br/>
        /// Default Value: reasoning
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("type")]
        public string? Type { get; set; }

        /// <summary>
        /// Whether the reasoning content was generated by a reasoner model that processed this step.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("is_native", Required = global::Newtonsoft.Json.Required.Always)]
        public bool IsNative { get; set; } = default!;

        /// <summary>
        /// The intermediate reasoning or thought process content.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("reasoning", Required = global::Newtonsoft.Json.Required.Always)]
        public string Reasoning { get; set; } = default!;

        /// <summary>
        /// A unique identifier for this reasoning step.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("signature")]
        public string? Signature { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ReasoningContent" /> class.
        /// </summary>
        /// <param name="isNative">
        /// Whether the reasoning content was generated by a reasoner model that processed this step.
        /// </param>
        /// <param name="reasoning">
        /// The intermediate reasoning or thought process content.
        /// </param>
        /// <param name="type">
        /// Indicates this is a reasoning/intermediate step.<br/>
        /// Default Value: reasoning
        /// </param>
        /// <param name="signature">
        /// A unique identifier for this reasoning step.
        /// </param>
        public ReasoningContent(
            bool isNative,
            string reasoning,
            string? type,
            string? signature)
        {
            this.Type = type;
            this.IsNative = isNative;
            this.Reasoning = reasoning ?? throw new global::System.ArgumentNullException(nameof(reasoning));
            this.Signature = signature;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ReasoningContent" /> class.
        /// </summary>
        public ReasoningContent()
        {
        }
    }
}