//HintName: G.Models.CreateProjectAutomationConfigVariant2Credentials.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    public sealed partial class CreateProjectAutomationConfigVariant2Credentials
    {
        /// <summary>
        /// 
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("type")]
        public global::G.CreateProjectAutomationConfigVariant2CredentialsType Type { get; set; }

        /// <summary>
        /// The ARN of the IAM role to use
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("role_arn", Required = global::Newtonsoft.Json.Required.Always)]
        public string RoleArn { get; set; } = default!;

        /// <summary>
        /// The automation-specific external id component (auto-generated by default)
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("external_id", Required = global::Newtonsoft.Json.Required.Always)]
        public string ExternalId { get; set; } = default!;

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateProjectAutomationConfigVariant2Credentials" /> class.
        /// </summary>
        /// <param name="roleArn">
        /// The ARN of the IAM role to use
        /// </param>
        /// <param name="externalId">
        /// The automation-specific external id component (auto-generated by default)
        /// </param>
        /// <param name="type"></param>
        public CreateProjectAutomationConfigVariant2Credentials(
            string roleArn,
            string externalId,
            global::G.CreateProjectAutomationConfigVariant2CredentialsType type)
        {
            this.Type = type;
            this.RoleArn = roleArn ?? throw new global::System.ArgumentNullException(nameof(roleArn));
            this.ExternalId = externalId ?? throw new global::System.ArgumentNullException(nameof(externalId));
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateProjectAutomationConfigVariant2Credentials" /> class.
        /// </summary>
        public CreateProjectAutomationConfigVariant2Credentials()
        {
        }
    }
}