//HintName: G.Models.ListArtifactsResponse.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    public sealed partial class ListArtifactsResponse
    {
        /// <summary>
        /// Artifacts generated by the cloud agent. Returns at most 100 artifacts.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("artifacts", Required = global::Newtonsoft.Json.Required.Always)]
        public global::System.Collections.Generic.IList<global::G.Artifact> Artifacts { get; set; } = default!;

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ListArtifactsResponse" /> class.
        /// </summary>
        /// <param name="artifacts">
        /// Artifacts generated by the cloud agent. Returns at most 100 artifacts.
        /// </param>
        public ListArtifactsResponse(
            global::System.Collections.Generic.IList<global::G.Artifact> artifacts)
        {
            this.Artifacts = artifacts ?? throw new global::System.ArgumentNullException(nameof(artifacts));
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ListArtifactsResponse" /> class.
        /// </summary>
        public ListArtifactsResponse()
        {
        }
    }
}