<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" Version="9.6.0" />
    <PackageReference Include="GitHubActionsTestLogger" Version="3.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MSTest" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../libs/tryAGI.Extensions.HttpClientFactory/tryAGI.Extensions.HttpClientFactory.csproj" />
  </ItemGroup>

</Project>
