<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" Version="9.6.0" />
    <PackageReference Include="MSTest" Version="4.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../libs/tryAGI.Extensions.HttpClientFactory/tryAGI.Extensions.HttpClientFactory.csproj" />
  </ItemGroup>

</Project>
