//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.EvaluationRunStatusJsonConverter),
            typeof(global::G.JsonConverters.EvaluationRunStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.EdgeConditionalOperatorJsonConverter),
            typeof(global::G.JsonConverters.EdgeConditionalOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.GetPromptTemplateProvider2JsonConverter),
            typeof(global::G.JsonConverters.GetPromptTemplateProvider2NullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionPromptContentItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.CompletionPromptContentItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionPromptTemplateFormatJsonConverter),
            typeof(global::G.JsonConverters.CompletionPromptTemplateFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionPromptTypeJsonConverter),
            typeof(global::G.JsonConverters.CompletionPromptTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TextContentTypeJsonConverter),
            typeof(global::G.JsonConverters.TextContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ThinkingContentTypeJsonConverter),
            typeof(global::G.JsonConverters.ThinkingContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MediaFormatJsonConverter),
            typeof(global::G.JsonConverters.MediaFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.ImageContentTypeJsonConverter),
            typeof(global::G.JsonConverters.ImageContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MediaContentTypeJsonConverter),
            typeof(global::G.JsonConverters.MediaContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MediaVariableTypeJsonConverter),
            typeof(global::G.JsonConverters.MediaVariableTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.OutputMediaContentTypeJsonConverter),
            typeof(global::G.JsonConverters.OutputMediaContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.OutputMediaContentMediaTypeJsonConverter),
            typeof(global::G.JsonConverters.OutputMediaContentMediaTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CodeContentTypeJsonConverter),
            typeof(global::G.JsonConverters.CodeContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerToolUseContentTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerToolUseContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WebSearchResultTypeJsonConverter),
            typeof(global::G.JsonConverters.WebSearchResultTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WebSearchToolResultContentTypeJsonConverter),
            typeof(global::G.JsonConverters.WebSearchToolResultContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CodeExecutionResultContentTypeJsonConverter),
            typeof(global::G.JsonConverters.CodeExecutionResultContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.McpListToolsContentTypeJsonConverter),
            typeof(global::G.JsonConverters.McpListToolsContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.McpCallContentTypeJsonConverter),
            typeof(global::G.JsonConverters.McpCallContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.McpApprovalRequestContentTypeJsonConverter),
            typeof(global::G.JsonConverters.McpApprovalRequestContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.McpApprovalResponseContentTypeJsonConverter),
            typeof(global::G.JsonConverters.McpApprovalResponseContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BashCodeExecutionToolResultContentTypeJsonConverter),
            typeof(global::G.JsonConverters.BashCodeExecutionToolResultContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TextEditorCodeExecutionToolResultContentTypeJsonConverter),
            typeof(global::G.JsonConverters.TextEditorCodeExecutionToolResultContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ShellCallContentTypeJsonConverter),
            typeof(global::G.JsonConverters.ShellCallContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ShellCallOutputContentTypeJsonConverter),
            typeof(global::G.JsonConverters.ShellCallOutputContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ApplyPatchCallContentTypeJsonConverter),
            typeof(global::G.JsonConverters.ApplyPatchCallContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ApplyPatchCallOutputContentTypeJsonConverter),
            typeof(global::G.JsonConverters.ApplyPatchCallOutputContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BuiltInToolTypeJsonConverter),
            typeof(global::G.JsonConverters.BuiltInToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SystemMessageTemplateFormatJsonConverter),
            typeof(global::G.JsonConverters.SystemMessageTemplateFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.SystemMessageContentItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.SystemMessageContentItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UserMessageTemplateFormatJsonConverter),
            typeof(global::G.JsonConverters.UserMessageTemplateFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.UserMessageContentItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.UserMessageContentItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AssistantMessageTemplateFormatJsonConverter),
            typeof(global::G.JsonConverters.AssistantMessageTemplateFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.AssistantMessageContentVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.AssistantMessageContentVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionMessageTemplateFormatJsonConverter),
            typeof(global::G.JsonConverters.FunctionMessageTemplateFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionMessageContentVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionMessageContentVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DeveloperMessageTemplateFormatJsonConverter),
            typeof(global::G.JsonConverters.DeveloperMessageTemplateFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.DeveloperMessageContentItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.DeveloperMessageContentItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatPromptMessageDiscriminatorRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatPromptMessageDiscriminatorRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatPromptTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatPromptTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetPromptTemplateResponsePromptTemplateDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetPromptTemplateResponsePromptTemplateDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetPromptTemplateRawResponsePromptTemplateDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetPromptTemplateRawResponsePromptTemplateDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionPromptTemplateDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionPromptTemplateDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreatePromptTemplateResponsePromptTemplateDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.CreatePromptTemplateResponsePromptTemplateDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageTemplateFormatJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageTemplateFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageContentItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageContentItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PlaceholderMessageTemplateFormatJsonConverter),
            typeof(global::G.JsonConverters.PlaceholderMessageTemplateFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.PlaceholderMessageContentVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PlaceholderMessageContentVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PlaceholderMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.PlaceholderMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.LogRequestInputDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LogRequestInputDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LogRequestOutputDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LogRequestOutputDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LogRequestStatusJsonConverter),
            typeof(global::G.JsonConverters.LogRequestStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.LogRequestErrorType2JsonConverter),
            typeof(global::G.JsonConverters.LogRequestErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.LogRequestResponseStatusJsonConverter),
            typeof(global::G.JsonConverters.LogRequestResponseStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptBlueprintPromptTemplateDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptBlueprintPromptTemplateDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SpanKindJsonConverter),
            typeof(global::G.JsonConverters.SpanKindNullableJsonConverter),
            typeof(global::G.JsonConverters.StatusCodeJsonConverter),
            typeof(global::G.JsonConverters.StatusCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.EntityTypeJsonConverter),
            typeof(global::G.JsonConverters.EntityTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptEntityMetadataTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptEntityMetadataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SearchRequestLogsRequestSortByJsonConverter),
            typeof(global::G.JsonConverters.SearchRequestLogsRequestSortByNullableJsonConverter),
            typeof(global::G.JsonConverters.SearchRequestLogsRequestSortOrderJsonConverter),
            typeof(global::G.JsonConverters.SearchRequestLogsRequestSortOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.StructuredFilterFieldJsonConverter),
            typeof(global::G.JsonConverters.StructuredFilterFieldNullableJsonConverter),
            typeof(global::G.JsonConverters.StructuredFilterOperatorJsonConverter),
            typeof(global::G.JsonConverters.StructuredFilterOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.StructuredFilterGroupLogicJsonConverter),
            typeof(global::G.JsonConverters.StructuredFilterGroupLogicNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateEvaluationPipelineRequestScoreConfigurationCodeLanguageJsonConverter),
            typeof(global::G.JsonConverters.CreateEvaluationPipelineRequestScoreConfigurationCodeLanguageNullableJsonConverter),
            typeof(global::G.JsonConverters.AddReportColumnRequestColumnTypeJsonConverter),
            typeof(global::G.JsonConverters.AddReportColumnRequestColumnTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListDatasetsStatusJsonConverter),
            typeof(global::G.JsonConverters.ListDatasetsStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ListEvaluationsStatusJsonConverter),
            typeof(global::G.JsonConverters.ListEvaluationsStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetAllPromptTemplatesGetStatusJsonConverter),
            typeof(global::G.JsonConverters.GetAllPromptTemplatesGetStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ListFolderEntitiesApiPublicV2FoldersEntitiesGetFilterType2JsonConverter),
            typeof(global::G.JsonConverters.ListFolderEntitiesApiPublicV2FoldersEntitiesGetFilterType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ListFolderEntitiesApiPublicV2FoldersEntitiesGetFilterTypeItemJsonConverter),
            typeof(global::G.JsonConverters.ListFolderEntitiesApiPublicV2FoldersEntitiesGetFilterTypeItemNullableJsonConverter),
            typeof(global::G.JsonConverters.IngestOtlpTracesContentTypeJsonConverter),
            typeof(global::G.JsonConverters.IngestOtlpTracesContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IngestOtlpTracesContentEncodingJsonConverter),
            typeof(global::G.JsonConverters.IngestOtlpTracesContentEncodingNullableJsonConverter),
            typeof(global::G.JsonConverters.GetRequestSearchSuggestionsFieldJsonConverter),
            typeof(global::G.JsonConverters.GetRequestSearchSuggestionsFieldNullableJsonConverter),
            typeof(global::G.JsonConverters.GetReportResponseStatusJsonConverter),
            typeof(global::G.JsonConverters.GetReportResponseStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetReportScoreResponseScoreScoreTypeJsonConverter),
            typeof(global::G.JsonConverters.GetReportScoreResponseScoreScoreTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetDatasetRowsResponseRowItemTypeJsonConverter),
            typeof(global::G.JsonConverters.GetDatasetRowsResponseRowItemTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetEvaluationRowsResponseRowItemTypeJsonConverter),
            typeof(global::G.JsonConverters.GetEvaluationRowsResponseRowItemTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetEvaluationRowsResponseRowItemStatusJsonConverter),
            typeof(global::G.JsonConverters.GetEvaluationRowsResponseRowItemStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ContentItemJsonConverter),
            typeof(global::G.JsonConverters.ContentItem2JsonConverter),
            typeof(global::G.JsonConverters.ContentItem3JsonConverter),
            typeof(global::G.JsonConverters.ContentVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.ContentVariant1Item2JsonConverter),
            typeof(global::G.JsonConverters.ContentItem4JsonConverter),
            typeof(global::G.JsonConverters.MessagesItemJsonConverter),
            typeof(global::G.JsonConverters.PromptTemplateJsonConverter),
            typeof(global::G.JsonConverters.PromptTemplate2JsonConverter),
            typeof(global::G.JsonConverters.PromptTemplate3JsonConverter),
            typeof(global::G.JsonConverters.PromptTemplate4JsonConverter),
            typeof(global::G.JsonConverters.ContentItem5JsonConverter),
            typeof(global::G.JsonConverters.ToolJsonConverter),
            typeof(global::G.JsonConverters.ContentVariant1Item3JsonConverter),
            typeof(global::G.JsonConverters.InputJsonConverter),
            typeof(global::G.JsonConverters.OutputJsonConverter),
            typeof(global::G.JsonConverters.PromptTemplate5JsonConverter),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.NodeUpdate, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.WebAnnotation, global::G.FileAnnotation, global::G.MapAnnotation, global::G.ContainerFileAnnotation>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.MessageFunctionCall, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ChatToolChoice, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.PromptEntityMetadata, global::G.WorkflowEntityMetadata, global::G.DatasetEntityMetadata, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, double?, bool?, byte[], object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.StructuredFilter, global::G.StructuredFilterGroup>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ListFolderEntitiesApiPublicV2FoldersEntitiesGetFilterType2?, global::System.Collections.Generic.IList<global::G.ListFolderEntitiesApiPublicV2FoldersEntitiesGetFilterTypeItem>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.GetReportScoreResponseScoreDetailsVariant1, global::G.GetReportScoreResponseScoreDetailsVariant2, global::G.GetReportScoreResponseScoreDetailsVariant3, global::G.GetReportScoreResponseScoreDetailsVariant4>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.BadRequestError, global::G.ValidationError>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::System.Collections.Generic.Dictionary<string, global::G.GetWorkflowVersionExecutionResultsResponseVariant12>, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::System.Collections.Generic.Dictionary<string, global::G.GetWorkflowVersionExecutionResultsResponseVariant14>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.FolderExistsError, string>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}