//HintName: JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.ChatRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FinishReasonJsonConverter),
            typeof(global::G.JsonConverters.FinishReasonNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatStreamEventEventTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatStreamEventEventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatStreamEventDiscriminatorEventTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatStreamEventDiscriminatorEventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatStreamEndEventVariant2FinishReasonJsonConverter),
            typeof(global::G.JsonConverters.ChatStreamEndEventVariant2FinishReasonNullableJsonConverter),
            typeof(global::G.JsonConverters.TextContentTypeJsonConverter),
            typeof(global::G.JsonConverters.TextContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UserMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.UserMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolCallV2TypeJsonConverter),
            typeof(global::G.JsonConverters.ToolCallV2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AssistantMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.AssistantMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.SystemMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.SystemMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.DocumentContentTypeJsonConverter),
            typeof(global::G.JsonConverters.DocumentContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolContentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolContentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageV2RoleJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageV2RoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageV2DiscriminatorRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageV2DiscriminatorRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolV2TypeJsonConverter),
            typeof(global::G.JsonConverters.ToolV2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CitationOptionsModeJsonConverter),
            typeof(global::G.JsonConverters.CitationOptionsModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatTypeV2JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatTypeV2NullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatV2DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatV2DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatFinishReasonJsonConverter),
            typeof(global::G.JsonConverters.ChatFinishReasonNullableJsonConverter),
            typeof(global::G.JsonConverters.AssistantMessageResponseRoleJsonConverter),
            typeof(global::G.JsonConverters.AssistantMessageResponseRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.AssistantMessageResponseContentItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.AssistantMessageResponseContentItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatStreamEventTypeTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatStreamEventTypeTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageStartEventVariant2DeltaMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageStartEventVariant2DeltaMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatContentStartEventVariant2DeltaMessageContentTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatContentStartEventVariant2DeltaMessageContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatToolCallStartEventVariant2DeltaToolCallTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatToolCallStartEventVariant2DeltaToolCallTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GenerateStreamEventEventTypeJsonConverter),
            typeof(global::G.JsonConverters.GenerateStreamEventEventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbedInputTypeJsonConverter),
            typeof(global::G.JsonConverters.EmbedInputTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingTypeJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbedFloatsResponseResponseTypeJsonConverter),
            typeof(global::G.JsonConverters.EmbedFloatsResponseResponseTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbedByTypeResponseResponseTypeJsonConverter),
            typeof(global::G.JsonConverters.EmbedByTypeResponseResponseTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbedJobStatusJsonConverter),
            typeof(global::G.JsonConverters.EmbedJobStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbedJobTruncateJsonConverter),
            typeof(global::G.JsonConverters.EmbedJobTruncateNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateEmbedJobRequestTruncateJsonConverter),
            typeof(global::G.JsonConverters.CreateEmbedJobRequestTruncateNullableJsonConverter),
            typeof(global::G.JsonConverters.DatasetValidationStatusJsonConverter),
            typeof(global::G.JsonConverters.DatasetValidationStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.DatasetTypeJsonConverter),
            typeof(global::G.JsonConverters.DatasetTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConnectorAuthStatusJsonConverter),
            typeof(global::G.JsonConverters.ConnectorAuthStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.AuthTokenTypeJsonConverter),
            typeof(global::G.JsonConverters.AuthTokenTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetClusterJobResponseStatusJsonConverter),
            typeof(global::G.JsonConverters.GetClusterJobResponseStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.UpdateClusterJobRequestStatusJsonConverter),
            typeof(global::G.JsonConverters.UpdateClusterJobRequestStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.CompatibleEndpointJsonConverter),
            typeof(global::G.JsonConverters.CompatibleEndpointNullableJsonConverter),
            typeof(global::G.JsonConverters.BaseTypeJsonConverter),
            typeof(global::G.JsonConverters.BaseTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.StrategyJsonConverter),
            typeof(global::G.JsonConverters.StrategyNullableJsonConverter),
            typeof(global::G.JsonConverters.LoraTargetModulesJsonConverter),
            typeof(global::G.JsonConverters.LoraTargetModulesNullableJsonConverter),
            typeof(global::G.JsonConverters.StatusJsonConverter),
            typeof(global::G.JsonConverters.StatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatRequestPromptTruncationJsonConverter),
            typeof(global::G.JsonConverters.ChatRequestPromptTruncationNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatRequestCitationQualityJsonConverter),
            typeof(global::G.JsonConverters.ChatRequestCitationQualityNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatRequestSafetyModeJsonConverter),
            typeof(global::G.JsonConverters.ChatRequestSafetyModeNullableJsonConverter),
            typeof(global::G.JsonConverters.Chatv2RequestSafetyModeJsonConverter),
            typeof(global::G.JsonConverters.Chatv2RequestSafetyModeNullableJsonConverter),
            typeof(global::G.JsonConverters.GenerateRequestTruncateJsonConverter),
            typeof(global::G.JsonConverters.GenerateRequestTruncateNullableJsonConverter),
            typeof(global::G.JsonConverters.GenerateRequestReturnLikelihoodsJsonConverter),
            typeof(global::G.JsonConverters.GenerateRequestReturnLikelihoodsNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbedRequestTruncateJsonConverter),
            typeof(global::G.JsonConverters.EmbedRequestTruncateNullableJsonConverter),
            typeof(global::G.JsonConverters.Embedv2RequestTruncateJsonConverter),
            typeof(global::G.JsonConverters.Embedv2RequestTruncateNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifyRequestTruncateJsonConverter),
            typeof(global::G.JsonConverters.ClassifyRequestTruncateNullableJsonConverter),
            typeof(global::G.JsonConverters.SummarizeRequestLengthJsonConverter),
            typeof(global::G.JsonConverters.SummarizeRequestLengthNullableJsonConverter),
            typeof(global::G.JsonConverters.SummarizeRequestFormatJsonConverter),
            typeof(global::G.JsonConverters.SummarizeRequestFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.SummarizeRequestExtractivenessJsonConverter),
            typeof(global::G.JsonConverters.SummarizeRequestExtractivenessNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatAcceptsJsonConverter),
            typeof(global::G.JsonConverters.ChatAcceptsNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifyResponseClassificationClassificationTypeJsonConverter),
            typeof(global::G.JsonConverters.ClassifyResponseClassificationClassificationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MessageJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatJsonConverter),
            typeof(global::G.JsonConverters.ChatStreamStartEventJsonConverter),
            typeof(global::G.JsonConverters.ChatSearchQueriesGenerationEventJsonConverter),
            typeof(global::G.JsonConverters.ChatSearchResultsEventJsonConverter),
            typeof(global::G.JsonConverters.ChatTextGenerationEventJsonConverter),
            typeof(global::G.JsonConverters.ChatCitationGenerationEventJsonConverter),
            typeof(global::G.JsonConverters.ChatToolCallsGenerationEventJsonConverter),
            typeof(global::G.JsonConverters.ChatStreamEndEventJsonConverter),
            typeof(global::G.JsonConverters.ChatToolCallsChunkEventJsonConverter),
            typeof(global::G.JsonConverters.StreamedChatResponseJsonConverter),
            typeof(global::G.JsonConverters.ContentJsonConverter),
            typeof(global::G.JsonConverters.SourceJsonConverter),
            typeof(global::G.JsonConverters.ToolContentJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageV2JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatV2JsonConverter),
            typeof(global::G.JsonConverters.ContentItemJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageStartEventJsonConverter),
            typeof(global::G.JsonConverters.ChatContentStartEventJsonConverter),
            typeof(global::G.JsonConverters.ChatContentDeltaEventJsonConverter),
            typeof(global::G.JsonConverters.ChatContentEndEventJsonConverter),
            typeof(global::G.JsonConverters.ChatToolPlanDeltaEventJsonConverter),
            typeof(global::G.JsonConverters.ChatToolCallStartEventJsonConverter),
            typeof(global::G.JsonConverters.ChatToolCallDeltaEventJsonConverter),
            typeof(global::G.JsonConverters.ChatToolCallEndEventJsonConverter),
            typeof(global::G.JsonConverters.CitationStartEventJsonConverter),
            typeof(global::G.JsonConverters.CitationEndEventJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageEndEventJsonConverter),
            typeof(global::G.JsonConverters.StreamedChatResponseV2JsonConverter),
            typeof(global::G.JsonConverters.GenerateStreamTextJsonConverter),
            typeof(global::G.JsonConverters.GenerateStreamEndJsonConverter),
            typeof(global::G.JsonConverters.GenerateStreamErrorJsonConverter),
            typeof(global::G.JsonConverters.GenerateStreamedResponseJsonConverter),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.Content>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.OneOf<global::G.TextContent>>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.TextContent>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.OneOf<global::G.TextContent>>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.TextContent>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ToolContent>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::G.Document>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::G.RerankDocument>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::G.RerankDocument>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.NonStreamedChatResponse, global::G.StreamedChatResponse?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ChatResponse, global::G.StreamedChatResponseV2?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.EmbedFloatsResponse, global::G.EmbedByTypeResponse>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}