//HintName: G.Models.ChatCompletionMessage.g.cs

#pragma warning disable CS0618 // Type or member is obsolete

#nullable enable

namespace G
{
    /// <summary>
    /// A chat completion message generated by the model.
    /// </summary>
    public sealed partial class ChatCompletionMessage
    {
        /// <summary>
        /// The contents of the message.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("content")]
        public string? Content { get; set; }

        /// <summary>
        /// The refusal message generated by the model.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("refusal")]
        public string? Refusal { get; set; }

        /// <summary>
        /// The role of the author of this message.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("role")]
        [global::Newtonsoft.Json.JsonConverter(typeof(global::G.JsonConverters.ChatCompletionMessageRoleJsonConverter))]
        public global::G.ChatCompletionMessageRole Role { get; set; }

        /// <summary>
        /// Annotations for the message, when applicable, as when using the<br/>
        /// [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("annotations")]
        public global::System.Collections.Generic.IList<global::G.ChatCompletionMessageAnnotation>? Annotations { get; set; }

        /// <summary>
        /// If the audio output modality is requested, this object contains data about the<br/>
        /// audio response from the model.<br/>
        /// [Learn more](https://platform.openai.com/docs/guides/audio).
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("audio")]
        public global::G.ChatCompletionAudio? Audio { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("function_call")]
        [global::System.Obsolete("This property marked as deprecated.")]
        public global::G.ChatCompletionMessageFunctionCall? FunctionCall { get; set; }

        /// <summary>
        /// The tool calls generated by the model, such as function calls.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("tool_calls")]
        public global::System.Collections.Generic.IList<global::G.ChatCompletionMessageToolCall>? ToolCalls { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatCompletionMessage" /> class.
        /// </summary>
        /// <param name="content">
        /// The contents of the message.
        /// </param>
        /// <param name="refusal">
        /// The refusal message generated by the model.
        /// </param>
        /// <param name="role">
        /// The role of the author of this message.
        /// </param>
        /// <param name="annotations">
        /// Annotations for the message, when applicable, as when using the<br/>
        /// [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).
        /// </param>
        /// <param name="audio">
        /// If the audio output modality is requested, this object contains data about the<br/>
        /// audio response from the model.<br/>
        /// [Learn more](https://platform.openai.com/docs/guides/audio).
        /// </param>
        /// <param name="toolCalls">
        /// The tool calls generated by the model, such as function calls.
        /// </param>
        public ChatCompletionMessage(
            string? content,
            string? refusal,
            global::G.ChatCompletionMessageRole role,
            global::System.Collections.Generic.IList<global::G.ChatCompletionMessageAnnotation>? annotations,
            global::G.ChatCompletionAudio? audio,
            global::System.Collections.Generic.IList<global::G.ChatCompletionMessageToolCall>? toolCalls)
        {
            this.Content = content;
            this.Refusal = refusal;
            this.Role = role;
            this.Annotations = annotations;
            this.Audio = audio;
            this.ToolCalls = toolCalls;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatCompletionMessage" /> class.
        /// </summary>
        public ChatCompletionMessage()
        {
        }
    }
}