//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.TTSRequestFormatJsonConverter),
            typeof(global::G.JsonConverters.TTSRequestFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.TTSRequestLatencyJsonConverter),
            typeof(global::G.JsonConverters.TTSRequestLatencyNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelEntityTypeJsonConverter),
            typeof(global::G.JsonConverters.ModelEntityTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelEntityTrainModeJsonConverter),
            typeof(global::G.JsonConverters.ModelEntityTrainModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelEntityStateJsonConverter),
            typeof(global::G.JsonConverters.ModelEntityStateNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelEntityVisibilityJsonConverter),
            typeof(global::G.JsonConverters.ModelEntityVisibilityNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateModelRequestVisibilityJsonConverter),
            typeof(global::G.JsonConverters.CreateModelRequestVisibilityNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateModelRequestTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateModelRequestTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateModelRequestTrainModeJsonConverter),
            typeof(global::G.JsonConverters.CreateModelRequestTrainModeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateModelRequestVisibility2JsonConverter),
            typeof(global::G.JsonConverters.CreateModelRequestVisibility2NullableJsonConverter),
            typeof(global::G.JsonConverters.CreateModelRequestType2JsonConverter),
            typeof(global::G.JsonConverters.CreateModelRequestType2NullableJsonConverter),
            typeof(global::G.JsonConverters.CreateModelRequestTrainMode2JsonConverter),
            typeof(global::G.JsonConverters.CreateModelRequestTrainMode2NullableJsonConverter),
            typeof(global::G.JsonConverters.PatchModelRequestVisibility2JsonConverter),
            typeof(global::G.JsonConverters.PatchModelRequestVisibility2NullableJsonConverter),
            typeof(global::G.JsonConverters.PatchModelRequestVisibility4JsonConverter),
            typeof(global::G.JsonConverters.PatchModelRequestVisibility4NullableJsonConverter),
            typeof(global::G.JsonConverters.PatchModelRequestVisibility6JsonConverter),
            typeof(global::G.JsonConverters.PatchModelRequestVisibility6NullableJsonConverter),
            typeof(global::G.JsonConverters.PatchModelRequestVisibility8JsonConverter),
            typeof(global::G.JsonConverters.PatchModelRequestVisibility8NullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTtsModelJsonConverter),
            typeof(global::G.JsonConverters.CreateTtsModelNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelSortByJsonConverter),
            typeof(global::G.JsonConverters.GetModelSortByNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTtsResponseItemInJsonConverter),
            typeof(global::G.JsonConverters.CreateTtsResponseItemInNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateAsrResponseItemInJsonConverter),
            typeof(global::G.JsonConverters.CreateAsrResponseItemInNullableJsonConverter),
            typeof(global::G.JsonConverters.GetWalletPackageResponseItemInJsonConverter),
            typeof(global::G.JsonConverters.GetWalletPackageResponseItemInNullableJsonConverter),
            typeof(global::G.JsonConverters.GetWalletApiCreditResponseItemInJsonConverter),
            typeof(global::G.JsonConverters.GetWalletApiCreditResponseItemInNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelResponseItemInJsonConverter),
            typeof(global::G.JsonConverters.GetModelResponseItemInNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateModelResponseTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateModelResponseTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateModelResponseTrainModeJsonConverter),
            typeof(global::G.JsonConverters.CreateModelResponseTrainModeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateModelResponseStateJsonConverter),
            typeof(global::G.JsonConverters.CreateModelResponseStateNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateModelResponseVisibilityJsonConverter),
            typeof(global::G.JsonConverters.CreateModelResponseVisibilityNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateModelResponseItemInJsonConverter),
            typeof(global::G.JsonConverters.CreateModelResponseItemInNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelResponseTypeJsonConverter),
            typeof(global::G.JsonConverters.GetModelResponseTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelResponseTrainModeJsonConverter),
            typeof(global::G.JsonConverters.GetModelResponseTrainModeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelResponseStateJsonConverter),
            typeof(global::G.JsonConverters.GetModelResponseStateNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelResponseVisibilityJsonConverter),
            typeof(global::G.JsonConverters.GetModelResponseVisibilityNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelResponseItemIn2JsonConverter),
            typeof(global::G.JsonConverters.GetModelResponseItemIn2NullableJsonConverter),
            typeof(global::G.JsonConverters.PatchModelResponseItemInJsonConverter),
            typeof(global::G.JsonConverters.PatchModelResponseItemInNullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteModelResponseItemInJsonConverter),
            typeof(global::G.JsonConverters.DeleteModelResponseItemInNullableJsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.ReferenceAudio>, global::System.Collections.Generic.IList<global::System.Collections.Generic.IList<global::G.ReferenceAudio>>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<byte[]>, byte[]>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<byte[]>, byte[]>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string, object>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}