<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
    <GeneratePackageOnBuild Condition="'$(PublishAot)' == 'true'">false</GeneratePackageOnBuild>
    <NoWarn>$(NoWarn);CA1724;CA1303</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="NuGet">
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>autosdk</ToolCommandName>
    <Description>Allows you to partially (for example, only models) or completely generate a native (without dependencies) C# client sdk according to the OpenAPI specification. Inspired by NSwag.</Description>
    <PackageTags>openapi;sdk;generator;source generator;dotnet;netstandard;netframework;native;nswag;incremental;cli</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="H.Resources.Generator" Version="1.8.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <Compile Remove="Resources\**\*.cs" />
    <AdditionalFiles Remove="Resources\obj\**" />
    <AdditionalFiles Remove="Resources\bin\**" />
    <EmbeddedResource Remove="Resources\obj\**" />
    <EmbeddedResource Remove="Resources\bin\**" />
    <PackageReference Include="Microsoft.OpenApi" Version="$(MicrosoftOpenApiVersion)" />
    <PackageReference Include="Microsoft.OpenApi.YamlReader" Version="$(MicrosoftOpenApiVersion)" />
    <PackageReference Include="Google.Protobuf" Version="3.36.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoSDK\AutoSDK.csproj" />
    <ProjectReference Include="..\AutoSDK.CSharp\AutoSDK.CSharp.csproj" />
    <ProjectReference Include="..\AutoSDK.Docs\AutoSDK.Docs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AutoSDK.UnitTests, PublicKey=00240000048000009400000006020000002400005253413100040000010001001f19b61333e1eb711068408b81d6b1c75f72c3c87c0395f3aa057a917677d4bb6e6e50904842c62c8bef6633723c97df81f47ee772246fe89858fd7d7e68902cdc67919265616cc74593771e83b3534dde9993eb0ed7e119be2996aca3149326e0dec36bdc6084b93de79d32e6a8b3c55f8da727c52a08f9c3ab7d9af6e0ecca" />
  </ItemGroup>

</Project>
