//HintName: JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.TextChunkTypeJsonConverter),
            typeof(global::G.JsonConverters.TextChunkTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SystemMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.SystemMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ImageURLChunkTypeJsonConverter),
            typeof(global::G.JsonConverters.ImageURLChunkTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DocumentURLChunkTypeJsonConverter),
            typeof(global::G.JsonConverters.DocumentURLChunkTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ReferenceChunkTypeJsonConverter),
            typeof(global::G.JsonConverters.ReferenceChunkTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ContentChunkDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ContentChunkDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UserMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.UserMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.AssistantMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.AssistantMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolTypesJsonConverter),
            typeof(global::G.JsonConverters.ToolTypesNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsCompletionRequestMessageDiscriminatorRoleJsonConverter),
            typeof(global::G.JsonConverters.AgentsCompletionRequestMessageDiscriminatorRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.PredictionTypeJsonConverter),
            typeof(global::G.JsonConverters.PredictionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatsJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatsNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolChoiceEnumJsonConverter),
            typeof(global::G.JsonConverters.ToolChoiceEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiEndpointJsonConverter),
            typeof(global::G.JsonConverters.ApiEndpointNullableJsonConverter),
            typeof(global::G.JsonConverters.ArchiveFTModelOutObjectJsonConverter),
            typeof(global::G.JsonConverters.ArchiveFTModelOutObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.BaseModelCardTypeJsonConverter),
            typeof(global::G.JsonConverters.BaseModelCardTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchJobOutObjectJsonConverter),
            typeof(global::G.JsonConverters.BatchJobOutObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchJobStatusJsonConverter),
            typeof(global::G.JsonConverters.BatchJobStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchJobsOutObjectJsonConverter),
            typeof(global::G.JsonConverters.BatchJobsOutObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.InstructRequestMessageDiscriminatorRoleJsonConverter),
            typeof(global::G.JsonConverters.InstructRequestMessageDiscriminatorRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionChoiceFinishReasonJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionChoiceFinishReasonNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageDiscriminatorRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageDiscriminatorRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatModerationRequestInputVariant1ItemDiscriminatorRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatModerationRequestInputVariant1ItemDiscriminatorRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatModerationRequestInputVariant2ItemItemDiscriminatorRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatModerationRequestInputVariant2ItemItemDiscriminatorRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.FTClassifierLossFunctionJsonConverter),
            typeof(global::G.JsonConverters.FTClassifierLossFunctionNullableJsonConverter),
            typeof(global::G.JsonConverters.WandbIntegrationOutTypeJsonConverter),
            typeof(global::G.JsonConverters.WandbIntegrationOutTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifierDetailedJobOutIntegrationDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ClassifierDetailedJobOutIntegrationDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifierDetailedJobOutJobTypeJsonConverter),
            typeof(global::G.JsonConverters.ClassifierDetailedJobOutJobTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FineTuneableModelJsonConverter),
            typeof(global::G.JsonConverters.FineTuneableModelNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifierDetailedJobOutObjectJsonConverter),
            typeof(global::G.JsonConverters.ClassifierDetailedJobOutObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifierDetailedJobOutStatusJsonConverter),
            typeof(global::G.JsonConverters.ClassifierDetailedJobOutStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifierFTModelOutModelTypeJsonConverter),
            typeof(global::G.JsonConverters.ClassifierFTModelOutModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifierFTModelOutObjectJsonConverter),
            typeof(global::G.JsonConverters.ClassifierFTModelOutObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifierJobOutIntegrationDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ClassifierJobOutIntegrationDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifierJobOutJobTypeJsonConverter),
            typeof(global::G.JsonConverters.ClassifierJobOutJobTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifierJobOutObjectJsonConverter),
            typeof(global::G.JsonConverters.ClassifierJobOutObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifierJobOutStatusJsonConverter),
            typeof(global::G.JsonConverters.ClassifierJobOutStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionResponseStreamChoiceFinishReasonJsonConverter),
            typeof(global::G.JsonConverters.CompletionResponseStreamChoiceFinishReasonNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionDetailedJobOutIntegrationDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.CompletionDetailedJobOutIntegrationDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionDetailedJobOutJobTypeJsonConverter),
            typeof(global::G.JsonConverters.CompletionDetailedJobOutJobTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionDetailedJobOutObjectJsonConverter),
            typeof(global::G.JsonConverters.CompletionDetailedJobOutObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.GithubRepositoryOutTypeJsonConverter),
            typeof(global::G.JsonConverters.GithubRepositoryOutTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionDetailedJobOutRepositorieDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.CompletionDetailedJobOutRepositorieDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionDetailedJobOutStatusJsonConverter),
            typeof(global::G.JsonConverters.CompletionDetailedJobOutStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionFTModelOutModelTypeJsonConverter),
            typeof(global::G.JsonConverters.CompletionFTModelOutModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionFTModelOutObjectJsonConverter),
            typeof(global::G.JsonConverters.CompletionFTModelOutObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionJobOutIntegrationDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.CompletionJobOutIntegrationDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionJobOutJobTypeJsonConverter),
            typeof(global::G.JsonConverters.CompletionJobOutJobTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionJobOutObjectJsonConverter),
            typeof(global::G.JsonConverters.CompletionJobOutObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionJobOutRepositorieDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.CompletionJobOutRepositorieDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CompletionJobOutStatusJsonConverter),
            typeof(global::G.JsonConverters.CompletionJobOutStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.FTModelCardTypeJsonConverter),
            typeof(global::G.JsonConverters.FTModelCardTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FilePurposeJsonConverter),
            typeof(global::G.JsonConverters.FilePurposeNullableJsonConverter),
            typeof(global::G.JsonConverters.SampleTypeJsonConverter),
            typeof(global::G.JsonConverters.SampleTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SourceJsonConverter),
            typeof(global::G.JsonConverters.SourceNullableJsonConverter),
            typeof(global::G.JsonConverters.FineTuneableModelTypeJsonConverter),
            typeof(global::G.JsonConverters.FineTuneableModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GithubRepositoryInTypeJsonConverter),
            typeof(global::G.JsonConverters.GithubRepositoryInTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WandbIntegrationTypeJsonConverter),
            typeof(global::G.JsonConverters.WandbIntegrationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.JobInIntegrationDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.JobInIntegrationDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.JobInRepositorieDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.JobInRepositorieDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.JobsOutDataItemDiscriminatorJobTypeJsonConverter),
            typeof(global::G.JsonConverters.JobsOutDataItemDiscriminatorJobTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.JobsOutObjectJsonConverter),
            typeof(global::G.JsonConverters.JobsOutObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.LegacyJobMetadataOutObjectJsonConverter),
            typeof(global::G.JsonConverters.LegacyJobMetadataOutObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelListDataItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ModelListDataItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UnarchiveFTModelOutObjectJsonConverter),
            typeof(global::G.JsonConverters.UnarchiveFTModelOutObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningGetFineTuningJobsStatusJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningGetFineTuningJobsStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningCreateFineTuningJobResponseVariant1DiscriminatorJobTypeJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningCreateFineTuningJobResponseVariant1DiscriminatorJobTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningGetFineTuningJobResponseDiscriminatorJobTypeJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningGetFineTuningJobResponseDiscriminatorJobTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningCancelFineTuningJobResponseDiscriminatorJobTypeJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningCancelFineTuningJobResponseDiscriminatorJobTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningStartFineTuningJobResponseDiscriminatorJobTypeJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningStartFineTuningJobResponseDiscriminatorJobTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningUpdateFineTunedModelResponseDiscriminatorModelTypeJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningUpdateFineTunedModelResponseDiscriminatorModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.RetrieveModelV1ModelsModelIdGetResponseDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.RetrieveModelV1ModelsModelIdGetResponseDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MessagesItemJsonConverter),
            typeof(global::G.JsonConverters.ContentChunkJsonConverter),
            typeof(global::G.JsonConverters.ChatClassificationRequestInputsJsonConverter),
            typeof(global::G.JsonConverters.MessagesItem3JsonConverter),
            typeof(global::G.JsonConverters.MessagesItem2JsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionResponseJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionResponseBaseJsonConverter),
            typeof(global::G.JsonConverters.InputVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.InputVariant2ItemItemJsonConverter),
            typeof(global::G.JsonConverters.IntegrationsItemJsonConverter),
            typeof(global::G.JsonConverters.IntegrationsItem2JsonConverter),
            typeof(global::G.JsonConverters.IntegrationsItem3JsonConverter),
            typeof(global::G.JsonConverters.RepositoriesItemJsonConverter),
            typeof(global::G.JsonConverters.IntegrationsItem4JsonConverter),
            typeof(global::G.JsonConverters.RepositoriesItem2JsonConverter),
            typeof(global::G.JsonConverters.EmbeddingResponseJsonConverter),
            typeof(global::G.JsonConverters.FIMCompletionResponseJsonConverter),
            typeof(global::G.JsonConverters.IntegrationsItem5JsonConverter),
            typeof(global::G.JsonConverters.RepositoriesItem3JsonConverter),
            typeof(global::G.JsonConverters.DataItemJsonConverter),
            typeof(global::G.JsonConverters.DataItem2JsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningCreateFineTuningJobResponseVariant1JsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningGetFineTuningJobResponseJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningCancelFineTuningJobResponseJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningStartFineTuningJobResponseJsonConverter),
            typeof(global::G.JsonConverters.JobsApiRoutesFineTuningUpdateFineTunedModelResponseJsonConverter),
            typeof(global::G.JsonConverters.RetrieveModelV1ModelsModelIdGetResponseJsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.TextChunk>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object, global::System.Collections.Generic.IList<global::G.ContentChunk>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ImageURL, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object, global::System.Collections.Generic.IList<global::G.ContentChunk>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object, global::System.Collections.Generic.IList<global::G.ContentChunk>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ToolChoice3, global::G.ToolChoiceEnum?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ToolChoice3, global::G.ToolChoiceEnum?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.InputVariant1Item>, global::System.Collections.Generic.IList<global::System.Collections.Generic.IList<global::G.InputVariant2ItemItem>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object, global::System.Collections.Generic.IList<global::G.ContentChunk>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.CompletionTrainingParametersIn, global::G.ClassifierTrainingParametersIn>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.DocumentURLChunk, global::G.ImageURLChunk>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.JobsApiRoutesFineTuningCreateFineTuningJobResponseVariant1?, global::G.LegacyJobMetadataOut>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}