//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.CreateImageToVideoRequestGen4TurboRatioJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestGen4TurboRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestGen4TurboContentModerationPublicFigureThresholdJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestGen4TurboContentModerationPublicFigureThresholdNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestVeo31PromptImagePromptImagePositionJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestVeo31PromptImagePromptImagePositionNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestVeo31RatioJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestVeo31RatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestGen3aTurboPromptImagePromptImagePositionJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestGen3aTurboPromptImagePromptImagePositionNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestGen3aTurboRatioJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestGen3aTurboRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestGen3aTurboContentModerationPublicFigureThresholdJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestGen3aTurboContentModerationPublicFigureThresholdNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestVeo31FastPromptImagePromptImagePositionJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestVeo31FastPromptImagePromptImagePositionNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestVeo31FastRatioJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestVeo31FastRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestVeo3RatioJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestVeo3RatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToVideoRequestVeo31RatioJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToVideoRequestVeo31RatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToVideoRequestVeo31FastRatioJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToVideoRequestVeo31FastRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToVideoRequestVeo3RatioJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToVideoRequestVeo3RatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateVideoToVideoRequestGen4AlephRatioJsonConverter),
            typeof(global::G.JsonConverters.CreateVideoToVideoRequestGen4AlephRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateVideoToVideoRequestGen4AlephContentModerationPublicFigureThresholdJsonConverter),
            typeof(global::G.JsonConverters.CreateVideoToVideoRequestGen4AlephContentModerationPublicFigureThresholdNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToImageRequestGen4ImageTurboRatioJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToImageRequestGen4ImageTurboRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToImageRequestGen4ImageTurboContentModerationPublicFigureThresholdJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToImageRequestGen4ImageTurboContentModerationPublicFigureThresholdNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToImageRequestGen4ImageRatioJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToImageRequestGen4ImageRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToImageRequestGen4ImageContentModerationPublicFigureThresholdJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToImageRequestGen4ImageContentModerationPublicFigureThresholdNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToImageRequestGemini25FlashRatioJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToImageRequestGemini25FlashRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateCharacterPerformanceRequestActTwoRatioJsonConverter),
            typeof(global::G.JsonConverters.CreateCharacterPerformanceRequestActTwoRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateCharacterPerformanceRequestActTwoContentModerationPublicFigureThresholdJsonConverter),
            typeof(global::G.JsonConverters.CreateCharacterPerformanceRequestActTwoContentModerationPublicFigureThresholdNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateSpeechToSpeechRequestElevenMultilingualStsV2VoiceRunwayPresetVoicePresetIdJsonConverter),
            typeof(global::G.JsonConverters.CreateSpeechToSpeechRequestElevenMultilingualStsV2VoiceRunwayPresetVoicePresetIdNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToSpeechRequestElevenMultilingualV2VoiceRunwayPresetVoicePresetIdJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToSpeechRequestElevenMultilingualV2VoiceRunwayPresetVoicePresetIdNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateVoiceDubbingRequestElevenVoiceDubbingTargetLangJsonConverter),
            typeof(global::G.JsonConverters.CreateVoiceDubbingRequestElevenVoiceDubbingTargetLangNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateUploadsRequestTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateUploadsRequestTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateOrganizationUsageResponseResultUsedCreditModelJsonConverter),
            typeof(global::G.JsonConverters.CreateOrganizationUsageResponseResultUsedCreditModelNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateOrganizationUsageResponseModelJsonConverter),
            typeof(global::G.JsonConverters.CreateOrganizationUsageResponseModelNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateImageToVideoRequestJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToVideoRequestJsonConverter),
            typeof(global::G.JsonConverters.CreateVideoToVideoRequestJsonConverter),
            typeof(global::G.JsonConverters.ReferencesItemJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToImageRequestJsonConverter),
            typeof(global::G.JsonConverters.CreateCharacterPerformanceRequestJsonConverter),
            typeof(global::G.JsonConverters.CharacterJsonConverter),
            typeof(global::G.JsonConverters.CreateSoundEffectRequestJsonConverter),
            typeof(global::G.JsonConverters.CreateSpeechToSpeechRequestJsonConverter),
            typeof(global::G.JsonConverters.MediaJsonConverter),
            typeof(global::G.JsonConverters.CreateTextToSpeechRequestJsonConverter),
            typeof(global::G.JsonConverters.CreateVoiceDubbingRequestJsonConverter),
            typeof(global::G.JsonConverters.CreateVoiceIsolationRequestJsonConverter),
            typeof(global::G.JsonConverters.GetTasksResponseJsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string?, global::System.Collections.Generic.IList<global::G.CreateImageToVideoRequestGen4TurboPromptImagePromptImage>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string?, global::System.Collections.Generic.IList<global::G.CreateImageToVideoRequestVeo31PromptImagePromptImage>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string?, global::System.Collections.Generic.IList<global::G.CreateImageToVideoRequestGen3aTurboPromptImagePromptImage>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string?, global::System.Collections.Generic.IList<global::G.CreateImageToVideoRequestVeo31FastPromptImagePromptImage>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string?, global::System.Collections.Generic.IList<global::G.CreateImageToVideoRequestVeo3PromptImagePromptImage>>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}