//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.RequestGen4TurboRatioJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4TurboRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4TurboContentModerationPublicFigureThresholdJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4TurboContentModerationPublicFigureThresholdNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestVeo31PromptImagePromptImagePositionJsonConverter),
            typeof(global::G.JsonConverters.RequestVeo31PromptImagePromptImagePositionNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestVeo31RatioJsonConverter),
            typeof(global::G.JsonConverters.RequestVeo31RatioNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestGen3aTurboPromptImagePromptImagePositionJsonConverter),
            typeof(global::G.JsonConverters.RequestGen3aTurboPromptImagePromptImagePositionNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestGen3aTurboRatioJsonConverter),
            typeof(global::G.JsonConverters.RequestGen3aTurboRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestGen3aTurboContentModerationPublicFigureThresholdJsonConverter),
            typeof(global::G.JsonConverters.RequestGen3aTurboContentModerationPublicFigureThresholdNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestVeo31FastPromptImagePromptImagePositionJsonConverter),
            typeof(global::G.JsonConverters.RequestVeo31FastPromptImagePromptImagePositionNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestVeo31FastRatioJsonConverter),
            typeof(global::G.JsonConverters.RequestVeo31FastRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestVeo3RatioJsonConverter),
            typeof(global::G.JsonConverters.RequestVeo3RatioNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestVeo31Ratio2JsonConverter),
            typeof(global::G.JsonConverters.RequestVeo31Ratio2NullableJsonConverter),
            typeof(global::G.JsonConverters.RequestVeo31FastRatio2JsonConverter),
            typeof(global::G.JsonConverters.RequestVeo31FastRatio2NullableJsonConverter),
            typeof(global::G.JsonConverters.RequestVeo3Ratio2JsonConverter),
            typeof(global::G.JsonConverters.RequestVeo3Ratio2NullableJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4AlephRatioJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4AlephRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4AlephContentModerationPublicFigureThresholdJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4AlephContentModerationPublicFigureThresholdNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4ImageTurboRatioJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4ImageTurboRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4ImageTurboContentModerationPublicFigureThresholdJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4ImageTurboContentModerationPublicFigureThresholdNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4ImageRatioJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4ImageRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4ImageContentModerationPublicFigureThresholdJsonConverter),
            typeof(global::G.JsonConverters.RequestGen4ImageContentModerationPublicFigureThresholdNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestGemini25FlashRatioJsonConverter),
            typeof(global::G.JsonConverters.RequestGemini25FlashRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestActTwoRatioJsonConverter),
            typeof(global::G.JsonConverters.RequestActTwoRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestActTwoContentModerationPublicFigureThresholdJsonConverter),
            typeof(global::G.JsonConverters.RequestActTwoContentModerationPublicFigureThresholdNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestElevenMultilingualStsV2VoiceRunwayPresetVoicePresetIdJsonConverter),
            typeof(global::G.JsonConverters.RequestElevenMultilingualStsV2VoiceRunwayPresetVoicePresetIdNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestElevenMultilingualV2VoiceRunwayPresetVoicePresetIdJsonConverter),
            typeof(global::G.JsonConverters.RequestElevenMultilingualV2VoiceRunwayPresetVoicePresetIdNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestElevenVoiceDubbingTargetLangJsonConverter),
            typeof(global::G.JsonConverters.RequestElevenVoiceDubbingTargetLangNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestTypeJsonConverter),
            typeof(global::G.JsonConverters.RequestTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseResultUsedCreditModelJsonConverter),
            typeof(global::G.JsonConverters.ResponseResultUsedCreditModelNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseModelJsonConverter),
            typeof(global::G.JsonConverters.ResponseModelNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestJsonConverter),
            typeof(global::G.JsonConverters.Request2JsonConverter),
            typeof(global::G.JsonConverters.Request3JsonConverter),
            typeof(global::G.JsonConverters.ReferencesItemJsonConverter),
            typeof(global::G.JsonConverters.Request4JsonConverter),
            typeof(global::G.JsonConverters.Request5JsonConverter),
            typeof(global::G.JsonConverters.CharacterJsonConverter),
            typeof(global::G.JsonConverters.Request6JsonConverter),
            typeof(global::G.JsonConverters.Request7JsonConverter),
            typeof(global::G.JsonConverters.MediaJsonConverter),
            typeof(global::G.JsonConverters.Request8JsonConverter),
            typeof(global::G.JsonConverters.Request9JsonConverter),
            typeof(global::G.JsonConverters.Request10JsonConverter),
            typeof(global::G.JsonConverters.ResponseJsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string?, global::System.Collections.Generic.IList<global::G.RequestGen4TurboPromptImagePromptImage>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string?, global::System.Collections.Generic.IList<global::G.RequestVeo31PromptImagePromptImage>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string?, global::System.Collections.Generic.IList<global::G.RequestGen3aTurboPromptImagePromptImage>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string?, global::System.Collections.Generic.IList<global::G.RequestVeo31FastPromptImagePromptImage>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string?, global::System.Collections.Generic.IList<global::G.RequestVeo3PromptImagePromptImage>>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}