//HintName: G.Models.ApiDmViewsCreateRequestDataFiltersItemFilter.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// Filter identifier, it should start with `filter:tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
    /// </summary>
    [global::System.Runtime.Serialization.DataContract]
    public enum ApiDmViewsCreateRequestDataFiltersItemFilter
    {
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:agreement")]
        Filter_tasks_agreement,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:annotations_results")]
        Filter_tasks_annotationsResults,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:annotators")]
        Filter_tasks_annotators,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:cancelled_annotations")]
        Filter_tasks_cancelledAnnotations,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:comments")]
        Filter_tasks_comments,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:completed_at")]
        Filter_tasks_completedAt,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:created_at")]
        Filter_tasks_createdAt,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:file_upload")]
        Filter_tasks_fileUpload,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:ground_truth")]
        Filter_tasks_groundTruth,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:id")]
        Filter_tasks_id,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:inner_id")]
        Filter_tasks_innerId,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:predictions_model_versions")]
        Filter_tasks_predictionsModelVersions,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:predictions_results")]
        Filter_tasks_predictionsResults,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:predictions_score")]
        Filter_tasks_predictionsScore,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:reviewed")]
        Filter_tasks_reviewed,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:reviewers")]
        Filter_tasks_reviewers,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:reviews_accepted")]
        Filter_tasks_reviewsAccepted,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:reviews_rejected")]
        Filter_tasks_reviewsRejected,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:total_annotations")]
        Filter_tasks_totalAnnotations,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:total_predictions")]
        Filter_tasks_totalPredictions,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:unresolved_comment_count")]
        Filter_tasks_unresolvedCommentCount,
        /// <summary>
        /// tasks:` prefix, e.g. `filter:tasks:agreement`. For `task.data` fields it may look like `filter:tasks:data.field_name`. If you need more info about columns, check the [Get data manager columns](#tag/Data-Manager/operation/api_dm_columns_list) API endpoint. Possible values:&lt;li&gt;`filter:tasks:agreement` (Number) Agreement for annotation results for a specific task (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:annotations_results` (String) Annotation results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:annotators` (List) Annotators that completed the task (Community). Can include assigned annotators (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:cancelled_annotations` (Number) Number of cancelled or skipped annotations for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:comments` (Number) Number of comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:completed_at` (Datetime) Time when a task was fully annotated&lt;/li&gt;&lt;li&gt;`filter:tasks:created_at` (Datetime) Time the task was created at&lt;/li&gt;&lt;li&gt;`filter:tasks:file_upload` (String) Name of the file uploaded to create the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:ground_truth` (Boolean) Ground truth status of the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:id` (Number) Task ID&lt;/li&gt;&lt;li&gt;`filter:tasks:inner_id` (Number) Task Inner ID, it starts from 1 for all projects&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_model_versions` (String) Model version used for the predictions&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_results` (String) Prediction results for the tasks&lt;/li&gt;&lt;li&gt;`filter:tasks:predictions_score` (Number) Prediction score for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewed` (Boolean) Whether the tasks have been reviewed (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviewers` (String) Reviewers that reviewed the task, or assigned reviewers (Enterprise only). Important note: the filter `type` should be List, but the filter `value` is integer&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_accepted` (Number) Number of annotations accepted for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:reviews_rejected` (Number) Number of annotations rejected for a task in review (Enterprise only)&lt;/li&gt;&lt;li&gt;`filter:tasks:total_annotations` (Number) Total number of annotations on a task&lt;/li&gt;&lt;li&gt;`filter:tasks:total_predictions` (Number) Total number of predictions for the task&lt;/li&gt;&lt;li&gt;`filter:tasks:unresolved_comment_count` (Number) Number of unresolved comments in a task&lt;/li&gt;&lt;li&gt;`filter:tasks:updated_at` (Datetime) Time the task was updated at (e.g. new annotation was created, review added, etc)&lt;/li&gt;
        /// </summary>
        [global::System.Runtime.Serialization.EnumMember(Value="filter:tasks:updated_at")]
        Filter_tasks_updatedAt,
    }

    /// <summary>
    /// Enum extensions to do fast conversions without the reflection.
    /// </summary>
    public static class ApiDmViewsCreateRequestDataFiltersItemFilterExtensions
    {
        /// <summary>
        /// Converts an enum to a string.
        /// </summary>
        public static string ToValueString(this ApiDmViewsCreateRequestDataFiltersItemFilter value)
        {
            return value switch
            {
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_agreement => "filter:tasks:agreement",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_annotationsResults => "filter:tasks:annotations_results",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_annotators => "filter:tasks:annotators",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_cancelledAnnotations => "filter:tasks:cancelled_annotations",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_comments => "filter:tasks:comments",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_completedAt => "filter:tasks:completed_at",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_createdAt => "filter:tasks:created_at",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_fileUpload => "filter:tasks:file_upload",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_groundTruth => "filter:tasks:ground_truth",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_id => "filter:tasks:id",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_innerId => "filter:tasks:inner_id",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_predictionsModelVersions => "filter:tasks:predictions_model_versions",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_predictionsResults => "filter:tasks:predictions_results",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_predictionsScore => "filter:tasks:predictions_score",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_reviewed => "filter:tasks:reviewed",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_reviewers => "filter:tasks:reviewers",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_reviewsAccepted => "filter:tasks:reviews_accepted",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_reviewsRejected => "filter:tasks:reviews_rejected",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_totalAnnotations => "filter:tasks:total_annotations",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_totalPredictions => "filter:tasks:total_predictions",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_unresolvedCommentCount => "filter:tasks:unresolved_comment_count",
                ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_updatedAt => "filter:tasks:updated_at",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(value), value, null),
            };
        }
        /// <summary>
        /// Converts an string to a enum.
        /// </summary>
        public static ApiDmViewsCreateRequestDataFiltersItemFilter? ToEnum(string value)
        {
            return value switch
            {
                "filter:tasks:agreement" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_agreement,
                "filter:tasks:annotations_results" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_annotationsResults,
                "filter:tasks:annotators" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_annotators,
                "filter:tasks:cancelled_annotations" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_cancelledAnnotations,
                "filter:tasks:comments" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_comments,
                "filter:tasks:completed_at" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_completedAt,
                "filter:tasks:created_at" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_createdAt,
                "filter:tasks:file_upload" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_fileUpload,
                "filter:tasks:ground_truth" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_groundTruth,
                "filter:tasks:id" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_id,
                "filter:tasks:inner_id" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_innerId,
                "filter:tasks:predictions_model_versions" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_predictionsModelVersions,
                "filter:tasks:predictions_results" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_predictionsResults,
                "filter:tasks:predictions_score" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_predictionsScore,
                "filter:tasks:reviewed" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_reviewed,
                "filter:tasks:reviewers" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_reviewers,
                "filter:tasks:reviews_accepted" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_reviewsAccepted,
                "filter:tasks:reviews_rejected" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_reviewsRejected,
                "filter:tasks:total_annotations" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_totalAnnotations,
                "filter:tasks:total_predictions" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_totalPredictions,
                "filter:tasks:unresolved_comment_count" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_unresolvedCommentCount,
                "filter:tasks:updated_at" => ApiDmViewsCreateRequestDataFiltersItemFilter.Filter_tasks_updatedAt,
                _ => null,
            };
        }
    }
}