//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.AIMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.AIMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolCallTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolCallTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.InvalidToolCallTypeJsonConverter),
            typeof(global::G.JsonConverters.InvalidToolCallTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AIMessageChunkTypeJsonConverter),
            typeof(global::G.JsonConverters.AIMessageChunkTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolCallChunkTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolCallChunkTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AccessScopeJsonConverter),
            typeof(global::G.JsonConverters.AccessScopeNullableJsonConverter),
            typeof(global::G.JsonConverters.AuthProviderJsonConverter),
            typeof(global::G.JsonConverters.AuthProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.RunTypeEnumJsonConverter),
            typeof(global::G.JsonConverters.RunTypeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.RunsFilterDataSourceTypeEnumJsonConverter),
            typeof(global::G.JsonConverters.RunsFilterDataSourceTypeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.RunSelectJsonConverter),
            typeof(global::G.JsonConverters.RunSelectNullableJsonConverter),
            typeof(global::G.JsonConverters.RunDateOrderJsonConverter),
            typeof(global::G.JsonConverters.RunDateOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.DataTypeJsonConverter),
            typeof(global::G.JsonConverters.DataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BulkExportFormatJsonConverter),
            typeof(global::G.JsonConverters.BulkExportFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.BulkExportCompressionJsonConverter),
            typeof(global::G.JsonConverters.BulkExportCompressionNullableJsonConverter),
            typeof(global::G.JsonConverters.BulkExportStatusJsonConverter),
            typeof(global::G.JsonConverters.BulkExportStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.BulkExportDestinationTypeJsonConverter),
            typeof(global::G.JsonConverters.BulkExportDestinationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BulkExportRunStatusJsonConverter),
            typeof(global::G.JsonConverters.BulkExportRunStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.BulkExportUpdateStatusJsonConverter),
            typeof(global::G.JsonConverters.BulkExportUpdateStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ChangePaymentPlanReqJsonConverter),
            typeof(global::G.JsonConverters.ChangePaymentPlanReqNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageChunkTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageChunkTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConfiguredByJsonConverter),
            typeof(global::G.JsonConverters.ConfiguredByNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateEventRequestEventTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateEventRequestEventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedbackTypeJsonConverter),
            typeof(global::G.JsonConverters.FeedbackTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CustomChartTypeJsonConverter),
            typeof(global::G.JsonConverters.CustomChartTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CustomChartMetricJsonConverter),
            typeof(global::G.JsonConverters.CustomChartMetricNullableJsonConverter),
            typeof(global::G.JsonConverters.RunStatsGroupByAttributeJsonConverter),
            typeof(global::G.JsonConverters.RunStatsGroupByAttributeNullableJsonConverter),
            typeof(global::G.JsonConverters.RunStatsGroupBySeriesResponseAttributeJsonConverter),
            typeof(global::G.JsonConverters.RunStatsGroupBySeriesResponseAttributeNullableJsonConverter),
            typeof(global::G.JsonConverters.RunStatsGroupBySeriesResponseSetByJsonConverter),
            typeof(global::G.JsonConverters.RunStatsGroupBySeriesResponseSetByNullableJsonConverter),
            typeof(global::G.JsonConverters.MissingMissing1JsonConverter),
            typeof(global::G.JsonConverters.MissingMissing1NullableJsonConverter),
            typeof(global::G.JsonConverters.PaymentPlanTierJsonConverter),
            typeof(global::G.JsonConverters.PaymentPlanTierNullableJsonConverter),
            typeof(global::G.JsonConverters.DatasetTransformationTypeJsonConverter),
            typeof(global::G.JsonConverters.DatasetTransformationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EPromptOptimizationAlgorithmJsonConverter),
            typeof(global::G.JsonConverters.EPromptOptimizationAlgorithmNullableJsonConverter),
            typeof(global::G.JsonConverters.EPromptOptimizationJobLogTypeJsonConverter),
            typeof(global::G.JsonConverters.EPromptOptimizationJobLogTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EPromptOptimizationJobStatusJsonConverter),
            typeof(global::G.JsonConverters.EPromptOptimizationJobStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ExampleListOrderJsonConverter),
            typeof(global::G.JsonConverters.ExampleListOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ExampleSelectJsonConverter),
            typeof(global::G.JsonConverters.ExampleSelectNullableJsonConverter),
            typeof(global::G.JsonConverters.TraceTierJsonConverter),
            typeof(global::G.JsonConverters.TraceTierNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedbackLevelJsonConverter),
            typeof(global::G.JsonConverters.FeedbackLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.FilterViewTypeJsonConverter),
            typeof(global::G.JsonConverters.FilterViewTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionMessageChunkTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionMessageChunkTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GroupExampleRunsByFieldJsonConverter),
            typeof(global::G.JsonConverters.GroupExampleRunsByFieldNullableJsonConverter),
            typeof(global::G.JsonConverters.HumanMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.HumanMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.HumanMessageChunkTypeJsonConverter),
            typeof(global::G.JsonConverters.HumanMessageChunkTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResourceTypeJsonConverter),
            typeof(global::G.JsonConverters.ResourceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.OAuthProviderJsonConverter),
            typeof(global::G.JsonConverters.OAuthProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.OrganizationDashboardColorSchemeJsonConverter),
            typeof(global::G.JsonConverters.OrganizationDashboardColorSchemeNullableJsonConverter),
            typeof(global::G.JsonConverters.OrganizationDashboardTypeJsonConverter),
            typeof(global::G.JsonConverters.OrganizationDashboardTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PagerdutySeverityJsonConverter),
            typeof(global::G.JsonConverters.PagerdutySeverityNullableJsonConverter),
            typeof(global::G.JsonConverters.SystemMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.SystemMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageStatusJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.SystemMessageChunkTypeJsonConverter),
            typeof(global::G.JsonConverters.SystemMessageChunkTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageChunkTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageChunkTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageChunkStatusJsonConverter),
            typeof(global::G.JsonConverters.ToolMessageChunkStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.PlaygroundPromptCanvasPayloadArtifactLengthJsonConverter),
            typeof(global::G.JsonConverters.PlaygroundPromptCanvasPayloadArtifactLengthNullableJsonConverter),
            typeof(global::G.JsonConverters.PlaygroundPromptCanvasPayloadReadingLevelJsonConverter),
            typeof(global::G.JsonConverters.PlaygroundPromptCanvasPayloadReadingLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.PlaygroundPromptCanvasPayloadTemplateFormatJsonConverter),
            typeof(global::G.JsonConverters.PlaygroundPromptCanvasPayloadTemplateFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.QueryExampleSchemaWithRunsFormatJsonConverter),
            typeof(global::G.JsonConverters.QueryExampleSchemaWithRunsFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.SortParamsForRunsComparisonViewSortOrderJsonConverter),
            typeof(global::G.JsonConverters.SortParamsForRunsComparisonViewSortOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.RunsGenerateQueryFeedbackKeysJsonConverter),
            typeof(global::G.JsonConverters.RunsGenerateQueryFeedbackKeysNullableJsonConverter),
            typeof(global::G.JsonConverters.RuleLogActionOutcomeJsonConverter),
            typeof(global::G.JsonConverters.RuleLogActionOutcomeNullableJsonConverter),
            typeof(global::G.JsonConverters.RunGroupByJsonConverter),
            typeof(global::G.JsonConverters.RunGroupByNullableJsonConverter),
            typeof(global::G.JsonConverters.RunRulesAlertTypeJsonConverter),
            typeof(global::G.JsonConverters.RunRulesAlertTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SessionSortableColumnsJsonConverter),
            typeof(global::G.JsonConverters.SessionSortableColumnsNullableJsonConverter),
            typeof(global::G.JsonConverters.SortByComparativeExperimentColumnJsonConverter),
            typeof(global::G.JsonConverters.SortByComparativeExperimentColumnNullableJsonConverter),
            typeof(global::G.JsonConverters.SortByDatasetColumnJsonConverter),
            typeof(global::G.JsonConverters.SortByDatasetColumnNullableJsonConverter),
            typeof(global::G.JsonConverters.SourceTypeJsonConverter),
            typeof(global::G.JsonConverters.SourceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TenantShareDatasetTokenTypeJsonConverter),
            typeof(global::G.JsonConverters.TenantShareDatasetTokenTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TenantShareRunTokenTypeJsonConverter),
            typeof(global::G.JsonConverters.TenantShareRunTokenTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TenantShareTokensResponseEntitieDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.TenantShareTokensResponseEntitieDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TenantUsageLimitTypeJsonConverter),
            typeof(global::G.JsonConverters.TenantUsageLimitTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UsageLimitTypeJsonConverter),
            typeof(global::G.JsonConverters.UsageLimitTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateRunRequestRunTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateRunRequestRunTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchIngestRunsRequestPostItemRunTypeJsonConverter),
            typeof(global::G.JsonConverters.BatchIngestRunsRequestPostItemRunTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListRulesApiV1RunsRulesGetTypeJsonConverter),
            typeof(global::G.JsonConverters.ListRulesApiV1RunsRulesGetTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListReposApiV1ReposGetIsArchivedJsonConverter),
            typeof(global::G.JsonConverters.ListReposApiV1ReposGetIsArchivedNullableJsonConverter),
            typeof(global::G.JsonConverters.ListReposApiV1ReposGetIsPublicJsonConverter),
            typeof(global::G.JsonConverters.ListReposApiV1ReposGetIsPublicNullableJsonConverter),
            typeof(global::G.JsonConverters.ListReposApiV1ReposGetSortDirectionVariant1JsonConverter),
            typeof(global::G.JsonConverters.ListReposApiV1ReposGetSortDirectionVariant1NullableJsonConverter),
            typeof(global::G.JsonConverters.ListReposApiV1ReposGetSortDirectionVariant2JsonConverter),
            typeof(global::G.JsonConverters.ListReposApiV1ReposGetSortDirectionVariant2NullableJsonConverter),
            typeof(global::G.JsonConverters.ListRepoTagsApiV1ReposTagsGetIsArchivedJsonConverter),
            typeof(global::G.JsonConverters.ListRepoTagsApiV1ReposTagsGetIsArchivedNullableJsonConverter),
            typeof(global::G.JsonConverters.ListRepoTagsApiV1ReposTagsGetIsPublicJsonConverter),
            typeof(global::G.JsonConverters.ListRepoTagsApiV1ReposTagsGetIsPublicNullableJsonConverter),
            typeof(global::G.JsonConverters.EntitiesItemJsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<string, object>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<string, object>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<string, object>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<string, object>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Guid?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.CustomChartType?, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.CustomChartSeriesUpdate>, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Guid?, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.CustomChartSeriesFilters, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, double?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Guid?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Guid?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Guid?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.DatasetTransformation>, global::G.Missing>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.ExampleWithRuns>, global::System.Collections.Generic.IList<global::G.ExampleWithRunsCH>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, bool?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, bool?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.AppFeedbackSource, global::G.APIFeedbackSource, global::G.ModelFeedbackSource, global::G.AutoEvalFeedbackSource>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, bool?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, bool?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.AppFeedbackSource, global::G.APIFeedbackSource, global::G.ModelFeedbackSource, global::G.AutoEvalFeedbackSource>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, bool?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, bool?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, bool?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, bool?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, bool?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, bool?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<string, object>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<string, object>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<string, object>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<string, object>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PromptimConfig, global::G.DemoConfig>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.AIMessage, global::G.HumanMessage, global::G.ChatMessage, global::G.SystemMessage, global::G.FunctionMessage, global::G.ToolMessage, global::G.AIMessageChunk, global::G.HumanMessageChunk, global::G.ChatMessageChunk, global::G.SystemMessageChunk, global::G.FunctionMessageChunk, global::G.ToolMessageChunk>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<string, object>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<string, object>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<string, object>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<string, object>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<object>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PromptimConfig, global::G.DemoConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PromptimConfig, global::G.DemoConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PromptimConfig, global::G.DemoConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, double?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, double?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, double?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, double?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, double?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, double?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.FeedbackIngestTokenCreateSchema, global::System.Collections.Generic.IList<global::G.FeedbackIngestTokenCreateSchema>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.DataType>, global::G.DataType?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, bool?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, bool?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ListReposApiV1ReposGetSortDirectionVariant1?, global::G.ListReposApiV1ReposGetSortDirectionVariant2?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.ExampleWithRuns>, global::System.Collections.Generic.IList<global::G.ExampleWithRunsCH>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.RunStats, global::System.Collections.Generic.Dictionary<string, global::G.RunStats>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.FeedbackIngestTokenSchema, global::System.Collections.Generic.IList<global::G.FeedbackIngestTokenSchema>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.PublicExampleWithRuns>, global::System.Collections.Generic.IList<global::G.ExampleWithRunsCH>>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<string, global::G.Response3>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<string, global::G.Response6>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<string, global::G.Response10>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}