//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.EmbeddingFunctionConfigurationVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingFunctionConfigurationVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingFunctionConfigurationVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingFunctionConfigurationVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingFunctionConfigurationVariant3TypeJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingFunctionConfigurationVariant3TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IncludeJsonConverter),
            typeof(global::G.JsonConverters.IncludeNullableJsonConverter),
            typeof(global::G.JsonConverters.KeyVariant1JsonConverter),
            typeof(global::G.JsonConverters.KeyVariant1NullableJsonConverter),
            typeof(global::G.JsonConverters.KeyVariant2JsonConverter),
            typeof(global::G.JsonConverters.KeyVariant2NullableJsonConverter),
            typeof(global::G.JsonConverters.KeyVariant3JsonConverter),
            typeof(global::G.JsonConverters.KeyVariant3NullableJsonConverter),
            typeof(global::G.JsonConverters.KeyVariant4JsonConverter),
            typeof(global::G.JsonConverters.KeyVariant4NullableJsonConverter),
            typeof(global::G.JsonConverters.QuantizationJsonConverter),
            typeof(global::G.JsonConverters.QuantizationNullableJsonConverter),
            typeof(global::G.JsonConverters.ReadLevelJsonConverter),
            typeof(global::G.JsonConverters.ReadLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.Space2JsonConverter),
            typeof(global::G.JsonConverters.Space2NullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteCollectionRecordsPayloadJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingFunctionConfigurationJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingsPayloadJsonConverter),
            typeof(global::G.JsonConverters.GetRequestPayloadJsonConverter),
            typeof(global::G.JsonConverters.KeyJsonConverter),
            typeof(global::G.JsonConverters.QueryRequestPayloadJsonConverter),
            typeof(global::G.JsonConverters.UpdateEmbeddingsPayloadJsonConverter),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.HashMap>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::System.Guid?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.BoolInvertedIndexType>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.HashMap>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.Schema3>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.EmbeddingFunctionConfiguration?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.HnswConfiguration>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.SpannConfiguration>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.CollectionConfiguration>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.HashMap>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.Schema3>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.EmbeddingFunctionNewConfiguration, global::G.EmbeddingFunctionConfigurationVariant22>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.VectorIndexType>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.FloatInvertedIndexType>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.HashMap>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<bool?, long?, double?, string, global::G.SparseVector, global::System.Collections.Generic.IList<bool>, global::System.Collections.Generic.IList<long>, global::System.Collections.Generic.IList<double>, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.Space2?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.IntInvertedIndexType>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.HashMap>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.HashMap>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.Space2?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.EmbeddingFunctionConfiguration?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.SparseVectorIndexType>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.FtsIndexType>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.StringInvertedIndexType>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.EmbeddingFunctionConfiguration?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.UpdateHnswConfiguration>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.UpdateSpannConfiguration>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.UpdateCollectionConfiguration>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.HashMap>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.UpdateEmbeddingsPayload?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.HashMap>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.HashMap>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.BoolValueType>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.FloatValueType>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.FloatListValueType>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.IntValueType>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.SparseVectorValueType>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.StringValueType>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.HashMap>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.Schema3>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.EmbeddingFunctionConfiguration?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.HnswIndexConfig>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.Space2?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<object, global::G.SpannIndexConfig>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}