//HintName: G.Models.GeneratedAssetResponseAttributes.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// The id and attributes of the generated asset.
    /// </summary>
    public sealed partial class GeneratedAssetResponseAttributes
    {
        /// <summary>
        /// The owner id of the asset.<br/>
        /// Example: 5ca6hu7s9k
        /// </summary>
        /// <example>5ca6hu7s9k</example>
        [global::System.Text.Json.Serialization.JsonPropertyName("owner")]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required string Owner { get; set; }

        /// <summary>
        /// The native or third party provider that generated the asset, `shotstack`, `elevenlabs`, `heygen` or `d-id`.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("provider")]
        [global::System.Text.Json.Serialization.JsonConverter(typeof(global::G.JsonConverters.GeneratedAssetResponseAttributesProviderJsonConverter))]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required global::G.GeneratedAssetResponseAttributesProvider Provider { get; set; }

        /// <summary>
        /// The type of service used to generate the asset, `text-to-speech` or `text-to-avatar`.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("type")]
        [global::System.Text.Json.Serialization.JsonConverter(typeof(global::G.JsonConverters.GeneratedAssetResponseAttributesTypeJsonConverter))]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required global::G.GeneratedAssetResponseAttributesType Type { get; set; }

        /// <summary>
        /// The URL of the asset file hosted by Shotstack. The file at the URL can be used by the Edit API. Generated asset file URL's consist of a base URL (AWS bucket), owner id, asset id and extension. The extension varies depending on the type of file generated.<br/>
        /// Example: https://shotstack-create-api-v1-assets.s3.amazonaws.com/5ca6hu7s9k/01gz0-tj679-xj30t-hr8zk-3hasvk.mp3
        /// </summary>
        /// <example>https://shotstack-create-api-v1-assets.s3.amazonaws.com/5ca6hu7s9k/01gz0-tj679-xj30t-hr8zk-3hasvk.mp3</example>
        [global::System.Text.Json.Serialization.JsonPropertyName("url")]
        public string? Url { get; set; }

        /// <summary>
        /// The status of the asset file generation task. &lt;ul&gt;<br/>
        ///   &lt;li&gt;`queued` - generation task is queued waiting to be processed&lt;/li&gt;<br/>
        ///   &lt;li&gt;`processing` - the asset is being generated by the provider&lt;/li&gt;<br/>
        ///   &lt;li&gt;`saving` - the asset is being saved to Shotstack&lt;/li&gt;<br/>
        ///   &lt;li&gt;`done` - the asset has been generated and stored&lt;/li&gt;<br/>
        ///   &lt;li&gt;`failed` - there was an error generating the asset&lt;/li&gt;<br/>
        /// &lt;/ul&gt;<br/>
        /// Example: done
        /// </summary>
        /// <example>done</example>
        [global::System.Text.Json.Serialization.JsonPropertyName("status")]
        [global::System.Text.Json.Serialization.JsonConverter(typeof(global::G.JsonConverters.GeneratedAssetResponseAttributesStatusJsonConverter))]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required global::G.GeneratedAssetResponseAttributesStatus Status { get; set; }

        /// <summary>
        /// The time the generate asset task was initially queued.<br/>
        /// Example: 2023-01-02T01:47:18.973Z
        /// </summary>
        /// <example>2023-01-02T01:47:18.973Z</example>
        [global::System.Text.Json.Serialization.JsonPropertyName("created")]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required string Created { get; set; }

        /// <summary>
        /// The time the asset status was last updated.<br/>
        /// Example: 2023-01-02T01:47:37.260Z
        /// </summary>
        /// <example>2023-01-02T01:47:37.260Z</example>
        [global::System.Text.Json.Serialization.JsonPropertyName("updated")]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required string Updated { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::System.Text.Json.Serialization.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="GeneratedAssetResponseAttributes" /> class.
        /// </summary>
        /// <param name="owner">
        /// The owner id of the asset.<br/>
        /// Example: 5ca6hu7s9k
        /// </param>
        /// <param name="provider">
        /// The native or third party provider that generated the asset, `shotstack`, `elevenlabs`, `heygen` or `d-id`.
        /// </param>
        /// <param name="type">
        /// The type of service used to generate the asset, `text-to-speech` or `text-to-avatar`.
        /// </param>
        /// <param name="status">
        /// The status of the asset file generation task. &lt;ul&gt;<br/>
        ///   &lt;li&gt;`queued` - generation task is queued waiting to be processed&lt;/li&gt;<br/>
        ///   &lt;li&gt;`processing` - the asset is being generated by the provider&lt;/li&gt;<br/>
        ///   &lt;li&gt;`saving` - the asset is being saved to Shotstack&lt;/li&gt;<br/>
        ///   &lt;li&gt;`done` - the asset has been generated and stored&lt;/li&gt;<br/>
        ///   &lt;li&gt;`failed` - there was an error generating the asset&lt;/li&gt;<br/>
        /// &lt;/ul&gt;<br/>
        /// Example: done
        /// </param>
        /// <param name="created">
        /// The time the generate asset task was initially queued.<br/>
        /// Example: 2023-01-02T01:47:18.973Z
        /// </param>
        /// <param name="updated">
        /// The time the asset status was last updated.<br/>
        /// Example: 2023-01-02T01:47:37.260Z
        /// </param>
        /// <param name="url">
        /// The URL of the asset file hosted by Shotstack. The file at the URL can be used by the Edit API. Generated asset file URL's consist of a base URL (AWS bucket), owner id, asset id and extension. The extension varies depending on the type of file generated.<br/>
        /// Example: https://shotstack-create-api-v1-assets.s3.amazonaws.com/5ca6hu7s9k/01gz0-tj679-xj30t-hr8zk-3hasvk.mp3
        /// </param>
#if NET7_0_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
#endif
        public GeneratedAssetResponseAttributes(
            string owner,
            global::G.GeneratedAssetResponseAttributesProvider provider,
            global::G.GeneratedAssetResponseAttributesType type,
            global::G.GeneratedAssetResponseAttributesStatus status,
            string created,
            string updated,
            string? url)
        {
            this.Owner = owner ?? throw new global::System.ArgumentNullException(nameof(owner));
            this.Provider = provider;
            this.Type = type;
            this.Url = url;
            this.Status = status;
            this.Created = created ?? throw new global::System.ArgumentNullException(nameof(created));
            this.Updated = updated ?? throw new global::System.ArgumentNullException(nameof(updated));
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GeneratedAssetResponseAttributes" /> class.
        /// </summary>
        public GeneratedAssetResponseAttributes()
        {
        }
    }
}