//HintName: G.Models.Source.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// The details of the file to be ingested and any transformations to be applied. Once the source file has been ingested, new renditions can be created from it. The renditions are specified in the **outputs** property.<br/>
    /// A rendition is a new version, generated from the source. This can be used to create new sizes and aspect ratios tht serve different purposes within an application.
    /// </summary>
    public sealed partial class Source
    {
        /// <summary>
        /// The URL of the file to be ingested. The URL must be publicly accessible or include credentials.<br/>
        /// Example: https://github.com/shotstack/test-media/raw/main/captioning/scott-ko.mp4
        /// </summary>
        /// <example>https://github.com/shotstack/test-media/raw/main/captioning/scott-ko.mp4</example>
        [global::System.Text.Json.Serialization.JsonPropertyName("url")]
        public string? Url { get; set; }

        /// <summary>
        /// The output renditions and transformations that should be generated from the source file.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("outputs")]
        public global::G.Outputs? Outputs { get; set; }

        /// <summary>
        /// A destination is a location where assets can be sent to for serving or hosting. Videos, images and audio files that are rendered by the [Edit API](#shotstack-edit) and [source](#tocs_source) and [rendition](#tocs_rendition) files generated by the [Ingest API](#shotstack-ingest) can be sent to destinations. You can also fetch a file from any public URL and [transfer](#transfer-asset) it to a destination. A file can be sent to one or more destinations including 3rd party destinations.<br/>
        /// By default all ingested and generated assets are automatically sent to the [Shotstack hosting destination](https://shotstack.io/docs/guide/serving-assets/hosting/). You can [opt-out](https://shotstack.io/docs/guide/serving-assets/self-host/) from by setting the Shotstack destination **exclude** property to **true**.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("destinations")]
        [global::System.Text.Json.Serialization.JsonConverter(typeof(global::G.JsonConverters.DestinationsJsonConverter))]
        public global::G.Destinations? Destinations { get; set; }

        /// <summary>
        /// An optional webhook callback URL used to receive status notifications when sources are uploaded and renditions processed.<br/>
        /// Example: https://my-server.com/callback.php
        /// </summary>
        /// <example>https://my-server.com/callback.php</example>
        [global::System.Text.Json.Serialization.JsonPropertyName("callback")]
        public string? Callback { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::System.Text.Json.Serialization.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="Source" /> class.
        /// </summary>
        /// <param name="url">
        /// The URL of the file to be ingested. The URL must be publicly accessible or include credentials.<br/>
        /// Example: https://github.com/shotstack/test-media/raw/main/captioning/scott-ko.mp4
        /// </param>
        /// <param name="outputs">
        /// The output renditions and transformations that should be generated from the source file.
        /// </param>
        /// <param name="destinations">
        /// A destination is a location where assets can be sent to for serving or hosting. Videos, images and audio files that are rendered by the [Edit API](#shotstack-edit) and [source](#tocs_source) and [rendition](#tocs_rendition) files generated by the [Ingest API](#shotstack-ingest) can be sent to destinations. You can also fetch a file from any public URL and [transfer](#transfer-asset) it to a destination. A file can be sent to one or more destinations including 3rd party destinations.<br/>
        /// By default all ingested and generated assets are automatically sent to the [Shotstack hosting destination](https://shotstack.io/docs/guide/serving-assets/hosting/). You can [opt-out](https://shotstack.io/docs/guide/serving-assets/self-host/) from by setting the Shotstack destination **exclude** property to **true**.
        /// </param>
        /// <param name="callback">
        /// An optional webhook callback URL used to receive status notifications when sources are uploaded and renditions processed.<br/>
        /// Example: https://my-server.com/callback.php
        /// </param>
#if NET7_0_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
#endif
        public Source(
            string? url,
            global::G.Outputs? outputs,
            global::G.Destinations? destinations,
            string? callback)
        {
            this.Url = url;
            this.Outputs = outputs;
            this.Destinations = destinations;
            this.Callback = callback;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Source" /> class.
        /// </summary>
        public Source()
        {
        }
    }
}