//HintName: G.Models.LemurQuestionAnswerResponseVariant2.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    public sealed partial class LemurQuestionAnswerResponseVariant2
    {
        /// <summary>
        /// The answers generated by LeMUR and their questions
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("response")]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required global::System.Collections.Generic.IList<global::G.LemurQuestionAnswer> Response { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::System.Text.Json.Serialization.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="LemurQuestionAnswerResponseVariant2" /> class.
        /// </summary>
        /// <param name="response">
        /// The answers generated by LeMUR and their questions
        /// </param>
#if NET7_0_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
#endif
        public LemurQuestionAnswerResponseVariant2(
            global::System.Collections.Generic.IList<global::G.LemurQuestionAnswer> response)
        {
            this.Response = response ?? throw new global::System.ArgumentNullException(nameof(response));
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LemurQuestionAnswerResponseVariant2" /> class.
        /// </summary>
        public LemurQuestionAnswerResponseVariant2()
        {
        }
    }
}