//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.DubbingOutputLanguageJsonConverter),
            typeof(global::G.JsonConverters.DubbingOutputLanguageNullableJsonConverter),
            typeof(global::G.JsonConverters.AddLocalesToDubbingProjectRequestVideoDurationJsonConverter),
            typeof(global::G.JsonConverters.AddLocalesToDubbingProjectRequestVideoDurationNullableJsonConverter),
            typeof(global::G.JsonConverters.AddLocalesToDubbingProjectRequestVisibilityJsonConverter),
            typeof(global::G.JsonConverters.AddLocalesToDubbingProjectRequestVisibilityNullableJsonConverter),
            typeof(global::G.JsonConverters.DubbingAssetRequestConfigurationNameJsonConverter),
            typeof(global::G.JsonConverters.DubbingAssetRequestConfigurationNameNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateAssetRequestContentTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateAssetRequestContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateAssetRequestConfigurationDiscriminatorNameJsonConverter),
            typeof(global::G.JsonConverters.CreateAssetRequestConfigurationDiscriminatorNameNullableJsonConverter),
            typeof(global::G.JsonConverters.DubbingInputLanguageJsonConverter),
            typeof(global::G.JsonConverters.DubbingInputLanguageNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateDubbingProjectApiRequestFromSourceAssetIdVideoDurationJsonConverter),
            typeof(global::G.JsonConverters.CreateDubbingProjectApiRequestFromSourceAssetIdVideoDurationNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateDubbingProjectApiRequestFromSourceAssetIdVisibilityJsonConverter),
            typeof(global::G.JsonConverters.CreateDubbingProjectApiRequestFromSourceAssetIdVisibilityNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateDubbingProjectApiRequestFromSourceVideoUrlVideoDurationJsonConverter),
            typeof(global::G.JsonConverters.CreateDubbingProjectApiRequestFromSourceVideoUrlVideoDurationNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateDubbingProjectApiRequestFromSourceVideoUrlVisibilityJsonConverter),
            typeof(global::G.JsonConverters.CreateDubbingProjectApiRequestFromSourceVideoUrlVisibilityNullableJsonConverter),
            typeof(global::G.JsonConverters.UpsertVideoTranslationsApiRequestAutoGenerateJsonConverter),
            typeof(global::G.JsonConverters.UpsertVideoTranslationsApiRequestAutoGenerateNullableJsonConverter),
            typeof(global::G.JsonConverters.PublicApiImportedAndDubbedVideosErrorCodeJsonConverter),
            typeof(global::G.JsonConverters.PublicApiImportedAndDubbedVideosErrorCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.DubbedAssetCompleteStatusJsonConverter),
            typeof(global::G.JsonConverters.DubbedAssetCompleteStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.DubbedAssetCompleteVisibilityJsonConverter),
            typeof(global::G.JsonConverters.DubbedAssetCompleteVisibilityNullableJsonConverter),
            typeof(global::G.JsonConverters.DubbedAssetErrorStatusJsonConverter),
            typeof(global::G.JsonConverters.DubbedAssetErrorStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.DubbedAssetInProgressStatusJsonConverter),
            typeof(global::G.JsonConverters.DubbedAssetInProgressStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.AssetContentTypeJsonConverter),
            typeof(global::G.JsonConverters.AssetContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LanguageBCP47JsonConverter),
            typeof(global::G.JsonConverters.LanguageBCP47NullableJsonConverter),
            typeof(global::G.JsonConverters.PublicApiUserUploadedAssetErrorCodesJsonConverter),
            typeof(global::G.JsonConverters.PublicApiUserUploadedAssetErrorCodesNullableJsonConverter),
            typeof(global::G.JsonConverters.PublicApiUserUploadedAssetStatusJsonConverter),
            typeof(global::G.JsonConverters.PublicApiUserUploadedAssetStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetDubbingProjectVideosResponseUploadingStatusJsonConverter),
            typeof(global::G.JsonConverters.GetDubbingProjectVideosResponseUploadingStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetDubbingProjectVideosResponseInProgressStatusJsonConverter),
            typeof(global::G.JsonConverters.GetDubbingProjectVideosResponseInProgressStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetDubbingProjectVideosResponseCompleteStatusJsonConverter),
            typeof(global::G.JsonConverters.GetDubbingProjectVideosResponseCompleteStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetDubbingProjectVideosResponseErrorStatusJsonConverter),
            typeof(global::G.JsonConverters.GetDubbingProjectVideosResponseErrorStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ActorTypeJsonConverter),
            typeof(global::G.JsonConverters.ActorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TargetTypeJsonConverter),
            typeof(global::G.JsonConverters.TargetTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UpsertVideoTranslationsRunningWorkflowApiItemStatusJsonConverter),
            typeof(global::G.JsonConverters.UpsertVideoTranslationsRunningWorkflowApiItemStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.UpsertVideoTranslationsRunningWorkflowApiItemStepJsonConverter),
            typeof(global::G.JsonConverters.UpsertVideoTranslationsRunningWorkflowApiItemStepNullableJsonConverter),
            typeof(global::G.JsonConverters.TranslationStatusApiItemErrorStatusJsonConverter),
            typeof(global::G.JsonConverters.TranslationStatusApiItemErrorStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.TranslationStatusApiItemErrorErrorCodeJsonConverter),
            typeof(global::G.JsonConverters.TranslationStatusApiItemErrorErrorCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.TranslationStatusApiItemSuccessStatusJsonConverter),
            typeof(global::G.JsonConverters.TranslationStatusApiItemSuccessStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.TranslationStatusApiItemSuccessStepJsonConverter),
            typeof(global::G.JsonConverters.TranslationStatusApiItemSuccessStepNullableJsonConverter),
            typeof(global::G.JsonConverters.GetVideoTranslationsApiResponseTranslationDiscriminatorStatusJsonConverter),
            typeof(global::G.JsonConverters.GetVideoTranslationsApiResponseTranslationDiscriminatorStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplateResponseVisibilityJsonConverter),
            typeof(global::G.JsonConverters.TemplateResponseVisibilityNullableJsonConverter),
            typeof(global::G.JsonConverters.ActorSettingsHorizontalAlignJsonConverter),
            typeof(global::G.JsonConverters.ActorSettingsHorizontalAlignNullableJsonConverter),
            typeof(global::G.JsonConverters.ActorSettingsStyleJsonConverter),
            typeof(global::G.JsonConverters.ActorSettingsStyleNullableJsonConverter),
            typeof(global::G.JsonConverters.InputVideoBackgroundSettingsShortBackgroundContentMatchModeJsonConverter),
            typeof(global::G.JsonConverters.InputVideoBackgroundSettingsShortBackgroundContentMatchModeNullableJsonConverter),
            typeof(global::G.JsonConverters.InputVideoBackgroundSettingsLongBackgroundContentMatchModeJsonConverter),
            typeof(global::G.JsonConverters.InputVideoBackgroundSettingsLongBackgroundContentMatchModeNullableJsonConverter),
            typeof(global::G.JsonConverters.InputScriptLanguageJsonConverter),
            typeof(global::G.JsonConverters.InputScriptLanguageNullableJsonConverter),
            typeof(global::G.JsonConverters.InputTransitionJsonConverter),
            typeof(global::G.JsonConverters.InputTransitionNullableJsonConverter),
            typeof(global::G.JsonConverters.VideoResponseAspectRatioJsonConverter),
            typeof(global::G.JsonConverters.VideoResponseAspectRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.VideoResponseSoundtrackJsonConverter),
            typeof(global::G.JsonConverters.VideoResponseSoundtrackNullableJsonConverter),
            typeof(global::G.JsonConverters.VideoResponseVisibilityJsonConverter),
            typeof(global::G.JsonConverters.VideoResponseVisibilityNullableJsonConverter),
            typeof(global::G.JsonConverters.VideoResponseStatusJsonConverter),
            typeof(global::G.JsonConverters.VideoResponseStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.VideoFromTemplateApiVisibilityJsonConverter),
            typeof(global::G.JsonConverters.VideoFromTemplateApiVisibilityNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateVideoRequestAspectRatioJsonConverter),
            typeof(global::G.JsonConverters.CreateVideoRequestAspectRatioNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateVideoRequestSoundtrackJsonConverter),
            typeof(global::G.JsonConverters.CreateVideoRequestSoundtrackNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateVideoRequestVisibilityJsonConverter),
            typeof(global::G.JsonConverters.CreateVideoRequestVisibilityNullableJsonConverter),
            typeof(global::G.JsonConverters.UpdateVideoMetadataRequestVisibilityJsonConverter),
            typeof(global::G.JsonConverters.UpdateVideoMetadataRequestVisibilityNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateWebhookRequestEventJsonConverter),
            typeof(global::G.JsonConverters.CreateWebhookRequestEventNullableJsonConverter),
            typeof(global::G.JsonConverters.GetTemplatesSourceItemJsonConverter),
            typeof(global::G.JsonConverters.GetTemplatesSourceItemNullableJsonConverter),
            typeof(global::G.JsonConverters.GetVideosSourceItemJsonConverter),
            typeof(global::G.JsonConverters.GetVideosSourceItemNullableJsonConverter),
            typeof(global::G.JsonConverters.GetVideosXliffXliffVersionJsonConverter),
            typeof(global::G.JsonConverters.GetVideosXliffXliffVersionNullableJsonConverter),
            typeof(global::G.JsonConverters.TranslationsItemJsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.DubbedAssetInProgress, global::G.DubbedAssetComplete, global::G.DubbedAssetError>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.DubbedAssetInProgress, global::G.DubbedAssetComplete, global::G.DubbedAssetError>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.DubbedAssetInProgress, global::G.DubbedAssetComplete, global::G.DubbedAssetError>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.CreateDubbingProjectApiRequestFromSourceAssetId, global::G.CreateDubbingProjectApiRequestFromSourceVideoUrl?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.CreateDubbingProjectApiResponseFail, global::G.CreateDubbingResponse2>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.GetDubbingProjectVideosResponseUploading, global::G.GetDubbingProjectVideosResponseInProgress, global::G.GetDubbingProjectVideosResponseComplete, global::G.GetDubbingProjectVideosResponseError>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}