//HintName: G.Models.Response.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// The response resource.
    /// </summary>
    public sealed partial class Response
    {
        /// <summary>
        /// The unique ID of the response.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The object type.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("object")]
        public global::G.ResponseObject? Object { get; set; }

        /// <summary>
        /// The status of the response.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("status")]
        public global::G.ResponseStatus? Status { get; set; }

        /// <summary>
        /// Additional details about the status.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("status_details")]
        public object? StatusDetails { get; set; }

        /// <summary>
        /// The list of output items generated by the response.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("output")]
        public global::System.Collections.Generic.IList<global::G.ConversationItem>? Output { get; set; }

        /// <summary>
        /// Usage statistics for a response.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("usage")]
        public global::G.UsageDetails? Usage { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="Response" /> class.
        /// </summary>
        /// <param name="id">
        /// The unique ID of the response.
        /// </param>
        /// <param name="object">
        /// The object type.
        /// </param>
        /// <param name="status">
        /// The status of the response.
        /// </param>
        /// <param name="statusDetails">
        /// Additional details about the status.
        /// </param>
        /// <param name="output">
        /// The list of output items generated by the response.
        /// </param>
        /// <param name="usage">
        /// Usage statistics for a response.
        /// </param>
        public Response(
            string? id,
            global::G.ResponseObject? @object,
            global::G.ResponseStatus? status,
            object? statusDetails,
            global::System.Collections.Generic.IList<global::G.ConversationItem>? output,
            global::G.UsageDetails? usage)
        {
            this.Id = id;
            this.Object = @object;
            this.Status = status;
            this.StatusDetails = statusDetails;
            this.Output = output;
            this.Usage = usage;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Response" /> class.
        /// </summary>
        public Response()
        {
        }
    }
}