//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.DataEntryVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.DataEntryVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DataEntryVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.DataEntryVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DataEntryVariant3ContentJsonConverter),
            typeof(global::G.JsonConverters.DataEntryVariant3ContentNullableJsonConverter),
            typeof(global::G.JsonConverters.DataEntryVariant3TypeJsonConverter),
            typeof(global::G.JsonConverters.DataEntryVariant3TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DataEntryVariant4ContentJsonConverter),
            typeof(global::G.JsonConverters.DataEntryVariant4ContentNullableJsonConverter),
            typeof(global::G.JsonConverters.DataEntryVariant4TypeJsonConverter),
            typeof(global::G.JsonConverters.DataEntryVariant4TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LastMileConfigFormVariant2Variant1TypeJsonConverter),
            typeof(global::G.JsonConverters.LastMileConfigFormVariant2Variant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LastMileConfigFormVariant2Variant2TypeJsonConverter),
            typeof(global::G.JsonConverters.LastMileConfigFormVariant2Variant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EvaluatorStatsRecentTrendJsonConverter),
            typeof(global::G.JsonConverters.EvaluatorStatsRecentTrendNullableJsonConverter),
            typeof(global::G.JsonConverters.OpenAIChatRequestMessageToolCallTypeJsonConverter),
            typeof(global::G.JsonConverters.OpenAIChatRequestMessageToolCallTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.OpenAIChatRequestToolTypeJsonConverter),
            typeof(global::G.JsonConverters.OpenAIChatRequestToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.OpenAIChatRequestToolChoiceEnumFunctionTypeJsonConverter),
            typeof(global::G.JsonConverters.OpenAIChatRequestToolChoiceEnumFunctionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.OpenAIChatRequestToolChoiceEnum2JsonConverter),
            typeof(global::G.JsonConverters.OpenAIChatRequestToolChoiceEnum2NullableJsonConverter),
            typeof(global::G.JsonConverters.OpenAIChatRequestReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.OpenAIChatRequestReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.OpenAIChatRequestVerbosityJsonConverter),
            typeof(global::G.JsonConverters.OpenAIChatRequestVerbosityNullableJsonConverter),
            typeof(global::G.JsonConverters.Prompt2025VersionPromptBodyMessageToolCallTypeJsonConverter),
            typeof(global::G.JsonConverters.Prompt2025VersionPromptBodyMessageToolCallTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.Prompt2025VersionPromptBodyToolTypeJsonConverter),
            typeof(global::G.JsonConverters.Prompt2025VersionPromptBodyToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.Prompt2025VersionPromptBodyToolChoiceFunctionTypeJsonConverter),
            typeof(global::G.JsonConverters.Prompt2025VersionPromptBodyToolChoiceFunctionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptsFilterNodeEnumJsonConverter),
            typeof(global::G.JsonConverters.PromptsFilterNodeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptsFilterBranchOperatorJsonConverter),
            typeof(global::G.JsonConverters.PromptsFilterBranchOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionsFilterNodeEnumJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionsFilterNodeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionsFilterBranchOperatorJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionsFilterBranchOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.UpgradeToProRequestUiModeJsonConverter),
            typeof(global::G.JsonConverters.UpgradeToProRequestUiModeNullableJsonConverter),
            typeof(global::G.JsonConverters.UpgradeToTeamBundleRequestUiModeJsonConverter),
            typeof(global::G.JsonConverters.UpgradeToTeamBundleRequestUiModeNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestFilterNodeEnumJsonConverter),
            typeof(global::G.JsonConverters.RequestFilterNodeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestFilterBranchOperatorJsonConverter),
            typeof(global::G.JsonConverters.RequestFilterBranchOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.SortDirectionJsonConverter),
            typeof(global::G.JsonConverters.SortDirectionNullableJsonConverter),
            typeof(global::G.JsonConverters.ProviderNameJsonConverter),
            typeof(global::G.JsonConverters.ProviderNameNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelProviderNameJsonConverter),
            typeof(global::G.JsonConverters.ModelProviderNameNullableJsonConverter),
            typeof(global::G.JsonConverters.ProviderEnumJsonConverter),
            typeof(global::G.JsonConverters.ProviderEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.LlmTypeJsonConverter),
            typeof(global::G.JsonConverters.LlmTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MessageAnnotationTypeJsonConverter),
            typeof(global::G.JsonConverters.MessageAnnotationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MessageTypeJsonConverter),
            typeof(global::G.JsonConverters.MessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MessageRoleJsonConverter),
            typeof(global::G.JsonConverters.MessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.MessageType2JsonConverter),
            typeof(global::G.JsonConverters.MessageType2NullableJsonConverter),
            typeof(global::G.JsonConverters.HeliconeEventToolTypeJsonConverter),
            typeof(global::G.JsonConverters.HeliconeEventToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.HeliconeEventVectorDBTypeJsonConverter),
            typeof(global::G.JsonConverters.HeliconeEventVectorDBTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.HeliconeEventVectorDBOperationJsonConverter),
            typeof(global::G.JsonConverters.HeliconeEventVectorDBOperationNullableJsonConverter),
            typeof(global::G.JsonConverters.HeliconeEventDataTypeJsonConverter),
            typeof(global::G.JsonConverters.HeliconeEventDataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LLMRequestBodyReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.LLMRequestBodyReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.LLMRequestBodyVerbosityJsonConverter),
            typeof(global::G.JsonConverters.LLMRequestBodyVerbosityNullableJsonConverter),
            typeof(global::G.JsonConverters.LLMRequestBodyToolChoiceTypeJsonConverter),
            typeof(global::G.JsonConverters.LLMRequestBodyToolChoiceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseRoleJsonConverter),
            typeof(global::G.JsonConverters.ResponseRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseType2JsonConverter),
            typeof(global::G.JsonConverters.ResponseType2NullableJsonConverter),
            typeof(global::G.JsonConverters.LLMResponseBodyDataDetailsResponseTypeJsonConverter),
            typeof(global::G.JsonConverters.LLMResponseBodyDataDetailsResponseTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LLMResponseBodyVectorDBDetailsResponseTypeJsonConverter),
            typeof(global::G.JsonConverters.LLMResponseBodyVectorDBDetailsResponseTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LLMResponseBodyToolDetailsResponseTypeJsonConverter),
            typeof(global::G.JsonConverters.LLMResponseBodyToolDetailsResponseTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UserFilterNodeEnumJsonConverter),
            typeof(global::G.JsonConverters.UserFilterNodeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.UserFilterBranchOperatorJsonConverter),
            typeof(global::G.JsonConverters.UserFilterBranchOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.PSizeJsonConverter),
            typeof(global::G.JsonConverters.PSizeNullableJsonConverter),
            typeof(global::G.JsonConverters.StatsTimeFrameJsonConverter),
            typeof(global::G.JsonConverters.StatsTimeFrameNullableJsonConverter),
            typeof(global::G.JsonConverters.SessionFilterNodeEnumJsonConverter),
            typeof(global::G.JsonConverters.SessionFilterNodeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.SessionFilterBranchOperatorJsonConverter),
            typeof(global::G.JsonConverters.SessionFilterBranchOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.SessionNameQueryParamsPSizeJsonConverter),
            typeof(global::G.JsonConverters.SessionNameQueryParamsPSizeNullableJsonConverter),
            typeof(global::G.JsonConverters.SessionMetricsQueryParamsPSizeJsonConverter),
            typeof(global::G.JsonConverters.SessionMetricsQueryParamsPSizeNullableJsonConverter),
            typeof(global::G.JsonConverters.TimeFrameJsonConverter),
            typeof(global::G.JsonConverters.TimeFrameNullableJsonConverter),
            typeof(global::G.JsonConverters.FilterNodeEnum2JsonConverter),
            typeof(global::G.JsonConverters.FilterNodeEnum2NullableJsonConverter),
            typeof(global::G.JsonConverters.FilterBranchOperatorJsonConverter),
            typeof(global::G.JsonConverters.FilterBranchOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestClickhouseFilterNodeEnumJsonConverter),
            typeof(global::G.JsonConverters.RequestClickhouseFilterNodeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.RequestClickhouseFilterBranchOperatorJsonConverter),
            typeof(global::G.JsonConverters.RequestClickhouseFilterBranchOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.TimeIncrementJsonConverter),
            typeof(global::G.JsonConverters.TimeIncrementNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageAnnotationTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageAnnotationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageFunctionToolCallTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageFunctionToolCallTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageCustomToolCallTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageCustomToolCallTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionChoiceFinishReasonJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionChoiceFinishReasonNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionObjectJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionServiceTierJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionServiceTierNullableJsonConverter),
            typeof(global::G.JsonConverters.AuthorNameJsonConverter),
            typeof(global::G.JsonConverters.AuthorNameNullableJsonConverter),
            typeof(global::G.JsonConverters.StandardParameterJsonConverter),
            typeof(global::G.JsonConverters.StandardParameterNullableJsonConverter),
            typeof(global::G.JsonConverters.PluginIdJsonConverter),
            typeof(global::G.JsonConverters.PluginIdNullableJsonConverter),
            typeof(global::G.JsonConverters.BodyMappingTypeJsonConverter),
            typeof(global::G.JsonConverters.BodyMappingTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelProviderConfigQuantizationJsonConverter),
            typeof(global::G.JsonConverters.ModelProviderConfigQuantizationNullableJsonConverter),
            typeof(global::G.JsonConverters.InputModalityJsonConverter),
            typeof(global::G.JsonConverters.InputModalityNullableJsonConverter),
            typeof(global::G.JsonConverters.OutputModalityJsonConverter),
            typeof(global::G.JsonConverters.OutputModalityNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelCapabilityJsonConverter),
            typeof(global::G.JsonConverters.ModelCapabilityNullableJsonConverter),
            typeof(global::G.JsonConverters.OAIModelObjectJsonConverter),
            typeof(global::G.JsonConverters.OAIModelObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.OAIModelsResponseObjectJsonConverter),
            typeof(global::G.JsonConverters.OAIModelsResponseObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.ExperimentFilterNodeEnumJsonConverter),
            typeof(global::G.JsonConverters.ExperimentFilterNodeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ExperimentFilterBranchOperatorJsonConverter),
            typeof(global::G.JsonConverters.ExperimentFilterBranchOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.NewDatasetParamsDatasetTypeJsonConverter),
            typeof(global::G.JsonConverters.NewDatasetParamsDatasetTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DatasetFilterNodeEnumJsonConverter),
            typeof(global::G.JsonConverters.DatasetFilterNodeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.DatasetFilterBranchOperatorJsonConverter),
            typeof(global::G.JsonConverters.DatasetFilterBranchOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.EvalFilterNodeEnumJsonConverter),
            typeof(global::G.JsonConverters.EvalFilterNodeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.EvalFilterBranchOperatorJsonConverter),
            typeof(global::G.JsonConverters.EvalFilterBranchOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateAPIKeyRequestKeyPermissionsJsonConverter),
            typeof(global::G.JsonConverters.CreateAPIKeyRequestKeyPermissionsNullableJsonConverter),
            typeof(global::G.JsonConverters.TrackShareRequestPlatformJsonConverter),
            typeof(global::G.JsonConverters.TrackShareRequestPlatformNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateNewExperimentHypothesisRequestStatusJsonConverter),
            typeof(global::G.JsonConverters.CreateNewExperimentHypothesisRequestStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.AddOnsProductTypeJsonConverter),
            typeof(global::G.JsonConverters.AddOnsProductTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteAddOnsProductTypeJsonConverter),
            typeof(global::G.JsonConverters.DeleteAddOnsProductTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetSpendBreakdownTimeRangeJsonConverter),
            typeof(global::G.JsonConverters.GetSpendBreakdownTimeRangeNullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteProviderKeyResponseVariant1ProviderNameJsonConverter),
            typeof(global::G.JsonConverters.DeleteProviderKeyResponseVariant1ProviderNameNullableJsonConverter),
            typeof(global::G.JsonConverters.ResultIdStringProviderNameStringStringJsonConverter),
            typeof(global::G.JsonConverters.ResultApiKeyHashStringApiKeyNameStringCreatedAtStringGovernanceBooleanIdNumberKeyPermissionsStringOrganizationIdStringSoftDeleteBooleanTempKeyBooleanUpdatedAtStringUserIdStringArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultEvaluatorResultStringJsonConverter),
            typeof(global::G.JsonConverters.ResultEvaluatorResultArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultNullStringJsonConverter),
            typeof(global::G.JsonConverters.ResultEvaluatorExperimentArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultOnlineEvaluatorByEvaluatorIdArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultOutputStringTracesStringArrayStatusCode63NumberStringJsonConverter),
            typeof(global::G.JsonConverters.ResultEvaluatorScoreStringJsonConverter),
            typeof(global::G.JsonConverters.ResultScoreNumberInputStringOutputStringGroundTruth63StringStringJsonConverter),
            typeof(global::G.JsonConverters.DataEntryJsonConverter),
            typeof(global::G.JsonConverters.LastMileConfigFormJsonConverter),
            typeof(global::G.JsonConverters.ResultEvaluatorStatsStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPrompt2025StringJsonConverter),
            typeof(global::G.JsonConverters.ResultStringArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPrompt2025InputStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPromptCreateResponseStringJsonConverter),
            typeof(global::G.JsonConverters.ResultIdStringStringJsonConverter),
            typeof(global::G.JsonConverters.ResultNumberStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPrompt2025ArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPrompt2025VersionStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPrompt2025VersionArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPromptVersionCountsStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPrompt2025Version91PromptBody93StringJsonConverter),
            typeof(global::G.JsonConverters.ResultHasPromptsBooleanStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPromptsResultArrayStringJsonConverter),
            typeof(global::G.JsonConverters.PromptsFilterNodeJsonConverter),
            typeof(global::G.JsonConverters.ResultPromptResultStringJsonConverter),
            typeof(global::G.JsonConverters.ResultCreatePromptResponseStringJsonConverter),
            typeof(global::G.JsonConverters.ResultMetadataRecordStringAnyStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPromptVersionResultStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPromptInputRecordArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultIdStringCreatedAtStringNumHypothesesNumberDatasetStringMetaRecordStringAnyArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPromptVersionResultArrayStringJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionsFilterNodeJsonConverter),
            typeof(global::G.JsonConverters.ResultPromptVersionResultCompiledStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPromptVersionResultFilledStringJsonConverter),
            typeof(global::G.JsonConverters.ResultExperimentIdStringStringJsonConverter),
            typeof(global::G.JsonConverters.ResultExperimentV2ArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultExtendedExperimentDataStringJsonConverter),
            typeof(global::G.JsonConverters.JsonJsonConverter),
            typeof(global::G.JsonConverters.ResultExperimentV2PromptVersionArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultStringStringJsonConverter),
            typeof(global::G.JsonConverters.ResultBooleanStringJsonConverter),
            typeof(global::G.JsonConverters.ResultRecordStringScoreV2StringJsonConverter),
            typeof(global::G.JsonConverters.ResultScoreV2OrNullStringJsonConverter),
            typeof(global::G.JsonConverters.ResultArrayIntegrationStringJsonConverter),
            typeof(global::G.JsonConverters.ResultIntegrationStringJsonConverter),
            typeof(global::G.JsonConverters.ResultArrayIdStringNameStringStringJsonConverter),
            typeof(global::G.JsonConverters.RequestFilterNodeJsonConverter),
            typeof(global::G.JsonConverters.ProviderJsonConverter),
            typeof(global::G.JsonConverters.ResultHeliconeRequestArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultHeliconeRequestStringJsonConverter),
            typeof(global::G.JsonConverters.ResultInputsRecordStringAnyPromptIdStringVersionIdStringEnvironmentStringOrNullOrNullStringJsonConverter),
            typeof(global::G.JsonConverters.ResultHeliconeRequestAssetStringJsonConverter),
            typeof(global::G.JsonConverters.ResultWrappedStatsStringJsonConverter),
            typeof(global::G.JsonConverters.ResultHasDataBooleanStringJsonConverter),
            typeof(global::G.JsonConverters.ResultIdStringCreatedAtStringDestinationStringVersionStringConfigStringHmacKeyStringArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultSuccessBooleanMessageStringStringJsonConverter),
            typeof(global::G.JsonConverters.ResultSuccessBooleanPosition63NumberAlreadyOnList63BooleanSharedPlatforms63StringArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultIsOnWaitlistBooleanStringJsonConverter),
            typeof(global::G.JsonConverters.ResultCountNumberStringJsonConverter),
            typeof(global::G.JsonConverters.ResultSuccessBooleanNewPosition63NumberMessageStringStringJsonConverter),
            typeof(global::G.JsonConverters.ResultDecryptedProviderKeyArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultDecryptedProviderKeyStringJsonConverter),
            typeof(global::G.JsonConverters.ResultRequestCountHistogramRowArrayUserCostHistogramRowArrayStringJsonConverter),
            typeof(global::G.JsonConverters.UserFilterNodeJsonConverter),
            typeof(global::G.JsonConverters.ResultUsersUserMetricsResultArrayCountNumberHasUsersBooleanStringJsonConverter),
            typeof(global::G.JsonConverters.ResultCountNumberPromptTokensNumberCompletionTokensNumberUserIdStringCostNumberArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultModelUsageResponseStringJsonConverter),
            typeof(global::G.JsonConverters.ResultMarketShareResponseStringJsonConverter),
            typeof(global::G.JsonConverters.ResultProviderUsageResponseStringJsonConverter),
            typeof(global::G.JsonConverters.ResultAuthorStatsResponseStringJsonConverter),
            typeof(global::G.JsonConverters.ResultProviderStatsResponseStringJsonConverter),
            typeof(global::G.JsonConverters.ResultModelStatsResponseStringJsonConverter),
            typeof(global::G.JsonConverters.ResultSessionResultArrayStringJsonConverter),
            typeof(global::G.JsonConverters.SessionFilterNodeJsonConverter),
            typeof(global::G.JsonConverters.ResultSessionsAggregateMetricsStringJsonConverter),
            typeof(global::G.JsonConverters.ResultSessionNameResultArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultSessionMetricsStringJsonConverter),
            typeof(global::G.JsonConverters.ResultStringOrNullStringJsonConverter),
            typeof(global::G.JsonConverters.ResultProviderMetricsArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultProviderMetricsStringJsonConverter),
            typeof(global::G.JsonConverters.ResultProviderMetricArrayStringJsonConverter),
            typeof(global::G.JsonConverters.FilterNodeJsonConverter),
            typeof(global::G.JsonConverters.ResultPropertyStringTotalCostNumberRequestCountNumberCreatedAtTruncStringArrayStringJsonConverter),
            typeof(global::G.JsonConverters.RequestClickhouseFilterNodeJsonConverter),
            typeof(global::G.JsonConverters.ResultPropertyArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultValueStringCostNumberArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultValueStringCountNumberArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageToolCallJsonConverter),
            typeof(global::G.JsonConverters.ResultChatCompletionOrContentStringReasoningStringCallsAnyStringJsonConverter),
            typeof(global::G.JsonConverters.ResultApiKeyStringStringJsonConverter),
            typeof(global::G.JsonConverters.ResultCostNumberCreatedAtTruncStringArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultModelRegistryResponseStringJsonConverter),
            typeof(global::G.JsonConverters.TokenMetricStatsJsonConverter),
            typeof(global::G.JsonConverters.ResultModelArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultTokensPerRequestStringJsonConverter),
            typeof(global::G.JsonConverters.ResultRequestsOverTimeArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultCostOverTimeArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultTokensOverTimeArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultLatencyOverTimeArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultTimeToFirstTokenOverTimeArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultUsersOverTimeArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultThreatsOverTimeArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultErrorOverTimeArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultModelMetricArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultCountryDataArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultQuantilesArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultUnsafeBooleanStringJsonConverter),
            typeof(global::G.JsonConverters.ResultClickHouseTableSchemaArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultExecuteSqlResponseStringJsonConverter),
            typeof(global::G.JsonConverters.ResultArrayHqlSavedQueryStringJsonConverter),
            typeof(global::G.JsonConverters.ResultHqlSavedQueryOrNullStringJsonConverter),
            typeof(global::G.JsonConverters.ResultVoidStringJsonConverter),
            typeof(global::G.JsonConverters.ResultHqlSavedQueryArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultHqlSavedQueryStringJsonConverter),
            typeof(global::G.JsonConverters.ResultTableIdStringExperimentIdStringStringJsonConverter),
            typeof(global::G.JsonConverters.ResultExperimentTableStringJsonConverter),
            typeof(global::G.JsonConverters.ResultExperimentTableSimplifiedStringJsonConverter),
            typeof(global::G.JsonConverters.ResultExperimentTableSimplifiedArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultHypothesisIdStringStringJsonConverter),
            typeof(global::G.JsonConverters.ResultRunsCountNumberScoresRecordStringScoreStringJsonConverter),
            typeof(global::G.JsonConverters.ResultExperimentArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ExperimentFilterNodeJsonConverter),
            typeof(global::G.JsonConverters.ResultDatasetIdStringStringJsonConverter),
            typeof(global::G.JsonConverters.DatasetFilterNodeJsonConverter),
            typeof(global::G.JsonConverters.ResultDatasetResultArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultHeliconeDatasetRowArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultHeliconeDatasetArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultEvalArrayStringJsonConverter),
            typeof(global::G.JsonConverters.EvalFilterNodeJsonConverter),
            typeof(global::G.JsonConverters.ResultScoreDistributionArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultScoreKeyStringScoreSumNumberCreatedAtTruncStringArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultCreditBalanceResponseStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPaginatedPurchasedCreditsStringJsonConverter),
            typeof(global::G.JsonConverters.ResultTotalSpendNumberStringJsonConverter),
            typeof(global::G.JsonConverters.ResultSpendBreakdownResponseStringJsonConverter),
            typeof(global::G.JsonConverters.ResultPTBInvoiceArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultOrgDiscountArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultIdNumberActiveBooleanTitleStringMessageStringCreatedAtStringUpdatedAtStringArrayStringJsonConverter),
            typeof(global::G.JsonConverters.ResultInAppThreadStringJsonConverter),
            typeof(global::G.JsonConverters.ResultSuccessBooleanStringJsonConverter),
            typeof(global::G.JsonConverters.ResultThreadSummaryArrayStringJsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, bool?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.LastMileConfigFormVariant2Variant1, global::G.LastMileConfigFormVariant2Variant2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.OpenAIChatRequestMessageContentVariant2Item>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.OpenAIChatRequestToolChoiceEnum, global::G.OpenAIChatRequestToolChoiceEnum2?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.OpenAIChatRequestFunctionCall>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.Prompt2025VersionPromptBodyMessageContentVariant2Item>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.Prompt2025VersionPromptBodyToolChoice>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.MessageRole?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<string>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, bool?>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.MetricsData, global::G.ProviderMetricsMetrics>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ChatCompletion, global::G.ResultSuccessChatCompletionOrContentStringReasoningStringCallsAnyData>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.DataOverTimeRequest, global::G.GetPropertiesOverTimeRequest2>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.OpenAIChatRequest, global::G.GenerateRequest2>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.OpenAIChatRequest, global::G.GenerateRequest4>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.DeleteProviderKeyResponseVariant1, global::G.DeleteProviderKeyResponseVariant2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.DecryptedProviderKey, global::G.GetProviderKeyResponse2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.CreateProviderKeyResponseVariant1, global::G.CreateProviderKeyResponseVariant2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.ProviderKeyRow>, global::G.GetProviderKeysResponse2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.CreateAPIKeyResponseVariant1, global::G.CreateAPIKeyResponseVariant2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.CreateProxyKeyResponseVariant1, global::G.CreateProxyKeyResponseVariant2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.DeleteAPIKeyResponseVariant1, global::G.DeleteAPIKeyResponseVariant2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.UpdateAPIKeyResponseVariant1, global::G.UpdateAPIKeyResponseVariant2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ResultSuccessUnknown, global::G.ResultErrorUnknown>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ValidationResult, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ResultErrorString, global::G.ResultSuccessString, global::G.ResultSuccessUnknownArray, global::G.HidePropertyResponse2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ResultErrorString, global::G.ResultSuccessString, global::G.ResultSuccessUnknownArray, global::G.RestorePropertyResponse2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ResultErrorString, global::G.ResultSuccessUnknown>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ResultErrorUnknown, global::G.ResultSuccessAny>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}