//HintName: G.Models.ChatCompletionChoice.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    public sealed partial class ChatCompletionChoice
    {
        /// <summary>
        /// The reason the model stopped generating tokens. This will be `stop` if the model<br/>
        /// hit a natural stop point or a provided stop sequence, `length` if the maximum<br/>
        /// number of tokens specified in the request was reached, `content_filter` if<br/>
        /// content was omitted due to a flag from our content filters, `tool_calls` if the<br/>
        /// model called a tool, or `function_call` (deprecated) if the model called a<br/>
        /// function.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("finish_reason")]
        [global::System.Text.Json.Serialization.JsonConverter(typeof(global::G.JsonConverters.ChatCompletionChoiceFinishReasonJsonConverter))]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required global::G.ChatCompletionChoiceFinishReason FinishReason { get; set; }

        /// <summary>
        /// The index of the choice in the list of choices.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("index")]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required double Index { get; set; }

        /// <summary>
        /// Log probability information for the choice.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("logprobs")]
        public global::G.ChatCompletionChoiceLogprobs? Logprobs { get; set; }

        /// <summary>
        /// A chat completion message generated by the model.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("message")]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required global::G.ChatCompletionMessage Message { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::System.Text.Json.Serialization.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatCompletionChoice" /> class.
        /// </summary>
        /// <param name="finishReason">
        /// The reason the model stopped generating tokens. This will be `stop` if the model<br/>
        /// hit a natural stop point or a provided stop sequence, `length` if the maximum<br/>
        /// number of tokens specified in the request was reached, `content_filter` if<br/>
        /// content was omitted due to a flag from our content filters, `tool_calls` if the<br/>
        /// model called a tool, or `function_call` (deprecated) if the model called a<br/>
        /// function.
        /// </param>
        /// <param name="index">
        /// The index of the choice in the list of choices.
        /// </param>
        /// <param name="message">
        /// A chat completion message generated by the model.
        /// </param>
        /// <param name="logprobs">
        /// Log probability information for the choice.
        /// </param>
#if NET7_0_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
#endif
        public ChatCompletionChoice(
            global::G.ChatCompletionChoiceFinishReason finishReason,
            double index,
            global::G.ChatCompletionMessage message,
            global::G.ChatCompletionChoiceLogprobs? logprobs)
        {
            this.FinishReason = finishReason;
            this.Index = index;
            this.Logprobs = logprobs;
            this.Message = message ?? throw new global::System.ArgumentNullException(nameof(message));
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatCompletionChoice" /> class.
        /// </summary>
        public ChatCompletionChoice()
        {
        }
    }
}