//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.CreateAnnotationConfigDataDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateAnnotationConfigDataDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateAnnotationConfigResponseBodyDataDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateAnnotationConfigResponseBodyDataDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateUserRequestBodyUserDiscriminatorAuthMethodJsonConverter),
            typeof(global::G.JsonConverters.CreateUserRequestBodyUserDiscriminatorAuthMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateUserResponseBodyDataDiscriminatorAuthMethodJsonConverter),
            typeof(global::G.JsonConverters.CreateUserResponseBodyDataDiscriminatorAuthMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteAnnotationConfigResponseBodyDataDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.DeleteAnnotationConfigResponseBodyDataDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetAnnotationConfigResponseBodyDataDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetAnnotationConfigResponseBodyDataDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetAnnotationConfigsResponseBodyDataItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetAnnotationConfigsResponseBodyDataItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetUsersResponseBodyDataItemDiscriminatorAuthMethodJsonConverter),
            typeof(global::G.JsonConverters.GetUsersResponseBodyDataItemDiscriminatorAuthMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.GetViewerResponseBodyDataDiscriminatorAuthMethodJsonConverter),
            typeof(global::G.JsonConverters.GetViewerResponseBodyDataDiscriminatorAuthMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.LDAPUserRoleJsonConverter),
            typeof(global::G.JsonConverters.LDAPUserRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.LDAPUserDataRoleJsonConverter),
            typeof(global::G.JsonConverters.LDAPUserDataRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.LocalUserRoleJsonConverter),
            typeof(global::G.JsonConverters.LocalUserRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.LocalUserDataRoleJsonConverter),
            typeof(global::G.JsonConverters.LocalUserDataRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelProviderJsonConverter),
            typeof(global::G.JsonConverters.ModelProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.OAuth2UserRoleJsonConverter),
            typeof(global::G.JsonConverters.OAuth2UserRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.OAuth2UserDataRoleJsonConverter),
            typeof(global::G.JsonConverters.OAuth2UserDataRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.OptimizationDirectionJsonConverter),
            typeof(global::G.JsonConverters.OptimizationDirectionNullableJsonConverter),
            typeof(global::G.JsonConverters.OtlpDoubleValueJsonConverter),
            typeof(global::G.JsonConverters.OtlpDoubleValueNullableJsonConverter),
            typeof(global::G.JsonConverters.OtlpKindJsonConverter),
            typeof(global::G.JsonConverters.OtlpKindNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptAnthropicInvocationParametersContentThinkingDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptAnthropicInvocationParametersContentThinkingDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptAzureOpenAIInvocationParametersContentReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.PromptAzureOpenAIInvocationParametersContentReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptCerebrasInvocationParametersContentReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.PromptCerebrasInvocationParametersContentReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptDeepSeekInvocationParametersContentReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.PromptDeepSeekInvocationParametersContentReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptFireworksInvocationParametersContentReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.PromptFireworksInvocationParametersContentReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptGroqInvocationParametersContentReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.PromptGroqInvocationParametersContentReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.PromptMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptMessageContentVariant2ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptMessageContentVariant2ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptMoonshotInvocationParametersContentReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.PromptMoonshotInvocationParametersContentReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptOllamaInvocationParametersContentReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.PromptOllamaInvocationParametersContentReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptOpenAIInvocationParametersContentReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.PromptOpenAIInvocationParametersContentReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptPerplexityInvocationParametersContentReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.PromptPerplexityInvocationParametersContentReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptTemplateFormatJsonConverter),
            typeof(global::G.JsonConverters.PromptTemplateFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptTemplateTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptTemplateTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptTogetherInvocationParametersContentReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.PromptTogetherInvocationParametersContentReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptToolsToolDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptToolsToolDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptToolsToolChoiceDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptToolsToolChoiceDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionTemplateDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionTemplateDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionInvocationParametersDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionInvocationParametersDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionDataTemplateDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionDataTemplateDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionDataInvocationParametersDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionDataInvocationParametersDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionDataResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptVersionDataResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptXAIInvocationParametersContentReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.PromptXAIInvocationParametersContentReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.SessionAnnotationSourceJsonConverter),
            typeof(global::G.JsonConverters.SessionAnnotationSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.SessionAnnotationAnnotatorKindJsonConverter),
            typeof(global::G.JsonConverters.SessionAnnotationAnnotatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.SessionAnnotationDataAnnotatorKindJsonConverter),
            typeof(global::G.JsonConverters.SessionAnnotationDataAnnotatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.SpanAnnotationSourceJsonConverter),
            typeof(global::G.JsonConverters.SpanAnnotationSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.SpanAnnotationAnnotatorKindJsonConverter),
            typeof(global::G.JsonConverters.SpanAnnotationAnnotatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.SpanAnnotationDataAnnotatorKindJsonConverter),
            typeof(global::G.JsonConverters.SpanAnnotationDataAnnotatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.SpanDocumentAnnotationDataAnnotatorKindJsonConverter),
            typeof(global::G.JsonConverters.SpanDocumentAnnotationDataAnnotatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolCallContentPartToolCallDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolCallContentPartToolCallDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TraceAnnotationSourceJsonConverter),
            typeof(global::G.JsonConverters.TraceAnnotationSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.TraceAnnotationAnnotatorKindJsonConverter),
            typeof(global::G.JsonConverters.TraceAnnotationAnnotatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.TraceAnnotationDataAnnotatorKindJsonConverter),
            typeof(global::G.JsonConverters.TraceAnnotationDataAnnotatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.UpdateAnnotationConfigResponseBodyDataDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.UpdateAnnotationConfigResponseBodyDataDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UpsertExperimentEvaluationRequestBodyAnnotatorKindJsonConverter),
            typeof(global::G.JsonConverters.UpsertExperimentEvaluationRequestBodyAnnotatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.UploadDatasetRequestActionJsonConverter),
            typeof(global::G.JsonConverters.UploadDatasetRequestActionNullableJsonConverter),
            typeof(global::G.JsonConverters.UploadDatasetRequestAction2JsonConverter),
            typeof(global::G.JsonConverters.UploadDatasetRequestAction2NullableJsonConverter),
            typeof(global::G.JsonConverters.ListProjectTracesSortJsonConverter),
            typeof(global::G.JsonConverters.ListProjectTracesSortNullableJsonConverter),
            typeof(global::G.JsonConverters.ListProjectTracesOrderJsonConverter),
            typeof(global::G.JsonConverters.ListProjectTracesOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListProjectSessionsOrderJsonConverter),
            typeof(global::G.JsonConverters.ListProjectSessionsOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateAnnotationConfigDataJsonConverter),
            typeof(global::G.JsonConverters.DataJsonConverter),
            typeof(global::G.JsonConverters.UserJsonConverter),
            typeof(global::G.JsonConverters.Data2JsonConverter),
            typeof(global::G.JsonConverters.Data3JsonConverter),
            typeof(global::G.JsonConverters.Data4JsonConverter),
            typeof(global::G.JsonConverters.DataItemJsonConverter),
            typeof(global::G.JsonConverters.DataItem2JsonConverter),
            typeof(global::G.JsonConverters.Data5JsonConverter),
            typeof(global::G.JsonConverters.ThinkingJsonConverter),
            typeof(global::G.JsonConverters.ContentVariant2ItemJsonConverter),
            typeof(global::G.JsonConverters.ToolsItemJsonConverter),
            typeof(global::G.JsonConverters.ToolChoiceJsonConverter),
            typeof(global::G.JsonConverters.TemplateJsonConverter),
            typeof(global::G.JsonConverters.InvocationParametersJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant1JsonConverter),
            typeof(global::G.JsonConverters.Template2JsonConverter),
            typeof(global::G.JsonConverters.InvocationParameters2JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant12JsonConverter),
            typeof(global::G.JsonConverters.Data6JsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, global::G.OtlpDoubleValue?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<long?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<long?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.OtlpKind?, int?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<long?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ContentVariant2Item>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<bool?, int?, double?, string, object, global::System.Collections.Generic.IList<object>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<string>, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, object>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}