//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.CreateSpeechRequestModelJsonConverter),
            typeof(global::G.JsonConverters.CreateSpeechRequestModelNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateSpeechRequestResponseFormatJsonConverter),
            typeof(global::G.JsonConverters.CreateSpeechRequestResponseFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTranscriptionRequestModelJsonConverter),
            typeof(global::G.JsonConverters.CreateTranscriptionRequestModelNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTranscriptionRequestLanguageJsonConverter),
            typeof(global::G.JsonConverters.CreateTranscriptionRequestLanguageNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTranscriptionRequestResponseFormatJsonConverter),
            typeof(global::G.JsonConverters.CreateTranscriptionRequestResponseFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTranscriptionRequestTimestampGranularitieJsonConverter),
            typeof(global::G.JsonConverters.CreateTranscriptionRequestTimestampGranularitieNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTranslationRequestModelJsonConverter),
            typeof(global::G.JsonConverters.CreateTranslationRequestModelNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTranslationRequestResponseFormatJsonConverter),
            typeof(global::G.JsonConverters.CreateTranslationRequestResponseFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchObjectJsonConverter),
            typeof(global::G.JsonConverters.BatchObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchStatusJsonConverter),
            typeof(global::G.JsonConverters.BatchStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchRequestInputMethodJsonConverter),
            typeof(global::G.JsonConverters.BatchRequestInputMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.ListBatchesResponseObjectJsonConverter),
            typeof(global::G.JsonConverters.ListBatchesResponseObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageContentPartImageTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageContentPartImageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageContentPartImageImageUrlDetailJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageContentPartImageImageUrlDetailNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageContentPartTextTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageContentPartTextTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageContentPartDocumentTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageContentPartDocumentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionDocumentSourceDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionDocumentSourceDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionDocumentSourceTextTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionDocumentSourceTextTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionDocumentSourceJSONTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionDocumentSourceJSONTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageDiscriminatorRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageDiscriminatorRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestSystemMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestSystemMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestUserMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestUserMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestAssistantMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestAssistantMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestToolMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestToolMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestFunctionMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestFunctionMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionToolTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionToolChoiceOptionEnumJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionToolChoiceOptionEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionNamedToolChoiceTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionNamedToolChoiceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageToolCallTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageToolCallTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageToolCallChunkTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageToolCallChunkTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionResponseMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionResponseMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionStreamResponseDeltaRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionStreamResponseDeltaRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionRequestModelJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionRequestModelNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionRequestServiceTierJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionRequestServiceTierNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionRequestReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionRequestReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionRequestReasoningFormatJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionRequestReasoningFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionRequestFunctionCallJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionRequestFunctionCallNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionRequestCitationOptionsJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionRequestCitationOptionsNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatJsonObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatJsonObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatJsonSchemaTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatJsonSchemaTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatTextTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatTextTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionResponseChoiceFinishReasonJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionResponseChoiceFinishReasonNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionResponseObjectJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionResponseObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionResponseServiceTierJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionResponseServiceTierNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionStreamResponseChoiceFinishReasonJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionStreamResponseChoiceFinishReasonNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionStreamResponseObjectJsonConverter),
            typeof(global::G.JsonConverters.CreateChatCompletionStreamResponseObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.ChartTypeJsonConverter),
            typeof(global::G.JsonConverters.ChartTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AnnotationTypeJsonConverter),
            typeof(global::G.JsonConverters.AnnotationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingObjectJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateEmbeddingRequestModelJsonConverter),
            typeof(global::G.JsonConverters.CreateEmbeddingRequestModelNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateEmbeddingRequestEncodingFormatJsonConverter),
            typeof(global::G.JsonConverters.CreateEmbeddingRequestEncodingFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateEmbeddingResponseObjectJsonConverter),
            typeof(global::G.JsonConverters.CreateEmbeddingResponseObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.FileObjectJsonConverter),
            typeof(global::G.JsonConverters.FileObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.FilePurposeJsonConverter),
            typeof(global::G.JsonConverters.FilePurposeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateFileRequestPurposeJsonConverter),
            typeof(global::G.JsonConverters.CreateFileRequestPurposeNullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteFileResponseObjectJsonConverter),
            typeof(global::G.JsonConverters.DeleteFileResponseObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.ListFilesResponseObjectJsonConverter),
            typeof(global::G.JsonConverters.ListFilesResponseObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelObjectJsonConverter),
            typeof(global::G.JsonConverters.ModelObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.ListModelsResponseObjectJsonConverter),
            typeof(global::G.JsonConverters.ListModelsResponseObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseRequestModelJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseRequestModelNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseRequestReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseRequestReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseRequestServiceTierJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseRequestServiceTierNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseRequestTruncationJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseRequestTruncationNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseEasyInputMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ResponseEasyInputMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputMessageStatusJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputMessageStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputContentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputContentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputTextContentTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputTextContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseItemReferenceTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseItemReferenceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFunctionCallTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseFunctionCallTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFunctionCallStatusJsonConverter),
            typeof(global::G.JsonConverters.ResponseFunctionCallStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFunctionCallOutputTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseFunctionCallOutputTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFunctionCallOutputStatusJsonConverter),
            typeof(global::G.JsonConverters.ResponseFunctionCallOutputStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseToolTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseToolChoiceOptionEnumJsonConverter),
            typeof(global::G.JsonConverters.ResponseToolChoiceOptionEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseNamedToolChoiceTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseNamedToolChoiceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TextResponseFormatJsonSchemaTypeJsonConverter),
            typeof(global::G.JsonConverters.TextResponseFormatJsonSchemaTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseResponseObjectJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseResponseObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseResponseStatusJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseResponseStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseResponseReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseResponseReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseResponseTruncationJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseResponseTruncationNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseResponseServiceTierJsonConverter),
            typeof(global::G.JsonConverters.CreateResponseResponseServiceTierNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputMessageStatusJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputMessageStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputContentDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputContentDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputTextContentTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputTextContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseAnnotationDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseAnnotationDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFileCitationTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseFileCitationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseUrlCitationTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseUrlCitationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputFunctionCallTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputFunctionCallTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputFunctionCallStatusJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputFunctionCallStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputReasoningTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputReasoningTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateBatchRequestEndpointJsonConverter),
            typeof(global::G.JsonConverters.CreateBatchRequestEndpointNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageContentPartJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionDocumentSourceJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionRequestMessageJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionToolChoiceOptionJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputItemJsonConverter),
            typeof(global::G.JsonConverters.ResponseInputContentJsonConverter),
            typeof(global::G.JsonConverters.ResponseToolChoiceOptionJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatConfigurationJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputItemJsonConverter),
            typeof(global::G.JsonConverters.ResponseOutputContentJsonConverter),
            typeof(global::G.JsonConverters.ResponseAnnotationJsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.CreateSpeechRequestModel?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.CreateTranscriptionRequestModel?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.CreateTranscriptionRequestLanguage?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.CreateTranslationRequestModel?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ChatCompletionRequestMessageContentPartText>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ChatCompletionRequestMessageContentPart>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ChatCompletionRequestMessageContentPartText>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ChatCompletionRequestMessageContentPart>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ChatCompletionToolType?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.CreateChatCompletionRequestModel?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ResponseFormatText, global::G.ResponseFormatJsonSchema, global::G.ResponseFormatJsonObject>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.CreateChatCompletionRequestFunctionCall?, global::G.ChatCompletionFunctionCallOption>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::System.Collections.Generic.IList<double>, string>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.CreateEmbeddingRequestModel?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.CreateResponseRequestModel?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ResponseInputItem>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ResponseInputContent>>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}