//HintName: G.Models.CreateAssistantDTOFirstMessageMode.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// This is the mode for the first message. Default is 'assistant-speaks-first'.<br/>
    /// Use:<br/>
    /// - 'assistant-speaks-first' to have the assistant speak first.<br/>
    /// - 'assistant-waits-for-user' to have the assistant wait for the user to speak first.<br/>
    /// - 'assistant-speaks-first-with-model-generated-message' to have the assistant speak first with a message generated by the model based on the conversation state. (`assistant.model.messages` at call start, `call.messages` at squad transfer points).<br/>
    /// @default 'assistant-speaks-first'<br/>
    /// Example: assistant-speaks-first
    /// </summary>
    public enum CreateAssistantDTOFirstMessageMode
    {
        /// <summary>
        /// 
        /// </summary>
        AssistantSpeaksFirst,
        /// <summary>
        /// 
        /// </summary>
        AssistantSpeaksFirstWithModelGeneratedMessage,
        /// <summary>
        /// 
        /// </summary>
        AssistantWaitsForUser,
    }

    /// <summary>
    /// Enum extensions to do fast conversions without the reflection.
    /// </summary>
    public static class CreateAssistantDTOFirstMessageModeExtensions
    {
        /// <summary>
        /// Converts an enum to a string.
        /// </summary>
        public static string ToValueString(this CreateAssistantDTOFirstMessageMode value)
        {
            return value switch
            {
                CreateAssistantDTOFirstMessageMode.AssistantSpeaksFirst => "assistant-speaks-first",
                CreateAssistantDTOFirstMessageMode.AssistantSpeaksFirstWithModelGeneratedMessage => "assistant-speaks-first-with-model-generated-message",
                CreateAssistantDTOFirstMessageMode.AssistantWaitsForUser => "assistant-waits-for-user",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(value), value, null),
            };
        }
        /// <summary>
        /// Converts an string to a enum.
        /// </summary>
        public static CreateAssistantDTOFirstMessageMode? ToEnum(string value)
        {
            return value switch
            {
                "assistant-speaks-first" => CreateAssistantDTOFirstMessageMode.AssistantSpeaksFirst,
                "assistant-speaks-first-with-model-generated-message" => CreateAssistantDTOFirstMessageMode.AssistantSpeaksFirstWithModelGeneratedMessage,
                "assistant-waits-for-user" => CreateAssistantDTOFirstMessageMode.AssistantWaitsForUser,
                _ => null,
            };
        }
    }
}