using System.Collections.Immutable;
using AutoSDK.Naming.Methods;
using AutoSDK.Serialization.Json;

namespace AutoSDK.Models;

public record struct Settings(
    string TargetFramework,
    string Namespace,
    string ClassName,
    string ClsCompliantEnumPrefix,
    IdentifierCharacterSet IdentifierCharacterSet,
    NamingConvention NamingConvention,
    JsonSerializerType JsonSerializerType,
    SdkFeatureUsage UseRequiredKeyword,
    SdkFeatureUsage UseExperimentalAttributes,
    SdkFeatureUsage UseSetsRequiredMembersAttributes,

    bool GenerateConstructors,
    bool GroupByTags,
    bool GenerateMethods,
    MethodNamingConvention MethodNamingConvention,
    MethodNamingConvention MethodNamingConventionFallback,
    bool GenerateMethodsAsHttpClientExtensions,
    bool GenerateMethodsUsingSystemNetHttpJson,
    bool GenerateDependencyInjection,
    bool GenerateConfigurationBinding,
    bool GenerateHttpResilienceExtensions,
    bool GenerateHttpExceptionHierarchy,
    bool GenerateIdempotencyHelpers,
    string IdempotencyHeaderName,
    bool GenerateRetryHandler,
    bool GenerateWebhookVerifier,
    string WebhookVerifierClassName,
    string WebhookIdHeaderName,
    string WebhookTimestampHeaderName,
    string WebhookSignatureHeaderName,
    string WebhookSignatureVersion,
    int WebhookTimestampToleranceSeconds,
    bool GenerateDynamicMultipartHelpers,
    string DynamicMultipartHelperClassName,
    bool GenerateMultipartUploadHelpers,
    string MultipartUploadHelperClassName,
    bool GeneratePolymorphicArrayHelpers,
    bool GeneratePromptTemplateHelpers,
    string PromptTemplateHelperClassName,
    bool GenerateObservabilityLifecycleHelpers,
    string ObservabilityLifecycleHelperClassName,
    bool GeneratePredictionWorkflowHelpers,
    string PredictionWorkflowHelperClassName,
    bool GenerateEvaluationWorkflowHelpers,
    string EvaluationWorkflowHelperClassName,
    bool GenerateCloudSigningHelpers,
    string CloudSigningHelperClassName,
    bool AutoDetectStatusPolling,
    bool GeneratePageableHelpers,
    ImmutableArray<string> IncludeOperationIds,
    ImmutableArray<string> ExcludeOperationIds,
    ImmutableArray<string> IncludeTags,
    ImmutableArray<string> ExcludeTags,
    bool ExcludeDeprecatedOperations,
    bool UseExtensionNaming,
    string JsonSerializerContext,
    bool GenerateJsonSerializerContextTypes,
    bool DirectionAwareJsonGenerationMode,
    bool ComputeDiscriminators,
    bool AddMissingPathParameters,

    bool GenerateModels,
    bool GenerateModelValidationMethods,
    bool ValidateAnyOfs,
    bool GenerateRawModelData,
    ModelStyle ModelStyle,
    ImmutableArray<string> IncludeModels,
    ImmutableArray<string> ExcludeModels,
    string NamespaceDelimiter,
    ExcludedModelNamespaceMode ExcludedModelNamespaceMode,
    
    bool IgnoreOpenApiErrors,
    bool IgnoreOpenApiWarnings,

    bool GeneratePolyfills,
    bool GenerateExceptions,

    bool GenerateSdk,
    bool FromCli,

    bool GenerateCli,

    ImmutableArray<string> SecuritySchemes,
    ImmutableArray<string> AuthorizationEnvironmentVariables,
    string BaseUrl,
    ImmutableArray<string> BaseUrlEnvironmentVariables,
    ImmutableArray<string> OpenApiOverrides,

    bool GenerateWebSocketClient,
    string WebSocketClientClassName,
    string TypesNamespace,

    bool SplitByTags,
    string BasePackageId,
    string PackageMapPath,
    string StrongNamePublicKey)
{
    /// <summary>
    /// Accessibility emitted for shared runtime members that generated tag assemblies must reach
    /// across an assembly boundary when <see cref="SplitByTags"/> is enabled.
    /// Stays <c>internal</c> in the default single-project mode, and also in split mode when
    /// <see cref="StrongNamePublicKey"/> lets AutoSDK emit <c>InternalsVisibleTo</c> instead.
    /// </summary>
    public string SharedMemberAccessibility =>
        SplitByTags && string.IsNullOrWhiteSpace(StrongNamePublicKey)
            ? "public"
            : "internal";

    /// <summary>
    /// True when shared runtime members are widened to <c>public</c> and therefore need
    /// <c>[EditorBrowsable(Never)]</c> so they stay out of consumer IntelliSense.
    /// </summary>
    public bool HidesSharedMembersFromIntelliSense =>
        SplitByTags && string.IsNullOrWhiteSpace(StrongNamePublicKey);

    public static Settings Default => new(
        TargetFramework: "net10.0",
        Namespace: string.Empty,
        ClassName: string.Empty,
        ClsCompliantEnumPrefix: string.Empty,
        IdentifierCharacterSet: IdentifierCharacterSet.UnicodeLetters,
        NamingConvention: default,
        JsonSerializerType: default,
        UseRequiredKeyword: default,
        UseExperimentalAttributes: default,
        UseSetsRequiredMembersAttributes: default,
        GenerateConstructors: false,
        GroupByTags: true,
        GenerateMethods: false,
        MethodNamingConvention: default,
        MethodNamingConventionFallback: MethodNamingConvention.MethodAndPath,
        GenerateMethodsAsHttpClientExtensions: false,
        GenerateMethodsUsingSystemNetHttpJson: false,
        GenerateDependencyInjection: false,
        GenerateConfigurationBinding: false,
        GenerateHttpResilienceExtensions: false,
        GenerateHttpExceptionHierarchy: false,
        GenerateIdempotencyHelpers: false,
        IdempotencyHeaderName: "Idempotency-Key",
        GenerateRetryHandler: false,
        GenerateWebhookVerifier: false,
        WebhookVerifierClassName: string.Empty,
        WebhookIdHeaderName: "webhook-id",
        WebhookTimestampHeaderName: "webhook-timestamp",
        WebhookSignatureHeaderName: "webhook-signature",
        WebhookSignatureVersion: "v1",
        WebhookTimestampToleranceSeconds: 300,
        GenerateDynamicMultipartHelpers: false,
        DynamicMultipartHelperClassName: string.Empty,
        GenerateMultipartUploadHelpers: false,
        MultipartUploadHelperClassName: string.Empty,
        GeneratePolymorphicArrayHelpers: false,
        GeneratePromptTemplateHelpers: false,
        PromptTemplateHelperClassName: string.Empty,
        GenerateObservabilityLifecycleHelpers: false,
        ObservabilityLifecycleHelperClassName: string.Empty,
        GeneratePredictionWorkflowHelpers: false,
        PredictionWorkflowHelperClassName: string.Empty,
        GenerateEvaluationWorkflowHelpers: false,
        EvaluationWorkflowHelperClassName: string.Empty,
        GenerateCloudSigningHelpers: false,
        CloudSigningHelperClassName: string.Empty,
        AutoDetectStatusPolling: false,
        GeneratePageableHelpers: false,
        IncludeOperationIds: ImmutableArray<string>.Empty,
        ExcludeOperationIds: ImmutableArray<string>.Empty,
        IncludeTags: ImmutableArray<string>.Empty,
        ExcludeTags: ImmutableArray<string>.Empty,
        ExcludeDeprecatedOperations: false,
        UseExtensionNaming: true,
        JsonSerializerContext: string.Empty,
        GenerateJsonSerializerContextTypes: false,
        DirectionAwareJsonGenerationMode: false,
        ComputeDiscriminators: false,
        AddMissingPathParameters: true,
        GenerateModels: false,
        GenerateModelValidationMethods: false,
        ValidateAnyOfs: false,
        GenerateRawModelData: false,
        ModelStyle: default,
        IncludeModels: ImmutableArray<string>.Empty,
        ExcludeModels: ImmutableArray<string>.Empty,
        NamespaceDelimiter: string.Empty,
        ExcludedModelNamespaceMode: ExcludedModelNamespaceMode.External,
        IgnoreOpenApiErrors: true,
        IgnoreOpenApiWarnings: true,
        GeneratePolyfills: true,
        GenerateExceptions: true,
        GenerateSdk: true,
        FromCli: false,
        GenerateCli: false,
        SecuritySchemes: ImmutableArray<string>.Empty,
        AuthorizationEnvironmentVariables: ImmutableArray<string>.Empty,
        BaseUrl: string.Empty,
        BaseUrlEnvironmentVariables: ImmutableArray<string>.Empty,
        OpenApiOverrides: ImmutableArray<string>.Empty,
        GenerateWebSocketClient: true,
        WebSocketClientClassName: string.Empty,
        TypesNamespace: string.Empty,
        SplitByTags: false,
        BasePackageId: string.Empty,
        PackageMapPath: string.Empty,
        StrongNamePublicKey: string.Empty
    );
}
