using System.Collections.Immutable;
using AutoSDK.Naming.Methods;
using AutoSDK.Serialization.Json;

namespace AutoSDK.Models;

public record struct Settings(
    string TargetFramework,
    string Namespace,
    string ClassName,
    string ClsCompliantEnumPrefix,
    IdentifierCharacterSet IdentifierCharacterSet,
    NamingConvention NamingConvention,
    JsonSerializerType JsonSerializerType,
    SdkFeatureUsage UseRequiredKeyword,
    SdkFeatureUsage UseExperimentalAttributes,
    SdkFeatureUsage UseSetsRequiredMembersAttributes,

    bool GenerateConstructors,
    bool GroupByTags,
    bool GenerateMethods,
    MethodNamingConvention MethodNamingConvention,
    MethodNamingConvention MethodNamingConventionFallback,
    bool GenerateMethodsAsHttpClientExtensions,
    bool GenerateMethodsUsingSystemNetHttpJson,
    bool GenerateDependencyInjection,
    bool GenerateConfigurationBinding,
    bool GenerateHttpResilienceExtensions,
    bool GenerateWebhookVerifier,
    string WebhookVerifierClassName,
    string WebhookIdHeaderName,
    string WebhookTimestampHeaderName,
    string WebhookSignatureHeaderName,
    string WebhookSignatureVersion,
    int WebhookTimestampToleranceSeconds,
    ImmutableArray<string> IncludeOperationIds,
    ImmutableArray<string> ExcludeOperationIds,
    ImmutableArray<string> IncludeTags,
    ImmutableArray<string> ExcludeTags,
    bool ExcludeDeprecatedOperations,
    bool UseExtensionNaming,
    string JsonSerializerContext,
    bool GenerateJsonSerializerContextTypes,
    bool ComputeDiscriminators,
    bool AddMissingPathParameters,

    bool GenerateModels,
    bool GenerateModelValidationMethods,
    bool ValidateAnyOfs,
    bool GenerateRawModelData,
    ModelStyle ModelStyle,
    ImmutableArray<string> IncludeModels,
    ImmutableArray<string> ExcludeModels,
    string NamespaceDelimiter,
    ExcludedModelNamespaceMode ExcludedModelNamespaceMode,
    
    bool IgnoreOpenApiErrors,
    bool IgnoreOpenApiWarnings,

    bool GeneratePolyfills,
    bool GenerateExceptions,

    bool GenerateSdk,
    bool FromCli,

    bool GenerateCli,

    ImmutableArray<string> SecuritySchemes,
    ImmutableArray<string> AuthorizationEnvironmentVariables,
    string BaseUrl,
    ImmutableArray<string> BaseUrlEnvironmentVariables,
    ImmutableArray<string> OpenApiOverrides,

    bool GenerateWebSocketClient,
    string WebSocketClientClassName,
    string TypesNamespace)
{
    public static Settings Default => new(
        TargetFramework: "net10.0",
        Namespace: string.Empty,
        ClassName: string.Empty,
        ClsCompliantEnumPrefix: string.Empty,
        IdentifierCharacterSet: IdentifierCharacterSet.UnicodeLetters,
        NamingConvention: default,
        JsonSerializerType: default,
        UseRequiredKeyword: default,
        UseExperimentalAttributes: default,
        UseSetsRequiredMembersAttributes: default,
        GenerateConstructors: false,
        GroupByTags: true,
        GenerateMethods: false,
        MethodNamingConvention: default,
        MethodNamingConventionFallback: MethodNamingConvention.MethodAndPath,
        GenerateMethodsAsHttpClientExtensions: false,
        GenerateMethodsUsingSystemNetHttpJson: false,
        GenerateDependencyInjection: false,
        GenerateConfigurationBinding: false,
        GenerateHttpResilienceExtensions: false,
        GenerateWebhookVerifier: false,
        WebhookVerifierClassName: string.Empty,
        WebhookIdHeaderName: "webhook-id",
        WebhookTimestampHeaderName: "webhook-timestamp",
        WebhookSignatureHeaderName: "webhook-signature",
        WebhookSignatureVersion: "v1",
        WebhookTimestampToleranceSeconds: 300,
        IncludeOperationIds: ImmutableArray<string>.Empty,
        ExcludeOperationIds: ImmutableArray<string>.Empty,
        IncludeTags: ImmutableArray<string>.Empty,
        ExcludeTags: ImmutableArray<string>.Empty,
        ExcludeDeprecatedOperations: false,
        UseExtensionNaming: true,
        JsonSerializerContext: string.Empty,
        GenerateJsonSerializerContextTypes: false,
        ComputeDiscriminators: false,
        AddMissingPathParameters: true,
        GenerateModels: false,
        GenerateModelValidationMethods: false,
        ValidateAnyOfs: false,
        GenerateRawModelData: false,
        ModelStyle: default,
        IncludeModels: ImmutableArray<string>.Empty,
        ExcludeModels: ImmutableArray<string>.Empty,
        NamespaceDelimiter: string.Empty,
        ExcludedModelNamespaceMode: ExcludedModelNamespaceMode.External,
        IgnoreOpenApiErrors: true,
        IgnoreOpenApiWarnings: true,
        GeneratePolyfills: true,
        GenerateExceptions: true,
        GenerateSdk: true,
        FromCli: false,
        GenerateCli: false,
        SecuritySchemes: ImmutableArray<string>.Empty,
        AuthorizationEnvironmentVariables: ImmutableArray<string>.Empty,
        BaseUrl: string.Empty,
        BaseUrlEnvironmentVariables: ImmutableArray<string>.Empty,
        OpenApiOverrides: ImmutableArray<string>.Empty,
        GenerateWebSocketClient: true,
        WebSocketClientClassName: string.Empty,
        TypesNamespace: string.Empty
    );
}
