//HintName: G.Models.ResponseVariant3.g.cs

#pragma warning disable CS0618 // Type or member is obsolete

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    public sealed partial class ResponseVariant3
    {
        /// <summary>
        /// Unique identifier for this Response.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("id", Required = global::Newtonsoft.Json.Required.Always)]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The object type of this resource - always set to `response`.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("object")]
        public global::G.ResponseVariant3Object Object { get; set; }

        /// <summary>
        /// The status of the response generation. One of `completed`, `failed`, <br/>
        /// `in_progress`, `cancelled`, `queued`, or `incomplete`.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("status")]
        public global::G.ResponseVariant3Status? Status { get; set; }

        /// <summary>
        /// Unix timestamp (in seconds) of when this Response was created.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("created_at", Required = global::Newtonsoft.Json.Required.Always)]
        public double CreatedAt { get; set; } = default!;

        /// <summary>
        /// An error object returned when the model fails to generate a Response.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("error", Required = global::Newtonsoft.Json.Required.Always)]
        public global::G.ResponseError? Error { get; set; } = default!;

        /// <summary>
        /// Details about why the response is incomplete.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("incomplete_details", Required = global::Newtonsoft.Json.Required.Always)]
        public global::G.ResponseVariant3IncompleteDetails? IncompleteDetails { get; set; } = default!;

        /// <summary>
        /// An array of content items generated by the model.<br/>
        /// - The length and order of items in the `output` array is dependent<br/>
        ///   on the model's response.<br/>
        /// - Rather than accessing the first item in the `output` array and <br/>
        ///   assuming it's an `assistant` message with the content generated by<br/>
        ///   the model, you might consider using the `output_text` property where<br/>
        ///   supported in SDKs.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("output", Required = global::Newtonsoft.Json.Required.Always)]
        public global::System.Collections.Generic.IList<global::G.OutputItem> Output { get; set; } = default!;

        /// <summary>
        /// A system (or developer) message inserted into the model's context.<br/>
        /// When using along with `previous_response_id`, the instructions from a previous<br/>
        /// response will not be carried over to the next response. This makes it simple<br/>
        /// to swap out system (or developer) messages in new responses.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("instructions", Required = global::Newtonsoft.Json.Required.Always)]
        public global::G.OneOf<string, global::System.Collections.Generic.IList<global::G.InputItem>>? Instructions { get; set; } = default!;

        /// <summary>
        /// SDK-only convenience property that contains the aggregated text output <br/>
        /// from all `output_text` items in the `output` array, if any are present. <br/>
        /// Supported in the Python and JavaScript SDKs.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("output_text")]
        public string? OutputText { get; set; }

        /// <summary>
        /// Represents token usage details including input tokens, output tokens,<br/>
        /// a breakdown of output tokens, and the total tokens used.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("usage")]
        public global::G.ResponseUsage? Usage { get; set; }

        /// <summary>
        /// Whether to allow the model to run tool calls in parallel.<br/>
        /// Default Value: true
        /// </summary>
        /// <default>true</default>
        [global::Newtonsoft.Json.JsonProperty("parallel_tool_calls", Required = global::Newtonsoft.Json.Required.Always)]
        public bool ParallelToolCalls { get; set; } = default!;

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseVariant3" /> class.
        /// </summary>
        /// <param name="id">
        /// Unique identifier for this Response.
        /// </param>
        /// <param name="object">
        /// The object type of this resource - always set to `response`.
        /// </param>
        /// <param name="status">
        /// The status of the response generation. One of `completed`, `failed`, <br/>
        /// `in_progress`, `cancelled`, `queued`, or `incomplete`.
        /// </param>
        /// <param name="createdAt">
        /// Unix timestamp (in seconds) of when this Response was created.
        /// </param>
        /// <param name="error">
        /// An error object returned when the model fails to generate a Response.
        /// </param>
        /// <param name="incompleteDetails">
        /// Details about why the response is incomplete.
        /// </param>
        /// <param name="output">
        /// An array of content items generated by the model.<br/>
        /// - The length and order of items in the `output` array is dependent<br/>
        ///   on the model's response.<br/>
        /// - Rather than accessing the first item in the `output` array and <br/>
        ///   assuming it's an `assistant` message with the content generated by<br/>
        ///   the model, you might consider using the `output_text` property where<br/>
        ///   supported in SDKs.
        /// </param>
        /// <param name="instructions">
        /// A system (or developer) message inserted into the model's context.<br/>
        /// When using along with `previous_response_id`, the instructions from a previous<br/>
        /// response will not be carried over to the next response. This makes it simple<br/>
        /// to swap out system (or developer) messages in new responses.
        /// </param>
        /// <param name="outputText">
        /// SDK-only convenience property that contains the aggregated text output <br/>
        /// from all `output_text` items in the `output` array, if any are present. <br/>
        /// Supported in the Python and JavaScript SDKs.
        /// </param>
        /// <param name="usage">
        /// Represents token usage details including input tokens, output tokens,<br/>
        /// a breakdown of output tokens, and the total tokens used.
        /// </param>
        /// <param name="parallelToolCalls">
        /// Whether to allow the model to run tool calls in parallel.<br/>
        /// Default Value: true
        /// </param>
        public ResponseVariant3(
            string id,
            double createdAt,
            global::G.ResponseError? error,
            global::G.ResponseVariant3IncompleteDetails? incompleteDetails,
            global::System.Collections.Generic.IList<global::G.OutputItem> output,
            global::G.OneOf<string, global::System.Collections.Generic.IList<global::G.InputItem>>? instructions,
            bool parallelToolCalls,
            global::G.ResponseVariant3Object @object,
            global::G.ResponseVariant3Status? status,
            string? outputText,
            global::G.ResponseUsage? usage)
        {
            this.Id = id ?? throw new global::System.ArgumentNullException(nameof(id));
            this.CreatedAt = createdAt;
            this.Error = error ?? throw new global::System.ArgumentNullException(nameof(error));
            this.IncompleteDetails = incompleteDetails ?? throw new global::System.ArgumentNullException(nameof(incompleteDetails));
            this.Output = output ?? throw new global::System.ArgumentNullException(nameof(output));
            this.Instructions = instructions;
            this.ParallelToolCalls = parallelToolCalls;
            this.Object = @object;
            this.Status = status;
            this.OutputText = outputText;
            this.Usage = usage;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseVariant3" /> class.
        /// </summary>
        public ResponseVariant3()
        {
        }
    }
}