//HintName: G.Models.LocalShellToolCallOutput.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// The output of a local shell tool call.
    /// </summary>
    public sealed partial class LocalShellToolCallOutput
    {
        /// <summary>
        /// The type of the local shell tool call output. Always `local_shell_call_output`.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("type")]
        public global::G.LocalShellToolCallOutputType Type { get; set; }

        /// <summary>
        /// The unique ID of the local shell tool call generated by the model.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("id", Required = global::Newtonsoft.Json.Required.Always)]
        public string Id { get; set; } = default!;

        /// <summary>
        /// A JSON string of the output of the local shell tool call.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("output", Required = global::Newtonsoft.Json.Required.Always)]
        public string Output { get; set; } = default!;

        /// <summary>
        /// The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("status")]
        public global::G.LocalShellToolCallOutputStatus? Status { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalShellToolCallOutput" /> class.
        /// </summary>
        /// <param name="type">
        /// The type of the local shell tool call output. Always `local_shell_call_output`.
        /// </param>
        /// <param name="id">
        /// The unique ID of the local shell tool call generated by the model.
        /// </param>
        /// <param name="output">
        /// A JSON string of the output of the local shell tool call.
        /// </param>
        /// <param name="status">
        /// The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        /// </param>
        public LocalShellToolCallOutput(
            string id,
            string output,
            global::G.LocalShellToolCallOutputType type,
            global::G.LocalShellToolCallOutputStatus? status)
        {
            this.Id = id ?? throw new global::System.ArgumentNullException(nameof(id));
            this.Output = output ?? throw new global::System.ArgumentNullException(nameof(output));
            this.Type = type;
            this.Status = status;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalShellToolCallOutput" /> class.
        /// </summary>
        public LocalShellToolCallOutput()
        {
        }
    }
}