//HintName: G.Models.EasyInputMessage.g.cs

#pragma warning disable CS0618 // Type or member is obsolete

#nullable enable

namespace G
{
    /// <summary>
    /// A message input to the model with a role indicating instruction following<br/>
    /// hierarchy. Instructions given with the `developer` or `system` role take<br/>
    /// precedence over instructions given with the `user` role. Messages with the<br/>
    /// `assistant` role are presumed to have been generated by the model in previous<br/>
    /// interactions.
    /// </summary>
    public sealed partial class EasyInputMessage
    {
        /// <summary>
        /// The role of the message input. One of `user`, `assistant`, `system`, or<br/>
        /// `developer`.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("role", Required = global::Newtonsoft.Json.Required.Always)]
        public global::G.EasyInputMessageRole Role { get; set; } = default!;

        /// <summary>
        /// Text, image, or audio input to the model, used to generate a response.<br/>
        /// Can also contain previous assistant responses.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("content", Required = global::Newtonsoft.Json.Required.Always)]
        public global::G.OneOf<string, global::System.Collections.Generic.IList<global::G.InputContent>> Content { get; set; } = default!;

        /// <summary>
        /// The type of the message input. Always `message`.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("type")]
        public global::G.EasyInputMessageType? Type { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="EasyInputMessage" /> class.
        /// </summary>
        /// <param name="role">
        /// The role of the message input. One of `user`, `assistant`, `system`, or<br/>
        /// `developer`.
        /// </param>
        /// <param name="content">
        /// Text, image, or audio input to the model, used to generate a response.<br/>
        /// Can also contain previous assistant responses.
        /// </param>
        /// <param name="type">
        /// The type of the message input. Always `message`.
        /// </param>
        public EasyInputMessage(
            global::G.EasyInputMessageRole role,
            global::G.OneOf<string, global::System.Collections.Generic.IList<global::G.InputContent>> content,
            global::G.EasyInputMessageType? type)
        {
            this.Role = role;
            this.Content = content;
            this.Type = type;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="EasyInputMessage" /> class.
        /// </summary>
        public EasyInputMessage()
        {
        }
    }
}