//HintName: G.Models.FunctionToolCallOutput.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// The output of a function tool call.
    /// </summary>
    public sealed partial class FunctionToolCallOutput
    {
        /// <summary>
        /// The unique ID of the function tool call output. Populated when this item<br/>
        /// is returned via API.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The type of the function tool call output. Always `function_call_output`.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("type")]
        public global::G.FunctionToolCallOutputType Type { get; set; }

        /// <summary>
        /// The unique ID of the function tool call generated by the model.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("call_id", Required = global::Newtonsoft.Json.Required.Always)]
        public string CallId { get; set; } = default!;

        /// <summary>
        /// A JSON string of the output of the function tool call.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("output", Required = global::Newtonsoft.Json.Required.Always)]
        public string Output { get; set; } = default!;

        /// <summary>
        /// The status of the item. One of `in_progress`, `completed`, or<br/>
        /// `incomplete`. Populated when items are returned via API.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("status")]
        public global::G.FunctionToolCallOutputStatus? Status { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="FunctionToolCallOutput" /> class.
        /// </summary>
        /// <param name="id">
        /// The unique ID of the function tool call output. Populated when this item<br/>
        /// is returned via API.
        /// </param>
        /// <param name="type">
        /// The type of the function tool call output. Always `function_call_output`.
        /// </param>
        /// <param name="callId">
        /// The unique ID of the function tool call generated by the model.
        /// </param>
        /// <param name="output">
        /// A JSON string of the output of the function tool call.
        /// </param>
        /// <param name="status">
        /// The status of the item. One of `in_progress`, `completed`, or<br/>
        /// `incomplete`. Populated when items are returned via API.
        /// </param>
        public FunctionToolCallOutput(
            string callId,
            string output,
            string? id,
            global::G.FunctionToolCallOutputType type,
            global::G.FunctionToolCallOutputStatus? status)
        {
            this.CallId = callId ?? throw new global::System.ArgumentNullException(nameof(callId));
            this.Output = output ?? throw new global::System.ArgumentNullException(nameof(output));
            this.Id = id;
            this.Type = type;
            this.Status = status;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FunctionToolCallOutput" /> class.
        /// </summary>
        public FunctionToolCallOutput()
        {
        }
    }
}