//HintName: G.Models.CreateEvalItem.g.cs
#pragma warning disable CS0618 // Type or member is obsolete

#nullable enable

namespace G
{
    /// <summary>
    /// A chat message that makes up the prompt or context. May include variable references to the `item` namespace, ie {{item.name}}.
    /// </summary>
    public readonly partial struct CreateEvalItem : global::System.IEquatable<CreateEvalItem>
    {
        /// <summary>
        /// 
        /// </summary>
#if NET6_0_OR_GREATER
        public global::G.CreateEvalItemSimpleInputMessage? SimpleInputMessage { get; init; }
#else
        public global::G.CreateEvalItemSimpleInputMessage? SimpleInputMessage { get; }
#endif

        /// <summary>
        /// 
        /// </summary>
#if NET6_0_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.MemberNotNullWhen(true, nameof(SimpleInputMessage))]
#endif
        public bool IsSimpleInputMessage => SimpleInputMessage != null;

        /// <summary>
        /// A message input to the model with a role indicating instruction following<br/>
        /// hierarchy. Instructions given with the `developer` or `system` role take<br/>
        /// precedence over instructions given with the `user` role. Messages with the<br/>
        /// `assistant` role are presumed to have been generated by the model in previous<br/>
        /// interactions.
        /// </summary>
#if NET6_0_OR_GREATER
        public global::G.EvalItem? EvalMessageObject { get; init; }
#else
        public global::G.EvalItem? EvalMessageObject { get; }
#endif

        /// <summary>
        /// 
        /// </summary>
#if NET6_0_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.MemberNotNullWhen(true, nameof(EvalMessageObject))]
#endif
        public bool IsEvalMessageObject => EvalMessageObject != null;
        /// <summary>
        /// 
        /// </summary>
        public static implicit operator CreateEvalItem(global::G.CreateEvalItemSimpleInputMessage value) => new CreateEvalItem((global::G.CreateEvalItemSimpleInputMessage?)value);

        /// <summary>
        /// 
        /// </summary>
        public static implicit operator global::G.CreateEvalItemSimpleInputMessage?(CreateEvalItem @this) => @this.SimpleInputMessage;

        /// <summary>
        /// 
        /// </summary>
        public CreateEvalItem(global::G.CreateEvalItemSimpleInputMessage? value)
        {
            SimpleInputMessage = value;
        }

        /// <summary>
        /// 
        /// </summary>
        public static implicit operator CreateEvalItem(global::G.EvalItem value) => new CreateEvalItem((global::G.EvalItem?)value);

        /// <summary>
        /// 
        /// </summary>
        public static implicit operator global::G.EvalItem?(CreateEvalItem @this) => @this.EvalMessageObject;

        /// <summary>
        /// 
        /// </summary>
        public CreateEvalItem(global::G.EvalItem? value)
        {
            EvalMessageObject = value;
        }

        /// <summary>
        /// 
        /// </summary>
        public CreateEvalItem(
            global::G.CreateEvalItemSimpleInputMessage? simpleInputMessage,
            global::G.EvalItem? evalMessageObject
            )
        {
            SimpleInputMessage = simpleInputMessage;
            EvalMessageObject = evalMessageObject;
        }

        /// <summary>
        /// 
        /// </summary>
        public object? Object =>
            EvalMessageObject as object ??
            SimpleInputMessage as object 
            ;

        /// <summary>
        /// 
        /// </summary>
        public override string? ToString() =>
            SimpleInputMessage?.ToString() ??
            EvalMessageObject?.ToString() 
            ;

        /// <summary>
        /// 
        /// </summary>
        public bool Validate()
        {
            return IsSimpleInputMessage && !IsEvalMessageObject || !IsSimpleInputMessage && IsEvalMessageObject;
        }

        /// <summary>
        /// 
        /// </summary>
        public TResult? Match<TResult>(
            global::System.Func<global::G.CreateEvalItemSimpleInputMessage?, TResult>? simpleInputMessage = null,
            global::System.Func<global::G.EvalItem?, TResult>? evalMessageObject = null,
            bool validate = true)
        {
            if (validate)
            {
                Validate();
            }

            if (IsSimpleInputMessage && simpleInputMessage != null)
            {
                return simpleInputMessage(SimpleInputMessage!);
            }
            else if (IsEvalMessageObject && evalMessageObject != null)
            {
                return evalMessageObject(EvalMessageObject!);
            }

            return default(TResult);
        }

        /// <summary>
        /// 
        /// </summary>
        public void Match(
            global::System.Action<global::G.CreateEvalItemSimpleInputMessage?>? simpleInputMessage = null,
            global::System.Action<global::G.EvalItem?>? evalMessageObject = null,
            bool validate = true)
        {
            if (validate)
            {
                Validate();
            }

            if (IsSimpleInputMessage)
            {
                simpleInputMessage?.Invoke(SimpleInputMessage!);
            }
            else if (IsEvalMessageObject)
            {
                evalMessageObject?.Invoke(EvalMessageObject!);
            }
        }

        /// <summary>
        /// 
        /// </summary>
        public override int GetHashCode()
        {
            var fields = new object?[]
            {
                SimpleInputMessage,
                typeof(global::G.CreateEvalItemSimpleInputMessage),
                EvalMessageObject,
                typeof(global::G.EvalItem),
            };
            const int offset = unchecked((int)2166136261);
            const int prime = 16777619;
            static int HashCodeAggregator(int hashCode, object? value) => value == null
                ? (hashCode ^ 0) * prime
                : (hashCode ^ value.GetHashCode()) * prime;

            return global::System.Linq.Enumerable.Aggregate(fields, offset, HashCodeAggregator);
        }

        /// <summary>
        /// 
        /// </summary>
        public bool Equals(CreateEvalItem other)
        {
            return
                global::System.Collections.Generic.EqualityComparer<global::G.CreateEvalItemSimpleInputMessage?>.Default.Equals(SimpleInputMessage, other.SimpleInputMessage) &&
                global::System.Collections.Generic.EqualityComparer<global::G.EvalItem?>.Default.Equals(EvalMessageObject, other.EvalMessageObject) 
                ;
        }

        /// <summary>
        /// 
        /// </summary>
        public static bool operator ==(CreateEvalItem obj1, CreateEvalItem obj2)
        {
            return global::System.Collections.Generic.EqualityComparer<CreateEvalItem>.Default.Equals(obj1, obj2);
        }

        /// <summary>
        /// 
        /// </summary>
        public static bool operator !=(CreateEvalItem obj1, CreateEvalItem obj2)
        {
            return !(obj1 == obj2);
        }

        /// <summary>
        /// 
        /// </summary>
        public override bool Equals(object? obj)
        {
            return obj is CreateEvalItem o && Equals(o);
        }
    }
}
