//HintName: G.Models.FunctionCallOutputItemParam.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// The output of a function tool call.
    /// </summary>
    public sealed partial class FunctionCallOutputItemParam
    {
        /// <summary>
        /// 
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The unique ID of the function tool call generated by the model.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("call_id", Required = global::Newtonsoft.Json.Required.Always)]
        public string CallId { get; set; } = default!;

        /// <summary>
        /// The type of the function tool call output. Always `function_call_output`.<br/>
        /// Default Value: function_call_output
        /// </summary>
        /// <default>global::G.FunctionCallOutputItemParamType.FunctionCallOutput</default>
        [global::Newtonsoft.Json.JsonProperty("type")]
        public global::G.FunctionCallOutputItemParamType Type { get; set; } = global::G.FunctionCallOutputItemParamType.FunctionCallOutput;

        /// <summary>
        /// A JSON string of the output of the function tool call.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("output", Required = global::Newtonsoft.Json.Required.Always)]
        public string Output { get; set; } = default!;

        /// <summary>
        /// 
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("status")]
        public global::G.FunctionCallOutputItemParamStatus2? Status { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="FunctionCallOutputItemParam" /> class.
        /// </summary>
        /// <param name="id"></param>
        /// <param name="callId">
        /// The unique ID of the function tool call generated by the model.
        /// </param>
        /// <param name="type">
        /// The type of the function tool call output. Always `function_call_output`.<br/>
        /// Default Value: function_call_output
        /// </param>
        /// <param name="output">
        /// A JSON string of the output of the function tool call.
        /// </param>
        /// <param name="status"></param>
        public FunctionCallOutputItemParam(
            string callId,
            string output,
            string? id,
            global::G.FunctionCallOutputItemParamStatus2? status,
            global::G.FunctionCallOutputItemParamType type = global::G.FunctionCallOutputItemParamType.FunctionCallOutput)
        {
            this.CallId = callId ?? throw new global::System.ArgumentNullException(nameof(callId));
            this.Output = output ?? throw new global::System.ArgumentNullException(nameof(output));
            this.Id = id;
            this.Type = type;
            this.Status = status;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FunctionCallOutputItemParam" /> class.
        /// </summary>
        public FunctionCallOutputItemParam()
        {
        }
    }
}