//HintName: G.Models.AgentResponse.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// Response containing the complete list of events generated by an agent.
    /// </summary>
    public sealed partial class AgentResponse
    {
        /// <summary>
        /// List of all events generated during agent processing.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("events", Required = global::Newtonsoft.Json.Required.Always)]
        public global::System.Collections.Generic.IList<global::G.AgentEvent> Events { get; set; } = default!;

        /// <summary>
        /// A unique key that identifies an agent session.<br/>
        /// Example: customer_support_chat
        /// </summary>
        /// <example>customer_support_chat</example>
        [global::Newtonsoft.Json.JsonProperty("session_key", Required = global::Newtonsoft.Json.Required.Always)]
        public string SessionKey { get; set; } = default!;

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentResponse" /> class.
        /// </summary>
        /// <param name="events">
        /// List of all events generated during agent processing.
        /// </param>
        /// <param name="sessionKey">
        /// A unique key that identifies an agent session.<br/>
        /// Example: customer_support_chat
        /// </param>
        public AgentResponse(
            global::System.Collections.Generic.IList<global::G.AgentEvent> events,
            string sessionKey)
        {
            this.Events = events ?? throw new global::System.ArgumentNullException(nameof(events));
            this.SessionKey = sessionKey ?? throw new global::System.ArgumentNullException(nameof(sessionKey));
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AgentResponse" /> class.
        /// </summary>
        public AgentResponse()
        {
        }
    }
}