//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.EstimatePricingRequestVariant1EstimateTypeJsonConverter),
            typeof(global::G.JsonConverters.EstimatePricingRequestVariant1EstimateTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EstimatePricingRequestVariant2EstimateTypeJsonConverter),
            typeof(global::G.JsonConverters.EstimatePricingRequestVariant2EstimateTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsHistoryRequestItemConditionTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsHistoryRequestItemConditionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsStreamRequestItemConditionTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsStreamRequestItemConditionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceRequestInstanceTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceRequestInstanceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceRequestSectorJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceRequestSectorNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelsStatusJsonConverter),
            typeof(global::G.JsonConverters.GetModelsStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetUsageTimeframeJsonConverter),
            typeof(global::G.JsonConverters.GetUsageTimeframeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetUsageBoundToTimeframeJsonConverter),
            typeof(global::G.JsonConverters.GetUsageBoundToTimeframeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsTimeframeJsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsTimeframeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsBoundToTimeframeJsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsBoundToTimeframeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointStatusJsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointSortByJsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointSortByNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsHistoryRunSourceJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsHistoryRunSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsStreamRunSourceJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsStreamRunSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointStatusJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointSortByJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointSortByNullableJsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportSourceJsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportTimeframeJsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportTimeframeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportBoundToTimeframeJsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportBoundToTimeframeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseModelMetadataStatusJsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseModelMetadataStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseModelMetadataLicenseTypeJsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseModelMetadataLicenseTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseModelMetadataKindJsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseModelMetadataKindNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseModelEnterpriseStatusEnumJsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseModelEnterpriseStatusEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.GetModelsResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.GetPricingResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetPricingResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetPricingResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.GetPricingResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.GetPricingResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.GetPricingResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.GetPricingResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.GetPricingResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.EstimatePricingResponseEstimateTypeJsonConverter),
            typeof(global::G.JsonConverters.EstimatePricingResponseEstimateTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EstimatePricingResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.EstimatePricingResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EstimatePricingResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.EstimatePricingResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.EstimatePricingResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.EstimatePricingResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.EstimatePricingResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.EstimatePricingResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.GetUsageResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetUsageResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetUsageResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.GetUsageResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.GetUsageResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.GetUsageResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.GetUsageResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.GetUsageResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.GetUsageResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.GetUsageResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.GetAnalyticsResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.GetBillingEventsResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetBillingEventsResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetBillingEventsResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.GetBillingEventsResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.GetBillingEventsResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.GetBillingEventsResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.GetBillingEventsResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.GetBillingEventsResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.GetBillingEventsResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.GetBillingEventsResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteRequestPayloadsResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.DeleteRequestPayloadsResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteRequestPayloadsResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.DeleteRequestPayloadsResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteRequestPayloadsResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.DeleteRequestPayloadsResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteRequestPayloadsResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.DeleteRequestPayloadsResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteRequestPayloadsResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.DeleteRequestPayloadsResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteRequestPayloadsResponseErrorType6JsonConverter),
            typeof(global::G.JsonConverters.DeleteRequestPayloadsResponseErrorType6NullableJsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.ListRequestsByEndpointResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.SearchRequestsResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.SearchRequestsResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SearchRequestsResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.SearchRequestsResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.SearchRequestsResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.SearchRequestsResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.SearchRequestsResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.SearchRequestsResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.ListWorkflowsResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ListWorkflowsResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListWorkflowsResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ListWorkflowsResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ListWorkflowsResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ListWorkflowsResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ListWorkflowsResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.ListWorkflowsResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.GetWorkflowResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetWorkflowResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetWorkflowResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.GetWorkflowResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.GetWorkflowResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.GetWorkflowResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.GetWorkflowResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.GetWorkflowResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.GetWorkflowResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.GetWorkflowResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.GetWorkflowResponseErrorType6JsonConverter),
            typeof(global::G.JsonConverters.GetWorkflowResponseErrorType6NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetAppQueueInfoResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetAppQueueInfoResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetAppQueueInfoResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetAppQueueInfoResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetAppQueueInfoResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetAppQueueInfoResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetAppQueueInfoResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetAppQueueInfoResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetAppQueueInfoResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetAppQueueInfoResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessFlushAppQueueResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerlessFlushAppQueueResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessFlushAppQueueResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ServerlessFlushAppQueueResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessFlushAppQueueResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ServerlessFlushAppQueueResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessFlushAppQueueResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.ServerlessFlushAppQueueResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessFlushAppQueueResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.ServerlessFlushAppQueueResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessFlushAppQueueResponseErrorType6JsonConverter),
            typeof(global::G.JsonConverters.ServerlessFlushAppQueueResponseErrorType6NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRootResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRootResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRootResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRootResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRootResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRootResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListDirectoryResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListDirectoryResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListDirectoryResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ServerlessListDirectoryResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListDirectoryResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ServerlessListDirectoryResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessDownloadFileResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerlessDownloadFileResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessDownloadFileResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ServerlessDownloadFileResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessDownloadFileResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ServerlessDownloadFileResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessDownloadFileResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.ServerlessDownloadFileResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadFromUrlResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadFromUrlResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadFromUrlResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadFromUrlResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadFromUrlResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadFromUrlResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadLocalFileResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadLocalFileResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadLocalFileResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadLocalFileResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadLocalFileResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadLocalFileResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadLocalFileResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.ServerlessUploadLocalFileResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetMetricsResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetMetricsResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetMetricsResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetMetricsResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetMetricsResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ServerlessGetMetricsResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsHistoryResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsHistoryResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsHistoryResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsHistoryResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsHistoryResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsHistoryResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsStreamResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsStreamResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsStreamResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsStreamResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsStreamResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ServerlessLogsStreamResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointResponseErrorType6JsonConverter),
            typeof(global::G.JsonConverters.ServerlessListRequestsByEndpointResponseErrorType6NullableJsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseInstanceInstanceTypeJsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseInstanceInstanceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseInstanceRegionJsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseInstanceRegionNullableJsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseInstanceSectorJsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseInstanceSectorNullableJsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseInstanceStatusJsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseInstanceStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.ListComputeInstancesResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseInstanceTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseInstanceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseRegionJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseRegionNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseSectorJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseSectorNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseStatusJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.CreateComputeInstanceResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseInstanceTypeJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseInstanceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseRegionJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseRegionNullableJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseSectorJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseSectorNullableJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseStatusJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.GetComputeInstanceResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteComputeInstanceResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.DeleteComputeInstanceResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteComputeInstanceResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.DeleteComputeInstanceResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteComputeInstanceResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.DeleteComputeInstanceResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteComputeInstanceResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.DeleteComputeInstanceResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteComputeInstanceResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.DeleteComputeInstanceResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.ListApiKeysResponseKeyScopeJsonConverter),
            typeof(global::G.JsonConverters.ListApiKeysResponseKeyScopeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListApiKeysResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.ListApiKeysResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListApiKeysResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.ListApiKeysResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ListApiKeysResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.ListApiKeysResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.ListApiKeysResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.ListApiKeysResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.CreateApiKeyResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateApiKeyResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateApiKeyResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.CreateApiKeyResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.CreateApiKeyResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.CreateApiKeyResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.CreateApiKeyResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.CreateApiKeyResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.CreateApiKeyResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.CreateApiKeyResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteApiKeyResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.DeleteApiKeyResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteApiKeyResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.DeleteApiKeyResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteApiKeyResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.DeleteApiKeyResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.DeleteApiKeyResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.DeleteApiKeyResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.GetAccountBillingResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetAccountBillingResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetAccountBillingResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.GetAccountBillingResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.GetAccountBillingResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.GetAccountBillingResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.GetAccountBillingResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.GetAccountBillingResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.GetAccountBillingResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.GetAccountBillingResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportResponseErrorType3JsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportResponseErrorType3NullableJsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportResponseErrorType4JsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportResponseErrorType4NullableJsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportResponseErrorType5JsonConverter),
            typeof(global::G.JsonConverters.GetFocusReportResponseErrorType5NullableJsonConverter),
            typeof(global::G.JsonConverters.GetMetaResponseErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.GetMetaResponseErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetMetaResponseErrorType2JsonConverter),
            typeof(global::G.JsonConverters.GetMetaResponseErrorType2NullableJsonConverter),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.EstimatePricingRequestVariant1, global::G.EstimatePricingRequestVariant2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.DateTime?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.GetModelsResponseModelOpenapiVariant1, global::G.GetModelsResponseModelOpenapiVariant2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.GetModelsResponseModelEnterpriseStatusEnum?, global::G.GetModelsResponseModelEnterpriseStatusEnum2>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}