//HintName: G.Models.ChatCompletionStreamingChoice.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    public sealed partial class ChatCompletionStreamingChoice
    {
        /// <summary>
        /// The index of the choice in the list of completions generated by the model.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("index")]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required int Index { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("finish_reason")]
        [global::System.Text.Json.Serialization.JsonConverter(typeof(global::G.JsonConverters.ChatCompletionFinishReasonJsonConverter))]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required global::G.ChatCompletionFinishReason FinishReason { get; set; }

        /// <summary>
        /// The chat completion message from the model. Note: this field is deprecated for streaming. Use `delta` instead.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("message")]
        public global::G.ChatCompletionResponseMessage? Message { get; set; }

        /// <summary>
        /// The chat completion message from the model. Note: this field is deprecated for streaming. Use `delta` instead.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("delta")]
        [global::System.Text.Json.Serialization.JsonRequired]
        public required global::G.ChatCompletionStreamingDelta Delta { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("logprobs")]
        public global::G.Logprobs? Logprobs { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::System.Text.Json.Serialization.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatCompletionStreamingChoice" /> class.
        /// </summary>
        /// <param name="index">
        /// The index of the choice in the list of completions generated by the model.
        /// </param>
        /// <param name="finishReason"></param>
        /// <param name="delta">
        /// The chat completion message from the model. Note: this field is deprecated for streaming. Use `delta` instead.
        /// </param>
        /// <param name="message">
        /// The chat completion message from the model. Note: this field is deprecated for streaming. Use `delta` instead.
        /// </param>
        /// <param name="logprobs"></param>
#if NET7_0_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
#endif
        public ChatCompletionStreamingChoice(
            int index,
            global::G.ChatCompletionFinishReason finishReason,
            global::G.ChatCompletionStreamingDelta delta,
            global::G.ChatCompletionResponseMessage? message,
            global::G.Logprobs? logprobs)
        {
            this.Index = index;
            this.FinishReason = finishReason;
            this.Message = message;
            this.Delta = delta ?? throw new global::System.ArgumentNullException(nameof(delta));
            this.Logprobs = logprobs;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChatCompletionStreamingChoice" /> class.
        /// </summary>
        public ChatCompletionStreamingChoice()
        {
        }
    }
}