//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.CodeLanguageLabelJsonConverter),
            typeof(global::G.JsonConverters.CodeLanguageLabelNullableJsonConverter),
            typeof(global::G.JsonConverters.ContentLayerJsonConverter),
            typeof(global::G.JsonConverters.ContentLayerNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversionStatusJsonConverter),
            typeof(global::G.JsonConverters.ConversionStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ConvertDocumentsRequestSourceDiscriminatorKindJsonConverter),
            typeof(global::G.JsonConverters.ConvertDocumentsRequestSourceDiscriminatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.ConvertDocumentsRequestTargetDiscriminatorKindJsonConverter),
            typeof(global::G.JsonConverters.ConvertDocumentsRequestTargetDiscriminatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.CoordOriginJsonConverter),
            typeof(global::G.JsonConverters.CoordOriginNullableJsonConverter),
            typeof(global::G.JsonConverters.DoclingComponentTypeJsonConverter),
            typeof(global::G.JsonConverters.DoclingComponentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphCellLabelJsonConverter),
            typeof(global::G.JsonConverters.GraphCellLabelNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphLinkLabelJsonConverter),
            typeof(global::G.JsonConverters.GraphLinkLabelNullableJsonConverter),
            typeof(global::G.JsonConverters.GroupLabelJsonConverter),
            typeof(global::G.JsonConverters.GroupLabelNullableJsonConverter),
            typeof(global::G.JsonConverters.HierarchicalChunkerOptionsDocumentsRequestSourceDiscriminatorKindJsonConverter),
            typeof(global::G.JsonConverters.HierarchicalChunkerOptionsDocumentsRequestSourceDiscriminatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.HierarchicalChunkerOptionsDocumentsRequestTargetDiscriminatorKindJsonConverter),
            typeof(global::G.JsonConverters.HierarchicalChunkerOptionsDocumentsRequestTargetDiscriminatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.HybridChunkerOptionsDocumentsRequestSourceDiscriminatorKindJsonConverter),
            typeof(global::G.JsonConverters.HybridChunkerOptionsDocumentsRequestSourceDiscriminatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.HybridChunkerOptionsDocumentsRequestTargetDiscriminatorKindJsonConverter),
            typeof(global::G.JsonConverters.HybridChunkerOptionsDocumentsRequestTargetDiscriminatorKindNullableJsonConverter),
            typeof(global::G.JsonConverters.ImageRefModeJsonConverter),
            typeof(global::G.JsonConverters.ImageRefModeNullableJsonConverter),
            typeof(global::G.JsonConverters.InferenceFrameworkJsonConverter),
            typeof(global::G.JsonConverters.InferenceFrameworkNullableJsonConverter),
            typeof(global::G.JsonConverters.InputFormatJsonConverter),
            typeof(global::G.JsonConverters.InputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.OutputFormatJsonConverter),
            typeof(global::G.JsonConverters.OutputFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.PdfBackendJsonConverter),
            typeof(global::G.JsonConverters.PdfBackendNullableJsonConverter),
            typeof(global::G.JsonConverters.PictureClassificationLabelJsonConverter),
            typeof(global::G.JsonConverters.PictureClassificationLabelNullableJsonConverter),
            typeof(global::G.JsonConverters.ProcessingPipelineJsonConverter),
            typeof(global::G.JsonConverters.ProcessingPipelineNullableJsonConverter),
            typeof(global::G.JsonConverters.ProfilingScopeJsonConverter),
            typeof(global::G.JsonConverters.ProfilingScopeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.ScriptJsonConverter),
            typeof(global::G.JsonConverters.ScriptNullableJsonConverter),
            typeof(global::G.JsonConverters.TableFormerModeJsonConverter),
            typeof(global::G.JsonConverters.TableFormerModeNullableJsonConverter),
            typeof(global::G.JsonConverters.TargetNameJsonConverter),
            typeof(global::G.JsonConverters.TargetNameNullableJsonConverter),
            typeof(global::G.JsonConverters.TaskTypeJsonConverter),
            typeof(global::G.JsonConverters.TaskTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TransformersModelTypeJsonConverter),
            typeof(global::G.JsonConverters.TransformersModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.VlmEngineTypeJsonConverter),
            typeof(global::G.JsonConverters.VlmEngineTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.VlmModelTypeJsonConverter),
            typeof(global::G.JsonConverters.VlmModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.OcrEnginesEnumJsonConverter),
            typeof(global::G.JsonConverters.OcrEnginesEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.SourcesItemJsonConverter),
            typeof(global::G.JsonConverters.TargetJsonConverter),
            typeof(global::G.JsonConverters.SourcesItem2JsonConverter),
            typeof(global::G.JsonConverters.Target2JsonConverter),
            typeof(global::G.JsonConverters.SourcesItem3JsonConverter),
            typeof(global::G.JsonConverters.Target3JsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.VlmConvertOptions, object, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PictureDescriptionVlmEngineOptions, object, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.CodeFormulaVlmOptions, object, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.RichTableCell, global::G.TableCell>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConvertDocumentResponse, global::G.PresignedUrlConvertDocumentResponse>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConvertDocumentResponse, global::G.PresignedUrlConvertDocumentResponse>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConvertDocumentResponse, global::G.PresignedUrlConvertDocumentResponse, global::G.ChunkDocumentResponse>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}