openapi: 3.0.1
info:
  title: recraft.ai external api
  version: 0.0.1
paths:
  /ping:
    get:
      operationId: GetPing
      responses:
        '200':
          description: OK
  /v1/images/clarityUpscale:
    post:
      tags:
        - image
      summary: Clarity Upscale
      operationId: ClarityUpscale
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProcessImageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessImageResponse'
  /v1/images/generations:
    post:
      tags:
        - image
      summary: Generate image from prompt
      operationId: GenerateImage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateImageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenerateImageResponse'
  /v1/images/generativeUpscale:
    post:
      tags:
        - image
      summary: Generative Upscale
      operationId: GenerativeUpscale
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProcessImageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessImageResponse'
  /v1/images/removeBackground:
    post:
      tags:
        - image
      summary: Remove background
      operationId: RemoveBackground
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProcessImageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessImageResponse'
  /v1/images/vectorize:
    post:
      tags:
        - image
      summary: Vectorize image
      operationId: VectorizeImage
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProcessImageRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProcessImageResponse'
  /v1/styles:
    get:
      tags:
        - style
      summary: List Styles
      operationId: ListStyles
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListStylesResponse'
    post:
      tags:
        - style
      summary: Create Style
      operationId: CreateStyle
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateStyleRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateStyleResponse'
  '/v1/styles/{style_id}':
    delete:
      tags:
        - style
      summary: Delete Style
      operationId: DeleteStyle
      parameters:
        - name: style_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            x-go-name: StyleID
            x-go-type: uuid.UUID
            x-go-type-import:
              path: github.com/gofrs/uuid/v5
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /v1/users/me:
    get:
      tags:
        - user
      summary: Get current user info
      operationId: GetCurrentUser
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    CreateStyleRequest:
      required:
        - images
        - style
      type: object
      properties:
        images:
          type: array
          items:
            type: string
            format: binary
        style:
          $ref: '#/components/schemas/ImageStyle'
    CreateStyleResponse:
      required:
        - id
      type: object
      properties:
        id:
          type: string
          format: uuid
          x-go-name: StyleID
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/gofrs/uuid/v5
    GenerateImageRequest:
      required:
        - prompt
      type: object
      properties:
        controls:
          $ref: '#/components/schemas/UserControls'
        model:
          $ref: '#/components/schemas/TransformModel'
        n:
          type: integer
        prompt:
          type: string
        random_seed:
          type: integer
          format: uint32
        response_format:
          $ref: '#/components/schemas/ResponseFormat'
        size:
          $ref: '#/components/schemas/ImageSize'
        style:
          $ref: '#/components/schemas/ImageStyle'
        style_id:
          type: string
          format: uuid
          x-go-name: StyleID
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/gofrs/uuid/v5
        substyle:
          $ref: '#/components/schemas/ImageSubStyle'
    GenerateImageResponse:
      required:
        - created
        - data
      type: object
      properties:
        created:
          type: integer
        data:
          type: array
          items:
            $ref: '#/components/schemas/Image'
    Image:
      type: object
      properties:
        b64_json:
          type: string
        revised_prompt:
          type: string
        url:
          type: string
    ImageColor:
      type: object
      properties:
        rgb:
          type: array
          items:
            type: integer
        std:
          type: array
          items:
            type: number
        weight:
          type: number
    ImageSize:
      enum:
        - 1024x1024
        - 1365x1024
        - 1024x1365
        - 1536x1024
        - 1024x1536
        - 1820x1024
        - 1024x1820
        - 1024x2048
        - 2048x1024
        - 1434x1024
        - 1024x1434
        - 1024x1280
        - 1280x1024
        - 1024x1707
        - 1707x1024
      type: string
    ImageStyle:
      enum:
        - digital_illustration
        - icon
        - realistic_image
        - vector_illustration
      type: string
    ImageSubStyle:
      enum:
        - 2d_art_poster
        - 3d
        - 80s
        - glow
        - grain
        - hand_drawn
        - infantile_sketch
        - kawaii
        - pixel_art
        - psychedelic
        - seamless
        - voxel
        - watercolor
        - broken_line
        - colored_outline
        - colored_shapes
        - colored_shapes_gradient
        - doodle_fill
        - doodle_offset_fill
        - offset_fill
        - outline
        - outline_gradient
        - uneven_fill
        - 70s
        - cartoon
        - doodle_line_art
        - engraving
        - flat_2
        - kawaii
        - line_art
        - linocut
        - seamless
        - b_and_w
        - enterprise
        - hard_flash
        - hdr
        - motion_blur
        - natural_light
        - studio_portrait
        - line_circuit
        - 2d_art_poster_2
        - engraving_color
        - flat_air_art
        - hand_drawn_outline
        - handmade_3d
        - stickers_drawings
      type: string
    ListStylesResponse:
      required:
        - styles
      type: object
      properties:
        styles:
          type: array
          items:
            $ref: '#/components/schemas/Style'
    ProcessImageRequest:
      required:
        - image
      type: object
      properties:
        image:
          type: string
          format: binary
        response_format:
          $ref: '#/components/schemas/ResponseFormat'
    ProcessImageResponse:
      required:
        - created
        - image
      type: object
      properties:
        created:
          type: integer
        image:
          $ref: '#/components/schemas/Image'
    ResponseFormat:
      enum:
        - url
        - b64_json
      type: string
    Style:
      required:
        - id
        - creation_time
      type: object
      properties:
        creation_time:
          type: string
          format: date-time
        id:
          type: string
          format: uuid
          x-go-name: ID
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/gofrs/uuid/v5
    TransformModel:
      enum:
        - refm1
        - recraft20b
        - recraftv3
      type: string
    User:
      required:
        - id
      type: object
      properties:
        email:
          type: string
          format: email
        id:
          type: string
          format: uuid
          x-go-name: ID
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/gofrs/uuid/v5
        name:
          type: string
        registration_time:
          type: string
          format: date-time
    UserControls:
      type: object
      properties:
        background_color:
          $ref: '#/components/schemas/ImageColor'
        colors:
          type: array
          items:
            $ref: '#/components/schemas/ImageColor'
  securitySchemes:
    auth0:
      type: http
      scheme: bearer
      bearerFormat: JWT