//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.ApplyStatusDetailsStatusJsonConverter),
            typeof(global::G.JsonConverters.ApplyStatusDetailsStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.AutoModeParsingConfTier2JsonConverter),
            typeof(global::G.JsonConverters.AutoModeParsingConfTier2NullableJsonConverter),
            typeof(global::G.JsonConverters.AutoModeParsingConfVersionJsonConverter),
            typeof(global::G.JsonConverters.AutoModeParsingConfVersionNullableJsonConverter),
            typeof(global::G.JsonConverters.AutoModeParsingConfSpecializedChartParsing2JsonConverter),
            typeof(global::G.JsonConverters.AutoModeParsingConfSpecializedChartParsing2NullableJsonConverter),
            typeof(global::G.JsonConverters.BatchFileStatusJsonConverter),
            typeof(global::G.JsonConverters.BatchFileStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchJobStatusJsonConverter),
            typeof(global::G.JsonConverters.BatchJobStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchJobTypeJsonConverter),
            typeof(global::G.JsonConverters.BatchJobTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchParseJobConfigPriority2JsonConverter),
            typeof(global::G.JsonConverters.BatchParseJobConfigPriority2NullableJsonConverter),
            typeof(global::G.JsonConverters.BatchParseJobConfigImagesToSaveVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.BatchParseJobConfigImagesToSaveVariant1ItemNullableJsonConverter),
            typeof(global::G.JsonConverters.BoxAuthMechanismJsonConverter),
            typeof(global::G.JsonConverters.BoxAuthMechanismNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifyModeJsonConverter),
            typeof(global::G.JsonConverters.ClassifyModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifyV2JobResponseStatusJsonConverter),
            typeof(global::G.JsonConverters.ClassifyV2JobResponseStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ClassifyV2JobResponseDocumentInputTypeJsonConverter),
            typeof(global::G.JsonConverters.ClassifyV2JobResponseDocumentInputTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CloudJiraDataSourceV2ApiVersionJsonConverter),
            typeof(global::G.JsonConverters.CloudJiraDataSourceV2ApiVersionNullableJsonConverter),
            typeof(global::G.JsonConverters.CompositeRetrievalModeJsonConverter),
            typeof(global::G.JsonConverters.CompositeRetrievalModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConfigurableDataSinkNamesJsonConverter),
            typeof(global::G.JsonConverters.ConfigurableDataSinkNamesNullableJsonConverter),
            typeof(global::G.JsonConverters.ConfigurableDataSourceNamesJsonConverter),
            typeof(global::G.JsonConverters.ConfigurableDataSourceNamesNullableJsonConverter),
            typeof(global::G.JsonConverters.ConfigurationCreateRequestParametersDiscriminatorProductTypeJsonConverter),
            typeof(global::G.JsonConverters.ConfigurationCreateRequestParametersDiscriminatorProductTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConfigurationResponseProductTypeJsonConverter),
            typeof(global::G.JsonConverters.ConfigurationResponseProductTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConfigurationResponseParametersDiscriminatorProductTypeJsonConverter),
            typeof(global::G.JsonConverters.ConfigurationResponseParametersDiscriminatorProductTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConfigurationUpdateRequestParametersVariant1DiscriminatorProductTypeJsonConverter),
            typeof(global::G.JsonConverters.ConfigurationUpdateRequestParametersVariant1DiscriminatorProductTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DataSourceReaderVersionMetadataReaderVersion2JsonConverter),
            typeof(global::G.JsonConverters.DataSourceReaderVersionMetadataReaderVersion2NullableJsonConverter),
            typeof(global::G.JsonConverters.DiffingStatusDetailsStatusJsonConverter),
            typeof(global::G.JsonConverters.DiffingStatusDetailsStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.DocumentChunkModeJsonConverter),
            typeof(global::G.JsonConverters.DocumentChunkModeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingModelConfigEmbeddingConfigDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingModelConfigEmbeddingConfigDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingModelConfigCreateEmbeddingConfigDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingModelConfigCreateEmbeddingConfigDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingModelConfigUpdateEmbeddingConfigVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingModelConfigUpdateEmbeddingConfigVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ExtractConfigPriority2JsonConverter),
            typeof(global::G.JsonConverters.ExtractConfigPriority2NullableJsonConverter),
            typeof(global::G.JsonConverters.ExtractConfigurationTierJsonConverter),
            typeof(global::G.JsonConverters.ExtractConfigurationTierNullableJsonConverter),
            typeof(global::G.JsonConverters.ExtractConfigurationExtractionTargetJsonConverter),
            typeof(global::G.JsonConverters.ExtractConfigurationExtractionTargetNullableJsonConverter),
            typeof(global::G.JsonConverters.ExtractJobStatusJsonConverter),
            typeof(global::G.JsonConverters.ExtractJobStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ExtractJobCreatePriority2JsonConverter),
            typeof(global::G.JsonConverters.ExtractJobCreatePriority2NullableJsonConverter),
            typeof(global::G.JsonConverters.ExtractModeJsonConverter),
            typeof(global::G.JsonConverters.ExtractModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ExtractModelsJsonConverter),
            typeof(global::G.JsonConverters.ExtractModelsNullableJsonConverter),
            typeof(global::G.JsonConverters.ExtractStateJsonConverter),
            typeof(global::G.JsonConverters.ExtractStateNullableJsonConverter),
            typeof(global::G.JsonConverters.ExtractTargetJsonConverter),
            typeof(global::G.JsonConverters.ExtractTargetNullableJsonConverter),
            typeof(global::G.JsonConverters.ExtractV2ParametersTierJsonConverter),
            typeof(global::G.JsonConverters.ExtractV2ParametersTierNullableJsonConverter),
            typeof(global::G.JsonConverters.ExtractV2ParametersExtractionTargetJsonConverter),
            typeof(global::G.JsonConverters.ExtractV2ParametersExtractionTargetNullableJsonConverter),
            typeof(global::G.JsonConverters.FailPageModeJsonConverter),
            typeof(global::G.JsonConverters.FailPageModeNullableJsonConverter),
            typeof(global::G.JsonConverters.FileCreateStorageTypeJsonConverter),
            typeof(global::G.JsonConverters.FileCreateStorageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FileCreateFromUrlStorageTypeJsonConverter),
            typeof(global::G.JsonConverters.FileCreateFromUrlStorageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FilterConditionJsonConverter),
            typeof(global::G.JsonConverters.FilterConditionNullableJsonConverter),
            typeof(global::G.JsonConverters.FilterOperatorJsonConverter),
            typeof(global::G.JsonConverters.FilterOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.FooterItemItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.FooterItemItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.HeaderItemItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.HeaderItemItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ImageMetadataCategory2JsonConverter),
            typeof(global::G.JsonConverters.ImageMetadataCategory2NullableJsonConverter),
            typeof(global::G.JsonConverters.JobNameMappingJsonConverter),
            typeof(global::G.JsonConverters.JobNameMappingNullableJsonConverter),
            typeof(global::G.JsonConverters.ListingStatusDetailsStatusJsonConverter),
            typeof(global::G.JsonConverters.ListingStatusDetailsStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.LlamaParseOutputOptionsImagesToSaveItemJsonConverter),
            typeof(global::G.JsonConverters.LlamaParseOutputOptionsImagesToSaveItemNullableJsonConverter),
            typeof(global::G.JsonConverters.LlamaParseParametersPriority2JsonConverter),
            typeof(global::G.JsonConverters.LlamaParseParametersPriority2NullableJsonConverter),
            typeof(global::G.JsonConverters.LlamaParseParametersImagesToSaveVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.LlamaParseParametersImagesToSaveVariant1ItemNullableJsonConverter),
            typeof(global::G.JsonConverters.LlamaParseProcessingOptionsSpecializedChartParsing2JsonConverter),
            typeof(global::G.JsonConverters.LlamaParseProcessingOptionsSpecializedChartParsing2NullableJsonConverter),
            typeof(global::G.JsonConverters.LlamaParseSupportedFileExtensionsJsonConverter),
            typeof(global::G.JsonConverters.LlamaParseSupportedFileExtensionsNullableJsonConverter),
            typeof(global::G.JsonConverters.ManagedIngestionStatusJsonConverter),
            typeof(global::G.JsonConverters.ManagedIngestionStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.MessageRoleJsonConverter),
            typeof(global::G.JsonConverters.MessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.NodeRelationshipJsonConverter),
            typeof(global::G.JsonConverters.NodeRelationshipNullableJsonConverter),
            typeof(global::G.JsonConverters.ObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.ObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PGVectorDistanceMethodJsonConverter),
            typeof(global::G.JsonConverters.PGVectorDistanceMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.PGVectorVectorTypeJsonConverter),
            typeof(global::G.JsonConverters.PGVectorVectorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ParseJobResponseStatusJsonConverter),
            typeof(global::G.JsonConverters.ParseJobResponseStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ParsePlanLevelJsonConverter),
            typeof(global::G.JsonConverters.ParsePlanLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.ParseRequestConfigurationTierJsonConverter),
            typeof(global::G.JsonConverters.ParseRequestConfigurationTierNullableJsonConverter),
            typeof(global::G.JsonConverters.ParseRequestConfigurationVersionJsonConverter),
            typeof(global::G.JsonConverters.ParseRequestConfigurationVersionNullableJsonConverter),
            typeof(global::G.JsonConverters.ParseV2ParametersTierJsonConverter),
            typeof(global::G.JsonConverters.ParseV2ParametersTierNullableJsonConverter),
            typeof(global::G.JsonConverters.ParseV2ParametersVersionJsonConverter),
            typeof(global::G.JsonConverters.ParseV2ParametersVersionNullableJsonConverter),
            typeof(global::G.JsonConverters.ParserLanguagesJsonConverter),
            typeof(global::G.JsonConverters.ParserLanguagesNullableJsonConverter),
            typeof(global::G.JsonConverters.ParsingModeJsonConverter),
            typeof(global::G.JsonConverters.ParsingModeNullableJsonConverter),
            typeof(global::G.JsonConverters.PartitionNamesJsonConverter),
            typeof(global::G.JsonConverters.PartitionNamesNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelineEmbeddingConfigDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PipelineEmbeddingConfigDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelineStatus2JsonConverter),
            typeof(global::G.JsonConverters.PipelineStatus2NullableJsonConverter),
            typeof(global::G.JsonConverters.PipelineCreateEmbeddingConfigVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PipelineCreateEmbeddingConfigVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelineDataSourceStatus2JsonConverter),
            typeof(global::G.JsonConverters.PipelineDataSourceStatus2NullableJsonConverter),
            typeof(global::G.JsonConverters.PipelineFileStatus2JsonConverter),
            typeof(global::G.JsonConverters.PipelineFileStatus2NullableJsonConverter),
            typeof(global::G.JsonConverters.PipelineFileResponseStatus2JsonConverter),
            typeof(global::G.JsonConverters.PipelineFileResponseStatus2NullableJsonConverter),
            typeof(global::G.JsonConverters.PipelineTypeJsonConverter),
            typeof(global::G.JsonConverters.PipelineTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelineUpdateEmbeddingConfigVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.PipelineUpdateEmbeddingConfigVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PoolingJsonConverter),
            typeof(global::G.JsonConverters.PoolingNullableJsonConverter),
            typeof(global::G.JsonConverters.PublicModelNameJsonConverter),
            typeof(global::G.JsonConverters.PublicModelNameNullableJsonConverter),
            typeof(global::G.JsonConverters.ReRankerTypeJsonConverter),
            typeof(global::G.JsonConverters.ReRankerTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.RetrievalModeJsonConverter),
            typeof(global::G.JsonConverters.RetrievalModeNullableJsonConverter),
            typeof(global::G.JsonConverters.SparseModelTypeJsonConverter),
            typeof(global::G.JsonConverters.SparseModelTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SplitStrategyAllowUncategorizedJsonConverter),
            typeof(global::G.JsonConverters.SplitStrategyAllowUncategorizedNullableJsonConverter),
            typeof(global::G.JsonConverters.SpreadsheetParsingConfigTableMergeSensitivityJsonConverter),
            typeof(global::G.JsonConverters.SpreadsheetParsingConfigTableMergeSensitivityNullableJsonConverter),
            typeof(global::G.JsonConverters.SpreadsheetResultTypeJsonConverter),
            typeof(global::G.JsonConverters.SpreadsheetResultTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.StatusEnumJsonConverter),
            typeof(global::G.JsonConverters.StatusEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.StructuredResultPageItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.StructuredResultPageItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SupportedLLMModelNamesJsonConverter),
            typeof(global::G.JsonConverters.SupportedLLMModelNamesNullableJsonConverter),
            typeof(global::G.JsonConverters.UsageMetricEventTypeJsonConverter),
            typeof(global::G.JsonConverters.UsageMetricEventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.VertexEmbeddingModeJsonConverter),
            typeof(global::G.JsonConverters.VertexEmbeddingModeNullableJsonConverter),
            typeof(global::G.JsonConverters.WebhookConfigurationWebhookEventsVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.WebhookConfigurationWebhookEventsVariant1ItemNullableJsonConverter),
            typeof(global::G.JsonConverters.ListPipelineFiles2ApiV1PipelinesPipelineIdFiles2GetStatusesVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.ListPipelineFiles2ApiV1PipelinesPipelineIdFiles2GetStatusesVariant1ItemNullableJsonConverter),
            typeof(global::G.JsonConverters.ListPipelineDocumentsApiV1PipelinesPipelineIdDocumentsGetStatusRefreshPolicyJsonConverter),
            typeof(global::G.JsonConverters.ListPipelineDocumentsApiV1PipelinesPipelineIdDocumentsGetStatusRefreshPolicyNullableJsonConverter),
            typeof(global::G.JsonConverters.PaginatedListPipelineDocumentsApiV1PipelinesPipelineIdDocumentsPaginatedGetStatusRefreshPolicyJsonConverter),
            typeof(global::G.JsonConverters.PaginatedListPipelineDocumentsApiV1PipelinesPipelineIdDocumentsPaginatedGetStatusRefreshPolicyNullableJsonConverter),
            typeof(global::G.JsonConverters.ListConfigurationsApiV1BetaConfigurationsGetProductTypeVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.ListConfigurationsApiV1BetaConfigurationsGetProductTypeVariant1ItemNullableJsonConverter),
            typeof(global::G.JsonConverters.ListSplitJobsApiV1BetaSplitJobsGetStatus2JsonConverter),
            typeof(global::G.JsonConverters.ListSplitJobsApiV1BetaSplitJobsGetStatus2NullableJsonConverter),
            typeof(global::G.JsonConverters.ListPipelineFilesApiV1BetaPipelinesPipelineIdFilesGetStatusesVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.ListPipelineFilesApiV1BetaPipelinesPipelineIdFilesGetStatusesVariant1ItemNullableJsonConverter),
            typeof(global::G.JsonConverters.ListParseJobsApiV2ParseGetStatus2JsonConverter),
            typeof(global::G.JsonConverters.ListParseJobsApiV2ParseGetStatus2NullableJsonConverter),
            typeof(global::G.JsonConverters.ListClassifyJobsApiV2ClassifyGetStatus2JsonConverter),
            typeof(global::G.JsonConverters.ListClassifyJobsApiV2ClassifyGetStatus2NullableJsonConverter),
            typeof(global::G.JsonConverters.ListExtractJobsApiV2ExtractGetStatus2JsonConverter),
            typeof(global::G.JsonConverters.ListExtractJobsApiV2ExtractGetStatus2NullableJsonConverter),
            typeof(global::G.JsonConverters.ParametersJsonConverter),
            typeof(global::G.JsonConverters.Parameters2JsonConverter),
            typeof(global::G.JsonConverters.ParametersVariant1JsonConverter),
            typeof(global::G.JsonConverters.EmbeddingConfigJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingConfig2JsonConverter),
            typeof(global::G.JsonConverters.EmbeddingConfigVariant1JsonConverter),
            typeof(global::G.JsonConverters.ItemsItemJsonConverter),
            typeof(global::G.JsonConverters.ItemsItem2JsonConverter),
            typeof(global::G.JsonConverters.EmbeddingConfig3JsonConverter),
            typeof(global::G.JsonConverters.EmbeddingConfigVariant12JsonConverter),
            typeof(global::G.JsonConverters.EmbeddingConfigVariant13JsonConverter),
            typeof(global::G.JsonConverters.ItemsItem4JsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.NoneSegmentationConfig, global::G.PageSegmentationConfig, global::G.ElementSegmentationConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.NoneChunkingConfig, global::G.CharacterChunkingConfig, global::G.TokenChunkingConfig, global::G.SentenceChunkingConfig, global::G.SemanticChunkingConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.AutoModeParsingConfVersion?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.BatchParseJobRecordCreate, global::G.ClassifyJob>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Guid?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::G.CloudPineconeVectorStore, global::G.CloudPostgresVectorStore, global::G.CloudQdrantVectorStore, global::G.CloudAzureAISearchVectorStore, global::G.CloudMongoDBAtlasVectorSearch, global::G.CloudMilvusVectorStore, global::G.CloudAstraDBVectorStore>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::G.CloudPineconeVectorStore, global::G.CloudPostgresVectorStore, global::G.CloudQdrantVectorStore, global::G.CloudAzureAISearchVectorStore, global::G.CloudMongoDBAtlasVectorSearch, global::G.CloudMilvusVectorStore, global::G.CloudAstraDBVectorStore>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::G.CloudPineconeVectorStore, global::G.CloudPostgresVectorStore, global::G.CloudQdrantVectorStore, global::G.CloudAzureAISearchVectorStore, global::G.CloudMongoDBAtlasVectorSearch, global::G.CloudMilvusVectorStore, global::G.CloudAstraDBVectorStore, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::G.CloudS3DataSource, global::G.CloudAzStorageBlobDataSource, global::G.CloudGoogleDriveDataSource, global::G.CloudOneDriveDataSource, global::G.CloudSharepointDataSource, global::G.CloudSlackDataSource, global::G.CloudNotionPageDataSource, global::G.CloudConfluenceDataSource, global::G.CloudJiraDataSource, global::G.CloudJiraDataSourceV2, global::G.CloudBoxDataSource>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::G.CloudS3DataSource, global::G.CloudAzStorageBlobDataSource, global::G.CloudGoogleDriveDataSource, global::G.CloudOneDriveDataSource, global::G.CloudSharepointDataSource, global::G.CloudSlackDataSource, global::G.CloudNotionPageDataSource, global::G.CloudConfluenceDataSource, global::G.CloudJiraDataSource, global::G.CloudJiraDataSourceV2, global::G.CloudBoxDataSource>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::G.CloudS3DataSource, global::G.CloudAzStorageBlobDataSource, global::G.CloudGoogleDriveDataSource, global::G.CloudOneDriveDataSource, global::G.CloudSharepointDataSource, global::G.CloudSlackDataSource, global::G.CloudNotionPageDataSource, global::G.CloudConfluenceDataSource, global::G.CloudJiraDataSource, global::G.CloudJiraDataSourceV2, global::G.CloudBoxDataSource, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ExtractModels?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.FileCreateStorageType?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.FileCreateFromUrlStorageType?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, string, global::System.DateTime?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, string, global::System.DateTime?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, string, global::System.DateTime?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, string, global::System.DateTime?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, string, global::System.DateTime?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, string, global::System.DateTime?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, string, global::System.DateTime?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<double?, int?, string, global::System.DateTime?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.TextItem, global::G.ListItem>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.MarkdownResultPage, global::G.FailedMarkdownPage>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, double?, string, global::System.Collections.Generic.IList<string>, global::System.Collections.Generic.IList<double>, global::System.Collections.Generic.IList<int>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.MetadataFilter, global::G.MetadataFilters>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ParseRequestConfigurationVersion?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ParseV2ParametersVersion?, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.AutoTransformConfig, global::G.AdvancedModeTransformConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.AutoTransformConfig, global::G.AdvancedModeTransformConfig, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::G.CloudS3DataSource, global::G.CloudAzStorageBlobDataSource, global::G.CloudGoogleDriveDataSource, global::G.CloudOneDriveDataSource, global::G.CloudSharepointDataSource, global::G.CloudSlackDataSource, global::G.CloudNotionPageDataSource, global::G.CloudConfluenceDataSource, global::G.CloudJiraDataSource, global::G.CloudJiraDataSourceV2, global::G.CloudBoxDataSource>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.AutoTransformConfig, global::G.AdvancedModeTransformConfig, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.BatchParseJobRecordCreate, global::G.ClassifyJob>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ObjectType?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<object, global::System.Collections.Generic.IList<object>, string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.StructuredResultPage, global::G.FailedStructuredPage>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?, double?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.RelatedNodeInfo, global::System.Collections.Generic.IList<global::G.RelatedNodeInfo>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}