//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.RemoveBackgroundPostParamsFormatJsonConverter),
            typeof(global::G.JsonConverters.RemoveBackgroundPostParamsFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.RemoveBackgroundPostParamsChannelsJsonConverter),
            typeof(global::G.JsonConverters.RemoveBackgroundPostParamsChannelsNullableJsonConverter),
            typeof(global::G.JsonConverters.RemoveBackgroundPostParamsSizeJsonConverter),
            typeof(global::G.JsonConverters.RemoveBackgroundPostParamsSizeNullableJsonConverter),
            typeof(global::G.JsonConverters.RemoveBackgroundPostParamsCropJsonConverter),
            typeof(global::G.JsonConverters.RemoveBackgroundPostParamsCropNullableJsonConverter),
            typeof(global::G.JsonConverters.RemoveBackgroundPostParamsDespillJsonConverter),
            typeof(global::G.JsonConverters.RemoveBackgroundPostParamsDespillNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetBackgroundBlurModeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetBackgroundBlurModeNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetBackgroundExpandPromptModeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetBackgroundExpandPromptModeNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetBackgroundScalingJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetBackgroundScalingNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetBeautifyModeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetBeautifyModeNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetExportFormatJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetExportFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetFlatLaySizeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetFlatLaySizeNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetGhostMannequinSizeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetGhostMannequinSizeNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetHorizontalAlignmentJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetHorizontalAlignmentNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetImageFromPromptSizeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetImageFromPromptSizeNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetKeepExistingAlphaChannelJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetKeepExistingAlphaChannelNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLayersVariant2ImageHorizontalAlignmentJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLayersVariant2ImageHorizontalAlignmentNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLayersVariant2ImageImageFromPromptSizeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLayersVariant2ImageImageFromPromptSizeNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLayersVariant2ImageRemoveBackgroundJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLayersVariant2ImageRemoveBackgroundNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLayersVariant2ImageSegmentationModeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLayersVariant2ImageSegmentationModeNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLayersVariant2ImageUseForAIBackgroundJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLayersVariant2ImageUseForAIBackgroundNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLayersVariant2ImageVerticalAlignmentJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLayersVariant2ImageVerticalAlignmentNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLightingModeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetLightingModeNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetPreserveMetadataJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetPreserveMetadataNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetReferenceBoxJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetReferenceBoxNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetScalingJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetScalingNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetSegmentationModeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetSegmentationModeNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetShadowModeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetShadowModeNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetTextRemovalModeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetTextRemovalModeNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetUpscaleModeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetUpscaleModeNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetVerticalAlignmentJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetVerticalAlignmentNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetVirtualModelModelVariant1PresetNameJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetVirtualModelModelVariant1PresetNameNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetVirtualModelPoseJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetVirtualModelPoseNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetVirtualModelQualityJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetVirtualModelQualityNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetVirtualModelSceneVariant1PresetNameJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetVirtualModelSceneVariant1PresetNameNullableJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetVirtualModelSizeJsonConverter),
            typeof(global::G.JsonConverters.EditImageGetVirtualModelSizeNullableJsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, string, global::G.EditImageGetBackgroundExpandPrompt2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.EditImageGetLayersVariant1, global::G.EditImageGetLayersVariant2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.EditImageGetVirtualModelModelVariant1, global::G.EditImageGetVirtualModelModelVariant2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.EditImageGetVirtualModelSceneVariant1, global::G.EditImageGetVirtualModelSceneVariant2>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}