//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.ChatCompletionFinishReasonJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionFinishReasonNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatResponseObjectJsonConverter),
            typeof(global::G.JsonConverters.ChatResponseObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionChunkObjectJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionChunkObjectNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionResponseMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionResponseMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageRequestRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageRequestRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphTypeJsonConverter),
            typeof(global::G.JsonConverters.GraphTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphStageStatusJsonConverter),
            typeof(global::G.JsonConverters.GraphStageStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.WebConnectorUrlTypeJsonConverter),
            typeof(global::G.JsonConverters.WebConnectorUrlTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WebConnectorUrlErrorTypeJsonConverter),
            typeof(global::G.JsonConverters.WebConnectorUrlErrorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.WebConnectorUrlStatusJsonConverter),
            typeof(global::G.JsonConverters.WebConnectorUrlStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ApiJobStatusJsonConverter),
            typeof(global::G.JsonConverters.ApiJobStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ApplicationTypeJsonConverter),
            typeof(global::G.JsonConverters.ApplicationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ApplicationStatusJsonConverter),
            typeof(global::G.JsonConverters.ApplicationStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ApplicationInputTypeJsonConverter),
            typeof(global::G.JsonConverters.ApplicationInputTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FileUploadTypeJsonConverter),
            typeof(global::G.JsonConverters.FileUploadTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionToolTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphToolTypeJsonConverter),
            typeof(global::G.JsonConverters.GraphToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LlmToolTypeJsonConverter),
            typeof(global::G.JsonConverters.LlmToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.VisionToolTypeJsonConverter),
            typeof(global::G.JsonConverters.VisionToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.VisionFunctionModelJsonConverter),
            typeof(global::G.JsonConverters.VisionFunctionModelNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolCallTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolCallTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolCallStreamingTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolCallStreamingTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.StringToolChoiceOptionsJsonConverter),
            typeof(global::G.JsonConverters.StringToolChoiceOptionsNullableJsonConverter),
            typeof(global::G.JsonConverters.AiDetectionResponseLabelJsonConverter),
            typeof(global::G.JsonConverters.AiDetectionResponseLabelNullableJsonConverter),
            typeof(global::G.JsonConverters.ComprehendMedicalTypeJsonConverter),
            typeof(global::G.JsonConverters.ComprehendMedicalTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SplittingStrategyJsonConverter),
            typeof(global::G.JsonConverters.SplittingStrategyNullableJsonConverter),
            typeof(global::G.JsonConverters.PdfConversionFormatJsonConverter),
            typeof(global::G.JsonConverters.PdfConversionFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.VisionRequestModelJsonConverter),
            typeof(global::G.JsonConverters.VisionRequestModelNullableJsonConverter),
            typeof(global::G.JsonConverters.TranslationRequestModelJsonConverter),
            typeof(global::G.JsonConverters.TranslationRequestModelNullableJsonConverter),
            typeof(global::G.JsonConverters.TranslationToolTypeJsonConverter),
            typeof(global::G.JsonConverters.TranslationToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TranslationFunctionModelJsonConverter),
            typeof(global::G.JsonConverters.TranslationFunctionModelNullableJsonConverter),
            typeof(global::G.JsonConverters.WebSearchRequestTopicJsonConverter),
            typeof(global::G.JsonConverters.WebSearchRequestTopicNullableJsonConverter),
            typeof(global::G.JsonConverters.WebSearchRequestSearchDepthJsonConverter),
            typeof(global::G.JsonConverters.WebSearchRequestSearchDepthNullableJsonConverter),
            typeof(global::G.JsonConverters.WebSearchRequestTimeRangeJsonConverter),
            typeof(global::G.JsonConverters.WebSearchRequestTimeRangeNullableJsonConverter),
            typeof(global::G.JsonConverters.WebSearchRequestIncludeRawContentJsonConverter),
            typeof(global::G.JsonConverters.WebSearchRequestIncludeRawContentNullableJsonConverter),
            typeof(global::G.JsonConverters.WebSearchRequestCountryJsonConverter),
            typeof(global::G.JsonConverters.WebSearchRequestCountryNullableJsonConverter),
            typeof(global::G.JsonConverters.WebSearchToolTypeJsonConverter),
            typeof(global::G.JsonConverters.WebSearchToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TextFragmentTypeJsonConverter),
            typeof(global::G.JsonConverters.TextFragmentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ImageFragmentTypeJsonConverter),
            typeof(global::G.JsonConverters.ImageFragmentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FindGraphsWithFileStatusOrderJsonConverter),
            typeof(global::G.JsonConverters.FindGraphsWithFileStatusOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.GatewayGetFilesOrderJsonConverter),
            typeof(global::G.JsonConverters.GatewayGetFilesOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.GatewayGetFilesStatusJsonConverter),
            typeof(global::G.JsonConverters.GatewayGetFilesStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetApplicationsOrderJsonConverter),
            typeof(global::G.JsonConverters.GetApplicationsOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ApplicationInputOptionsJsonConverter),
            typeof(global::G.JsonConverters.ToolJsonConverter),
            typeof(global::G.JsonConverters.ToolChoiceJsonConverter),
            typeof(global::G.JsonConverters.CompositeContentJsonConverter),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::System.Collections.Generic.IList<string>, string>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::System.Collections.Generic.IList<string>, string>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.CompositeContent>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.WebSearchRequestIncludeRawContent?, bool?>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}