//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.ViewTypeJsonConverter),
            typeof(global::G.JsonConverters.ViewTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AclObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.AclObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AclListOrgObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.AclListOrgObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AclListPermissionJsonConverter),
            typeof(global::G.JsonConverters.AclListPermissionNullableJsonConverter),
            typeof(global::G.JsonConverters.AclListRestrictObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.AclListRestrictObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectScoreTypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectScoreTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EnvVarObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.EnvVarObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionTypeEnumJsonConverter),
            typeof(global::G.JsonConverters.FunctionTypeEnumNullableJsonConverter),
            typeof(global::G.JsonConverters.NullableSavedFunctionIdFunctionTypeJsonConverter),
            typeof(global::G.JsonConverters.NullableSavedFunctionIdFunctionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.NullableSavedFunctionIdGlobalTypeJsonConverter),
            typeof(global::G.JsonConverters.NullableSavedFunctionIdGlobalTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectSettingsSpanFieldOrderItemLayoutVariant1JsonConverter),
            typeof(global::G.JsonConverters.ProjectSettingsSpanFieldOrderItemLayoutVariant1NullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectSettingsSpanFieldOrderItemLayoutVariant2JsonConverter),
            typeof(global::G.JsonConverters.ProjectSettingsSpanFieldOrderItemLayoutVariant2NullableJsonConverter),
            typeof(global::G.JsonConverters.SpanTypeJsonConverter),
            typeof(global::G.JsonConverters.SpanTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ObjectReferenceNullishObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.ObjectReferenceNullishObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SavedFunctionIdFunctionTypeJsonConverter),
            typeof(global::G.JsonConverters.SavedFunctionIdFunctionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SavedFunctionIdGlobalTypeJsonConverter),
            typeof(global::G.JsonConverters.SavedFunctionIdGlobalTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectLogsEventLogIdJsonConverter),
            typeof(global::G.JsonConverters.ProjectLogsEventLogIdNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedbackResponseSchemaStatusJsonConverter),
            typeof(global::G.JsonConverters.FeedbackResponseSchemaStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedbackProjectLogsItemSourceJsonConverter),
            typeof(global::G.JsonConverters.FeedbackProjectLogsItemSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedbackExperimentItemSourceJsonConverter),
            typeof(global::G.JsonConverters.FeedbackExperimentItemSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedbackDatasetItemSourceJsonConverter),
            typeof(global::G.JsonConverters.FeedbackDatasetItemSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartTextTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartTextTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartTextCacheControlTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartTextCacheControlTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartTextWithTitleTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartTextWithTitleTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartTextWithTitleCacheControlTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartTextWithTitleCacheControlTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartImageWithTitleImageUrlDetailAutoJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartImageWithTitleImageUrlDetailAutoNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartImageWithTitleImageUrlDetailLowJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartImageWithTitleImageUrlDetailLowNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartImageWithTitleImageUrlDetailHighJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartImageWithTitleImageUrlDetailHighNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartImageWithTitleTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartImageWithTitleTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartFileWithTitleTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartFileWithTitleTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageToolCallTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageToolCallTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamSystemRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamSystemRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamUserRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamUserRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamAssistantRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamAssistantRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamToolRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamToolRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamFunctionRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamFunctionRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamDeveloperRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamDeveloperRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamFallbackRoleJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamFallbackRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptBlockDataNullishChatTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptBlockDataNullishChatTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptBlockDataNullishCompletionTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptBlockDataNullishCompletionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatNullishJsonObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatNullishJsonObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatNullishJsonSchemaTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatNullishJsonSchemaTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatNullishTextTypeJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatNullishTextTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsToolChoiceAutoJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsToolChoiceAutoNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsToolChoiceNoneJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsToolChoiceNoneNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsToolChoiceRequiredJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsToolChoiceRequiredNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsToolChoiceFunctionTypeJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsToolChoiceFunctionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsFunctionCallAutoJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsFunctionCallAutoNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsFunctionCallNoneJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsFunctionCallNoneNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsVerbosityJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsOpenAIModelParamsVerbosityNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptParserNullishTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptParserNullishTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptDataNullishToolFunctionVariant2FunctionTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptDataNullishToolFunctionVariant2FunctionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptDataNullishToolFunctionVariant2GlobalTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptDataNullishToolFunctionVariant2GlobalTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptDataNullishTemplateFormatJsonConverter),
            typeof(global::G.JsonConverters.PromptDataNullishTemplateFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptDataNullishMcpMcpServerIdThisIsUsedForProjectLevelMcpServerDefinitionsTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptDataNullishMcpMcpServerIdThisIsUsedForProjectLevelMcpServerDefinitionsTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptDataNullishMcpMcpServerUrlThisIsUsedForInlineDefinitionsOfMcpServersTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptDataNullishMcpMcpServerUrlThisIsUsedForInlineDefinitionsOfMcpServersTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionTypeEnumNullishJsonConverter),
            typeof(global::G.JsonConverters.FunctionTypeEnumNullishNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptLogIdJsonConverter),
            typeof(global::G.JsonConverters.PromptLogIdNullableJsonConverter),
            typeof(global::G.JsonConverters.PermissionJsonConverter),
            typeof(global::G.JsonConverters.PermissionNullableJsonConverter),
            typeof(global::G.JsonConverters.RetentionObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.RetentionObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TopicMapFunctionAutomationFunctionVariant2FunctionTypeJsonConverter),
            typeof(global::G.JsonConverters.TopicMapFunctionAutomationFunctionVariant2FunctionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TopicMapFunctionAutomationFunctionVariant2GlobalTypeJsonConverter),
            typeof(global::G.JsonConverters.TopicMapFunctionAutomationFunctionVariant2GlobalTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SpanScopeTypeJsonConverter),
            typeof(global::G.JsonConverters.SpanScopeTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TraceScopeTypeJsonConverter),
            typeof(global::G.JsonConverters.TraceScopeTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GroupScopeTypeJsonConverter),
            typeof(global::G.JsonConverters.GroupScopeTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TopicAutomationDataScopeVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.TopicAutomationDataScopeVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TopicAutomationDataScopeVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.TopicAutomationDataScopeVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TopicAutomationDataScopeVariant3TypeJsonConverter),
            typeof(global::G.JsonConverters.TopicAutomationDataScopeVariant3TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TopicAutomationConfigEventTypeJsonConverter),
            typeof(global::G.JsonConverters.TopicAutomationConfigEventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TopicAutomationConfigFacetFunctionVariant2FunctionTypeJsonConverter),
            typeof(global::G.JsonConverters.TopicAutomationConfigFacetFunctionVariant2FunctionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TopicAutomationConfigFacetFunctionVariant2GlobalTypeJsonConverter),
            typeof(global::G.JsonConverters.TopicAutomationConfigFacetFunctionVariant2GlobalTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant1EventTypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant1EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant1ActionVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant1ActionVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant1ActionVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant1ActionVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant2EventTypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant2EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant2ExportDefinitionVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant2ExportDefinitionVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant2ExportDefinitionVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant2ExportDefinitionVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant2ExportDefinitionVariant3TypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant2ExportDefinitionVariant3TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant2FormatJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant2FormatNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant2CredentialsTypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant2CredentialsTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant3EventTypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant3EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant4EventTypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant4EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant4ActionVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant4ActionVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant4ActionVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.ProjectAutomationConfigVariant4ActionVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant1EventTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant1EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant1ActionVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant1ActionVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant1ActionVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant1ActionVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant2EventTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant2EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant2ExportDefinitionVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant2ExportDefinitionVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant2ExportDefinitionVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant2ExportDefinitionVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant2ExportDefinitionVariant3TypeJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant2ExportDefinitionVariant3TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant2FormatJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant2FormatNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant2CredentialsTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant2CredentialsTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant3EventTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant3EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant4EventTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant4EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant4ActionVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant4ActionVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant4ActionVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.CreateProjectAutomationConfigVariant4ActionVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant1EventTypeJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant1EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant1ActionVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant1ActionVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant1ActionVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant1ActionVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant2EventTypeJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant2EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant2ExportDefinitionVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant2ExportDefinitionVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant2ExportDefinitionVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant2ExportDefinitionVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant2ExportDefinitionVariant3TypeJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant2ExportDefinitionVariant3TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant2FormatJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant2FormatNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant2CredentialsTypeJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant2CredentialsTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant3EventTypeJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant3EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant4EventTypeJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant4EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant4ActionVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant4ActionVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant4ActionVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.PatchProjectAutomationConfigVariant4ActionVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.OnlineScoreConfigScorerVariant2FunctionTypeJsonConverter),
            typeof(global::G.JsonConverters.OnlineScoreConfigScorerVariant2FunctionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.OnlineScoreConfigScorerVariant2GlobalTypeJsonConverter),
            typeof(global::G.JsonConverters.OnlineScoreConfigScorerVariant2GlobalTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EvalStatusPageThemeJsonConverter),
            typeof(global::G.JsonConverters.EvalStatusPageThemeNullableJsonConverter),
            typeof(global::G.JsonConverters.EvalStatusPageConfigSortOrderJsonConverter),
            typeof(global::G.JsonConverters.EvalStatusPageConfigSortOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleRuntimeContextRuntimeJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleRuntimeContextRuntimeNullableJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationExperimentTypeJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationExperimentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationExperimentPositionVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationExperimentPositionVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationExperimentPositionScorerTypeJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationExperimentPositionScorerTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationFunctionTypeJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationFunctionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationVariant3TypeJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationVariant3TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationVariant3SandboxSpecVariant1ProviderJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationVariant3SandboxSpecVariant1ProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationVariant3SandboxSpecVariant2ProviderJsonConverter),
            typeof(global::G.JsonConverters.CodeBundleLocationVariant3SandboxSpecVariant2ProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptBlockDataChatTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptBlockDataChatTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptBlockDataCompletionTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptBlockDataCompletionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant3TypeJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant3TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant4TypeJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant4TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant5TypeJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant5TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant6TypeJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant6TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant7TypeJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant7TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant8TypeJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeVariant8TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphEdgePurposeJsonConverter),
            typeof(global::G.JsonConverters.GraphEdgePurposeNullableJsonConverter),
            typeof(global::G.JsonConverters.GraphDataTypeJsonConverter),
            typeof(global::G.JsonConverters.GraphDataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FacetDataTypeJsonConverter),
            typeof(global::G.JsonConverters.FacetDataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TopicMapDataTypeJsonConverter),
            typeof(global::G.JsonConverters.TopicMapDataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BatchedFacetDataTypeJsonConverter),
            typeof(global::G.JsonConverters.BatchedFacetDataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataPromptTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataPromptTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataCodeTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataCodeTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataCodeDataTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataCodeDataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataCodeDataType2JsonConverter),
            typeof(global::G.JsonConverters.FunctionDataCodeDataType2NullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataCodeDataRuntimeContextRuntimeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataCodeDataRuntimeContextRuntimeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataRemoteEvalTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataRemoteEvalTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataGlobalTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataGlobalTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataParametersTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataParametersTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataParametersSchemaTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataParametersSchemaTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionLogIdJsonConverter),
            typeof(global::G.JsonConverters.FunctionLogIdNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishPromptTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishPromptTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishCodeTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishCodeTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishCodeDataTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishCodeDataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishCodeDataType2JsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishCodeDataType2NullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishCodeDataRuntimeContextRuntimeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishCodeDataRuntimeContextRuntimeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishRemoteEvalTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishRemoteEvalTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishGlobalTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishGlobalTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishParametersTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishParametersTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishParametersSchemaTypeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishParametersSchemaTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.InvokeParentSpanParentStructObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.InvokeParentSpanParentStructObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.StreamingModeJsonConverter),
            typeof(global::G.JsonConverters.StreamingModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsMonitorViewOptionsViewTypeJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsMonitorViewOptionsViewTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsMonitorViewOptionsOptionsSpanTypeJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsMonitorViewOptionsOptionsSpanTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsMonitorViewOptionsOptionsTypeJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsMonitorViewOptionsOptionsTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsTableViewOptionsExcludedMeasureTypeJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsTableViewOptionsExcludedMeasureTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsTableViewOptionsYMetricTypeJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsTableViewOptionsYMetricTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsTableViewOptionsXAxisTypeJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsTableViewOptionsXAxisTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsTableViewOptionsSymbolGroupingTypeJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsTableViewOptionsSymbolGroupingTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsTableViewOptionsQueryShapeJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsTableViewOptionsQueryShapeNullableJsonConverter),
            typeof(global::G.JsonConverters.ViewViewTypeJsonConverter),
            typeof(global::G.JsonConverters.ViewViewTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateViewViewTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateViewViewTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchViewViewTypeJsonConverter),
            typeof(global::G.JsonConverters.PatchViewViewTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ImageRenderingModeJsonConverter),
            typeof(global::G.JsonConverters.ImageRenderingModeNullableJsonConverter),
            typeof(global::G.JsonConverters.PatchOrganizationMembersOutputStatusJsonConverter),
            typeof(global::G.JsonConverters.PatchOrganizationMembersOutputStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.EnvVarObjectType2JsonConverter),
            typeof(global::G.JsonConverters.EnvVarObjectType2NullableJsonConverter),
            typeof(global::G.JsonConverters.EnvVarSecretCategoryJsonConverter),
            typeof(global::G.JsonConverters.EnvVarSecretCategoryNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptDataToolFunctionVariant2FunctionTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptDataToolFunctionVariant2FunctionTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptDataToolFunctionVariant2GlobalTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptDataToolFunctionVariant2GlobalTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptDataTemplateFormatJsonConverter),
            typeof(global::G.JsonConverters.PromptDataTemplateFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptDataMcpMcpServerIdThisIsUsedForProjectLevelMcpServerDefinitionsTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptDataMcpMcpServerIdThisIsUsedForProjectLevelMcpServerDefinitionsTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptDataMcpMcpServerUrlThisIsUsedForInlineDefinitionsOfMcpServersTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptDataMcpMcpServerUrlThisIsUsedForInlineDefinitionsOfMcpServersTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FunctionIdInlineCodeInlineContextRuntimeJsonConverter),
            typeof(global::G.JsonConverters.FunctionIdInlineCodeInlineContextRuntimeNullableJsonConverter),
            typeof(global::G.JsonConverters.GitMetadataSettingsCollectJsonConverter),
            typeof(global::G.JsonConverters.GitMetadataSettingsCollectNullableJsonConverter),
            typeof(global::G.JsonConverters.GitMetadataSettingsFieldJsonConverter),
            typeof(global::G.JsonConverters.GitMetadataSettingsFieldNullableJsonConverter),
            typeof(global::G.JsonConverters.PostEnvVarRequestObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.PostEnvVarRequestObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PutEnvVarRequestObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.PutEnvVarRequestObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IdsJsonConverter),
            typeof(global::G.JsonConverters.UserGivenNameJsonConverter),
            typeof(global::G.JsonConverters.UserFamilyNameJsonConverter),
            typeof(global::G.JsonConverters.UserEmailJsonConverter),
            typeof(global::G.JsonConverters.AISecretTypeJsonConverter),
            typeof(global::G.JsonConverters.NullableSavedFunctionIdJsonConverter),
            typeof(global::G.JsonConverters.SavedFunctionIdJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionContentPartJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionMessageParamJsonConverter),
            typeof(global::G.JsonConverters.PromptBlockDataNullishJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatNullishJsonConverter),
            typeof(global::G.JsonConverters.ModelParamsJsonConverter),
            typeof(global::G.JsonConverters.TopicAutomationDataScopeJsonConverter),
            typeof(global::G.JsonConverters.ProjectScoreCategoriesJsonConverter),
            typeof(global::G.JsonConverters.PromptBlockDataJsonConverter),
            typeof(global::G.JsonConverters.GraphNodeJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataJsonConverter),
            typeof(global::G.JsonConverters.FunctionDataNullishJsonConverter),
            typeof(global::G.JsonConverters.InvokeParentJsonConverter),
            typeof(global::G.JsonConverters.ViewOptionsJsonConverter),
            typeof(global::G.JsonConverters.FunctionIdJsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ProjectSettingsSpanFieldOrderItemLayoutVariant1?, global::G.ProjectSettingsSpanFieldOrderItemLayoutVariant2?, object>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.ProjectSettings, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ChatCompletionContentPartImageWithTitleImageUrlDetailAuto?, global::G.ChatCompletionContentPartImageWithTitleImageUrlDetailLow?, global::G.ChatCompletionContentPartImageWithTitleImageUrlDetailHigh?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ChatCompletionContentPartText>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ChatCompletionContentPart>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ChatCompletionContentPartText>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ChatCompletionContentPartText>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ChatCompletionContentPartText>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.Dictionary<string, object?>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ModelParamsOpenAIModelParamsToolChoiceAuto?, global::G.ModelParamsOpenAIModelParamsToolChoiceNone?, global::G.ModelParamsOpenAIModelParamsToolChoiceRequired?, global::G.ModelParamsOpenAIModelParamsToolChoiceFunction>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ModelParamsOpenAIModelParamsFunctionCallAuto?, global::G.ModelParamsOpenAIModelParamsFunctionCallNone?, global::G.ModelParamsOpenAIModelParamsFunctionCallFunction>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.SavedFunctionId?, global::G.AnyOf<global::G.PromptDataNullishToolFunctionVariant2Function, global::G.PromptDataNullishToolFunctionVariant2Global>?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PromptDataNullishToolFunctionVariant2Function, global::G.PromptDataNullishToolFunctionVariant2Global>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.PromptDataNullishMcpMcpServerIdThisIsUsedForProjectLevelMcpServerDefinitions, global::G.PromptDataNullishMcpMcpServerUrlThisIsUsedForInlineDefinitionsOfMcpServers>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.SavedFunctionId?, global::G.AnyOf<global::G.TopicMapFunctionAutomationFunctionVariant2Function, global::G.TopicMapFunctionAutomationFunctionVariant2Global>?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.TopicMapFunctionAutomationFunctionVariant2Function, global::G.TopicMapFunctionAutomationFunctionVariant2Global>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.SavedFunctionId?, global::G.AnyOf<global::G.TopicAutomationConfigFacetFunctionVariant2Function, global::G.TopicAutomationConfigFacetFunctionVariant2Global>?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.TopicAutomationConfigFacetFunctionVariant2Function, global::G.TopicAutomationConfigFacetFunctionVariant2Global>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SpanScope, global::G.TraceScope, global::G.GroupScope, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.TopicAutomationConfigBackfillTimeRange, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ProjectAutomationConfigVariant1, global::G.ProjectAutomationConfigVariant2, global::G.ProjectAutomationConfigVariant3, global::G.ProjectAutomationConfigVariant4, global::G.TopicAutomationConfig>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ProjectAutomationConfigVariant1ActionVariant1, global::G.ProjectAutomationConfigVariant1ActionVariant2>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ProjectAutomationConfigVariant2ExportDefinitionVariant1, global::G.ProjectAutomationConfigVariant2ExportDefinitionVariant2, global::G.ProjectAutomationConfigVariant2ExportDefinitionVariant3>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ProjectAutomationConfigVariant4ActionVariant1, global::G.ProjectAutomationConfigVariant4ActionVariant2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.CreateProjectAutomationConfigVariant1, global::G.CreateProjectAutomationConfigVariant2, global::G.CreateProjectAutomationConfigVariant3, global::G.CreateProjectAutomationConfigVariant4, global::G.TopicAutomationConfig>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.CreateProjectAutomationConfigVariant1ActionVariant1, global::G.CreateProjectAutomationConfigVariant1ActionVariant2>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.CreateProjectAutomationConfigVariant2ExportDefinitionVariant1, global::G.CreateProjectAutomationConfigVariant2ExportDefinitionVariant2, global::G.CreateProjectAutomationConfigVariant2ExportDefinitionVariant3>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.CreateProjectAutomationConfigVariant4ActionVariant1, global::G.CreateProjectAutomationConfigVariant4ActionVariant2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PatchProjectAutomationConfigVariant1, global::G.PatchProjectAutomationConfigVariant2, global::G.PatchProjectAutomationConfigVariant3, global::G.PatchProjectAutomationConfigVariant4, global::G.TopicAutomationConfig, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.PatchProjectAutomationConfigVariant1ActionVariant1, global::G.PatchProjectAutomationConfigVariant1ActionVariant2>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.PatchProjectAutomationConfigVariant2ExportDefinitionVariant1, global::G.PatchProjectAutomationConfigVariant2ExportDefinitionVariant2, global::G.PatchProjectAutomationConfigVariant2ExportDefinitionVariant3>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.PatchProjectAutomationConfigVariant4ActionVariant1, global::G.PatchProjectAutomationConfigVariant4ActionVariant2>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.SavedFunctionId?, global::G.AnyOf<global::G.OnlineScoreConfigScorerVariant2Function, global::G.OnlineScoreConfigScorerVariant2Global>?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.OnlineScoreConfigScorerVariant2Function, global::G.OnlineScoreConfigScorerVariant2Global>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SpanScope, global::G.TraceScope, global::G.GroupScope, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.CodeBundleLocationExperiment, global::G.CodeBundleLocationFunction, global::G.CodeBundleLocationVariant3>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.CodeBundleLocationExperimentPositionVariant1, global::G.CodeBundleLocationExperimentPositionScorer>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.CodeBundleLocationVariant3SandboxSpecVariant1, global::G.CodeBundleLocationVariant3SandboxSpecVariant2>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.NullableSavedFunctionId?, object>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.NullableSavedFunctionId?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.AllOf<global::G.FunctionDataCodeData, global::G.CodeBundle>?, global::G.FunctionDataCodeData2>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.FunctionDataCodeData, global::G.CodeBundle>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.TopicMapData, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.AllOf<global::G.FunctionDataNullishCodeData, global::G.CodeBundle>?, global::G.FunctionDataNullishCodeData2>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.FunctionDataNullishCodeData, global::G.CodeBundle>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.TopicMapData, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::G.ViewOptionsTableViewOptionsTimeRangeFilter, object>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.SavedFunctionId?, global::G.AnyOf<global::G.PromptDataToolFunctionVariant2Function, global::G.PromptDataToolFunctionVariant2Global>?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.PromptDataToolFunctionVariant2Function, global::G.PromptDataToolFunctionVariant2Global>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.PromptDataMcpMcpServerIdThisIsUsedForProjectLevelMcpServerDefinitions, global::G.PromptDataMcpMcpServerUrlThisIsUsedForInlineDefinitionsOfMcpServers>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.RunEvalDataDatasetId, global::G.RunEvalDataProjectDatasetName, global::G.RunEvalDataDatasetRows>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.FunctionId?, object>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.InvokeParent?, object>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.RepoInfo, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ProjectScoreType?, global::System.Collections.Generic.IList<global::G.AllOf<global::G.ProjectScoreType?, object>>>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.ProjectScoreType?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Guid?, global::System.Collections.Generic.IList<global::System.Guid>>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}