//HintName: G.Models.CreateImageRequestModeration.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// Control the content-moderation level for images generated by `gpt-image-1`. Must be either `low` for less restrictive filtering or `auto` (default value).<br/>
    /// Default Value: auto<br/>
    /// Example: low
    /// </summary>
    public enum CreateImageRequestModeration
    {
        /// <summary>
        /// 
        /// </summary>
        Auto,
        /// <summary>
        /// 
        /// </summary>
        Low,
    }

    /// <summary>
    /// Enum extensions to do fast conversions without the reflection.
    /// </summary>
    public static class CreateImageRequestModerationExtensions
    {
        /// <summary>
        /// Converts an enum to a string.
        /// </summary>
        public static string ToValueString(this CreateImageRequestModeration value)
        {
            return value switch
            {
                CreateImageRequestModeration.Auto => "auto",
                CreateImageRequestModeration.Low => "low",
                _ => throw new global::System.ArgumentOutOfRangeException(nameof(value), value, null),
            };
        }
        /// <summary>
        /// Converts an string to a enum.
        /// </summary>
        public static CreateImageRequestModeration? ToEnum(string value)
        {
            return value switch
            {
                "auto" => CreateImageRequestModeration.Auto,
                "low" => CreateImageRequestModeration.Low,
                _ => null,
            };
        }
    }
}