//HintName: G.Models.CompletionsResponse.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// Example: {"choices":[{"text":"Sure! Here\u0027s a search engine optimized article about...","log_probs":"openapi-json-null-sentinel-value-2BF93600-0FE4-4250-987A-E5DDB203E464"}],"model":"palmyra-x-003-instruct"}
    /// </summary>
    public sealed partial class CompletionsResponse
    {
        /// <summary>
        /// A list of choices generated by the model, each containing the text of the completion and associated metadata such as log probabilities.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("choices", Required = global::Newtonsoft.Json.Required.Always)]
        public global::System.Collections.Generic.IList<global::G.CompletionsChoice> Choices { get; set; } = default!;

        /// <summary>
        /// The identifier of the model that was used to generate the responses in the 'choices' array.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("model")]
        public string? Model { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="CompletionsResponse" /> class.
        /// </summary>
        /// <param name="choices">
        /// A list of choices generated by the model, each containing the text of the completion and associated metadata such as log probabilities.
        /// </param>
        /// <param name="model">
        /// The identifier of the model that was used to generate the responses in the 'choices' array.
        /// </param>
        public CompletionsResponse(
            global::System.Collections.Generic.IList<global::G.CompletionsChoice> choices,
            string? model)
        {
            this.Choices = choices ?? throw new global::System.ArgumentNullException(nameof(choices));
            this.Model = model;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CompletionsResponse" /> class.
        /// </summary>
        public CompletionsResponse()
        {
        }
    }
}