//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.ContentsRequestLivecrawlJsonConverter),
            typeof(global::G.JsonConverters.ContentsRequestLivecrawlNullableJsonConverter),
            typeof(global::G.JsonConverters.CompanyEntityTypeJsonConverter),
            typeof(global::G.JsonConverters.CompanyEntityTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PersonEntityTypeJsonConverter),
            typeof(global::G.JsonConverters.PersonEntityTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EntityDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.EntityDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchCreateRequestDtoClassModelJsonConverter),
            typeof(global::G.JsonConverters.ResearchCreateRequestDtoClassModelNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant1ModelJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant1ModelNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant1StatusJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant1StatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant2ModelJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant2ModelNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant2StatusJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant2StatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant3ModelJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant3ModelNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant3StatusJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant3StatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant4ModelJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant4ModelNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant4StatusJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant4StatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant5ModelJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant5ModelNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant5StatusJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassVariant5StatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchOperationDtoClassVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchOperationDtoClassVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchOperationDtoClassVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchOperationDtoClassVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchOperationDtoClassVariant2SearchTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchOperationDtoClassVariant2SearchTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchOperationDtoClassVariant3TypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchOperationDtoClassVariant3TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant1Variant1EventTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant1Variant1EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant1Variant2EventTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant1Variant2EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant1Variant2OutputVariant1OutputTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant1Variant2OutputVariant1OutputTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant1Variant2OutputVariant2OutputTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant1Variant2OutputVariant2OutputTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant2Variant1EventTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant2Variant1EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant2Variant2EventTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant2Variant2EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant2Variant3EventTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant2Variant3EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant2Variant3OutputVariant1OutputTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant2Variant3OutputVariant1OutputTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant2Variant3OutputVariant2OutputTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant2Variant3OutputVariant2OutputTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant3Variant1EventTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant3Variant1EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant3Variant2EventTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant3Variant2EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant3Variant3EventTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant3Variant3EventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant3Variant3OutputOutputTypeJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant3Variant3OutputOutputTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SearchRequestTypeJsonConverter),
            typeof(global::G.JsonConverters.SearchRequestTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SearchRequestCategoryJsonConverter),
            typeof(global::G.JsonConverters.SearchRequestCategoryNullableJsonConverter),
            typeof(global::G.JsonConverters.SearchResponseSearchTypeJsonConverter),
            typeof(global::G.JsonConverters.SearchResponseSearchTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetContentsResponseStatuseStatusJsonConverter),
            typeof(global::G.JsonConverters.GetContentsResponseStatuseStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GetContentsResponseStatuseErrorTagJsonConverter),
            typeof(global::G.JsonConverters.GetContentsResponseStatuseErrorTagNullableJsonConverter),
            typeof(global::G.JsonConverters.EntityJsonConverter),
            typeof(global::G.JsonConverters.ResultWithContentJsonConverter),
            typeof(global::G.JsonConverters.ResearchDtoClassJsonConverter),
            typeof(global::G.JsonConverters.ResearchOperationDtoClassJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant1JsonConverter),
            typeof(global::G.JsonConverters.OutputJsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant2JsonConverter),
            typeof(global::G.JsonConverters.Output2JsonConverter),
            typeof(global::G.JsonConverters.ResearchEventDtoClassVariant3JsonConverter),
            typeof(global::G.JsonConverters.OneOfJsonConverter<bool?, global::G.ContentsRequestText>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<bool?, global::G.ContentsRequestContext>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<bool?, global::G.CommonRequestContext>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.EntityCompanyPropertiesFundingRound, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.EntityCompanyPropertiesWorkforce, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.EntityCompanyPropertiesHeadquarters, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.EntityCompanyPropertiesFinancials, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.EntityCompanyPropertiesWebTraffic, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.EntityDateRange, object>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.EntityPersonPropertiesCompanyRef, object>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.SearchRequest2, global::G.CommonRequest>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.FindSimilarRequest2, global::G.CommonRequest>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.GetContentsRequest2, global::G.ContentsRequest>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.AnswerResult, global::G.AnswerResponse2>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}