//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.AgentStateToolRulesVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.AgentStateToolRulesVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentStateModelSettingsVariant1DiscriminatorProviderTypeJsonConverter),
            typeof(global::G.JsonConverters.AgentStateModelSettingsVariant1DiscriminatorProviderTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentStateResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.AgentStateResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentTypeJsonConverter),
            typeof(global::G.JsonConverters.AgentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AnthropicModelSettingsResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.AnthropicModelSettingsResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AnthropicModelSettingsVerbosity2JsonConverter),
            typeof(global::G.JsonConverters.AnthropicModelSettingsVerbosity2NullableJsonConverter),
            typeof(global::G.JsonConverters.AnthropicModelSettingsEffort2JsonConverter),
            typeof(global::G.JsonConverters.AnthropicModelSettingsEffort2NullableJsonConverter),
            typeof(global::G.JsonConverters.AnthropicThinkingTypeJsonConverter),
            typeof(global::G.JsonConverters.AnthropicThinkingTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ApprovalCreateApprovalsVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ApprovalCreateApprovalsVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ApprovalResponseMessageApprovalsVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ApprovalResponseMessageApprovalsVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AzureModelSettingsResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.AzureModelSettingsResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BedrockModelSettingsResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.BedrockModelSettingsResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionServiceTier2JsonConverter),
            typeof(global::G.JsonConverters.ChatCompletionServiceTier2NullableJsonConverter),
            typeof(global::G.JsonConverters.ChatGPTOAuthReasoningReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.ChatGPTOAuthReasoningReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.ChoiceFinishReasonJsonConverter),
            typeof(global::G.JsonConverters.ChoiceFinishReasonNullableJsonConverter),
            typeof(global::G.JsonConverters.CompactionSettingsInputModelSettingsVariant1DiscriminatorProviderTypeJsonConverter),
            typeof(global::G.JsonConverters.CompactionSettingsInputModelSettingsVariant1DiscriminatorProviderTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CompactionSettingsInputModeJsonConverter),
            typeof(global::G.JsonConverters.CompactionSettingsInputModeNullableJsonConverter),
            typeof(global::G.JsonConverters.CompactionSettingsOutputModelSettingsVariant1DiscriminatorProviderTypeJsonConverter),
            typeof(global::G.JsonConverters.CompactionSettingsOutputModelSettingsVariant1DiscriminatorProviderTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CompactionSettingsOutputModeJsonConverter),
            typeof(global::G.JsonConverters.CompactionSettingsOutputModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ComparisonOperatorJsonConverter),
            typeof(global::G.JsonConverters.ComparisonOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationModelSettingsVariant1DiscriminatorProviderTypeJsonConverter),
            typeof(global::G.JsonConverters.ConversationModelSettingsVariant1DiscriminatorProviderTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ConversationMessageRequestInputVariant2ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ConversationMessageRequestInputVariant2ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateAgentRequestToolRulesVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateAgentRequestToolRulesVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateAgentRequestModelSettingsVariant1DiscriminatorProviderTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateAgentRequestModelSettingsVariant1DiscriminatorProviderTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateAgentRequestResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateAgentRequestResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateConversationModelSettingsVariant1DiscriminatorProviderTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateConversationModelSettingsVariant1DiscriminatorProviderTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateMCPServerRequestConfigDiscriminatorMcpServerTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateMCPServerRequestConfigDiscriminatorMcpServerTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DeepseekModelSettingsResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.DeepseekModelSettingsResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DuplicateFileHandlingJsonConverter),
            typeof(global::G.JsonConverters.DuplicateFileHandlingNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingConfigEmbeddingEndpointTypeJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingConfigEmbeddingEndpointTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingModelEmbeddingEndpointTypeJsonConverter),
            typeof(global::G.JsonConverters.EmbeddingModelEmbeddingEndpointTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedbackTypeJsonConverter),
            typeof(global::G.JsonConverters.FeedbackTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FileProcessingStatusJsonConverter),
            typeof(global::G.JsonConverters.FileProcessingStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.GoogleAIModelSettingsResponseSchemaVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GoogleAIModelSettingsResponseSchemaVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GoogleVertexModelSettingsResponseSchemaVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GoogleVertexModelSettingsResponseSchemaVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GroqModelSettingsResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.GroqModelSettingsResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GroupCreateManagerConfigDiscriminatorManagerTypeJsonConverter),
            typeof(global::G.JsonConverters.GroupCreateManagerConfigDiscriminatorManagerTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GroupSchemaManagerConfigDiscriminatorManagerTypeJsonConverter),
            typeof(global::G.JsonConverters.GroupSchemaManagerConfigDiscriminatorManagerTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GroupUpdateManagerConfigVariant1DiscriminatorManagerTypeJsonConverter),
            typeof(global::G.JsonConverters.GroupUpdateManagerConfigVariant1DiscriminatorManagerTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.HiddenReasoningMessageStateJsonConverter),
            typeof(global::G.JsonConverters.HiddenReasoningMessageStateNullableJsonConverter),
            typeof(global::G.JsonConverters.IdentityPropertyTypeJsonConverter),
            typeof(global::G.JsonConverters.IdentityPropertyTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IdentityTypeJsonConverter),
            typeof(global::G.JsonConverters.IdentityTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ImageContentSourceDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ImageContentSourceDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ImageURLDetailJsonConverter),
            typeof(global::G.JsonConverters.ImageURLDetailNullableJsonConverter),
            typeof(global::G.JsonConverters.InputAudioFormatJsonConverter),
            typeof(global::G.JsonConverters.InputAudioFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.InternalTemplateAgentCreateToolRulesVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.InternalTemplateAgentCreateToolRulesVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.InternalTemplateAgentCreateModelSettingsVariant1DiscriminatorProviderTypeJsonConverter),
            typeof(global::G.JsonConverters.InternalTemplateAgentCreateModelSettingsVariant1DiscriminatorProviderTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.InternalTemplateAgentCreateResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.InternalTemplateAgentCreateResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.InternalTemplateGroupCreateManagerConfigDiscriminatorManagerTypeJsonConverter),
            typeof(global::G.JsonConverters.InternalTemplateGroupCreateManagerConfigDiscriminatorManagerTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.JobStatusJsonConverter),
            typeof(global::G.JsonConverters.JobStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.JobTypeJsonConverter),
            typeof(global::G.JsonConverters.JobTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LLMConfigModelEndpointTypeJsonConverter),
            typeof(global::G.JsonConverters.LLMConfigModelEndpointTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LLMConfigReasoningEffort2JsonConverter),
            typeof(global::G.JsonConverters.LLMConfigReasoningEffort2NullableJsonConverter),
            typeof(global::G.JsonConverters.LLMConfigEffort2JsonConverter),
            typeof(global::G.JsonConverters.LLMConfigEffort2NullableJsonConverter),
            typeof(global::G.JsonConverters.LLMConfigCompatibilityType2JsonConverter),
            typeof(global::G.JsonConverters.LLMConfigCompatibilityType2NullableJsonConverter),
            typeof(global::G.JsonConverters.LLMConfigVerbosity2JsonConverter),
            typeof(global::G.JsonConverters.LLMConfigVerbosity2NullableJsonConverter),
            typeof(global::G.JsonConverters.LLMConfigResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LLMConfigResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaAsyncRequestInputVariant2ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaAsyncRequestInputVariant2ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaBatchRequestInputVariant2ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaBatchRequestInputVariant2ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaRequestInputVariant2ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaRequestInputVariant2ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaStreamingRequestInputVariant2ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaStreamingRequestInputVariant2ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaStreamingResponseDiscriminatorMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaStreamingResponseDiscriminatorMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MCPServerTypeJsonConverter),
            typeof(global::G.JsonConverters.MCPServerTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ManagerTypeJsonConverter),
            typeof(global::G.JsonConverters.ManagerTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MessageContentVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MessageContentVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MessageCreateRoleJsonConverter),
            typeof(global::G.JsonConverters.MessageCreateRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.MessageRoleJsonConverter),
            typeof(global::G.JsonConverters.MessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.MessageSearchRequestSearchModeJsonConverter),
            typeof(global::G.JsonConverters.MessageSearchRequestSearchModeNullableJsonConverter),
            typeof(global::G.JsonConverters.MessageTypeJsonConverter),
            typeof(global::G.JsonConverters.MessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ModalSandboxConfigLanguageJsonConverter),
            typeof(global::G.JsonConverters.ModalSandboxConfigLanguageNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelModelEndpointTypeJsonConverter),
            typeof(global::G.JsonConverters.ModelModelEndpointTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelReasoningEffort2JsonConverter),
            typeof(global::G.JsonConverters.ModelReasoningEffort2NullableJsonConverter),
            typeof(global::G.JsonConverters.ModelEffort2JsonConverter),
            typeof(global::G.JsonConverters.ModelEffort2NullableJsonConverter),
            typeof(global::G.JsonConverters.ModelCompatibilityType2JsonConverter),
            typeof(global::G.JsonConverters.ModelCompatibilityType2NullableJsonConverter),
            typeof(global::G.JsonConverters.ModelVerbosity2JsonConverter),
            typeof(global::G.JsonConverters.ModelVerbosity2NullableJsonConverter),
            typeof(global::G.JsonConverters.ModelResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ModelResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.OpenAIModelSettingsResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.OpenAIModelSettingsResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.OpenAIReasoningReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.OpenAIReasoningReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.OpenRouterModelSettingsResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.OpenRouterModelSettingsResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PassageSearchRequestTagMatchModeJsonConverter),
            typeof(global::G.JsonConverters.PassageSearchRequestTagMatchModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ProviderCategoryJsonConverter),
            typeof(global::G.JsonConverters.ProviderCategoryNullableJsonConverter),
            typeof(global::G.JsonConverters.ProviderTypeJsonConverter),
            typeof(global::G.JsonConverters.ProviderTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ReasoningMessageSourceJsonConverter),
            typeof(global::G.JsonConverters.ReasoningMessageSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.RunStatusJsonConverter),
            typeof(global::G.JsonConverters.RunStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.SandboxTypeJsonConverter),
            typeof(global::G.JsonConverters.SandboxTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SearchAllMessagesRequestSearchModeJsonConverter),
            typeof(global::G.JsonConverters.SearchAllMessagesRequestSearchModeNullableJsonConverter),
            typeof(global::G.JsonConverters.StepFeedback2JsonConverter),
            typeof(global::G.JsonConverters.StepFeedback2NullableJsonConverter),
            typeof(global::G.JsonConverters.StepStatus2JsonConverter),
            typeof(global::G.JsonConverters.StepStatus2NullableJsonConverter),
            typeof(global::G.JsonConverters.StopReasonTypeJsonConverter),
            typeof(global::G.JsonConverters.StopReasonTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TogetherModelSettingsResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.TogetherModelSettingsResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolExecutionResultStatusJsonConverter),
            typeof(global::G.JsonConverters.ToolExecutionResultStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolReturnMessageStatusJsonConverter),
            typeof(global::G.JsonConverters.ToolReturnMessageStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolSearchRequestSearchModeJsonConverter),
            typeof(global::G.JsonConverters.ToolSearchRequestSearchModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolTypeJsonConverter),
            typeof(global::G.JsonConverters.ToolTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TurnTokenDataRoleJsonConverter),
            typeof(global::G.JsonConverters.TurnTokenDataRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.UpdateAgentToolRulesVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.UpdateAgentToolRulesVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UpdateAgentModelSettingsVariant1DiscriminatorProviderTypeJsonConverter),
            typeof(global::G.JsonConverters.UpdateAgentModelSettingsVariant1DiscriminatorProviderTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UpdateAgentResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.UpdateAgentResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UpdateConversationModelSettingsVariant1DiscriminatorProviderTypeJsonConverter),
            typeof(global::G.JsonConverters.UpdateConversationModelSettingsVariant1DiscriminatorProviderTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.UpdateMCPServerRequestConfigDiscriminatorMcpServerTypeJsonConverter),
            typeof(global::G.JsonConverters.UpdateMCPServerRequestConfigDiscriminatorMcpServerTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.VectorDBProviderJsonConverter),
            typeof(global::G.JsonConverters.VectorDBProviderNullableJsonConverter),
            typeof(global::G.JsonConverters.XAIModelSettingsResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.XAIModelSettingsResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ZAIModelSettingsResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ZAIModelSettingsResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ZAIThinkingTypeJsonConverter),
            typeof(global::G.JsonConverters.ZAIThinkingTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasAgentFileAgentSchemaToolRulesVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasAgentFileAgentSchemaToolRulesVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasAgentFileAgentSchemaModelSettingsVariant1DiscriminatorProviderTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasAgentFileAgentSchemaModelSettingsVariant1DiscriminatorProviderTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasAgentFileAgentSchemaResponseFormatVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasAgentFileAgentSchemaResponseFormatVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasLettaMessageToolReturnStatusJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasLettaMessageToolReturnStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasMessageToolReturnInputStatusJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasMessageToolReturnInputStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasMessageToolReturnInputFuncResponseVariant2ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasMessageToolReturnInputFuncResponseVariant2ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasMessageToolReturnOutputStatusJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasMessageToolReturnOutputStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasMessageToolReturnOutputFuncResponseVariant2ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaSchemasMessageToolReturnOutputFuncResponseVariant2ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaMessageUnionDiscriminatorMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaMessageUnionDiscriminatorMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaMessageContentUnionDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaMessageContentUnionDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaAssistantMessageContentUnionDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaAssistantMessageContentUnionDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaToolReturnContentUnionDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaToolReturnContentUnionDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LettaUserMessageContentUnionDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LettaUserMessageContentUnionDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant1FieldJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant1FieldNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant2FieldJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant2FieldNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant2OperatorJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant2OperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant3FieldJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant3FieldNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant3OperatorJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant3OperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant4FieldJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant4FieldNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant4OperatorJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant4OperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant5FieldJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant5FieldNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant5OperatorJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant5OperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant6FieldJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant6FieldNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant6OperatorJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSearchItemVariant6OperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestCombinatorJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestCombinatorNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSortByJsonConverter),
            typeof(global::G.JsonConverters.AgentsSearchDeployedAgentsRequestSortByNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateAgentsFromTemplateRequestInitialMessageSequenceItemRoleJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateAgentsFromTemplateRequestInitialMessageSequenceItemRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateAgentsFromTemplateNoProjectRequestInitialMessageSequenceItemRoleJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateAgentsFromTemplateNoProjectRequestInitialMessageSequenceItemRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateTemplateNoProjectRequestVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateTemplateNoProjectRequestVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateTemplateNoProjectRequestVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateTemplateNoProjectRequestVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesSaveTemplateVersionNoProjectRequestBlockReconciliationStrategyJsonConverter),
            typeof(global::G.JsonConverters.TemplatesSaveTemplateVersionNoProjectRequestBlockReconciliationStrategyNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesSaveTemplateVersionRequestBlockReconciliationStrategyJsonConverter),
            typeof(global::G.JsonConverters.TemplatesSaveTemplateVersionRequestBlockReconciliationStrategyNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateTemplateRequestVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateTemplateRequestVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateTemplateRequestVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateTemplateRequestVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensCreateClientSideAccessTokenRequestPolicyItemVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensCreateClientSideAccessTokenRequestPolicyItemVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensCreateClientSideAccessTokenRequestPolicyItemVariant1AccesJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensCreateClientSideAccessTokenRequestPolicyItemVariant1AccesNullableJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendFeedbackRequestFeatureJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendFeedbackRequestFeatureNullableJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendTelemetryRequestServiceJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendTelemetryRequestServiceNullableJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendTelemetryRequestEventVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendTelemetryRequestEventVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendTelemetryRequestEventVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendTelemetryRequestEventVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendTelemetryRequestEventVariant3TypeJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendTelemetryRequestEventVariant3TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendTelemetryRequestEventVariant4TypeJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendTelemetryRequestEventVariant4TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendTelemetryRequestEventVariant5TypeJsonConverter),
            typeof(global::G.JsonConverters.MetadataSendTelemetryRequestEventVariant5TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestMessageContentVariant1ItemVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestMessageContentVariant1ItemVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestMessageContentVariant1ItemVariant2SourceTypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestMessageContentVariant1ItemVariant2SourceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestMessageContentVariant1ItemVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestMessageContentVariant1ItemVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestIncludeReturnMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestIncludeReturnMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestScheduleVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestScheduleVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestScheduleVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesScheduleAgentMessageRequestScheduleVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineRequestIntegrationTypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineRequestIntegrationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineRequestProducerConfigVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineRequestProducerConfigVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineRequestProducerConfigVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineRequestProducerConfigVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigRequestProducerConfigVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigRequestProducerConfigVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigRequestProducerConfigVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigRequestProducerConfigVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesPreviewPipelineRequestIntegrationTypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesPreviewPipelineRequestIntegrationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesPreviewPipelineRequestProducerConfigVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesPreviewPipelineRequestProducerConfigVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesPreviewPipelineRequestProducerConfigVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesPreviewPipelineRequestProducerConfigVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant1RoleJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant1RoleNullableJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant1ContentVariant2ItemTypeJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant1ContentVariant2ItemTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant2ApprovalVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant2ApprovalVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant2ApprovalVariant1ToolReturnVariant2ItemTypeJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant2ApprovalVariant1ToolReturnVariant2ItemTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant2ApprovalVariant1StatusJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant2ApprovalVariant1StatusNullableJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant2ApprovalVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendMessageRequestMessageVariant2ApprovalVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendModeChangeRequestModeJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsSendModeChangeRequestModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListArchivesOrderJsonConverter),
            typeof(global::G.JsonConverters.ListArchivesOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForArchiveOrderJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForArchiveOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForArchiveIncludeItemJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForArchiveIncludeItemNullableJsonConverter),
            typeof(global::G.JsonConverters.ListToolsOrderJsonConverter),
            typeof(global::G.JsonConverters.ListToolsOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListFoldersOrderJsonConverter),
            typeof(global::G.JsonConverters.ListFoldersOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForFolderOrderJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForFolderOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListFolderPassagesOrderJsonConverter),
            typeof(global::G.JsonConverters.ListFolderPassagesOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListFilesForFolderOrderJsonConverter),
            typeof(global::G.JsonConverters.ListFilesForFolderOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsIncludeItemJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsIncludeItemNullableJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsOrderJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsOrderByJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsOrderByNullableJsonConverter),
            typeof(global::G.JsonConverters.RetrieveAgentIncludeItemJsonConverter),
            typeof(global::G.JsonConverters.RetrieveAgentIncludeItemNullableJsonConverter),
            typeof(global::G.JsonConverters.ListToolsForAgentOrderJsonConverter),
            typeof(global::G.JsonConverters.ListToolsForAgentOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListAgentSourcesOrderJsonConverter),
            typeof(global::G.JsonConverters.ListAgentSourcesOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListFoldersForAgentOrderJsonConverter),
            typeof(global::G.JsonConverters.ListFoldersForAgentOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListFilesForAgentOrderJsonConverter),
            typeof(global::G.JsonConverters.ListFilesForAgentOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListCoreMemoryBlocksOrderJsonConverter),
            typeof(global::G.JsonConverters.ListCoreMemoryBlocksOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.SearchArchivalMemoryTagMatchModeJsonConverter),
            typeof(global::G.JsonConverters.SearchArchivalMemoryTagMatchModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListMessagesOrderJsonConverter),
            typeof(global::G.JsonConverters.ListMessagesOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListGroupsForAgentOrderJsonConverter),
            typeof(global::G.JsonConverters.ListGroupsForAgentOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListConversationsOrderJsonConverter),
            typeof(global::G.JsonConverters.ListConversationsOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListConversationsOrderByJsonConverter),
            typeof(global::G.JsonConverters.ListConversationsOrderByNullableJsonConverter),
            typeof(global::G.JsonConverters.ListConversationMessagesOrderJsonConverter),
            typeof(global::G.JsonConverters.ListConversationMessagesOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListGroupsOrderJsonConverter),
            typeof(global::G.JsonConverters.ListGroupsOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListGroupMessagesOrderJsonConverter),
            typeof(global::G.JsonConverters.ListGroupMessagesOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListIdentitiesOrderJsonConverter),
            typeof(global::G.JsonConverters.ListIdentitiesOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForIdentityOrderJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForIdentityOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForIdentityIncludeItemJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForIdentityIncludeItemNullableJsonConverter),
            typeof(global::G.JsonConverters.ListBlocksForIdentityOrderJsonConverter),
            typeof(global::G.JsonConverters.ListBlocksForIdentityOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListInternalBlocksOrderJsonConverter),
            typeof(global::G.JsonConverters.ListInternalBlocksOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForInternalBlockOrderJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForInternalBlockOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListInternalRunsOrderJsonConverter),
            typeof(global::G.JsonConverters.ListInternalRunsOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListInternalRunsOrderByJsonConverter),
            typeof(global::G.JsonConverters.ListInternalRunsOrderByNullableJsonConverter),
            typeof(global::G.JsonConverters.ListInternalRunsDurationOperator2JsonConverter),
            typeof(global::G.JsonConverters.ListInternalRunsDurationOperator2NullableJsonConverter),
            typeof(global::G.JsonConverters.ListBlocksOrderJsonConverter),
            typeof(global::G.JsonConverters.ListBlocksOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForBlockOrderJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForBlockOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForBlockIncludeItemJsonConverter),
            typeof(global::G.JsonConverters.ListAgentsForBlockIncludeItemNullableJsonConverter),
            typeof(global::G.JsonConverters.ListJobsOrderJsonConverter),
            typeof(global::G.JsonConverters.ListJobsOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListProvidersOrderJsonConverter),
            typeof(global::G.JsonConverters.ListProvidersOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListRunsOrderJsonConverter),
            typeof(global::G.JsonConverters.ListRunsOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListMessagesForRunOrderJsonConverter),
            typeof(global::G.JsonConverters.ListMessagesForRunOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListStepsForRunOrderJsonConverter),
            typeof(global::G.JsonConverters.ListStepsForRunOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListStepsOrderJsonConverter),
            typeof(global::G.JsonConverters.ListStepsOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListStepsFeedback2JsonConverter),
            typeof(global::G.JsonConverters.ListStepsFeedback2NullableJsonConverter),
            typeof(global::G.JsonConverters.ListMessagesForStepOrderJsonConverter),
            typeof(global::G.JsonConverters.ListMessagesForStepOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListTagsOrderJsonConverter),
            typeof(global::G.JsonConverters.ListTagsOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListAllMessagesOrderJsonConverter),
            typeof(global::G.JsonConverters.ListAllMessagesOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListBatchesOrderJsonConverter),
            typeof(global::G.JsonConverters.ListBatchesOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.ListMessagesForBatchOrderJsonConverter),
            typeof(global::G.JsonConverters.ListMessagesForBatchOrderNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant1FieldJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant1FieldNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant2FieldJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant2FieldNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant2OperatorJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant2OperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant3FieldJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant3FieldNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant3OperatorJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant3OperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant4FieldJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant4FieldNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant4OperatorJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant4OperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant5FieldJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant5FieldNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant5OperatorJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant5OperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant6FieldJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant6FieldNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant6OperatorJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsSearchItemVariant6OperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsCombinatorJsonConverter),
            typeof(global::G.JsonConverters.AgentsCountDeployedAgentsCombinatorNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesListTemplatesSortByJsonConverter),
            typeof(global::G.JsonConverters.TemplatesListTemplatesSortByNullableJsonConverter),
            typeof(global::G.JsonConverters.ModifyMessageResponseDiscriminatorMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ModifyMessageResponseDiscriminatorMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ModifyGroupMessageResponseDiscriminatorMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ModifyGroupMessageResponseDiscriminatorMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListMessagesForStepResponseItemDiscriminatorMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ListMessagesForStepResponseItemDiscriminatorMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.SearchAllMessagesResponseItemDiscriminatorMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.SearchAllMessagesResponseItemDiscriminatorMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.AgentsGetAgentVariablesResponseMessageJsonConverter),
            typeof(global::G.JsonConverters.AgentsGetAgentVariablesResponseMessageNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant3TypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant3TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant4TypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant4TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant5TypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant5TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant6TypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant6TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant7TypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant7TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant8TypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant8TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant9TypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant9TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentAgentTypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentAgentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentPropertiesVerbosityLevelJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentPropertiesVerbosityLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentPropertiesReasoningEffortJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseAgentPropertiesReasoningEffortNullableJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseTypeJsonConverter),
            typeof(global::G.JsonConverters.TemplatesGetTemplateSnapshotResponseTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensCreateClientSideAccessTokenResponsePolicyVersionJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensCreateClientSideAccessTokenResponsePolicyVersionNullableJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensCreateClientSideAccessTokenResponsePolicyDataItemVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensCreateClientSideAccessTokenResponsePolicyDataItemVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensCreateClientSideAccessTokenResponsePolicyDataItemVariant1AccesJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensCreateClientSideAccessTokenResponsePolicyDataItemVariant1AccesNullableJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensListClientSideAccessTokensResponseTokenPolicyVersionJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensListClientSideAccessTokensResponseTokenPolicyVersionNullableJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensListClientSideAccessTokensResponseTokenPolicyDataItemVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensListClientSideAccessTokensResponseTokenPolicyDataItemVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensListClientSideAccessTokensResponseTokenPolicyDataItemVariant1AccesJsonConverter),
            typeof(global::G.JsonConverters.ClientSideAccessTokensListClientSideAccessTokensResponseTokenPolicyDataItemVariant1AccesNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageContentVariant1ItemVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageContentVariant1ItemVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageContentVariant1ItemVariant2SourceTypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageContentVariant1ItemVariant2SourceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageContentVariant1ItemVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageContentVariant1ItemVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageIncludeReturnMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageIncludeReturnMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageScheduleVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageScheduleVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageScheduleVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesListScheduledMessagesResponseScheduledMessageScheduleVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageContentVariant1ItemVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageContentVariant1ItemVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageContentVariant1ItemVariant2SourceTypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageContentVariant1ItemVariant2SourceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageContentVariant1ItemVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageContentVariant1ItemVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageRoleJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseMessageIncludeReturnMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseMessageIncludeReturnMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseScheduleVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseScheduleVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseScheduleVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.ScheduledMessagesRetrieveScheduledMessageResponseScheduleVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedsSubscribeAgentResponseMergeStrategyJsonConverter),
            typeof(global::G.JsonConverters.FeedsSubscribeAgentResponseMergeStrategyNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedsSubscribeAgentResponseErrorCodeJsonConverter),
            typeof(global::G.JsonConverters.FeedsSubscribeAgentResponseErrorCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedsUpdateSubscriptionResponseMergeStrategyJsonConverter),
            typeof(global::G.JsonConverters.FeedsUpdateSubscriptionResponseMergeStrategyNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedsBackfillSubscriptionResponseErrorCodeJsonConverter),
            typeof(global::G.JsonConverters.FeedsBackfillSubscriptionResponseErrorCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedsListSubscriptionHistoryResponseRunTypeJsonConverter),
            typeof(global::G.JsonConverters.FeedsListSubscriptionHistoryResponseRunTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedsListSubscriptionHistoryResponseRunStatusJsonConverter),
            typeof(global::G.JsonConverters.FeedsListSubscriptionHistoryResponseRunStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedsListSubscriptionHistoryResponseErrorCodeJsonConverter),
            typeof(global::G.JsonConverters.FeedsListSubscriptionHistoryResponseErrorCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.FeedsListSubscriptionsResponseSubscriptionMergeStrategyJsonConverter),
            typeof(global::G.JsonConverters.FeedsListSubscriptionsResponseSubscriptionMergeStrategyNullableJsonConverter),
            typeof(global::G.JsonConverters.MemoryFilesListDirectoryResponseEntrieTypeJsonConverter),
            typeof(global::G.JsonConverters.MemoryFilesListDirectoryResponseEntrieTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineResponsePipelineIntegrationTypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineResponsePipelineIntegrationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineResponsePipelineConfigVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineResponsePipelineConfigVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineResponsePipelineConfigVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineResponsePipelineConfigVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineResponseErrorCodeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesCreatePipelineResponseErrorCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesListPipelinesResponsePipelineIntegrationTypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesListPipelinesResponsePipelineIntegrationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesListPipelinesResponsePipelineConfigVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesListPipelinesResponsePipelineConfigVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesListPipelinesResponsePipelineConfigVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesListPipelinesResponsePipelineConfigVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesGetPipelineResponsePipelineIntegrationTypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesGetPipelineResponsePipelineIntegrationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesGetPipelineResponsePipelineConfigVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesGetPipelineResponsePipelineConfigVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesGetPipelineResponsePipelineConfigVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesGetPipelineResponsePipelineConfigVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesGetPipelineResponseErrorCodeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesGetPipelineResponseErrorCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineResponsePipelineIntegrationTypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineResponsePipelineIntegrationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineResponsePipelineConfigVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineResponsePipelineConfigVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineResponsePipelineConfigVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineResponsePipelineConfigVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineResponseErrorCodeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineResponseErrorCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesDeletePipelineResponseErrorCodeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesDeletePipelineResponseErrorCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigResponsePipelineIntegrationTypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigResponsePipelineIntegrationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigResponsePipelineConfigVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigResponsePipelineConfigVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigResponsePipelineConfigVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigResponsePipelineConfigVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigResponseErrorCodeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigResponseErrorCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigResponseErrorCode2JsonConverter),
            typeof(global::G.JsonConverters.PipelinesUpdatePipelineProducerConfigResponseErrorCode2NullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesPreviewPipelineResponseErrorCodeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesPreviewPipelineResponseErrorCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesSyncPipelineResponseErrorCodeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesSyncPipelineResponseErrorCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesSyncPipelineResponseErrorCode2JsonConverter),
            typeof(global::G.JsonConverters.PipelinesSyncPipelineResponseErrorCode2NullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesListPipelineSyncHistoryResponseRunStatusJsonConverter),
            typeof(global::G.JsonConverters.PipelinesListPipelineSyncHistoryResponseRunStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.PipelinesListPipelineSyncHistoryResponseErrorCodeJsonConverter),
            typeof(global::G.JsonConverters.PipelinesListPipelineSyncHistoryResponseErrorCodeNullableJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsGetConnectionResponseCurrentModeJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsGetConnectionResponseCurrentModeNullableJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsListConnectionsResponseConnectionCurrentModeJsonConverter),
            typeof(global::G.JsonConverters.EnvironmentsListConnectionsResponseConnectionCurrentModeNullableJsonConverter),
            typeof(global::G.JsonConverters.ToolRulesVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.ModelSettingsVariant1JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant1JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant12JsonConverter),
            typeof(global::G.JsonConverters.ApprovalsVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.ApprovalsVariant1Item2JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant13JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant14JsonConverter),
            typeof(global::G.JsonConverters.ModelSettingsVariant12JsonConverter),
            typeof(global::G.JsonConverters.ModelSettingsVariant13JsonConverter),
            typeof(global::G.JsonConverters.ModelSettingsVariant14JsonConverter),
            typeof(global::G.JsonConverters.InputVariant2ItemJsonConverter),
            typeof(global::G.JsonConverters.ToolRulesVariant1Item2JsonConverter),
            typeof(global::G.JsonConverters.ModelSettingsVariant15JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant15JsonConverter),
            typeof(global::G.JsonConverters.ModelSettingsVariant16JsonConverter),
            typeof(global::G.JsonConverters.ConfigJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant16JsonConverter),
            typeof(global::G.JsonConverters.ResponseSchemaVariant1JsonConverter),
            typeof(global::G.JsonConverters.ResponseSchemaVariant12JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant17JsonConverter),
            typeof(global::G.JsonConverters.ManagerConfigJsonConverter),
            typeof(global::G.JsonConverters.ManagerConfig2JsonConverter),
            typeof(global::G.JsonConverters.ManagerConfigVariant1JsonConverter),
            typeof(global::G.JsonConverters.SourceJsonConverter),
            typeof(global::G.JsonConverters.ToolRulesVariant1Item3JsonConverter),
            typeof(global::G.JsonConverters.ModelSettingsVariant17JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant18JsonConverter),
            typeof(global::G.JsonConverters.ManagerConfig3JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant19JsonConverter),
            typeof(global::G.JsonConverters.InputVariant2Item2JsonConverter),
            typeof(global::G.JsonConverters.InputVariant2Item3JsonConverter),
            typeof(global::G.JsonConverters.InputVariant2Item4JsonConverter),
            typeof(global::G.JsonConverters.InputVariant2Item5JsonConverter),
            typeof(global::G.JsonConverters.LettaStreamingResponseJsonConverter),
            typeof(global::G.JsonConverters.ContentVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant110JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant111JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant112JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant113JsonConverter),
            typeof(global::G.JsonConverters.ToolRulesVariant1Item4JsonConverter),
            typeof(global::G.JsonConverters.ModelSettingsVariant18JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant114JsonConverter),
            typeof(global::G.JsonConverters.ModelSettingsVariant19JsonConverter),
            typeof(global::G.JsonConverters.Config4JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant115JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant116JsonConverter),
            typeof(global::G.JsonConverters.ToolRulesVariant1Item5JsonConverter),
            typeof(global::G.JsonConverters.ModelSettingsVariant110JsonConverter),
            typeof(global::G.JsonConverters.ResponseFormatVariant117JsonConverter),
            typeof(global::G.JsonConverters.FuncResponseVariant2ItemJsonConverter),
            typeof(global::G.JsonConverters.FuncResponseVariant2Item2JsonConverter),
            typeof(global::G.JsonConverters.LettaMessageUnionJsonConverter),
            typeof(global::G.JsonConverters.LettaMessageContentUnionJsonConverter),
            typeof(global::G.JsonConverters.LettaAssistantMessageContentUnionJsonConverter),
            typeof(global::G.JsonConverters.LettaToolReturnContentUnionJsonConverter),
            typeof(global::G.JsonConverters.LettaUserMessageContentUnionJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateTemplateNoProjectRequestJsonConverter),
            typeof(global::G.JsonConverters.TemplatesCreateTemplateRequestJsonConverter),
            typeof(global::G.JsonConverters.PolicyItemJsonConverter),
            typeof(global::G.JsonConverters.EventsItemJsonConverter),
            typeof(global::G.JsonConverters.ProducerConfigJsonConverter),
            typeof(global::G.JsonConverters.ProducerConfig2JsonConverter),
            typeof(global::G.JsonConverters.ProducerConfig3JsonConverter),
            typeof(global::G.JsonConverters.ModifyMessageResponseJsonConverter),
            typeof(global::G.JsonConverters.ModifyGroupMessageResponseJsonConverter),
            typeof(global::G.JsonConverters.ListMessagesForStepResponseItemJsonConverter),
            typeof(global::G.JsonConverters.SearchAllMessagesResponseItemJsonConverter),
            typeof(global::G.JsonConverters.DataItemJsonConverter),
            typeof(global::G.JsonConverters.DataItem2JsonConverter),
            typeof(global::G.JsonConverters.Config5JsonConverter),
            typeof(global::G.JsonConverters.Config6JsonConverter),
            typeof(global::G.JsonConverters.Config7JsonConverter),
            typeof(global::G.JsonConverters.Config8JsonConverter),
            typeof(global::G.JsonConverters.Config9JsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ToolCall2, global::G.ToolCallDelta>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.ToolCall2>, global::G.ToolCallDelta, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.LettaAssistantMessageContentUnion>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.LettaAssistantMessageContentUnion>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.ChatCompletionContentPartTextParam, global::G.ChatCompletionContentPartRefusalParam>>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ChatCompletionContentPartTextParam, global::G.ChatCompletionContentPartRefusalParam>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ChatCompletionMessageFunctionToolCallParam, global::G.ChatCompletionMessageCustomToolCallParam>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ChatCompletionContentPartTextParam>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ChatCompletionMessageFunctionToolCallOutput, global::G.ChatCompletionMessageCustomToolCall>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ChatCompletionDeveloperMessageParam, global::G.ChatCompletionSystemMessageParam, global::G.ChatCompletionUserMessageParam, global::G.ChatCompletionAssistantMessageParam, global::G.ChatCompletionToolMessageParam, global::G.ChatCompletionFunctionMessageParam>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ChatCompletionContentPartTextParam>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.ChatCompletionContentPartTextParam>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.ChatCompletionContentPartTextParam, global::G.ChatCompletionContentPartImageParam, global::G.ChatCompletionContentPartInputAudioParam, global::G.File>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ChatCompletionContentPartTextParam, global::G.ChatCompletionContentPartImageParam, global::G.ChatCompletionContentPartInputAudioParam, global::G.File>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.MessageCreate, global::G.ApprovalCreate, global::G.ToolReturnCreate>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.InputVariant2Item>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?, double?, bool?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.MessageCreate, global::G.ApprovalCreate, global::G.ToolReturnCreate>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.InputVariant2Item2>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.MessageCreate, global::G.ApprovalCreate, global::G.ToolReturnCreate>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.InputVariant2Item3>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.MessageCreate, global::G.ApprovalCreate, global::G.ToolReturnCreate>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.InputVariant2Item4>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.MessageCreate, global::G.ApprovalCreate, global::G.ToolReturnCreate>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.InputVariant2Item5>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.AgentType?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ApprovalReturn, global::G.LettaSchemasMessageToolReturnOutput>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.LettaMessageContentUnion>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.LocalSandboxConfig, global::G.E2BSandboxConfig, global::G.ModalSandboxConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.LocalSandboxConfig, global::G.E2BSandboxConfig, global::G.ModalSandboxConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ToolCall2, global::G.ToolCallDelta>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.ToolCall2>, global::G.ToolCallDelta, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.LettaAssistantMessageContentUnion>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.LettaUserMessageContentUnion>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.LettaUserMessageContentUnion>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.LettaUserMessageContentUnion>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.LettaMessageContentUnion>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ApprovalReturn, global::G.LettaSchemasMessageToolReturnInput>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.LettaToolReturnContentUnion>, string>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.FuncResponseVariant2Item>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.FuncResponseVariant2Item2>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.BaseToolRuleSchema, global::G.ChildToolRuleSchema, global::G.MaxCountPerStepToolRuleSchema, global::G.ConditionalToolRuleSchema>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.StdioServerConfig, global::G.SSEServerConfig, global::G.StreamableHTTPServerConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.LettaSchemasMcpUpdateStdioMCPServer, global::G.LettaSchemasMcpUpdateSSEMCPServer, global::G.LettaSchemasMcpUpdateStreamableHTTPMCPServer>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.StdioServerConfig, global::G.SSEServerConfig, global::G.StreamableHTTPServerConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.StdioServerConfig, global::G.SSEServerConfig, global::G.StreamableHTTPServerConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.UpdateSystemMessage, global::G.UpdateUserMessage, global::G.UpdateReasoningMessage, global::G.UpdateAssistantMessage>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.LettaRequest, global::G.LettaStreamingRequest>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.UpdateSystemMessage, global::G.UpdateUserMessage, global::G.UpdateReasoningMessage, global::G.UpdateAssistantMessage>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.AgentsSearchDeployedAgentsRequestSearchItemVariant1, global::G.AgentsSearchDeployedAgentsRequestSearchItemVariant2, global::G.AgentsSearchDeployedAgentsRequestSearchItemVariant3, global::G.AgentsSearchDeployedAgentsRequestSearchItemVariant4, global::G.AgentsSearchDeployedAgentsRequestSearchItemVariant5, global::G.AgentsSearchDeployedAgentsRequestSearchItemVariant6>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::System.Collections.Generic.IList<global::G.OneOf<global::G.ScheduledMessagesScheduleAgentMessageRequestMessageContentVariant1ItemVariant1, global::G.ScheduledMessagesScheduleAgentMessageRequestMessageContentVariant1ItemVariant2>>, string>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ScheduledMessagesScheduleAgentMessageRequestMessageContentVariant1ItemVariant1, global::G.ScheduledMessagesScheduleAgentMessageRequestMessageContentVariant1ItemVariant2>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ScheduledMessagesScheduleAgentMessageRequestScheduleVariant1, global::G.ScheduledMessagesScheduleAgentMessageRequestScheduleVariant2>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.EnvironmentsSendMessageRequestMessageVariant1, global::G.EnvironmentsSendMessageRequestMessageVariant2>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.EnvironmentsSendMessageRequestMessageVariant1ContentVariant2Item>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.EnvironmentsSendMessageRequestMessageVariant2ApprovalVariant1, global::G.EnvironmentsSendMessageRequestMessageVariant2ApprovalVariant2>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, global::System.Collections.Generic.IList<global::G.EnvironmentsSendMessageRequestMessageVariant2ApprovalVariant1ToolReturnVariant2Item>>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.AgentsCountDeployedAgentsSearchItemVariant1, global::G.AgentsCountDeployedAgentsSearchItemVariant2, global::G.AgentsCountDeployedAgentsSearchItemVariant3, global::G.AgentsCountDeployedAgentsSearchItemVariant4, global::G.AgentsCountDeployedAgentsSearchItemVariant5, global::G.AgentsCountDeployedAgentsSearchItemVariant6>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, double?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, double?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, double?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, double?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, double?>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<string, double?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SSEServerConfig, global::G.StdioServerConfig, global::G.StreamableHTTPServerConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.StdioServerConfig, global::G.SSEServerConfig, global::G.StreamableHTTPServerConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.StdioServerConfig, global::G.SSEServerConfig, global::G.StreamableHTTPServerConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.StdioServerConfig, global::G.SSEServerConfig, global::G.StreamableHTTPServerConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.StdioMCPServer, global::G.SSEMCPServer, global::G.StreamableHTTPMCPServer>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.StdioMCPServer, global::G.SSEMCPServer, global::G.StreamableHTTPMCPServer>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.StdioMCPServer, global::G.SSEMCPServer, global::G.StreamableHTTPMCPServer>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.StdioMCPServer, global::G.SSEMCPServer, global::G.StreamableHTTPMCPServer>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant1, global::G.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant2, global::G.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant3, global::G.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant4, global::G.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant5, global::G.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant6, global::G.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant7, global::G.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant8, global::G.TemplatesGetTemplateSnapshotResponseAgentToolRuleVariant9>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::System.Collections.Generic.IList<global::G.OneOf<global::G.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageContentVariant1ItemVariant1, global::G.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageContentVariant1ItemVariant2>>, string>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageContentVariant1ItemVariant1, global::G.ScheduledMessagesListScheduledMessagesResponseScheduledMessageMessageMessageContentVariant1ItemVariant2>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ScheduledMessagesListScheduledMessagesResponseScheduledMessageScheduleVariant1, global::G.ScheduledMessagesListScheduledMessagesResponseScheduledMessageScheduleVariant2>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::System.Collections.Generic.IList<global::G.OneOf<global::G.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageContentVariant1ItemVariant1, global::G.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageContentVariant1ItemVariant2>>, string>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageContentVariant1ItemVariant1, global::G.ScheduledMessagesRetrieveScheduledMessageResponseMessageMessageContentVariant1ItemVariant2>),
            typeof(global::G.JsonConverters.OneOfJsonConverter<global::G.ScheduledMessagesRetrieveScheduledMessageResponseScheduleVariant1, global::G.ScheduledMessagesRetrieveScheduledMessageResponseScheduleVariant2>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}