//HintName: G.Models.LettaUsageStatistics.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// Usage statistics for the agent interaction.<br/>
    /// Attributes:<br/>
    ///     completion_tokens (int): The number of tokens generated by the agent.<br/>
    ///     prompt_tokens (int): The number of tokens in the prompt.<br/>
    ///     total_tokens (int): The total number of tokens processed by the agent.<br/>
    ///     step_count (int): The number of steps taken by the agent.<br/>
    ///     cached_input_tokens (Optional[int]): The number of input tokens served from cache. None if not reported.<br/>
    ///     cache_write_tokens (Optional[int]): The number of input tokens written to cache. None if not reported.<br/>
    ///     reasoning_tokens (Optional[int]): The number of reasoning/thinking tokens generated. None if not reported.
    /// </summary>
    public sealed partial class LettaUsageStatistics
    {
        /// <summary>
        /// Default Value: usage_statistics
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("message_type")]
        public string? MessageType { get; set; }

        /// <summary>
        /// The number of tokens generated by the agent.<br/>
        /// Default Value: 0
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("completion_tokens")]
        public int? CompletionTokens { get; set; }

        /// <summary>
        /// The number of tokens in the prompt.<br/>
        /// Default Value: 0
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("prompt_tokens")]
        public int? PromptTokens { get; set; }

        /// <summary>
        /// The total number of tokens processed by the agent.<br/>
        /// Default Value: 0
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("total_tokens")]
        public int? TotalTokens { get; set; }

        /// <summary>
        /// The number of steps taken by the agent.<br/>
        /// Default Value: 0
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("step_count")]
        public int? StepCount { get; set; }

        /// <summary>
        /// The background task run IDs associated with the agent interaction
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("run_ids")]
        public global::System.Collections.Generic.IList<string>? RunIds { get; set; }

        /// <summary>
        /// The number of input tokens served from cache. None if not reported by provider.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("cached_input_tokens")]
        public int? CachedInputTokens { get; set; }

        /// <summary>
        /// The number of input tokens written to cache (Anthropic only). None if not reported by provider.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("cache_write_tokens")]
        public int? CacheWriteTokens { get; set; }

        /// <summary>
        /// The number of reasoning/thinking tokens generated. None if not reported by provider.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("reasoning_tokens")]
        public int? ReasoningTokens { get; set; }

        /// <summary>
        /// Estimate of tokens currently in the context window.
        /// </summary>
        [global::System.Text.Json.Serialization.JsonPropertyName("context_tokens")]
        public int? ContextTokens { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::System.Text.Json.Serialization.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="LettaUsageStatistics" /> class.
        /// </summary>
        /// <param name="messageType">
        /// Default Value: usage_statistics
        /// </param>
        /// <param name="completionTokens">
        /// The number of tokens generated by the agent.<br/>
        /// Default Value: 0
        /// </param>
        /// <param name="promptTokens">
        /// The number of tokens in the prompt.<br/>
        /// Default Value: 0
        /// </param>
        /// <param name="totalTokens">
        /// The total number of tokens processed by the agent.<br/>
        /// Default Value: 0
        /// </param>
        /// <param name="stepCount">
        /// The number of steps taken by the agent.<br/>
        /// Default Value: 0
        /// </param>
        /// <param name="runIds">
        /// The background task run IDs associated with the agent interaction
        /// </param>
        /// <param name="cachedInputTokens">
        /// The number of input tokens served from cache. None if not reported by provider.
        /// </param>
        /// <param name="cacheWriteTokens">
        /// The number of input tokens written to cache (Anthropic only). None if not reported by provider.
        /// </param>
        /// <param name="reasoningTokens">
        /// The number of reasoning/thinking tokens generated. None if not reported by provider.
        /// </param>
        /// <param name="contextTokens">
        /// Estimate of tokens currently in the context window.
        /// </param>
#if NET7_0_OR_GREATER
        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]
#endif
        public LettaUsageStatistics(
            string? messageType,
            int? completionTokens,
            int? promptTokens,
            int? totalTokens,
            int? stepCount,
            global::System.Collections.Generic.IList<string>? runIds,
            int? cachedInputTokens,
            int? cacheWriteTokens,
            int? reasoningTokens,
            int? contextTokens)
        {
            this.MessageType = messageType;
            this.CompletionTokens = completionTokens;
            this.PromptTokens = promptTokens;
            this.TotalTokens = totalTokens;
            this.StepCount = stepCount;
            this.RunIds = runIds;
            this.CachedInputTokens = cachedInputTokens;
            this.CacheWriteTokens = cacheWriteTokens;
            this.ReasoningTokens = reasoningTokens;
            this.ContextTokens = contextTokens;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LettaUsageStatistics" /> class.
        /// </summary>
        public LettaUsageStatistics()
        {
        }
    }
}