//HintName: G.Models.HeyGenTextToAvatarOptions.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// Options for the HeyGen text-to-avatar service. Set the text to be converted to an avatar and configure the avatars voice, speaking style, appearance and background. The output will be generated as an MP4 video file available at the URL returned in the response.
    /// </summary>
    public sealed partial class HeyGenTextToAvatarOptions
    {
        /// <summary>
        /// The type of asset to generate - set to `text-to-avatar` for text-to-avatar.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("type")]
        [global::Newtonsoft.Json.JsonConverter(typeof(global::G.JsonConverters.HeyGenTextToAvatarOptionsTypeJsonConverter))]
        public global::G.HeyGenTextToAvatarOptionsType Type { get; set; }

        /// <summary>
        /// The text or script that the avatar will narrate.<br/>
        /// Example: I am an avatar generated by HeyGen using a text prompt
        /// </summary>
        /// <example>I am an avatar generated by HeyGen using a text prompt</example>
        [global::Newtonsoft.Json.JsonProperty("text", Required = global::Newtonsoft.Json.Required.Always)]
        public string Text { get; set; } = default!;

        /// <summary>
        /// The avatar character to generate. Select from the list of available avatars: &lt;ul&gt;<br/>
        ///   &lt;li&gt;`Angela`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Bill`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Daisy`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Derek`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Eva`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jake`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jeff`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jerome`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Joon`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Kayla`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Kent`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Luna`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Mark`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Matthew`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Monica`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Peter`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Selina`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Tanya`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Thomas`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Tina`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Tyler`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Vanessa`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Vera`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Wilson`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Zoey`&lt;/li&gt;<br/>
        /// &lt;/ul&gt;
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("avatar", Required = global::Newtonsoft.Json.Required.Always)]
        [global::Newtonsoft.Json.JsonConverter(typeof(global::G.JsonConverters.HeyGenTextToAvatarOptionsAvatarJsonConverter))]
        public global::G.HeyGenTextToAvatarOptionsAvatar Avatar { get; set; } = default!;

        /// <summary>
        /// The avatars voice and speaking style. Select from the list of available voices: &lt;ul&gt;<br/>
        ///   &lt;li&gt;`Abb- - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Adam - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Aiston - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Alice - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Alison - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Amber - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Amy - Warm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Ana - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Antoni - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Aria - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Arnold - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Arthur - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Bella - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Belle - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Brandon - Warm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Brian - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Bruce - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Cerise - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Christopher - Calm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Clara - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Connor - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Dahlia - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Davis - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Dean - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Delbert - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Edward - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Elaine - Calm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Emily - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Emma - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Eric - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Grace - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Hailey - Calm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Indira - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Isabella - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jacob - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jahmai - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jane - Serious`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jason - Serious`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jelle - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jen - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jenny - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jodi - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Joey - Calm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Johan - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Josie - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Keanan - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Keith - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Kellie - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Lauren - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Leah - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Liam - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Libby - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Lily - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Lucas - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Luke - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Luna - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Marieke - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Matthew - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Michelle - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Mitchell - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Molly - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Monica - Calm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Natasha - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Neerja - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Noah - Serious`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Oliver - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Olivia - Calm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Paul - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Prabhat - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Raveena - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Rudi - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Ryan - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Sam - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Sara - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Sherry - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Sonia - Warm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Thomas - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Todd - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Tony - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Tracy - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Wayne - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Wilder - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Wille - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`William - Friendly`&lt;/li&gt;<br/>
        /// &lt;/ul&gt;
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("voice", Required = global::Newtonsoft.Json.Required.Always)]
        [global::Newtonsoft.Json.JsonConverter(typeof(global::G.JsonConverters.HeyGenTextToAvatarOptionsVoiceJsonConverter))]
        public global::G.HeyGenTextToAvatarOptionsVoice Voice { get; set; } = default!;

        /// <summary>
        /// The display style of the avatar, a rectangle `normal` or circular `circle` background. Defaults to `normal`.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("avatarStyle")]
        [global::Newtonsoft.Json.JsonConverter(typeof(global::G.JsonConverters.HeyGenTextToAvatarOptionsAvatarStyleJsonConverter))]
        public global::G.HeyGenTextToAvatarOptionsAvatarStyle? AvatarStyle { get; set; }

        /// <summary>
        /// The background color of the video. Defaults to `#ffffff`.<br/>
        /// Example: #ffffff
        /// </summary>
        /// <example>#ffffff</example>
        [global::Newtonsoft.Json.JsonProperty("background")]
        public string? Background { get; set; }

        /// <summary>
        /// The aspect ratio of the video, `16:9` horizontal or `9:16` vertical. Defaults to `16:9`.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("ratio")]
        [global::Newtonsoft.Json.JsonConverter(typeof(global::G.JsonConverters.HeyGenTextToAvatarOptionsRatioJsonConverter))]
        public global::G.HeyGenTextToAvatarOptionsRatio? Ratio { get; set; }

        /// <summary>
        /// A boolean flag indicating whether the video is for testing purposes. See the "test" parameter in [HeyGen](https://docs.heygen.com/reference/generate-video) for more details.<br/>
        /// Example: true
        /// </summary>
        /// <example>true</example>
        [global::Newtonsoft.Json.JsonProperty("test")]
        public bool? Test { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="HeyGenTextToAvatarOptions" /> class.
        /// </summary>
        /// <param name="text">
        /// The text or script that the avatar will narrate.<br/>
        /// Example: I am an avatar generated by HeyGen using a text prompt
        /// </param>
        /// <param name="avatar">
        /// The avatar character to generate. Select from the list of available avatars: &lt;ul&gt;<br/>
        ///   &lt;li&gt;`Angela`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Bill`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Daisy`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Derek`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Eva`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jake`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jeff`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jerome`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Joon`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Kayla`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Kent`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Luna`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Mark`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Matthew`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Monica`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Peter`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Selina`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Tanya`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Thomas`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Tina`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Tyler`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Vanessa`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Vera`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Wilson`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Zoey`&lt;/li&gt;<br/>
        /// &lt;/ul&gt;
        /// </param>
        /// <param name="voice">
        /// The avatars voice and speaking style. Select from the list of available voices: &lt;ul&gt;<br/>
        ///   &lt;li&gt;`Abb- - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Adam - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Aiston - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Alice - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Alison - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Amber - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Amy - Warm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Ana - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Antoni - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Aria - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Arnold - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Arthur - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Bella - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Belle - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Brandon - Warm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Brian - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Bruce - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Cerise - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Christopher - Calm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Clara - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Connor - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Dahlia - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Davis - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Dean - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Delbert - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Edward - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Elaine - Calm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Emily - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Emma - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Eric - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Grace - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Hailey - Calm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Indira - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Isabella - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jacob - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jahmai - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jane - Serious`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jason - Serious`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jelle - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jen - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jenny - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Jodi - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Joey - Calm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Johan - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Josie - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Keanan - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Keith - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Kellie - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Lauren - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Leah - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Liam - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Libby - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Lily - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Lucas - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Luke - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Luna - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Marieke - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Matthew - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Michelle - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Mitchell - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Molly - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Monica - Calm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Natasha - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Neerja - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Noah - Serious`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Oliver - Newscaster`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Olivia - Calm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Paul - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Prabhat - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Raveena - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Rudi - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Ryan - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Sam - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Sara - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Sherry - Friendly`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Sonia - Warm`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Thomas - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Todd - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Tony - Professional`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Tracy - Cheerful`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Wayne - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Wilder - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`Wille - Natural`&lt;/li&gt;<br/>
        ///   &lt;li&gt;`William - Friendly`&lt;/li&gt;<br/>
        /// &lt;/ul&gt;
        /// </param>
        /// <param name="type">
        /// The type of asset to generate - set to `text-to-avatar` for text-to-avatar.
        /// </param>
        /// <param name="avatarStyle">
        /// The display style of the avatar, a rectangle `normal` or circular `circle` background. Defaults to `normal`.
        /// </param>
        /// <param name="background">
        /// The background color of the video. Defaults to `#ffffff`.<br/>
        /// Example: #ffffff
        /// </param>
        /// <param name="ratio">
        /// The aspect ratio of the video, `16:9` horizontal or `9:16` vertical. Defaults to `16:9`.
        /// </param>
        /// <param name="test">
        /// A boolean flag indicating whether the video is for testing purposes. See the "test" parameter in [HeyGen](https://docs.heygen.com/reference/generate-video) for more details.<br/>
        /// Example: true
        /// </param>
        public HeyGenTextToAvatarOptions(
            string text,
            global::G.HeyGenTextToAvatarOptionsAvatar avatar,
            global::G.HeyGenTextToAvatarOptionsVoice voice,
            global::G.HeyGenTextToAvatarOptionsType type,
            global::G.HeyGenTextToAvatarOptionsAvatarStyle? avatarStyle,
            string? background,
            global::G.HeyGenTextToAvatarOptionsRatio? ratio,
            bool? test)
        {
            this.Type = type;
            this.Text = text ?? throw new global::System.ArgumentNullException(nameof(text));
            this.Avatar = avatar;
            this.Voice = voice;
            this.AvatarStyle = avatarStyle;
            this.Background = background;
            this.Ratio = ratio;
            this.Test = test;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="HeyGenTextToAvatarOptions" /> class.
        /// </summary>
        public HeyGenTextToAvatarOptions()
        {
        }
    }
}