//HintName: G.Models.TextToSpeechAsset.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// The TextToSpeechAsset lets you generate a voice over from text using a text-to-speech service. The generated audio can be trimmed, faded and have its volume and speed adjusted using the same properties available on the AudioAsset.
    /// </summary>
    public sealed partial class TextToSpeechAsset
    {
        /// <summary>
        /// The type of asset - set to `text-to-speech` for text-to-speech.<br/>
        /// Default Value: text-to-speech
        /// </summary>
        /// <default>global::G.TextToSpeechAssetType.TextToSpeech</default>
        [global::Newtonsoft.Json.JsonProperty("type")]
        public global::G.TextToSpeechAssetType Type { get; set; } = global::G.TextToSpeechAssetType.TextToSpeech;

        /// <summary>
        /// The text to convert to speech.<br/>
        /// Example: This is a text to speech example generated by Shotstack
        /// </summary>
        /// <example>This is a text to speech example generated by Shotstack</example>
        [global::Newtonsoft.Json.JsonProperty("text", Required = global::Newtonsoft.Json.Required.Always)]
        public string Text { get; set; } = default!;

        /// <summary>
        /// The voice to use for the text-to-speech conversion.<br/>
        /// Example: Matthew
        /// </summary>
        /// <example>Matthew</example>
        [global::Newtonsoft.Json.JsonProperty("voice", Required = global::Newtonsoft.Json.Required.Always)]
        public string Voice { get; set; } = default!;

        /// <summary>
        /// The language code for the text-to-speech conversion.<br/>
        /// Example: en-US
        /// </summary>
        /// <example>en-US</example>
        [global::Newtonsoft.Json.JsonProperty("language")]
        public string? Language { get; set; }

        /// <summary>
        /// Set the voice to newscaster mode.<br/>
        /// Default Value: false
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("newscaster")]
        public bool? Newscaster { get; set; }

        /// <summary>
        /// The start trim point of the audio clip, in seconds (defaults to 0). Audio will start from the trim point. The audio will play until the file ends or the Clip length is reached.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("trim")]
        public double? Trim { get; set; }

        /// <summary>
        /// Set the volume of the audio clip. Use a number or an array of [Tween](./#tocs_tween) objects to create custom volume transitions.
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("volume")]
        public global::G.OneOf<float?, global::System.Collections.Generic.IList<global::G.Tween>>? Volume { get; set; }

        /// <summary>
        /// Adjust the playback speed of the audio clip between 0 (paused) and 10 (10x normal speed), where 1 is normal speed (defaults to 1). Adjusting the speed will also adjust the duration of the clip and may require you to adjust the Clip length.<br/>
        /// Example: 1
        /// </summary>
        /// <example>1</example>
        [global::Newtonsoft.Json.JsonProperty("speed")]
        public float? Speed { get; set; }

        /// <summary>
        /// The effect to apply to the audio asset &lt;ul&gt;<br/>
        ///   &lt;li&gt;`fadeIn` - fade volume in only&lt;/li&gt;<br/>
        ///   &lt;li&gt;`fadeOut` - fade volume out only&lt;/li&gt;<br/>
        ///   &lt;li&gt;`fadeInFadeOut` - fade volume in and out&lt;/li&gt;<br/>
        /// &lt;/ul&gt;
        /// </summary>
        [global::Newtonsoft.Json.JsonProperty("effect")]
        public global::G.TextToSpeechAssetEffect? Effect { get; set; }

        /// <summary>
        /// Additional properties that are not explicitly defined in the schema
        /// </summary>
        [global::Newtonsoft.Json.JsonExtensionData]
        public global::System.Collections.Generic.IDictionary<string, object> AdditionalProperties { get; set; } = new global::System.Collections.Generic.Dictionary<string, object>();

        /// <summary>
        /// Initializes a new instance of the <see cref="TextToSpeechAsset" /> class.
        /// </summary>
        /// <param name="text">
        /// The text to convert to speech.<br/>
        /// Example: This is a text to speech example generated by Shotstack
        /// </param>
        /// <param name="voice">
        /// The voice to use for the text-to-speech conversion.<br/>
        /// Example: Matthew
        /// </param>
        /// <param name="language">
        /// The language code for the text-to-speech conversion.<br/>
        /// Example: en-US
        /// </param>
        /// <param name="newscaster">
        /// Set the voice to newscaster mode.<br/>
        /// Default Value: false
        /// </param>
        /// <param name="trim">
        /// The start trim point of the audio clip, in seconds (defaults to 0). Audio will start from the trim point. The audio will play until the file ends or the Clip length is reached.
        /// </param>
        /// <param name="volume">
        /// Set the volume of the audio clip. Use a number or an array of [Tween](./#tocs_tween) objects to create custom volume transitions.
        /// </param>
        /// <param name="speed">
        /// Adjust the playback speed of the audio clip between 0 (paused) and 10 (10x normal speed), where 1 is normal speed (defaults to 1). Adjusting the speed will also adjust the duration of the clip and may require you to adjust the Clip length.<br/>
        /// Example: 1
        /// </param>
        /// <param name="effect">
        /// The effect to apply to the audio asset &lt;ul&gt;<br/>
        ///   &lt;li&gt;`fadeIn` - fade volume in only&lt;/li&gt;<br/>
        ///   &lt;li&gt;`fadeOut` - fade volume out only&lt;/li&gt;<br/>
        ///   &lt;li&gt;`fadeInFadeOut` - fade volume in and out&lt;/li&gt;<br/>
        /// &lt;/ul&gt;
        /// </param>
        /// <param name="type">
        /// The type of asset - set to `text-to-speech` for text-to-speech.<br/>
        /// Default Value: text-to-speech
        /// </param>
        public TextToSpeechAsset(
            string text,
            string voice,
            string? language,
            bool? newscaster,
            double? trim,
            global::G.OneOf<float?, global::System.Collections.Generic.IList<global::G.Tween>>? volume,
            float? speed,
            global::G.TextToSpeechAssetEffect? effect,
            global::G.TextToSpeechAssetType type = global::G.TextToSpeechAssetType.TextToSpeech)
        {
            this.Type = type;
            this.Text = text ?? throw new global::System.ArgumentNullException(nameof(text));
            this.Voice = voice ?? throw new global::System.ArgumentNullException(nameof(voice));
            this.Language = language;
            this.Newscaster = newscaster;
            this.Trim = trim;
            this.Volume = volume;
            this.Speed = speed;
            this.Effect = effect;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TextToSpeechAsset" /> class.
        /// </summary>
        public TextToSpeechAsset()
        {
        }
    }
}