//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.AudioUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.AudioUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChunkingStrategyJsonConverter),
            typeof(global::G.JsonConverters.ChunkingStrategyNullableJsonConverter),
            typeof(global::G.JsonConverters.ConditionOperatorJsonConverter),
            typeof(global::G.JsonConverters.ConditionOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.DataSourceAuthParamsVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.DataSourceAuthParamsVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DataSourceTypeJsonConverter),
            typeof(global::G.JsonConverters.DataSourceTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ElementTypeJsonConverter),
            typeof(global::G.JsonConverters.ElementTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.EncodingFormat3JsonConverter),
            typeof(global::G.JsonConverters.EncodingFormat3NullableJsonConverter),
            typeof(global::G.JsonConverters.ImageUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ImageUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LinearDataSourceCreateOrUpdateParamsAuthParamsVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.LinearDataSourceCreateOrUpdateParamsAuthParamsVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ModeJsonConverter),
            typeof(global::G.JsonConverters.ModeNullableJsonConverter),
            typeof(global::G.JsonConverters.MultiModalQueryVariant2DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MultiModalQueryVariant2DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.NotionDataSourceCreateOrUpdateParamsAuthParamsVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.NotionDataSourceCreateOrUpdateParamsAuthParamsVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ParsingJobStatusJsonConverter),
            typeof(global::G.JsonConverters.ParsingJobStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.RegexFlagJsonConverter),
            typeof(global::G.JsonConverters.RegexFlagNullableJsonConverter),
            typeof(global::G.JsonConverters.ReturnFormatJsonConverter),
            typeof(global::G.JsonConverters.ReturnFormatNullableJsonConverter),
            typeof(global::G.JsonConverters.ScopeMethodJsonConverter),
            typeof(global::G.JsonConverters.ScopeMethodNullableJsonConverter),
            typeof(global::G.JsonConverters.ScoredStoreFileChunksVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ScoredStoreFileChunksVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScoredVectorStoreFileChunksVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.ScoredVectorStoreFileChunksVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.StoreEventHistogramBucketTypeJsonConverter),
            typeof(global::G.JsonConverters.StoreEventHistogramBucketTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.StoreEventListResponseDataItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.StoreEventListResponseDataItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.StoreFileChunksVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.StoreFileChunksVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.StoreFileParsingStrategyJsonConverter),
            typeof(global::G.JsonConverters.StoreFileParsingStrategyNullableJsonConverter),
            typeof(global::G.JsonConverters.StoreFileStatusJsonConverter),
            typeof(global::G.JsonConverters.StoreFileStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.StoreQAResultsSourceDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.StoreQAResultsSourceDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.StoreSearchResponseDataItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.StoreSearchResponseDataItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.StoreStatusJsonConverter),
            typeof(global::G.JsonConverters.StoreStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.SyncStatusJsonConverter),
            typeof(global::G.JsonConverters.SyncStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.TextInputChunkGeneratedMetadataVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.TextInputChunkGeneratedMetadataVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.VectorStoreFileChunksVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.VectorStoreFileChunksVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.VectorStoreFileStatusJsonConverter),
            typeof(global::G.JsonConverters.VectorStoreFileStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.VectorStoreQAResultsSourceDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.VectorStoreQAResultsSourceDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.VectorStoreSearchResponseDataItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.VectorStoreSearchResponseDataItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.VideoUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.VideoUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsScoredAudioUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsScoredAudioUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsScoredImageUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsScoredImageUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsScoredTextInputChunkGeneratedMetadataVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsScoredTextInputChunkGeneratedMetadataVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsScoredVideoUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsScoredVideoUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsSearchRuleCreateParamsRuleDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsSearchRuleCreateParamsRuleDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsSearchRuleResponseRuleDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsSearchRuleResponseRuleDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsSearchRuleSpecificDeleteParamsRuleDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsSearchRuleSpecificDeleteParamsRuleDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsSearchRuleSpecificDeletedDeletedRuleDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsSearchRuleSpecificDeletedDeletedRuleDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsSearchRuleUpdateParamsRulesVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1DeprecatedVectorStoresModelsSearchRuleUpdateParamsRulesVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1StoresRulesModelsSearchRuleCreateParamsRuleDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1StoresRulesModelsSearchRuleCreateParamsRuleDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1StoresRulesModelsSearchRuleResponseRuleDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1StoresRulesModelsSearchRuleResponseRuleDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1StoresRulesModelsSearchRuleSpecificDeleteParamsRuleDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1StoresRulesModelsSearchRuleSpecificDeleteParamsRuleDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1StoresRulesModelsSearchRuleSpecificDeletedDeletedRuleDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1StoresRulesModelsSearchRuleSpecificDeletedDeletedRuleDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1StoresRulesModelsSearchRuleUpdateParamsRulesVariant1ItemDiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniApiRoutesV1StoresRulesModelsSearchRuleUpdateParamsRulesVariant1ItemDiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniCoreStoreModelsChunkTypesScoredAudioUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniCoreStoreModelsChunkTypesScoredAudioUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniCoreStoreModelsChunkTypesScoredImageUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniCoreStoreModelsChunkTypesScoredImageUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniCoreStoreModelsChunkTypesScoredTextInputChunkGeneratedMetadataVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniCoreStoreModelsChunkTypesScoredTextInputChunkGeneratedMetadataVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniCoreStoreModelsChunkTypesScoredVideoUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeJsonConverter),
            typeof(global::G.JsonConverters.MxbaiOmniCoreStoreModelsChunkTypesScoredVideoUrlInputChunkGeneratedMetadataVariant1DiscriminatorTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ListStoreEventsEventTypeJsonConverter),
            typeof(global::G.JsonConverters.ListStoreEventsEventTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GeneratedMetadataVariant1JsonConverter),
            typeof(global::G.JsonConverters.AuthParamsVariant1JsonConverter),
            typeof(global::G.JsonConverters.EmbeddingItemJsonConverter),
            typeof(global::G.JsonConverters.GeneratedMetadataVariant12JsonConverter),
            typeof(global::G.JsonConverters.AuthParamsVariant12JsonConverter),
            typeof(global::G.JsonConverters.MultiModalQueryJsonConverter),
            typeof(global::G.JsonConverters.MultiModalQueryVariant2JsonConverter),
            typeof(global::G.JsonConverters.AuthParamsVariant13JsonConverter),
            typeof(global::G.JsonConverters.ChunksVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.ChunksVariant1Item2JsonConverter),
            typeof(global::G.JsonConverters.DataItemJsonConverter),
            typeof(global::G.JsonConverters.ChunksVariant1Item3JsonConverter),
            typeof(global::G.JsonConverters.SourcesItemJsonConverter),
            typeof(global::G.JsonConverters.DataItem2JsonConverter),
            typeof(global::G.JsonConverters.GeneratedMetadataVariant13JsonConverter),
            typeof(global::G.JsonConverters.ChunksVariant1Item4JsonConverter),
            typeof(global::G.JsonConverters.SourcesItem2JsonConverter),
            typeof(global::G.JsonConverters.DataItem3JsonConverter),
            typeof(global::G.JsonConverters.GeneratedMetadataVariant14JsonConverter),
            typeof(global::G.JsonConverters.GeneratedMetadataVariant15JsonConverter),
            typeof(global::G.JsonConverters.GeneratedMetadataVariant16JsonConverter),
            typeof(global::G.JsonConverters.GeneratedMetadataVariant17JsonConverter),
            typeof(global::G.JsonConverters.GeneratedMetadataVariant18JsonConverter),
            typeof(global::G.JsonConverters.RulesItemJsonConverter),
            typeof(global::G.JsonConverters.RulesItem2JsonConverter),
            typeof(global::G.JsonConverters.RuleJsonConverter),
            typeof(global::G.JsonConverters.DeletedRuleJsonConverter),
            typeof(global::G.JsonConverters.RulesVariant1ItemJsonConverter),
            typeof(global::G.JsonConverters.RulesItem3JsonConverter),
            typeof(global::G.JsonConverters.RulesItem4JsonConverter),
            typeof(global::G.JsonConverters.Rule2JsonConverter),
            typeof(global::G.JsonConverters.DeletedRule2JsonConverter),
            typeof(global::G.JsonConverters.RulesVariant1Item2JsonConverter),
            typeof(global::G.JsonConverters.GeneratedMetadataVariant19JsonConverter),
            typeof(global::G.JsonConverters.GeneratedMetadataVariant110JsonConverter),
            typeof(global::G.JsonConverters.GeneratedMetadataVariant111JsonConverter),
            typeof(global::G.JsonConverters.GeneratedMetadataVariant112JsonConverter),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<bool?, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<int?, string, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.EncodingFormat3?, global::System.Collections.Generic.IList<global::G.EncodingFormat3>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.Embedding>, global::System.Collections.Generic.IList<global::G.MultiEncodingEmbedding>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.EncodingFormat3?, global::System.Collections.Generic.IList<global::G.EncodingFormat3>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Collections.Generic.IList<string>, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.TextInput, global::G.ImageUrlInput2>>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.TextInput, global::G.ImageUrlInput2>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.SearchFilter, global::G.SearchFilterCondition>>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.SearchFilter, global::G.SearchFilterCondition>>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.AnyOf<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>>, global::System.Collections.Generic.IList<global::System.Guid>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<bool?, global::System.Collections.Generic.IList<string>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, object, global::System.Collections.Generic.IList<object>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.SearchFilter, global::G.SearchFilterCondition>>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<bool?, global::G.RerankConfig, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<bool?, global::G.AgenticSearchConfig, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.SearchFilter, global::G.SearchFilterCondition>>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.AnyOf<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>>, global::System.Collections.Generic.IList<global::System.Guid>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<bool?, global::G.ContextualizationConfig>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<bool?, global::G.RerankConfig, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<bool?, global::G.AgenticSearchConfig, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.SearchFilter, global::G.SearchFilterCondition>>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.AnyOf<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>>, global::System.Collections.Generic.IList<global::System.Guid>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.SearchFilter, global::G.SearchFilterCondition>>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.AnyOf<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>>, global::System.Collections.Generic.IList<global::System.Guid>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, int?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<bool?, global::G.RerankConfig, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<bool?, global::G.AgenticSearchConfig, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.SearchFilter, global::G.SearchFilterCondition>>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.AnyOf<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>>, global::System.Collections.Generic.IList<global::System.Guid>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<bool?, global::G.RerankConfig, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<bool?, global::G.AgenticSearchConfig, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.SearchFilter, global::G.SearchFilterCondition>>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.AnyOf<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>>, global::System.Collections.Generic.IList<global::System.Guid>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition, global::System.Collections.Generic.IList<global::G.AnyOf<global::G.SearchFilter, global::G.SearchFilterCondition>>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.SearchFilter, global::G.SearchFilterCondition>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::System.Collections.Generic.IList<global::G.AnyOf<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>>, global::System.Collections.Generic.IList<global::System.Guid>, object>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.ConditionOperator?, global::System.Collections.Generic.IList<global::System.Guid>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.NotionDataSourceCreateOrUpdateParams, global::G.LinearDataSourceCreateOrUpdateParams>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<global::G.NotionDataSourceCreateOrUpdateParams, global::G.LinearDataSourceCreateOrUpdateParams>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<bool?, global::System.Collections.Generic.IList<int>>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.AnyOfJsonConverter<string, global::System.Guid?>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}