name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    if: github.event.pull_request.draft == false
    uses: tryAGI/workflows/.github/workflows/generated-sdk-pull-request.yml@main
    with:
      project-path: AutoSDK.slnx
      additional-test-arguments: '--logger GitHubActions'
