//HintName: G.JsonSerializerContextConverters.g.cs

#nullable enable

namespace G
{
    /// <summary>
    /// 
    /// </summary>
    internal sealed partial class JsonSerializerContextConverters
    {
        private readonly global::System.Type[] _types = new global::System.Type[]
        {
            typeof(global::G.JsonConverters.AnnotationQueueStatusJsonConverter),
            typeof(global::G.JsonConverters.AnnotationQueueStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.AnnotationQueueObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.AnnotationQueueObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BlobStorageIntegrationTypeJsonConverter),
            typeof(global::G.JsonConverters.BlobStorageIntegrationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BlobStorageIntegrationFileTypeJsonConverter),
            typeof(global::G.JsonConverters.BlobStorageIntegrationFileTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.BlobStorageExportModeJsonConverter),
            typeof(global::G.JsonConverters.BlobStorageExportModeNullableJsonConverter),
            typeof(global::G.JsonConverters.BlobStorageExportFrequencyJsonConverter),
            typeof(global::G.JsonConverters.BlobStorageExportFrequencyNullableJsonConverter),
            typeof(global::G.JsonConverters.BlobStorageSyncStatusJsonConverter),
            typeof(global::G.JsonConverters.BlobStorageSyncStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ScoreV1Variant1DataTypeJsonConverter),
            typeof(global::G.JsonConverters.ScoreV1Variant1DataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScoreV1Variant2DataTypeJsonConverter),
            typeof(global::G.JsonConverters.ScoreV1Variant2DataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScoreV1Variant3DataTypeJsonConverter),
            typeof(global::G.JsonConverters.ScoreV1Variant3DataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScoreVariant1DataTypeJsonConverter),
            typeof(global::G.JsonConverters.ScoreVariant1DataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScoreVariant2DataTypeJsonConverter),
            typeof(global::G.JsonConverters.ScoreVariant2DataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScoreVariant3DataTypeJsonConverter),
            typeof(global::G.JsonConverters.ScoreVariant3DataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScoreVariant4DataTypeJsonConverter),
            typeof(global::G.JsonConverters.ScoreVariant4DataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PricingTierOperatorJsonConverter),
            typeof(global::G.JsonConverters.PricingTierOperatorNullableJsonConverter),
            typeof(global::G.JsonConverters.ModelUsageUnitJsonConverter),
            typeof(global::G.JsonConverters.ModelUsageUnitNullableJsonConverter),
            typeof(global::G.JsonConverters.ObservationLevelJsonConverter),
            typeof(global::G.JsonConverters.ObservationLevelNullableJsonConverter),
            typeof(global::G.JsonConverters.CommentObjectTypeJsonConverter),
            typeof(global::G.JsonConverters.CommentObjectTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.DatasetStatusJsonConverter),
            typeof(global::G.JsonConverters.DatasetStatusNullableJsonConverter),
            typeof(global::G.JsonConverters.ScoreSourceJsonConverter),
            typeof(global::G.JsonConverters.ScoreSourceNullableJsonConverter),
            typeof(global::G.JsonConverters.ScoreConfigDataTypeJsonConverter),
            typeof(global::G.JsonConverters.ScoreConfigDataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScoreDataTypeJsonConverter),
            typeof(global::G.JsonConverters.ScoreDataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant3TypeJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant3TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant4TypeJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant4TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant5TypeJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant5TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant6TypeJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant6TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant7TypeJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant7TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant8TypeJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant8TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant9TypeJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant9TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant10TypeJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventVariant10TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ObservationTypeJsonConverter),
            typeof(global::G.JsonConverters.ObservationTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.LlmAdapterJsonConverter),
            typeof(global::G.JsonConverters.LlmAdapterNullableJsonConverter),
            typeof(global::G.JsonConverters.MediaContentTypeJsonConverter),
            typeof(global::G.JsonConverters.MediaContentTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.MembershipRoleJsonConverter),
            typeof(global::G.JsonConverters.MembershipRoleNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptVariant1TypeJsonConverter),
            typeof(global::G.JsonConverters.PromptVariant1TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptVariant2TypeJsonConverter),
            typeof(global::G.JsonConverters.PromptVariant2TypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PromptTypeJsonConverter),
            typeof(global::G.JsonConverters.PromptTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.PlaceholderMessageTypeJsonConverter),
            typeof(global::G.JsonConverters.PlaceholderMessageTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateChatPromptTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateChatPromptTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.CreateTextPromptTypeJsonConverter),
            typeof(global::G.JsonConverters.CreateTextPromptTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetScoresResponseDataVariant1DataTypeJsonConverter),
            typeof(global::G.JsonConverters.GetScoresResponseDataVariant1DataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetScoresResponseDataVariant2DataTypeJsonConverter),
            typeof(global::G.JsonConverters.GetScoresResponseDataVariant2DataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetScoresResponseDataVariant3DataTypeJsonConverter),
            typeof(global::G.JsonConverters.GetScoresResponseDataVariant3DataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.GetScoresResponseDataVariant4DataTypeJsonConverter),
            typeof(global::G.JsonConverters.GetScoresResponseDataVariant4DataTypeNullableJsonConverter),
            typeof(global::G.JsonConverters.ScoreV1JsonConverter),
            typeof(global::G.JsonConverters.ScoreJsonConverter),
            typeof(global::G.JsonConverters.CreateScoreValueJsonConverter),
            typeof(global::G.JsonConverters.MapValueJsonConverter),
            typeof(global::G.JsonConverters.IngestionEventJsonConverter),
            typeof(global::G.JsonConverters.IngestionUsageJsonConverter),
            typeof(global::G.JsonConverters.UsageDetailsJsonConverter),
            typeof(global::G.JsonConverters.CreatePromptRequestJsonConverter),
            typeof(global::G.JsonConverters.PromptJsonConverter),
            typeof(global::G.JsonConverters.ChatMessageWithPlaceholdersJsonConverter),
            typeof(global::G.JsonConverters.GetScoresResponseDataJsonConverter),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.ScoreV1Variant12, global::G.NumericScoreV1>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.ScoreV1Variant22, global::G.CategoricalScoreV1>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.ScoreV1Variant32, global::G.BooleanScoreV1>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.ScoreVariant12, global::G.NumericScore>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.ScoreVariant22, global::G.CategoricalScore>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.ScoreVariant32, global::G.BooleanScore>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.ScoreVariant42, global::G.CorrectionScore>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.IngestionEventVariant12, global::G.TraceEvent>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.IngestionEventVariant22, global::G.ScoreEvent>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.IngestionEventVariant32, global::G.CreateSpanEvent>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.IngestionEventVariant42, global::G.UpdateSpanEvent>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.IngestionEventVariant52, global::G.CreateGenerationEvent>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.IngestionEventVariant62, global::G.UpdateGenerationEvent>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.IngestionEventVariant72, global::G.CreateEventEvent>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.IngestionEventVariant82, global::G.SDKLogEvent>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.IngestionEventVariant92, global::G.CreateObservationEvent>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.IngestionEventVariant102, global::G.UpdateObservationEvent>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.PromptVariant12, global::G.ChatPrompt>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.PromptVariant22, global::G.TextPrompt>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.GetScoresResponseDataVariant12, global::G.GetScoresResponseDataNumeric>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.GetScoresResponseDataVariant22, global::G.GetScoresResponseDataCategorical>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.GetScoresResponseDataVariant32, global::G.GetScoresResponseDataBoolean>),
            typeof(global::G.JsonConverters.AllOfJsonConverter<global::G.GetScoresResponseDataVariant42, global::G.GetScoresResponseDataCorrection>),
            typeof(global::G.JsonConverters.UnixTimestampJsonConverter),
        };
    }
}